'use strict';
// Navigation, design tokens, page structure and tool formulas reconciled to Ultra_OS main 1830b14.
// All records remain fictional browser-local fixtures. No production APIs are called.
const sections = [
  ['Coaching',[['overview','Coach Command Center'],['calendar','Coach Calendar'],['messages','Coach Messages'],['tools','Coach Tools'],['groups','Coach Groups']]],
  ['My Training',[['dashboard','Dashboard'],['calendar','Training Calendar'],['races','Race Calendar'],['race-plan','Race Blueprint'],['check-in','Daily Check-in'],['log-intervention','Log Intervention'],['history','Intervention History'],['insights','Insights'],['progress','Progress'],['explorer','Explorer']]],
  ['Platform',[['connections','Connections'],['research','Research']]],
  ['Help / Billing',[['guide','Guide'],['pricing','Pricing'],['support','Support']]],
  ['Account',[['settings','Athlete Settings'],['account','Account Settings'],['notifications','Notifications']]],
  ['Research demo',[['feedback','Your feedback']]]
];
navItems.splice(0,navItems.length,...[...new Map(sections.flatMap(([,items])=>items).map(([p,label])=>[p,[p,'',label]])).values()],['athletes','','Athlete Roster'],['library','','Workout Library']);
renderNav = active => sections.map(([label,items])=>`<section class="nav-section"><p>${label}</p>${items.map(([p,t])=>`<a href="#${p}" ${active===p?'class="active" aria-current="page"':''}>${t}</a>`).join('')}</section>`).join('')+'<a href="#athletes" class="button" style="color:white">Open Roster</a>';
function addDefaults(){
  state.groups ||= [...new Set(athletes.map(a=>a.group))].map((name,i)=>({id:'g'+i,name,description:['Consistency for newer runners','Road-race preparation','Trail race blocks and time on feet'][i],members:athletes.filter(a=>a.group===name).map(a=>a.id)}));
  state.documents ||= [{id:'d1',athlete:'eli',title:'Long-run fueling practice',category:'Nutrition',body:'Sample shared resource: record what you ate, when you ate it, and how it felt. Bring your notes to our next conversation.'},{id:'d2',athlete:'maya',title:'Getting started: your first four weeks',category:'Training',body:'Sample shared resource: keep sessions conversational, use walk breaks when needed, and tell your coach when the schedule needs to change.'}];
  state.interventions ||= [{id:'i1',athlete:'eli',type:'Fueling - Mid-Effort',date:'2026-10-06',duration:55,response:8,notes:'Sample log: practiced fueling during the long run.'},{id:'i2',athlete:'jordan',type:'Sleep Quality',date:'2026-10-07',duration:0,response:6,notes:'Sample log: earlier bedtime, still tired after downhill work.'}];
  state.races ||= [{id:'r1',athlete:'eli',name:'City Marathon',date:'2026-11-01',distance:'Marathon',priority:'A',strategy:'Keep the early effort controlled. Review pacing and familiar fueling with your coach.'},{id:'r2',athlete:'maya',name:'Neighborhood 5K',date:'2026-11-07',distance:'5K',priority:'B',strategy:'Focus on a comfortable start and completing the distance.'},{id:'r3',athlete:'jordan',name:'Pine Ridge 50K',date:'2026-12-05',distance:'50K',priority:'A',strategy:'Practice equipment and hike steeper climbs during preparation.'}];
  state.profile ||= {display_name:'Alex Carter Coaching',email:'alex@example.test',sport:'Running',units:'Metric',lthr:168,maxHr:185,restingHr:52,notes:'Consistency, clear feedback, and a plan that fits real life.'};
  state.notificationPrefs ||= {messages:true,comments:true,checkins:true,digest:false};
  state.invitations ||= [];
  state.bookmarks ||= [];
  state.checkins ||= {};
  state.readNotifications ||= [];
  save();
}
addDefaults();
features.push('Coach calculators','Training groups','Shared documents','Race calendar & blueprint','Intervention logging & history','Research library');
let commandTab='triage',depth='basic',advancedTab='protocols',researchQuery='',savedOnly=false,insightTab='training';
const baseProfile=profile,baseCalendar=calendar,baseInsights=insights,basePreview=preview;
const sample = '<p class="sample-label">Fictional demo data · Changes stay in this browser</p>';
const field=(label,name,value='',type='text',extra='')=>`<label class="field"><span>${label}</span><input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const textarea=(label,name,value='',extra='')=>`<label class="field"><span>${label}</span><textarea name="${name}" maxlength="5000" ${extra}>${esc(value)}</textarea></label>`;
const selectField=(label,name,options,current)=>`<label class="field"><span>${label}</span><select name="${name}">${options.map(o=>{const [v,t]=Array.isArray(o)?o:[o,o];return `<option value="${esc(v)}" ${String(v)===String(current)?'selected':''}>${esc(t)}</option>`;}).join('')}</select></label>`;
const tabs=(options,current,action)=>`<div class="tabs" role="tablist">${options.map(([id,label])=>`<button type="button" role="tab" class="tab ${current===id?'selected':''}" aria-selected="${current===id}" data-action="${action}" data-id="${id}">${label}</button>`).join('')}</div>`;
function hero(eyebrow,title,description,stats=[]){return `<section class="threshold-hero"><div><div class="eyebrow">${eyebrow}</div><h1>${esc(title)}</h1><p>${description}</p></div>${stats.length?`<div class="hero-stats">${stats.map(([label,value])=>`<div class="hero-stat"><span>${label}</span><b>${value}</b></div>`).join('')}</div>`:''}</section>`;}
function panel(title,body,action=''){return `<section class="panel"><div class="panel-header"><h2>${title}</h2>${action}</div><div class="panel-body">${body}</div></section>`;}
function protocolRows(){return state.protocols.map((p,i)=>`<div class="protocol-row">${avatar(person(p.athlete))}<div><h3>${esc(p.title)}</h3><p>${person(p.athlete).name} · ${esc(p.detail)}</p><small>${esc(p.status||'In progress')} · target ${p.target||85}% · ${esc(p.start||'Oct 5')} – ${esc(p.end||'Oct 25')}</small></div><div class="actions"><button class="button small outline" data-action="x-protocol-status" data-index="${i}">${p.status==='Completed'?'Reopen':'Mark completed'}</button></div></div>`).join('');}
function advanced(){
  if(depth==='basic')return '';
  let body='';
  if(advancedTab==='protocols')body=`<div class="actions"><button class="button small" data-action="x-protocol">Assign protocol</button><a class="button small outline" href="#groups">Assign to group</a></div>${protocolRows()}`;
  if(advancedTab==='invitations')body=`<div class="app-banner"><b>Coach code: DEMO-ALEX</b>Create a sample invitation and preview its link. No invitation email is sent.</div><button class="button small" data-action="x-invite">Invite an athlete</button>${state.invitations.map(i=>`<div class="history-row"><div><h3>${esc(i.name)}</h3><p>${esc(i.email)} · Pending demo invitation</p></div><span class="badge warn">Not delivered</span></div>`).join('')}`;
  if(advancedTab==='templates')body=`<div class="actions"><a class="button small outline" href="#library">Workout library</a><button class="button small" data-action="x-protocol">Protocol template</button><button class="button small outline" data-action="x-document">Share document</button></div><div class="app-banner"><b>Shared documents</b>Text resources are stored alongside athlete notes and messages.</div>${state.documents.map(d=>`<div class="history-row"><div><h3>${esc(d.title)}</h3><p>${person(d.athlete).name} · ${esc(d.category)}</p></div><button class="button small outline" data-action="x-open-document" data-id="${d.id}">Open</button></div>`).join('')}`;
  if(advancedTab==='settings')body=profileForm();
  return `<section class="panel" style="margin-bottom:24px"><div class="panel-body"><div class="eyebrow">Advanced workspace</div>${tabs([['protocols','Protocol Actions'],['invitations','Invitations'],['templates','Templates'],['settings','Profile Settings']],advancedTab,'x-advanced-tab')}${body}</div></section>`;
}
overview = function(){
  addDefaults();
  const needs=athletes.filter(a=>a.status!=='On track'&&!state.reviewed.includes(a.id));
  let body='';
  if(commandTab==='triage')body=`<section class="panel"><div class="panel-header"><div class="eyebrow" style="margin:0">Today’s coaching questions</div><span class="badge blue">Wed, Oct 7 · sample day</span></div><div class="questions">${[['Who needs attention?','Readiness and check-in signals',needs.filter(a=>a.id==='jordan')],['Who races soon?','Upcoming race block',[]],['Who is missing data?','No log in 5+ days',[person('nora')]],['Who is off-protocol?','Behind on logs or compliance',[person('eli')]],['Who needs a message?','No coach touchpoint in 3+ days',needs.filter(a=>a.id==='maya')],['What protocol actions are needed?','No active protocol assigned',athletes.filter(a=>!state.protocols.some(p=>p.athlete===a.id))]].map(([q,h,list])=>`<div class="question"><div class="triage-top"><h3>${q}</h3><span class="badge warn">${list.length}</span></div><p>${h}</p>${list.length?list.map(a=>`<a class="pill" href="#athlete/${a.id}">${a.name}</a>`).join(' '):'<small>All clear.</small>'}</div>`).join('')}</div></section><section class="triage-feed"><div class="triage-top"><div class="eyebrow" style="margin:0">Triage feed · sorted by urgency</div><span class="badge warn">${needs.length} needing attention</span></div>${needs.length?needs.map(a=>`<article class="triage-row"><div class="triage-top">${personHTML(a)}${badge(a)}</div><div class="actions" style="margin-top:12px"><a class="text-link" href="#athlete/${a.id}">Open detail file →</a><a class="text-link" href="#messages/${a.id}">Message athlete →</a></div><small style="margin-top:10px">Last logged ${a.id==='maya'?'today':'1d ago'} · ${a.race}</small><div class="flag-reason"><b>Why flagged:</b><p>${a.reason}</p>Action: Review the athlete’s feedback and agree the next step.</div><div class="actions"><button class="button small outline" data-action="x-protocol" data-id="${a.id}">Assign protocol</button><button class="button small outline" data-action="x-document" data-id="${a.id}">Share document</button></div></article>`).join(''):'<div class="empty">All attention items reviewed.</div>'}</section><section class="panel" style="margin-top:24px"><div class="panel-header"><h2>Active athletes</h2><a class="text-link" href="#athletes">Search roster →</a></div><div class="table-wrap"><table><thead><tr><th>Athlete</th><th>Next race</th><th>Protocols</th><th>Compliance</th><th>Status</th></tr></thead><tbody>${athletes.map(a=>`<tr><td><a href="#athlete/${a.id}">${personHTML(a)}</a></td><td>${a.race}</td><td>${state.protocols.filter(p=>p.athlete===a.id).length}</td><td>${a.compliance}</td><td>${badge(a)}</td></tr>`).join('')}</tbody></table></div></section>`;
  if(commandTab==='load-trends')body=`<div class="two-col">${athletes.map(a=>panel(a.name,chart(a)+`<div class="metrics" style="margin-top:18px"><div class="metric"><b>${a.volume}</b><small>Sample 7D distance</small></div><div class="metric"><b>${a.compliance}</b><small>Adherence</small></div><div class="metric"><b>${a.energy}/5</b><small>Energy</small></div></div><p class="chart-note">Six fictional weeks of athlete training history.</p>`)).join('')}</div>`;
  if(commandTab==='notes')body=`<div class="two-col">${athletes.map(a=>panel(a.name,`<p>${esc(state.notes[a.id])}</p><div class="actions" style="margin-top:16px"><a class="button small outline" href="#athlete/${a.id}">Edit coaching notes</a><a class="text-link" href="#messages/${a.id}">Recent messages →</a></div>`)).join('')}</div>`;
  if(commandTab==='alerts')body=panel('Athlete alerts',athletes.filter(a=>a.status!=='On track').map(a=>`<div class="alert-row"><h3>${a.name} · ${a.status}</h3><p>${a.reason}</p><a class="text-link" href="#athlete/${a.id}">Review signals →</a></div>`).join('')+sample);
  return hero('Coach Command Center',state.profile.display_name,'Manage athletes, assign protocols, and track compliance in one place.',[['Athletes',6],['Active protocols',state.protocols.filter(p=>p.status!=='Completed').length],['Need attention',needs.length],['Races in 30d',1],['Daily load','124'],['7D load','842']])+`<section class="kpis"><div class="eyebrow">Coach KPIs</div><div class="kpis-grid"><div><span class="small-label">At-risk athletes</span><b>${needs.length}</b></div><div><span class="small-label">Intervention lift</span><b>—</b></div><div><span class="small-label">Comm SLA (hrs)</span><b>12</b></div></div>${sample}</section><div class="actions"><button class="button" data-action="x-invite">Invite an athlete</button><a class="button outline" href="#groups">Manage groups</a><a class="button outline" href="#calendar">Training calendar</a></div>${tabs([['triage','Triage'],['load-trends','Load Trends'],['notes','Notes'],['alerts','Alerts']],commandTab,'x-command-tab')}<div class="screen-depth"><span>Screen depth</span>${tabs([['basic','Basic'],['advanced','Advanced']],depth,'x-depth')}</div>${advanced()}${body}`;
};
profile = id => {const a=person(id);let base=baseProfile(id);if(state.checkins[a.id])base=base.replace(esc(a.checkin),esc(state.checkins[a.id].note));return base+`<section class="panel" style="margin-top:24px"><div class="panel-header"><h2>Race readiness report</h2><a class="text-link" href="#race-plan">Race blueprint →</a></div><div class="panel-body"><p class="chart-note">Coach review of fictional athlete signals. These sample domains illustrate the actual athlete detail file.</p><div class="detail-readiness">${[['Training consistency',a.compliance],['Recovery',a.energy>2?'Steady':'Review'],['Protocol adherence',a.id==='eli'?'Needs follow-up':'On track'],['Race preparation',a.race.startsWith('No')?'No race set':'Building']].map(([k,v])=>`<div>${k}<b>${v}</b></div>`).join('')}</div><div class="actions" style="margin-top:20px"><button class="button small" data-action="x-protocol" data-id="${a.id}">Assign protocol</button><a class="button small outline" href="#history">Intervention history</a></div></div></section><div class="two-col" style="margin-top:24px">${panel('Shared documents',state.documents.filter(d=>d.athlete===a.id).map(d=>`<div class="history-row"><div><h3>${esc(d.title)}</h3><small>${esc(d.category)}</small></div><button class="button small outline" data-action="x-open-document" data-id="${d.id}">Open</button></div>`).join('')||'<p class="chart-note">No shared resources yet.</p>',`<button class="button small outline" data-action="x-document" data-id="${a.id}">Share document</button>`)}${panel('TrainingPeaks import',`<p class="chart-note">Inspect a sample import report with matched and unmatched sessions. No real file or account is imported.</p><div class="app-banner"><b>Sample import · 4 records</b>3 matched to planned workouts · 1 needs review · 0 duplicates</div><button class="button small outline" data-action="x-import" data-id="${a.id}">Review sample import</button>`)}</div>`;};
calendar = () => baseCalendar().replace('Training calendar','Coach Training Calendar')+`<div class="calendar-library"><div><h3>Workout library & group assignments</h3><p>Save time with reusable sessions and coach groups.</p></div><div class="actions"><a href="#library" class="button small outline">Workout library</a><a href="#groups" class="button small outline">Group calendar</a></div></div>`;
function profileForm(){const p=state.profile;return `<form id="x-profile-form">${field('Display name','display_name',p.display_name,'text','required maxlength="150"')}${textarea('Coaching bio / approach','notes',p.notes)}<div class="form-grid">${field('Email (demo only)','email',p.email,'email','required')}${selectField('Primary sport','sport',['Running','Cycling','Triathlon','Swimming','Other'],p.sport)}</div><button class="button small" type="submit">Save profile</button>${sample}</form>`;}
function groupsPage(){return heading('Coach Tools','Training Groups','Group similar athletes and assign protocols or calendar workouts to everyone at once.')+`<div class="two-col">${panel('Create a group',`<form id="x-group-form">${field('Group name','name','','text','required maxlength="150"')}${textarea('Description','description')}${athletes.map(a=>`<label class="member-choice"><input type="checkbox" name="member" value="${a.id}">${a.name} · ${a.goal}</label>`).join('')}<button class="button" style="margin-top:15px" type="submit">Create group</button></form>`)}${panel('Assign a workout to a group calendar',`<form id="x-group-workout-form">${selectField('Training group','group',state.groups.map(g=>[g.id,g.name]),state.groups[0]?.id)}${selectField('Library workout','template',library.map(t=>[t.id,t.title]),'easy')}${field('Workout date','date','2026-10-09','date','required')}<button class="button" type="submit">Assign workout</button>${sample}</form>`)}${panel('Assign a protocol template to a group',`<form id="x-group-protocol-form">${selectField('Training group','group',state.groups.map(g=>[g.id,g.name]),state.groups[0]?.id)}${selectField('Protocol template','title',['Sleep consistency','Long-run fueling practice','Gut Training','Heat Acclimation'],'Sleep consistency')}<div class="form-grid">${field('Start date','start','2026-10-09','date','required')}${field('End date','end','2026-10-23','date','required')}</div><button class="button" type="submit">Assign protocol</button>${sample}</form>`)}${panel('Your groups',state.groups.map(g=>`<div class="history-row"><div><h3>${esc(g.name)}</h3><p>${esc(g.description)}</p><div class="chips">${g.members.map(id=>`<a class="pill" href="#athlete/${id}">${person(id).name}</a>`).join('')||'<small>No athletes yet.</small>'}</div></div><button class="button small outline" data-action="x-group-members" data-id="${g.id}">Members</button></div>`).join(''))}</div>`;}
const toolDistances=[['mile','Mile',1609.34],['5k','5K',5000],['10k','10K',10000],['half','Half Marathon',21097.5],['marathon','Marathon',42195],['50k','50K',50000],['100k','100K',100000]];
function parseTime(v){const p=String(v).trim().split(':').map(Number);if(p.length>3||p.some(x=>!Number.isFinite(x)||x<0)||!v.trim())return null;return p.length===3?p[0]*3600+p[1]*60+p[2]:p.length===2?p[0]*60+p[1]:p[0]*60;}
function fmtTime(v){if(!Number.isFinite(v))return '—';v=Math.round(v);const h=Math.floor(v/3600),m=Math.floor(v%3600/60),s=String(v%60).padStart(2,'0');return h?`${h}:${String(m).padStart(2,'0')}:${s}`:`${m}:${s}`;}
function resultTable(rows,header='Range'){return `<table><thead><tr><th>Zone / target</th><th>${header}</th></tr></thead><tbody>${rows.map(([label,value])=>`<tr><td>${esc(label)}</td><td>${esc(value)}</td></tr>`).join('')}</tbody></table>`;}
function toolCard(id,title,blurb,inputs){return `<section class="tool-card"><div class="eyebrow">${id==='power'?'Cycling':id==='swim'?'Swimming':'Coach Tools'}</div><h2>${title}</h2><p>${blurb}</p><form class="tool-form" data-tool="${id}"><div class="form-grid">${inputs}</div><div class="result" id="result-${id}" aria-live="polite"></div></form></section>`;}
function toolsPage(){return hero('Threshold · Coach Tools','Coach Tools','Field-tested calculators across running, cycling, swimming, and general endurance — zones, race predictions, training paces, and load planning in one place.')+`<div class="tools-grid">${toolCard('hr','Heart-Rate Zone Calculator','The same three methods shown in Threshold: LTHR, Karvonen, or percentage of maximum heart rate.',selectField('Method','method',[['lthr','LTHR (Friel 7-zone)'],['karvonen','Karvonen (HR reserve)'],['max','% of Max HR']],'lthr')+field('Lactate threshold HR (bpm)','lthr',168,'number','min="1" max="250"')+field('Max HR (bpm)','max',185,'number','min="1" max="250"')+field('Resting HR (bpm)','rest',52,'number','min="1" max="200"'))}${toolCard('race','Race Predictor (Riegel)','Estimate other distances from a recent race, using the product’s Riegel formula.',selectField('Known race','distance',toolDistances.map(([id,t])=>[id,t]),'10k')+field('Finish time (h:mm:ss)','time','42:00')+field('Riegel exponent','exponent',1.06,'number','step="0.01" min="1" max="2"'))}${toolCard('paces','Training Pace Calculator','Running paces derived from a recent race, matching the actual Coach Tools calculation.',selectField('Recent race','distance',toolDistances.map(([id,t])=>[id,t]),'5k')+field('Finish time (h:mm:ss)','time','20:00'))}${toolCard('power','Power Zone Calculator','Coggan seven-zone model, calculated from FTP.',field('FTP (watts)','ftp',250,'number','min="1" max="1500"'))}${toolCard('swim','Critical Swim Speed (CSS)','From 400 m and 200 m time trials, with the same pool targets as the product.',field('400 m TT (m:ss)','t400','6:20')+field('200 m TT (m:ss)','t200','3:02'))}${toolCard('converter','Pace & Speed Converter','Goal time to pace in both unit systems.',field('Distance','distance',26.2,'number','step="0.1" min="0.1"')+selectField('Unit','unit',[['mi','miles'],['km','kilometers']],'mi')+field('Goal time (h:mm:ss)','time','3:30:00'))}${toolCard('ramp','Fitness Ramp Planner','Coach Pro’s planning model, with current fitness, target fitness, and weeks to race.',field('Current CTL','current',45,'number','min="0"')+field('Target CTL','target',70,'number','min="0"')+field('Weeks to race','weeks',12,'number','min="1" max="104"'))}</div><p class="app-banner">These are the product’s deterministic calculators with editable sample inputs. They are planning illustrations for this demo.</p>`;}
function updateTools(){document.querySelectorAll('.tool-form').forEach(form=>{const d=Object.fromEntries(new FormData(form)),id=form.dataset.tool;let html='Enter valid inputs to see results.';const table=rows=>resultTable(rows);if(id==='hr'){const lt=Number(d.lthr),max=Number(d.max),rest=Number(d.rest);if(d.method==='lthr'&&lt>0)html=table([['Z1 Recovery',`< ${Math.round(lt*.85)} bpm`],...[[.85,.89,'Z2 Aerobic'],[.9,.94,'Z3 Tempo'],[.95,.99,'Z4 SubThreshold'],[1,1.02,'Z5a Threshold'],[1.03,1.06,'Z5b VO2max']].map(([lo,hi,z])=>[z,`${Math.round(lt*lo)}–${Math.round(lt*hi)} bpm`]),['Z5c Anaerobic',`> ${Math.round(lt*1.07)} bpm`]]);else if(max>0&&(d.method==='max'||max>rest&&rest>0))html=table(['Recovery','Endurance','Tempo','Threshold','VO2max'].map((z,i)=>{const n=v=>Math.round(d.method==='max'?max*v:rest+(max-rest)*v);return [`Z${i+1} ${z}`,`${n(.5+i*.1)}–${n(.6+i*.1)} bpm`];}));}
  if(id==='race'||id==='paces'){const meters=toolDistances.find(t=>t[0]===d.distance)?.[2],t=parseTime(d.time),exp=id==='race'?Number(d.exponent):1.06;if(meters&&t>0&&exp>0){const prediction=m=>t*(m/meters)**exp;if(id==='race')html=resultTable(toolDistances.filter(x=>x[0]!==d.distance).map(([,name,m])=>[name,fmtTime(prediction(m))]),'Predicted time');else{const threshold=3600/(meters*(3600/t)**(1/exp)/1609.34),pace=m=>prediction(m)/(m/1609.34);html=resultTable([['Easy / Long run',`${fmtTime(threshold*1.28)}–${fmtTime(threshold*1.42)}/mi`],['Marathon pace',fmtTime(pace(42195))+'/mi'],['Threshold',fmtTime(threshold)+'/mi'],['Interval / VO2max',fmtTime(pace(3000))+'/mi'],['Repetition',fmtTime(pace(1609.34))+'/mi']],'Pace');}}}
  if(id==='power'&&Number(d.ftp)>0){const f=Number(d.ftp);html=table([['Z1 Recovery',`< ${Math.round(f*.55)} W`],...[[.56,.75,'Z2 Endurance'],[.76,.9,'Z3 Tempo'],[.91,1.05,'Z4 Threshold'],[1.06,1.2,'Z5 VO2max'],[1.21,1.5,'Z6 Anaerobic']].map(([lo,hi,z])=>[z,`${Math.round(f*lo)}–${Math.round(f*hi)} W`]),['Z7 Neuromuscular',`> ${Math.round(f*1.51)} W`]]);}
  if(id==='swim'){const a=parseTime(d.t400),b=parseTime(d.t200);if(a>b&&b>0){const pace=(a-b)/2;html=`<div class="value">${fmtTime(pace)}/100m</div>`+resultTable([['Easy / Recovery',1.1],['Endurance',1.05],['CSS / Threshold',1],['VO2max',.95],['Sprint',.88]].map(([z,f])=>[z,fmtTime(pace*f)+'/100m']),'Pace');}}
  if(id==='converter'){const n=Number(d.distance),t=parseTime(d.time);if(n>0&&t>0){const miles=d.unit==='mi'?n:n/1.60934,km=d.unit==='km'?n:n*1.60934;html=table([['Per mile',fmtTime(t/miles)],['Per km',fmtTime(t/km)],['mph',(miles/(t/3600)).toFixed(2)],['km/h',(km/(t/3600)).toFixed(2)]]);}}
  if(id==='ramp'){const current=Number(d.current),target=Number(d.target),weeks=Number(d.weeks);if(weeks>0&&current>=0&&target>=0){const ramp=(target-current)/weeks;html=table([['Ramp / week',ramp.toFixed(1)],['Weekly TSS (start)',Math.round(7*(current+ramp*6))],['Weekly TSS (end)',Math.round(7*(target+ramp*6))],['Mid-block weekly TSS',Math.round(7*((current+target)/2+ramp*6))]]);}}
  form.querySelector('.result').innerHTML=html;});}
function racesPage(){return heading('Training','Race Calendar','Manage your athletes’ target races and priorities.',`<button class="button" data-action="x-race">+ Add race</button>`)+`<div class="resource-list">${state.races.map(r=>`<section class="resource-entry"><div class="triage-top"><span class="badge warn">${esc(r.priority)} race</span><small>${esc(r.date)}</small></div><h2>${esc(r.name)}</h2><p>${person(r.athlete).name} · ${esc(r.distance)}</p><div class="actions"><button class="button small outline" data-action="x-blueprint" data-id="${r.id}">Race blueprint</button><button class="button small outline" data-action="x-race" data-id="${r.id}">Edit race</button></div></section>`).join('')}</div>`;}
let blueprintRace='r1';
function blueprintPage(){const r=state.races.find(r=>r.id===blueprintRace)||state.races[0];if(!r)return heading('Training','Race Blueprint','Add a target race to build its preparation plan.')+`<a class="button" href="#races">Race calendar</a>`;return hero('Race Blueprint','Your race, your blueprint.',`${esc(r.name)} · ${person(r.athlete).name} · ${esc(r.date)}`)+`<div class="two-col">${panel('Race preparation',`<form id="x-blueprint-form" data-id="${r.id}">${selectField('Race','race',state.races.map(r=>[r.id,`${r.name} · ${person(r.athlete).name}`]),r.id)}${textarea('Coach-written race strategy','strategy',r.strategy)}<div class="form-grid">${field('Target finish time','time',r.time||'3:20:00')}${field('Equipment / logistics','equipment',r.equipment||'Review familiar shoes, kit, and travel plans.')}</div><button class="button" type="submit">Save blueprint</button>${sample}</form>`)}${panel('Preparation timeline',`<div class="history-row"><div><h3>Four weeks out</h3><p>Review training consistency and practice familiar race routines.</p></div></div><div class="history-row"><div><h3>Two weeks out</h3><p>Check equipment, logistics, and recovery with the athlete.</p></div></div><div class="history-row"><div><h3>Race week</h3><p>Confirm the coach-written plan and answer final questions.</p></div></div><a class="button small outline" href="#messages/${r.athlete}">Discuss race plan</a><a class="button small outline" href="#history">Review intervention history</a>`)}</div>`;}
const interventionTypes=['Workout Check-in','Heat Acclimation','Gut Training','Fueling - Mid-Effort','Sauna - Recovery','Sleep Quality','Respiratory Training','Altitude Acclimatization'];
function loggerPage(){return heading('Training','Log Intervention','Capture the session, context, and athlete response.')+`<div class="two-col">${panel('New intervention',`<form id="x-intervention-form">${selectField('Athlete','athlete',athletes.map(a=>[a.id,a.name]),selected)}${selectField('Intervention type','type',interventionTypes,'Workout Check-in')}<div class="form-grid">${field('Date','date','2026-10-07','date','required')}${field('Duration (minutes)','duration',30,'number','min="0" max="1440" required')}${field('Response (1–10)','response',7,'number','min="1" max="10" required')}${field('Perceived effort / RPE (1–10)','rpe',4,'number','min="1" max="10"')}</div>${textarea('Notes / observations','notes')}<button class="button" type="submit">Save intervention</button>${sample}</form>`)}${panel('Favorite intervention types',`<div class="chips">${interventionTypes.slice(0,6).map(t=>`<button class="pill" data-action="x-intervention-type" data-type="${t}">${t}</button>`).join('')}</div><p class="chart-note">The actual product records intervention-specific details; this sample logger lets coaches try the selection, observations, and review loop.</p><a class="button small outline" href="#history">Open intervention history</a>`)}</div>`;}
function historyPage(){return heading('Training','Intervention History','Review logged sessions and coaching observations.',`<a class="button" href="#log-intervention">+ Log intervention</a>`)+`<div class="panel"><div class="panel-header"><h2>Recent logs</h2><span class="badge">${state.interventions.length} entries</span></div>${state.interventions.slice().reverse().map(i=>`<div class="history-row">${avatar(person(i.athlete))}<div><h3>${esc(i.type)}</h3><p>${person(i.athlete).name} · ${esc(i.date)} · ${i.duration} min · Response ${i.response}/10</p><p>${esc(i.notes)}</p></div><a class="text-link" href="#athlete/${i.athlete}">Athlete →</a></div>`).join('')}</div>`;}
function checkinPage(){const a=person(selected),c=state.checkins[a.id]||{};return heading('Training','Daily Check-in','A quick picture of how the athlete feels before you adjust the plan.')+`<div class="two-col">${panel('Today’s check-in',`<form id="x-checkin-form">${selectField('Athlete','athlete',athletes.map(a=>[a.id,a.name]),a.id)}<div class="form-grid">${field('Sleep (hours)','sleep',c.sleep||a.sleep,'number','step="0.1" min="0" max="24" required')}${field('Energy (1–5)','energy',c.energy||a.energy,'number','min="1" max="5" required')}${field('Soreness (1–5)','soreness',c.soreness||a.soreness,'number','min="1" max="5" required')}${field('Stress (1–5)','stress',c.stress||2,'number','min="1" max="5" required')}</div>${textarea('Anything your coach should know?','note',c.note||a.checkin)}<button class="button" type="submit">Save check-in</button>${sample}</form>`)}${panel('Coach feedback',`<p>${esc(state.messages[a.id].filter(m=>m.by==='Alex Carter').at(-1)?.body)}</p><div class="actions" style="margin-top:20px"><a class="button outline small" href="#preview/${a.id}">Athlete training view</a><a class="button outline small" href="#athlete/${a.id}">Coach detail file</a></div>`)}</div>`;}
function dashboardPage(){const a=person(selected);return hero('Dashboard','Today, with Threshold.','Your training, check-in, and coaching conversation in one place.')+`<div class="toolbar"><label><span class="small-label">Sample athlete perspective</span><select id="athlete-select">${athleteOptions()}</select></label></div><div class="two-col">${panel('Today’s training',state.workouts.filter(w=>w.athlete===a.id&&w.week===0).map(w=>workoutHTML(w,true)).join(''),'<a class="text-link" href="#calendar">Calendar →</a>')}${panel('How are you feeling?',`<p>“${esc(state.checkins[a.id]?.note||a.checkin)}”</p><div class="checkin-metrics"><div><b>${a.sleep}h</b><small>Sleep</small></div><div><b>${a.energy}/5</b><small>Energy</small></div><div><b>${a.soreness}/5</b><small>Soreness</small></div></div><div class="actions" style="margin-top:20px"><a class="button small" href="#check-in">Daily check-in</a><a class="button small outline" href="#log-intervention">Log intervention</a></div>`)}${panel('Weekly volume',chart(a))}${panel('Race preparation',`<h3>${a.race}</h3><p class="chart-note">Review your coach’s plan and preparation history.</p><a class="button small outline" href="#race-plan">Race blueprint</a>`)}</div>`;}
insights = () => heading('Training','Insights','Review deterministic training signals and coach-written context.')+tabs([['training','Training'],['protocols','Protocols'],['checkins','Check-ins']],insightTab,'x-insight-tab')+(insightTab==='protocols'?panel('Coaching protocols',protocolRows(),'<button class="button small" data-action="x-protocol">Assign protocol</button>'):insightTab==='checkins'?`<div class="two-col">${athletes.map(a=>panel(a.name,`<p>“${esc(state.checkins[a.id]?.note||a.checkin)}”</p><div class="checkin-metrics"><div><b>${a.sleep}h</b><small>Sample sleep</small></div><div><b>${a.energy}/5</b><small>Energy</small></div><div><b>${a.soreness}/5</b><small>Soreness</small></div></div>`)).join('')}</div>`:baseInsights().replace(/^[\s\S]*?<div class="toolbar">/,'<div class="toolbar">'));
function progressPage(){const a=person(selected);return heading('Training','Progress','Track volume, consistency, and logged interventions across time.')+`<div class="toolbar"><label><span class="small-label">Athlete</span><select id="athlete-select">${athleteOptions()}</select></label></div><div class="two-col">${panel('Six-week distance trend',chart(a)+sample)}${panel('Training consistency',`<div class="metrics"><div class="metric"><b>${a.compliance}</b><small>Sample adherence</small></div><div class="metric"><b>${a.volume}</b><small>7D distance</small></div><div class="metric"><b>${state.interventions.filter(i=>i.athlete===a.id).length}</b><small>Intervention logs</small></div></div><p class="chart-note">Use the training calendar and intervention history to review the underlying entries.</p><a class="button small outline" href="#history">View history</a>`)}</div>`;}
function explorerPage(){return hero('Training','Explorer','Explore the relationship between logged interventions and training context.')+panel('Sample exploration',`<form id="x-explorer-form"><div class="form-grid">${selectField('Intervention','intervention',interventionTypes,'Gut Training')}${selectField('Outcome','outcome',['Energy','Sleep','Training consistency'],'Energy')}</div><button class="button small" type="submit">Explore sample</button></form><div class="result" id="explorer-result"><h3>Gut Training × Energy</h3><p class="chart-note">Sample view: compare intervention days with athlete-reported energy. These six fictional observations do not establish an effect.</p>${chart(person('eli'))}</div><p class="chart-note">No AI-generated recommendation or causal conclusion is included.</p>`);}
const studyFixtures=[{id:'s1',title:'Carbohydrate intake during endurance exercise',topic:'Nutrition',sport:'Road Running',body:'Illustrative library entry: a coach can review an evidence summary, save it, and discuss questions about fueling with an athlete.'},{id:'s2',title:'Sleep and recovery in endurance training',topic:'Recovery',sport:'All sports',body:'Illustrative library entry: consider how sleep observations fit with training and the athlete’s reported experience.'},{id:'s3',title:'Heat acclimation and endurance preparation',topic:'Heat',sport:'Ultra / Trail',body:'Illustrative library entry: compare the research question, practical context, and limitations before considering a protocol.'}];
function researchPage(){const list=studyFixtures.filter(s=>(!savedOnly||state.bookmarks.includes(s.id))&&`${s.title} ${s.topic} ${s.sport}`.toLowerCase().includes(researchQuery.toLowerCase()));return hero('Platform','Research Library','Browse the same library workflow: studies, topics, sport filters, and saved reading. These entries are explicitly illustrative sample records.')+tabs([['all','All'],['saved',`Saved (${state.bookmarks.length})`]],savedOnly?'saved':'all','x-research-tab')+`<div class="toolbar"><label class="search"><span class="small-label">Search studies</span><input id="study-search" placeholder="Search studies" value="${esc(researchQuery)}"></label><button class="button small outline" data-action="x-clear-study">Clear filters</button></div><div class="resource-list" id="study-list">${studyRows(list)}</div><div class="app-banner"><b>PubMed search</b>The live product offers PubMed search. This no-account demo uses illustrative local entries instead of querying a research service.</div>`;}
function studyRows(list){return list.map(s=>`<article class="resource-entry"><span class="badge warn">Illustrative entry · ${s.topic}</span><h2>${s.title}</h2><p>${s.sport} · Sample evidence summary</p><p>${s.body}</p><div class="actions"><button class="button small outline" data-action="x-study" data-id="${s.id}">Read summary</button><button class="button small outline" data-action="x-bookmark" data-id="${s.id}">${state.bookmarks.includes(s.id)?'Saved ✓':'Save study'}</button></div></article>`).join('')||'<div class="empty">No studies match your filters.</div>';}
function connectionsPage(){return heading('Platform','Connections','Manage linked training sources and inspect import status.')+`<div class="app-banner"><b>Demo connections</b>No account is connected here. The sample import history lets you explore the workflow without authorizing a device or service.</div><div class="two-col">${['Strava','Garmin','COROS','Oura','Ultrahuman'].map((p,i)=>panel(p,`<span class="badge ${i?'warn':'blue'}">${i?'Coming later / unavailable':'Sample connection'}</span><p class="chart-note">${i?'Explore the planned connection information; no OAuth or data transfer occurs.':'Example status: 12 imported activities, last sample sync Oct 7.'}</p><button class="button small outline" style="margin-top:16px" data-action="x-connection" data-provider="${p}">View ${p} details</button>`)).join('')}${panel('Import health',`<div class="metrics"><div class="metric"><b>12</b><small>Sample imported</small></div><div class="metric"><b>1</b><small>Needs matching</small></div><div class="metric"><b>0</b><small>Duplicates</small></div></div><button class="button small outline" style="margin-top:20px" data-action="x-import" data-id="${selected}">Inspect sample import</button>`)}</div>`;}
function settingsPage(){const p=state.profile;return heading('Account','Athlete Settings','Set training baselines, zones, and display preferences.')+panel('Baselines & training zones',`<form id="x-settings-form"><div class="form-grid">${selectField('Units','units',['Metric','Imperial'],p.units)}${field('Max heart rate','maxHr',p.maxHr,'number','min="1" max="250" required')}${field('Resting heart rate','restingHr',p.restingHr,'number','min="1" max="200" required')}${field('Lactate threshold HR','lthr',p.lthr,'number','min="1" max="250" required')}</div><button class="button" type="submit">Save settings</button><a class="button outline" href="#tools">Zone calculators</a>${sample}</form>`);}
function accountPage(){return heading('Account','Account Settings','Profile, account data, and your coaching plan.')+`<div class="two-col">${panel('Coach profile',profileForm())}${panel('Your plan',`<span class="badge blue">Coach Pro · fictional demo account</span><p class="chart-note">The real product’s closed pilot and paid-plan access are separate. No purchase or billing action occurs in this demo.</p><a class="button small outline" href="#pricing">View plan overview</a><div class="form-section"><h3>Your demo data</h3><p class="chart-note">Export your research feedback or reset the sample workspace.</p><a class="button small outline" href="#feedback">Export feedback</a><button class="button small outline" data-action="x-reset">Reset demo data</button></div>`)}</div>`;}
function notificationPage(){return heading('Account','Notifications','Choose the updates you want and review recent coaching activity.')+`<div class="two-col">${panel('Notification preferences',`<form id="x-notification-form">${[['messages','Direct messages','New athlete and coach conversations'],['comments','Workout comments','Feedback attached to a session'],['checkins','Athlete check-ins','Updates that might need a plan adjustment'],['digest','Weekly digest','A summary of coaching activity']].map(([id,t,sub])=>`<label class="toggle-row"><input type="checkbox" name="${id}" ${state.notificationPrefs[id]?'checked':''}><span><b>${t}</b><small>${sub}</small></span></label>`).join('')}<button class="button" type="submit">Save preferences</button>${sample}</form>`)}${panel('Recent notifications',[['n1','Maya sent a check-in','Schedule change requested'],['n2','Eli commented on a workout','Tempo feedback to review'],['n3','Jordan logged recovery','Higher soreness reported']].map(([id,t,p])=>`<div class="history-row"><div><h3>${t}</h3><p>${p}</p></div><button class="button small outline" data-action="x-read-notification" data-id="${id}" ${state.readNotifications.includes(id)?'disabled':''}>${state.readNotifications.includes(id)?'Read ✓':'Mark read'}</button></div>`).join(''))}</div>`;}
function pricingPage(){return heading('Help / Billing','Plans for athletes and coaches','Plan names and displayed monthly prices matched to the current product source.')+`<div class="library-grid">${[['Free','$0','Manual logs and basic training'],['Athlete Core','$7','Research and training foundations'],['Athlete Pro','$18','Training analysis and broader tools'],['Coach Essentials','$29','Roster, planning, and communication'],['Coach Pro','$79','Coach tools and advanced metrics']].map(([t,p,desc])=>`<section class="panel library-card"><div class="eyebrow">${t}</div><h2>${p}<small>per month · reference only</small></h2><p>${desc}</p><span class="badge blue">No checkout in demo</span></section>`).join('')}</div><div class="app-banner"><b>Coach billing opens after the closed pilot.</b>Approved pilot coaches use Coach Pro tools at no cost during the pilot. The demo provides fictional access for feature exploration; it does not enroll anyone.</div>`;}
function supportPage(){return heading('Help / Billing','Support','A guide to exploring this fictional coaching workspace.')+`<div class="two-col">${panel('Demo help',`<p class="chart-note">Use Navigation to reach every coaching, training, research, and account page. Saved changes affect only this browser.</p><a class="button small outline" href="#guide">Open guide</a><a class="button small outline" href="#feedback">Share your feedback</a>`)}${panel('What is simulated?',`<p class="chart-note">All athlete records, messages, check-ins, imports, and account details are fictional. Connections, invitation delivery, billing, and live research queries are not executed. Local edits, group assignments, calculations, resource saving, and feedback export work.</p>`)}</div>`;}
Object.assign(demoViews,{tools:toolsPage,groups:groupsPage,dashboard:dashboardPage,races:racesPage,'race-plan':blueprintPage,'check-in':checkinPage,'log-intervention':loggerPage,history:historyPage,progress:progressPage,explorer:explorerPage,research:researchPage,connections:connectionsPage,settings:settingsPage,account:accountPage,notifications:notificationPage,pricing:pricingPage,support:supportPage});
// Render hooks keep calculator output and mobile active states consistent after navigation.
const coreRoute=route,coreRefresh=refresh;
function afterRender(){updateTools();const hash=(location.hash.slice(1)||'overview').split('/')[0];document.querySelectorAll('.mobile-bottom a').forEach(a=>{if(a.hash===`#${hash}`)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});}
route=()=>{coreRoute();afterRender();};refresh=()=>{coreRefresh();afterRender();};
function protocolDialog(id){if(id)selected=person(id).id;showDialog('Assign protocol',`<form id="x-protocol-form">${selectField('Athlete','athlete',athletes.map(a=>[a.id,a.name]),selected)}${selectField('Protocol type','title',['Sleep consistency','Long-run fueling practice','Gut Training','Heat Acclimation','Sauna - Recovery'],'Sleep consistency')}<div class="form-grid">${field('Start date','start','2026-10-09','date','required')}${field('End date','end','2026-10-23','date','required')}${field('Compliance target (%)','target',85,'number','min="0" max="100" required')}</div>${textarea('Coach instructions','detail','','required')}<div class="actions"><button class="button outline" type="button" data-action="close">Cancel</button><button class="button" type="submit">Assign in demo</button></div>${sample}</form>`);}
function raceDialog(id){const r=state.races.find(r=>r.id===id)||{id:'',athlete:selected,name:'',date:'2026-11-01',distance:'Marathon',priority:'A'};showDialog(r.id?'Edit race':'Add a race',`<form id="x-race-form" data-id="${r.id}">${selectField('Athlete','athlete',athletes.map(a=>[a.id,a.name]),r.athlete)}${field('Race name','name',r.name,'text','required maxlength="150"')}<div class="form-grid">${field('Race date','date',r.date,'date','required')}${selectField('Distance','distance',['5K','10K','Half Marathon','Marathon','50K','100K','Other'],r.distance)}${selectField('Priority','priority',['A','B','C'],r.priority)}</div><button class="button" type="submit">Save race</button>${sample}</form>`);}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const act=b.dataset.action,id=b.dataset.id;switch(act){
  case 'site-menu':showDialog('Navigation',`<div class="menu-list">${sections.map(([label,items])=>`<section><p>${label}</p>${items.map(([p,t])=>`<a href="#${p}">${t}</a>`).join('')}</section>`).join('')}</div>`);break;
  case 'x-command-tab':commandTab=id;refresh();break;
  case 'x-depth':depth=id;refresh();break;
  case 'x-advanced-tab':advancedTab=id;refresh();break;
  case 'x-insight-tab':insightTab=id;refresh();break;
  case 'x-protocol':protocolDialog(id);break;
  case 'x-protocol-status':{const p=state.protocols[Number(b.dataset.index)];p.status=p.status==='Completed'?'In progress':'Completed';record('protocol_status');refresh();toast('Protocol status updated.');break;}
  case 'x-invite':showDialog('Invite an athlete',`<p>Create a fictional invitation preview. No email is sent and no account is created.</p><form id="x-invite-form">${field('Athlete name','name','','text','required maxlength="150"')}${field('Athlete email (demo only)','email','athlete@example.test','email','required')}<button class="button" type="submit">Create sample invitation</button></form>`);break;
  case 'x-document':showDialog('Share a document',`<form id="x-document-form">${selectField('Athlete','athlete',athletes.map(a=>[a.id,a.name]),id||selected)}${field('Title','title','','text','required maxlength="150"')}${selectField('Category','category',['General','Training','Nutrition','Recovery','Race preparation'],'General')}${textarea('Document text','body','','required')}<button class="button" type="submit">Share in demo</button>${sample}</form>`);break;
  case 'x-open-document':{const d=state.documents.find(d=>d.id===id);showDialog(esc(d.title),`<span class="badge">${esc(d.category)} · ${person(d.athlete).name}</span><p class="note-box">${esc(d.body)}</p>${sample}`);record('open_document');break;}
  case 'x-import':showDialog('TrainingPeaks import · sample report',`<p>${person(id).name} · Four fictional import records.</p><div class="history-row"><div><h3>Easy run · matched</h3><p>Duration 35 min · planned session found</p></div><span class="badge">Matched</span></div><div class="history-row"><div><h3>Tempo run · matched</h3><p>Duration 55 min · athlete comment retained</p></div><span class="badge">Matched</span></div><div class="history-row"><div><h3>Long run · matched</h3><p>Duration 100 min · no duplicate</p></div><span class="badge">Matched</span></div><div class="history-row"><div><h3>Additional easy run</h3><p>No planned session found in this sample.</p></div><span class="badge warn">Needs review</span></div><div class="actions"><a class="button small" href="#calendar">Review calendar</a></div>${sample}`);record('review_import');break;
  case 'x-group-members':{const g=state.groups.find(g=>g.id===id);showDialog('Group members',`<form id="x-member-form" data-id="${id}">${athletes.map(a=>`<label class="member-choice"><input type="checkbox" name="member" value="${a.id}" ${g.members.includes(a.id)?'checked':''}>${a.name}</label>`).join('')}<button class="button" type="submit">Save members</button></form>`);break;}
  case 'x-race':raceDialog(id);break;
  case 'x-blueprint':blueprintRace=id;location.hash='race-plan';break;
  case 'x-intervention-type':$('#x-intervention-form [name=type]').value=b.dataset.type;break;
  case 'x-research-tab':savedOnly=id==='saved';refresh();break;
  case 'x-clear-study':researchQuery='';savedOnly=false;refresh();break;
  case 'x-bookmark':if(state.bookmarks.includes(id))state.bookmarks=state.bookmarks.filter(v=>v!==id);else state.bookmarks.push(id);record('save_study');refresh();break;
  case 'x-study':{const s=studyFixtures.find(s=>s.id===id);showDialog(s.title,`<span class="badge warn">Illustrative sample entry</span><p class="note-box">${s.body}</p><p class="chart-note">This record demonstrates the product’s research reading workflow. It is not a quotation or a real published study.</p>`);record('read_study');break;}
  case 'x-connection':showDialog(`${esc(b.dataset.provider)} connection`,`<p>No ${esc(b.dataset.provider)} account is connected to this research demo. External authentication and data transfer are not available here.</p><div class="app-banner"><b>Connection workflow</b>In the product, authorized providers can supply activity data. This demo shows fictional import status and matching outcomes.</div><button class="button small outline" data-action="x-import" data-id="${selected}">View sample import report</button>`);record('connection_details');break;
  case 'x-read-notification':state.readNotifications.push(id);record('read_notification');refresh();break;
  case 'x-reset':$('#reset').click();break;
  case 'confirm-reset':addDefaults();refresh();break;
}});
document.addEventListener('submit',e=>{const form=e.target;if(!form.id.startsWith('x-')){if(form.classList.contains('tool-form'))e.preventDefault();return;}e.preventDefault();const d=Object.fromEntries(new FormData(form));const done=label=>{record(label);closeDialog();refresh();toast('Saved in the demo. Changes stay in this browser.');};switch(form.id){
  case 'x-profile-form':Object.assign(state.profile,d);done('save_profile');break;
  case 'x-settings-form':Object.assign(state.profile,d);done('save_settings');break;
  case 'x-protocol-form':if(d.end<d.start){toast('Choose an end date after the start date.');return;}state.protocols.push({...d,status:'In progress'});done('assign_protocol');break;
  case 'x-invite-form':state.invitations.push({...d,id:'inv-'+Date.now()});record('create_invitation');showDialog('Sample invitation created',`<p>${esc(d.name)} · ${esc(d.email)}</p><div class="app-banner"><b>DEMO-ALEX</b>Invitation preview only. No email was sent.</div><a class="button outline" href="#dashboard">Preview athlete entry</a>`);break;
  case 'x-document-form':state.documents.push({...d,id:'doc-'+Date.now()});done('share_document');break;
  case 'x-group-form':if(!d.name.trim())return;state.groups.push({id:'group-'+Date.now(),name:d.name.trim(),description:d.description,members:new FormData(form).getAll('member')});done('create_group');break;
  case 'x-member-form':state.groups.find(g=>g.id===form.dataset.id).members=new FormData(form).getAll('member');done('edit_group_members');break;
  case 'x-group-workout-form':{const g=state.groups.find(g=>g.id===d.group),t=library.find(t=>t.id===d.template),offset=Math.round((Date.parse(d.date+'T00:00:00Z')-Date.UTC(2026,9,5))/86400000);if(!g?.members.length){toast('Choose a group with at least one athlete.');return;}g.members.forEach((athlete,i)=>state.workouts.push({id:`group-workout-${Date.now()}-${i}`,athlete,week:Math.floor(offset/7),day:((offset%7)+7)%7,title:t.title,type:t.type,duration:t.duration,description:t.description,done:false}));done('group_workout');break;}
  case 'x-group-protocol-form':{const g=state.groups.find(g=>g.id===d.group);if(!g?.members.length){toast('Choose a group with at least one athlete.');return;}if(d.end<d.start){toast('Choose an end date after the start date.');return;}g.members.forEach(athlete=>state.protocols.push({athlete,title:d.title,start:d.start,end:d.end,target:85,status:'In progress',detail:'Sample group assignment. Discuss the protocol details with your coach.'}));done('group_protocol');break;}
  case 'x-race-form':{const existing=state.races.find(r=>r.id===form.dataset.id);if(existing)Object.assign(existing,d);else state.races.push({...d,id:'race-'+Date.now(),strategy:''});done('save_race');break;}
  case 'x-blueprint-form':Object.assign(state.races.find(r=>r.id===form.dataset.id),{strategy:d.strategy,time:d.time,equipment:d.equipment});done('save_blueprint');break;
  case 'x-intervention-form':state.interventions.push({...d,id:'intervention-'+Date.now()});record('log_intervention');location.hash='history';toast('Intervention saved to sample history.');break;
  case 'x-checkin-form':state.checkins[d.athlete]=d;done('daily_checkin');break;
  case 'x-notification-form':for(const k of Object.keys(state.notificationPrefs))state.notificationPrefs[k]=form.elements[k].checked;done('notification_preferences');break;
  case 'x-explorer-form':$('#explorer-result').innerHTML=`<h3>${esc(d.intervention)} × ${esc(d.outcome)}</h3><p class="chart-note">Six fictional observations for this comparison. No causal conclusion can be drawn from sample data.</p>${chart(person('eli'))}`;record('explore_data');break;
}});
document.addEventListener('input',e=>{if(e.target.closest('.tool-form'))updateTools();if(e.target.id==='study-search'){researchQuery=e.target.value;$('#study-list').innerHTML=studyRows(studyFixtures.filter(s=>(!savedOnly||state.bookmarks.includes(s.id))&&`${s.title} ${s.topic} ${s.sport}`.toLowerCase().includes(researchQuery.toLowerCase())));}});
document.addEventListener('change',e=>{if(e.target.closest('.tool-form'))updateTools();if(e.target.form?.id==='x-blueprint-form'&&e.target.name==='race'){blueprintRace=e.target.value;refresh();}if(e.target.form?.id==='x-checkin-form'&&e.target.name==='athlete'){selected=e.target.value;refresh();}});
document.body.insertAdjacentHTML('beforeend','<a class="floating-message" href="#messages">Coach Messages ↗</a>');
