insert into public.research_library_entries (
  pubmed_id,
  title,
  authors,
  journal,
  publication_year,
  pubmed_url,
  topic_tags,
  plain_english_summary,
  practical_takeaway,
  commentary,
  ultra_score,
  gravel_score,
  triathlon_score,
  published
)
values
  (
    '39405022',
    'Decoding Ultramarathon: Muscle Damage as the Main Impediment to Performance.',
    'Tiller NB, Millet GY',
    'Sports medicine',
    2024,
    'https://pubmed.ncbi.nlm.nih.gov/39405022/',
    array['Recovery', 'Injury Prevention'],
    'In long ultramarathons, accumulated muscle damage and the fatigue it causes are more performance-limiting than aerobic capacity, running economy, or GI distress. The athlete who can tolerate eccentric loading and downhill pounding over many hours will hold pace better than the one with a bigger engine but fragile quads.',
    'Build eccentric tolerance with progressive downhill running in training. If the target race has significant vert, the ability to absorb descents late in the race is trainable and should not be left to chance.',
    'This reframes ultra performance: the limiter is often durability, not fitness. Strong relevance for mountain ultras and any race with heavy cumulative descent.',
    5,
    3,
    3,
    true
  ),
  (
    '40239961',
    'Total Energy Expenditure and Intake During a 161-km Mountain Ultramarathon.',
    'Creer AR, Kelly MR, Rosales AM, Levanger MT, Hart DR, Schoeller DA, Shriver TC, Thomas JV, Ruby BC',
    'International journal of sports physiology and performance',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40239961/',
    array['Fueling & Nutrition'],
    'Using doubly labeled water, two runners at a 161-km ultramarathon burned roughly 15,800 kcal during the race and managed to take in only about half of that. The energy deficit carried into a full week of suppressed recovery afterward, showing that the fueling gap in ultras is not just a race-day problem.',
    'Plan post-race nutrition as deliberately as race-day fueling. If the athlete only replaces half the energy cost during the event, the recovery window after is where the real debt gets paid down or compounded.',
    'Rare doubly-labeled-water data at this distance. Useful reality check for anyone building a 100-mile fueling plan.',
    5,
    3,
    3,
    true
  ),
  (
    '41615405',
    'Kidney injury risk during prolonged endurance running: lessons from the field.',
    'McKenna ZJ, Atkins WC, Babcock MC, Grosicki GJ, Linder BA, McDermott BP, Robinson AT',
    'Journal of applied physiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41615405/',
    array['Hydration', 'Recovery'],
    'Marathon and ultramarathon runners commonly show post-race spikes in kidney injury biomarkers. Most resolve on their own, but dehydration, heat, muscle damage, and NSAID use can push transient stress toward real clinical risk. The combination of multiple stressors at once is what makes it dangerous.',
    'Avoid stacking NSAIDs with dehydration and heat on race day. If an athlete is running hot, underfueling fluids, and popping ibuprofen, they are loading three kidney stressors at once.',
    'Practical field-based review. Especially relevant for hot-weather ultras and any athlete who reaches for painkillers mid-race.',
    5,
    2,
    3,
    true
  ),
  (
    '40087377',
    'Pacing in ultra-marathon running: the Western States 100-mile endurance run 2006-2023.',
    'Markovic S, Cuk I, Nikolaidis PT, Weiss K, Rosemann T, Scheer V, Thuany M, Knechtle B',
    'Scientific reports',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40087377/',
    array['Pacing'],
    'Pacing at the Western States 100 is heavily shaped by terrain, not just fatigue. Men start faster and slow down more; women pace more evenly. Both the fastest and slowest runners had less variability in pace than mid-pack runners, suggesting that both discipline and sheer exhaustion can flatten the pace curve.',
    'Pacing plans for trail ultras should be terrain-based, not purely time-based. Build checkpoint targets around elevation and heat exposure windows rather than even splits.',
    'Large dataset (3800+ runners, 18 years). The finding that mid-pack runners have the most variability suggests they are the ones most likely to benefit from a tighter plan.',
    5,
    3,
    3,
    true
  ),
  (
    '41757674',
    'Post-exercise ketone supplementation improves endurance performance and mitochondrial adaptations during an 8-week endurance training intervention.',
    'Robberechts R, Bekhuis Y, Stalmans M, Lauriks W, Kusters M, Taha K, Rosseel T, Claessen G, Poffe C',
    'The Journal of physiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41757674/',
    array['Supplementation', 'Fueling & Nutrition'],
    'Taking a ketone ester after training and before sleep over 8 weeks of periodized cycling improved 30-min time trial performance by about 4% compared to placebo. The gain came from better mitochondrial adaptations, not cardiac changes, meaning the muscles got more efficient at using oxygen.',
    'If ketone esters are accessible, post-workout and pre-sleep dosing may amplify training adaptations over a build block. This is not a race-day fueling play; it is a recovery and adaptation play.',
    'Strong controlled design. The practical barrier is cost, but for athletes in a targeted build phase this is one of the cleaner ketone findings to date.',
    4,
    5,
    5,
    true
  ),
  (
    '41374083',
    'Effects of Caffeine Dose and Administration Method on Time-Trial Performance: A Systematic Review and Network Meta-Analysis.',
    'Xue R, Huang J, Chen B, Ding L, Guo L, Cao Y, Girard O',
    'Nutrients',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/41374083/',
    array['Supplementation'],
    'A meta-analysis of 48 studies found that low-dose caffeine capsules (around 3 mg/kg) were the most effective form for time-trial performance, beating higher doses and alternative delivery methods like gum or mouth rinse. More caffeine is not necessarily better, and the delivery method matters.',
    'Start with ~3 mg/kg in capsule form and validate in training before racing. Higher doses add GI risk without proportional benefit for most athletes.',
    'Useful for dialing in caffeine strategy. The finding that low dose beats moderate dose challenges the more-is-better instinct many athletes have.',
    4,
    5,
    5,
    true
  ),
  (
    '41685663',
    'A comprehensive review of the physiology and evidence base to guide the use of ergogenic and medical supplements for enhanced cycling performance.',
    'Rowland A, Edwards S, Prieto-Bellver G, Menz B, Rowland A, Cornelisse E, Karapetis CS, Wallen MP, Hopkins AM',
    'Journal of the International Society of Sports Nutrition',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41685663/',
    array['Supplementation', 'Fueling & Nutrition'],
    'This review maps every major cycling supplement to the energy system it supports. Beta-alanine, caffeine, creatine, nitrates, sodium bicarbonate, and ketones each work through different metabolic pathways. The practical value is knowing which ones match the demands of a specific event or session type.',
    'Match supplements to the session: caffeine and carbs for long steady efforts, beta-alanine and bicarb for surge-heavy racing, nitrates for sustained threshold work. Do not stack everything for every ride.',
    'Useful reference for building a targeted supplement protocol for gravel and endurance cycling. Pairs well with metabolic testing data.',
    3,
    5,
    4,
    true
  ),
  (
    '40360152',
    'Use of Heart-Rate Variability to Examine Readiness to Perform in Response to Overload and Taper in Swimmers.',
    'Bulte KR, Bruce L, Hammond K, Corrigan SL, Main LC',
    'International journal of sports physiology and performance',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40360152/',
    array['HRV', 'Taper'],
    'In elite swimmers, the ratio of parasympathetic modulation to parasympathetic tone (rMSSD/AVNN) was more sensitive to training phase changes than either metric alone. Athletes who tapered well showed high parasympathetic activity early in taper followed by a sympathetic shift before competition.',
    'If using HRV to guide a taper, watch the ratio metrics rather than raw rMSSD alone. A shift from parasympathetic dominance toward more balanced autonomic tone heading into race week may signal readiness.',
    'Extends HRV monitoring beyond the simple green/yellow/red readiness model. Applicable to any endurance sport with a structured taper.',
    4,
    4,
    5,
    true
  ),
  (
    '39259398',
    'Orthostatic testing for heart rate and heart rate variability monitoring in exercise science and practice.',
    'Gronwald T, Schaffarczyk M, Hoos O',
    'European journal of applied physiology',
    2024,
    'https://pubmed.ncbi.nlm.nih.gov/39259398/',
    array['HRV', 'Recovery'],
    'Standing up from lying down creates a controlled autonomic challenge that reveals information a resting HRV reading alone can miss. In overtrained endurance athletes, both the parasympathetic and sympathetic responses to standing are blunted, which may be one of the earliest detectable signs of accumulated overload.',
    'Add a simple lying-to-standing HRV test to the morning routine. Track the magnitude of the HR and HRV shift on standing over time; a flattening response may flag overreaching before performance drops.',
    'Practical addition to any HRV monitoring protocol. Especially useful for athletes whose resting HRV has hit a parasympathetic ceiling.',
    4,
    4,
    4,
    true
  ),
  (
    '41934470',
    'Heat training augments hemoglobin mass during a moderate-altitude training camp in well-trained endurance athletes.',
    'Ronnestad BR, Urianstad Odden T, Blindheim PM, Hansen J, Hamarsland H, Ellefsen S, Urianstad Odden I, Molmen KS',
    'Journal of applied physiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41934470/',
    array['Heat Acclimation', 'Altitude'],
    'Adding three weekly heat-suit cycling sessions to a moderate-altitude camp (1,865 m) nearly tripled the hemoglobin mass gain compared to altitude alone. This means athletes who cannot access high altitude can still get meaningful hematological adaptations by combining moderate elevation with heat stress.',
    'If the altitude camp is moderate (under 2,000 m), layer in heat sessions to amplify the blood response. Three sessions per week of heat-suit cycling during the camp was enough to make a measurable difference.',
    'Solves a real logistics problem: most accessible altitude camps are too low for big hematological gains. Heat is the multiplier.',
    5,
    4,
    4,
    true
  ),
  (
    '41280657',
    'Exercise-Associated Hyponatremia: Serum Sodium, Symptomatology, Severity, and Sport Specificity.',
    'Armstrong LE, McDermott BP, Young SL, Casa DJ',
    'Open access journal of sports medicine',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/41280657/',
    array['Hydration'],
    'Hyponatremia risk varies dramatically by sport: running and hiking produce far more cases than cycling, swimming, or triathlon. The absolute sodium level is not a reliable predictor of severity, and no asymptomatic cases were found below 130 mmol/L, meaning even mildly low values with symptoms deserve attention.',
    'Educate athletes that overdrinking is as dangerous as underdrinking. In long events, drink to thirst rather than forcing a schedule, and recognize that nausea, confusion, and swelling may signal low sodium, not dehydration.',
    'Critical safety review for race medical planning and athlete education. Running and hiking events need the most vigilance.',
    5,
    3,
    4,
    true
  ),
  (
    '39345935',
    'Hyperthermia and Exertional Heatstroke During Running, Cycling, Open Water Swimming, and Triathlon Events.',
    'Armstrong LE, Johnson EC, Adams WM, Jardine JF',
    'Open access journal of sports medicine',
    2024,
    'https://pubmed.ncbi.nlm.nih.gov/39345935/',
    array['Heat Acclimation', 'Hydration'],
    'Heatstroke risk is not the same across endurance sports. Running and triathlon events account for the vast majority of cases because the cooling mechanisms differ: cyclists get airflow, swimmers get conduction, but runners rely almost entirely on evaporation, which fails in humidity.',
    'For hot-weather races, plan cooling strategy by sport. Runners need ice, dousing, and shade. Cyclists benefit from speed-generated airflow. Recognize that the run leg of a triathlon is where heat risk spikes hardest.',
    'Bridges multiple endurance sports in one review. Useful for coaches managing athletes across running, cycling, and triathlon in summer.',
    5,
    4,
    5,
    true
  ),
  (
    '42056382',
    'Pacing profiles and slowdown patterns in ultra-triathlon performance.',
    'Markovic S, Cuk I, Duric S, Forte P, Leite LB, Andrade MS, Nikolaidis PT, Weiss K, Rosemann T, Knechtle B',
    'Scientific reports',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42056382/',
    array['Pacing'],
    'In a Double Deca Iron ultra-triathlon (76 km swim, 3600 km bike, 844 km run), the best performers held a steady fast baseline and accepted occasional deep slowdowns rather than pacing conservatively the entire time. This suggests that strategic rest-then-resume may outperform constant moderation in extreme events.',
    'In very long events, plan for deliberate slowdowns or pauses rather than trying to hold a perfectly even effort. The top performers slow down hard when they need to, then return to a strong baseline, rather than drifting into a permanently slower pace.',
    'Extreme event, but the pacing principle scales: protect the baseline pace and allow controlled drops rather than grinding into a death spiral.',
    4,
    3,
    5,
    true
  ),
  (
    '41366823',
    'Subjective Assessment of Physical and Mental Fatigue Does Not Predict Objective Decline of Cognitive Functions After Ultra-Endurance Race (Veloreality).',
    'Lismane D, Vilite D, Raudeniece J, Laizane L, Gersone G, Barone I, Justamente I, Kovtuna K, Vanags E, Roelands B, Zolovs M, Reihmane D',
    'European journal of sport science',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41366823/',
    array['Sleep', 'Recovery'],
    'After an ultra-endurance cycling race, athletes showed measurable cognitive decline in reaction time and fine motor control, but their self-reported fatigue did not predict which cognitive functions actually dropped. In other words, how tired you feel is a poor guide to how impaired you actually are.',
    'Do not rely on how an athlete feels to judge cognitive readiness after a long event. Build in mandatory rest and avoid critical decisions (driving, technical descents) in the hours after finishing, even if the athlete says they feel fine.',
    'Direct relevance for ultra cyclists and any event where post-race decisions (driving home, navigating) carry real safety consequences.',
    5,
    5,
    3,
    true
  ),
  (
    '35878109',
    'Resistance Exercise for Improving Running Economy and Running Biomechanics and Decreasing Running-Related Injury Risk: A Narrative Review.',
    'Suc A, Sarko P, Plesa J, Kozinc Z',
    'Sports',
    2022,
    'https://pubmed.ncbi.nlm.nih.gov/35878109/',
    array['Strength Training', 'Running Economy', 'Injury Prevention'],
    'Lower-body resistance training improves running economy and may reduce injury risk. A combination of heavy strength work and plyometrics appears most effective, and isometric training is emerging as an option during high-volume phases when overall training load needs to be managed.',
    'Include at least two days of lower-body strength plus plyometrics per week during base phases. During peak volume, consider switching to isometrics to maintain strength stimulus without adding too much fatigue.',
    'Foundational review for any running-based endurance athlete. The isometric finding is particularly useful for managing training load in a big build.',
    5,
    3,
    4,
    true
  ),
  (
    '40507114',
    'Triathlon: Ergo Nutrition for Training, Competing, and Recovering.',
    'Miguel-Ortega A, Rodriguez-Rodrigo MA, Mielgo-Ayuso J, Calleja-Gonzalez J',
    'Nutrients',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40507114/',
    array['Fueling & Nutrition', 'Recovery'],
    'Triathletes face unique nutritional challenges because three disciplines with different fueling demands are stacked together. The review highlights that glycogen management across swim-bike-run transitions, RED-S risk from chronic energy deficits, and post-exercise protein timing are the highest-leverage nutrition targets.',
    'Periodize carbohydrate intake around the dominant training discipline of each day. Prioritize post-session protein within the transition window between disciplines, and screen for RED-S symptoms if chronic fatigue or hormonal disruption appears.',
    'Triathlon-specific nutrition review covering training and racing. Useful for athletes juggling three-sport fueling without a clear framework.',
    3,
    3,
    5,
    true
  ),
  (
    '31699159',
    'International Society of Sports Nutrition Position Stand: nutritional considerations for single-stage ultra-marathon training and racing.',
    'Tiller NB, Roberts JD, Beasley L, Chapman S, Pinto JM, Smith L, Wiffin M, Russell M, Sparks SA, Duckworth L, O''Hara J, Sutton L, Antonio J, et al.',
    'Journal of the International Society of Sports Nutrition',
    2019,
    'https://pubmed.ncbi.nlm.nih.gov/31699159/',
    array['Fueling & Nutrition', 'Hydration'],
    'The ISSN position stand on ultra-marathon nutrition recommends 150-400 kcal/hr during racing with a mix of carbs and protein, fluid intake of 450-750 mL/hr, and sodium concentrations above what most commercial products provide. It also supports gut training, strategic caffeine use late in races, and cautions that ketogenic approaches lack strong evidence for ultras.',
    'Use these ranges as starting guardrails: 30-50 g carbs/hr plus 5-10 g protein/hr, and train the gut to tolerate race-day intake over several weeks. Adjust sodium concentration upward in heat, and save caffeine for the back half of the race.',
    'The reference document for ultra-marathon nutrition planning. Coaches should use these ranges as a starting point and individualize from there.',
    5,
    4,
    3,
    true
  ),
  (
    '39786965',
    'Carbohydrate ingestion eliminates hypoglycemia and improves endurance exercise performance in triathletes adapted to very low- and high-carbohydrate isocaloric diets.',
    'Prins PJ, Noakes TD, Buga A, Gerhart HD, Cobb BM, D''Agostino DP, Volek JS, Buxton JD, Heckman K, Plank E, DiStefano S, et al.',
    'American journal of physiology. Cell physiology',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/39786965/',
    array['Carbohydrate Loading', 'Fueling & Nutrition'],
    'Triathletes on both low-carb and high-carb diets performed equally in time-to-exhaustion tests. The key finding: even minimal carbohydrate supplementation (just 10 g/hr) during exercise prevented hypoglycemia and improved performance by 22% on both diets. The diet itself mattered less than having some carbs available during the effort.',
    'Regardless of base diet philosophy, take in at least some carbohydrate during long efforts. Even a small amount prevents the blood sugar crash that cuts performance. Four weeks is the minimum adaptation window for a low-carb approach.',
    'Bridges the low-carb vs. high-carb debate with a practical answer: fuel during exercise either way. Relevant for athletes experimenting with dietary approaches.',
    4,
    4,
    5,
    true
  ),
  (
    '41845944',
    'A Review of Central and Peripheral Limitations to Endurance Exercise Performance on the Road to the Milano-Cortina 2026 Olympics.',
    'Skattebo O, Martin-Rincon M, Calbet JAL, Hallen J, Holmberg HC',
    'Scandinavian journal of medicine & science in sports',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41845944/',
    array['VO2max', 'Lactate Threshold'],
    'VO2max is primarily limited by oxygen delivery (cardiac output times arterial O2 content), but elite endurance athletes can extract over 95% of delivered oxygen at the muscle level. In sports with variable terrain like cross-country skiing and trail running, athletes routinely hit 100-160% of VO2max on climbs, relying on anaerobic reserves that must be recharged on descents.',
    'Train the ability to go above VO2max on climbs and recover on descents. For hilly races, the anaerobic recovery capacity between surges may matter more than the absolute VO2max ceiling.',
    'High-level physiology review with direct application to trail running, gravel racing, and any undulating course. The surge-and-recover model is key.',
    4,
    4,
    4,
    true
  ),
  (
    '36940222',
    'Short Severe Energy Restriction with Refueling Reduces Body Mass without Altering Training-Associated Performance Improvement.',
    'Burke LM, Whitfield J, Ross MLR, Tee N, Sharma AP, King AJ, Heikura IA, Morabito A, McKay AKA',
    'Medicine and science in sports and exercise',
    2023,
    'https://pubmed.ncbi.nlm.nih.gov/36940222/',
    array['Fueling & Nutrition', 'Taper'],
    'Elite race walkers who cut calories sharply for 9 days (to 15 kcal/kg FFM/day) during intensified training lost 2 kg of body mass, mostly fat, without losing the performance gains from the training block. The stress was high but brief enough that refueling afterward preserved the adaptation.',
    'Short, aggressive energy restriction may be a viable tool for making race weight if it is tightly time-boxed and followed by deliberate refueling. It should not be a chronic approach; the benefit came from brevity and precision.',
    'Burke et al. at AIS. Applicable for weight-sensitive endurance events like mountain ultras and hilly gravel races where power-to-weight matters. Use with care and coaching oversight.',
    4,
    4,
    3,
    true
  )
on conflict (pubmed_id) do update
set
  title = excluded.title,
  authors = excluded.authors,
  journal = excluded.journal,
  publication_year = excluded.publication_year,
  pubmed_url = excluded.pubmed_url,
  topic_tags = excluded.topic_tags,
  plain_english_summary = excluded.plain_english_summary,
  practical_takeaway = excluded.practical_takeaway,
  commentary = excluded.commentary,
  ultra_score = excluded.ultra_score,
  gravel_score = excluded.gravel_score,
  triathlon_score = excluded.triathlon_score,
  published = excluded.published,
  updated_at = now();
