insert into public.research_library_entries (
  pubmed_id,
  title,
  authors,
  journal,
  publication_year,
  pubmed_url,
  topic_tags,
  plain_english_summary,
  practical_takeaway,
  commentary,
  ultra_score,
  gravel_score,
  triathlon_score,
  published
)
values
  (
    '42066739',
    'Advanced adenomas among young endurance runners: A prospective hypothesis-generating prevalence study.',
    'Swain WR, Bonomelli S, Johnston L, Kaltman R, Cannon TL',
    'Cancer epidemiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42066739/',
    array['GI Health', 'Endurance Risk'],
    'In a group of 94 endurance runners aged 35-50 who had completed multiple ultramarathons or marathons, 15% had advanced adenomas on colonoscopy — well above the 1.2% historical rate for average-risk adults in the same age window. Most lesions were right-sided. The study is hypothesis-generating and cannot prove causation, but the signal is large enough to warrant attention.',
    'If you are a long-term endurance runner in your mid-30s to 50s, this study suggests discussing earlier colorectal screening with your doctor rather than waiting for the standard age-50 guideline. Recurrent GI stress from racing may carry downstream risk.',
    'An uncomfortable finding that deserves honest discussion in the endurance community. The sample is small but prospective and well-controlled.',
    5,
    3,
    4,
    true
  ),
  (
    '42056382',
    'Pacing profiles and slowdown patterns in ultra-triathlon performance.',
    'Markovic S, Cuk I, Duric S, Forte P, Knechtle B',
    'Scientific reports',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42056382/',
    array['Pacing', 'Ultra-Endurance'],
    'In a Double Deca Iron ultra-triathlon (76 km swim, 3600 km bike, 844 km run), the faster finishers maintained a relatively steady high baseline pace punctuated by occasional large slowdowns, rather than moving continuously at a slower and more variable pace. Swimming showed negative pacing while cycling and running were even or slightly positive.',
    'In ultra-distance events, aim to hold a fast sustainable baseline and accept occasional deep rest stops rather than trying to stay perfectly even. The best performers let themselves slow dramatically when needed rather than drifting into a permanently compromised pace.',
    'Fascinating data from one of the most extreme multi-sport formats in existence. The rest-spike pattern aligns with what experienced ultra athletes already practice intuitively.',
    5,
    3,
    5,
    true
  ),
  (
    '42051517',
    '(Ultra-)inflammation or adaptation? Comparison of different ultramarathon distances and their effect on the immune system.',
    'Bizjak DA, John L, Munk M, Bizjak R, Grau M',
    'Frontiers in immunology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42051517/',
    array['Immune System', 'Recovery'],
    'Comparing 100 km, 160.9 km, and 230 km ultramarathon runners, this study found that each distance produces a distinct inflammatory and immune profile. The 100 km distance (faster pace, shorter time) and the 230 km (slower pace, much longer time) triggered the strongest but different immune responses. Broad generalizations about immune impact from a single ultramarathon distance are not warranted.',
    'Recovery protocols should be distance-specific. A 100K race hammers the immune system differently than a 200+ miler. Do not assume the same post-race recovery timeline applies to all ultra distances.',
    'Useful evidence against the one-size-fits-all recovery template. Coaches should adjust the post-race return-to-training window based on actual race demands.',
    5,
    2,
    3,
    true
  ),
  (
    '41978086',
    'Digestive Vulnerability and Exercise Exposure as Correlates of Gastrointestinal Symptoms and Race Withdrawal in Endurance and Ultra-Endurance Athletes.',
    'Mauvieux B, Mahon E, Markov A, Pugh J, Edwards BJ',
    'Nutrients',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41978086/',
    array['GI Health', 'Fueling & Nutrition'],
    'Athletes who experience GI symptoms during training are nearly 4x more likely to have them during competition, and those competing in events lasting 6+ hours have over 2x the odds of GI-related withdrawal. After adjusting for digestive vulnerability and exercise duration, no single nutritional item was independently linked to GI outcomes — the athlete''s baseline gut sensitivity and cumulative race exposure mattered most.',
    'If you consistently get GI distress in training, address the vulnerability itself before blaming race-day nutrition choices. The gut''s baseline tolerance is a bigger predictor of race-day problems than any specific food or drink.',
    'Shifts the GI conversation from "what did you eat" to "how does your gut handle stress in the first place." Important reframe for athletes who keep tweaking nutrition without addressing underlying sensitivity.',
    5,
    4,
    4,
    true
  ),
  (
    '41847782',
    'Anomalous Perceptual Experience During Ultra-Endurance Sport: A Systematic Review.',
    'Davidson EE, Davidson SL, Glue P',
    'Wilderness & environmental medicine',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41847782/',
    array['Sleep', 'Mental Performance'],
    'Visual and auditory hallucinations, sensed presences, and somatic distortions are commonly reported in ultra-endurance events lasting 24+ hours, especially in darkness and after sleep deprivation. These are transient, nonpathological phenomena — no long-term psychiatric effects were found. Sleep deprivation was the most consistent trigger.',
    'If you are crewing or racing a 24h+ event, expect perceptual anomalies as a normal response to extreme stress and sleep loss, not a medical emergency. Build sleep and low-light management into your race plan to delay onset.',
    'Validates what experienced ultra crews already know: hallucinations are part of the territory, not a sign something is clinically wrong. Normalizing this helps athletes and crews respond calmly.',
    5,
    2,
    2,
    true
  ),
  (
    '41569815',
    'UCI Sports Nutrition Project: Nutrition for the Emerging Cycling Disciplines of Esports and Gravel.',
    'Whitfield J, Mujika I, Burke LM',
    'International journal of sport nutrition and exercise metabolism',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41569815/',
    array['Fueling & Nutrition', 'Gravel Cycling'],
    'This UCI-commissioned review addresses the unique nutritional challenges of gravel racing: limited and unpredictable feeding opportunities, rough terrain that makes eating and drinking harder, and a wide range of event durations. Supplements like caffeine, creatine, and glycerol may enhance performance when used according to evidence-based protocols.',
    'Plan gravel-race nutrition around when you can actually eat — smooth road sections, transitions, neutral feed zones — not around a fixed hourly target. Carry enough to be self-sufficient because aid stations are not guaranteed.',
    'First peer-reviewed nutrition guidance specifically addressing gravel racing. Essential reading for anyone racing events like Unbound, BWR, or SBT GRVL.',
    3,
    5,
    3,
    true
  ),
  (
    '41280657',
    'Exercise-Associated Hyponatremia: Serum Sodium, Symptomatology, Severity, and Sport Specificity.',
    'Armstrong LE, McDermott BP, Young SL, Casa DJ',
    'Open access journal of sports medicine',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/41280657/',
    array['Hydration', 'Endurance Risk'],
    'This comprehensive review of 220 exercise-associated hyponatremia cases across seven outdoor sports found that running and hiking produce far more cases than cycling, swimming, or triathlon. All cases below 130 mmol/L sodium were symptomatic. The absolute sodium number alone does not reliably predict severity — clinical presentation matters more.',
    'Do not rely on drinking to thirst alone in multi-hour events without also managing sodium intake. Learn the early signs of hyponatremia (nausea, weakness, dizziness, headache) and distinguish them from simple dehydration.',
    'Reinforces that overhydration without sodium is more dangerous than mild dehydration. Essential safety knowledge for race directors and medical crews.',
    5,
    4,
    4,
    true
  ),
  (
    '40507114',
    'Triathlon: Ergo Nutrition for Training, Competing, and Recovering.',
    'Miguel-Ortega A, Rodriguez-Rodrigo MA, Mielgo-Ayuso J, Calleja-Gonzalez J',
    'Nutrients',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40507114/',
    array['Fueling & Nutrition', 'Triathlon'],
    'A thorough review of nutritional strategies for triathlon training, competition, and recovery. Key takeaways: glycogen management is central to triathlon performance, triathletes (especially women) are at high risk of RED-S, carbohydrate loading and in-race hydration strategies are critical, and probiotics and targeted supplements may aid recovery.',
    'Treat each triathlon discipline''s nutrition needs separately — swimming limits intake, cycling is the primary fueling window, and running demands a gut that has already been trained. Plan the caloric load across all three legs, not just the bike.',
    'Good foundation reference for triathletes of all distances building a nutrition plan from scratch.',
    3,
    3,
    5,
    true
  ),
  (
    '42142183',
    'A speed-oriented phenotype is beneficial for 1500 m rowing at the Los Angeles 2028 Olympic Games.',
    'Baumann E, van der Vorst EMC, Hofmijster MJ',
    'European journal of applied physiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42142183/',
    array['Rowing', 'Training Methodology'],
    'With the 2028 Olympics shortening the rowing course from 2000 m to 1500 m, this study found that athletes with a more speed-oriented locomotor profile (higher power reserve ratio) performed relatively better over the shorter distance. Aerobic capacity remains essential, but explosive and anaerobic qualities gain importance.',
    'If you are a rower preparing for the new 1500 m format, emphasize anaerobic and explosive training alongside your aerobic base. The shortened distance rewards athletes who can sustain a higher percentage of their peak power.',
    'Timely research as the rowing community adapts to the LA 2028 format change. Relevant for any endurance athlete navigating a shift toward shorter, more intense racing.',
    2,
    2,
    3,
    true
  ),
  (
    '41926638',
    'Effects of glucose ingestion on blood flow in the small intestine and exercising limbs during endurance exercise.',
    'Endo MY, Kashima H, Miura A, Fukuba Y',
    'Journal of applied physiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41926638/',
    array['Fueling & Nutrition', 'Physiology'],
    'When athletes consumed glucose during high-intensity exercise, blood flow to the small intestine increased while blood flow to the working legs decreased — with no increase in cardiac output. The body redistributes existing blood supply from muscles to the gut for digestion, creating a direct competition for circulatory resources.',
    'Time your fuel intake for lower-intensity windows during a race when the circulatory tradeoff is smaller. Consuming a large bolus of carbohydrate during a hard effort literally steals blood from your working muscles.',
    'Elegant physiology study that explains why athletes sometimes feel a sudden performance dip right after eating during a race. The mechanism is circulatory redistribution, not just stomach fullness.',
    5,
    5,
    5,
    true
  ),
  (
    '41564305',
    'Prolonged stable hypothermia during a 10-hour cold open-water marathon swim.',
    'Roxburgh BH, Edgar DT, Cotter JD',
    'Experimental physiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41564305/',
    array['Open Water Swimming', 'Thermoregulation'],
    'A 52-year-old swimmer completed a 37 km crossing of New Zealand''s Foveaux Strait in ~10 hours in 13-14°C water with no wetsuit. Core temperature dropped below 35°C within 50 minutes and he remained hypothermic for over 6 hours — yet showed no cognitive or motor impairment and completed the swim unaided.',
    'Cold-adapted endurance swimmers can sustain prolonged hypothermia without performance collapse. For open-water athletes and crews, this shows that a low core temperature alone is not necessarily an emergency if the swimmer is lucid, moving well, and experienced in cold water.',
    'A remarkable case of human thermoregulatory tolerance. Challenges the automatic assumption that hypothermia equals incapacity in cold-adapted individuals.',
    3,
    1,
    4,
    true
  ),
  (
    '41868981',
    'Case Report: Stage-by-stage fueling, glucose dynamics, and next-day metabolism and biomarker responses after baseline testing in an 18.5-hour Swedish classic tetrathlon.',
    'Trinh J, Edin F, Andersson-Hall U, Pettersson S',
    'Frontiers in sports and active living',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41868981/',
    array['Fueling & Nutrition', 'Multi-Sport'],
    'An amateur athlete completed a Swedish Classic tetrathlon (316 km cycling, 3 km swimming, 84 km roller-skiing, 30 km trail running) in 18.5 hours. Total intake was 5825 kcal with 1051g carbohydrate. Continuous glucose monitoring showed stable blood sugar across most stages, with hypoglycemia only during the final run. The next day showed reduced carb oxidation and increased fat oxidation.',
    'Discipline-specific feeding windows — not generic hourly targets — determine how much fuel you can actually get in during a multi-sport ultra event. Plan intake around logistics: when can you actually eat, not just when you should eat.',
    'One of the first studies integrating CGM with weighed nutrition in a real multi-discipline ultra event. The logistics-aware fueling approach is highly practical.',
    5,
    4,
    5,
    true
  ),
  (
    '41672054',
    'Seasonal Changes in Performance, Physiological, and Kinematic Factors of Maximal Incremental Swimming in Elite Open-Water Swimmers.',
    'Lopez-Belmonte O, Ruiz-Navarro JJ, Baldassarre R, Piacentini MF',
    'International journal of sports physiology and performance',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41672054/',
    array['Open Water Swimming', 'Training Methodology'],
    'Across four seasonal time points, elite open-water swimmers maintained stable performance and physiological markers. However, stroke technique (length and index) changed across seasons in males, while females showed no kinematic changes. Maximum speed was associated with threshold speed and stroke mechanics.',
    'For open-water swimmers, monitoring stroke kinematics across the season can reveal technique drift that lab tests miss. Stable VO2 does not mean stable swimming — the mechanics may be shifting underneath.',
    'Highlights the importance of stroke monitoring as a training tool beyond just fitness testing, especially for male swimmers whose technique appears more variable across training phases.',
    2,
    1,
    4,
    true
  ),
  (
    '41685663',
    'A comprehensive review of the physiology and evidence base to guide the use of ergogenic and medical supplements for enhanced cycling performance.',
    'Rowland A, Edwards S, Prieto-Bellver G, Hopkins AM',
    'Journal of the International Society of Sports Nutrition',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41685663/',
    array['Supplementation', 'Cycling'],
    'This comprehensive review covers both ergogenic supplements (beta-alanine, caffeine, carbs, creatine, nitrates, ketones, sodium bicarbonate) and medical supplements (iron, vitamin D, omega-3, collagen, probiotics) for cycling performance. Strongest evidence supports AIS Group A compounds. Individualized strategies based on metabolic testing are recommended.',
    'Start with the proven basics — caffeine, carbohydrates, sodium bicarbonate, and nitrates — before exploring more novel supplements. Use metabolic testing to identify which energy systems you most need to support.',
    'An excellent single-source reference for any endurance cyclist building a supplementation protocol. Well-organized by evidence tier.',
    3,
    5,
    4,
    true
  ),
  (
    '41374083',
    'Effects of Caffeine Dose and Administration Method on Time-Trial Performance: A Systematic Review and Network Meta-Analysis.',
    'Xue R, Huang J, Chen B, Girard O',
    'Nutrients',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/41374083/',
    array['Caffeine', 'Supplementation'],
    'Across 48 studies with 612 participants, low-dose caffeine capsules (~3 mg/kg) were the most effective strategy for improving time-trial performance, outperforming moderate doses and caffeine gum. Moderate-dose capsules and gum were viable alternatives. Individual variability persists, so testing is essential.',
    'Less caffeine may be more effective than you think. Try 3 mg/kg in capsule form (about 200 mg for a 70 kg athlete) rather than defaulting to a higher dose. Test your personal response before race day.',
    'Challenges the "more is better" caffeine approach many athletes default to. The network meta-analysis design gives this strong comparative power across delivery methods.',
    5,
    5,
    5,
    true
  ),
  (
    '42072223',
    'Quantitative Analysis of Annual Training Volume and Periodization Patterns in Elite Female Cross-Country Skiers Using GPS Monitoring: A Three-Athlete Case Study.',
    'Xiao X, Moon S, Kim Y, Choi Y',
    'Bioengineering',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42072223/',
    array['Cross-Country Skiing', 'Training Methodology'],
    'A full season of GPS-tracked training data from three Korean national team female cross-country skiers revealed 668 hours of annual training across skiing (54%), running (23%), and strength (22.7%). Intensity distribution was polarized (91.5% in zones 1-2). Total volume was 18-30% below world-class benchmarks, and strength training proportion was notably higher than typical.',
    'Even at the national team level, real-world training data shows polarized intensity distribution works for cross-country skiing. Running and strength training play larger roles than many assume in a ski-specific program.',
    'Rare quantitative training data from female Nordic skiers. The high strength allocation relative to world-class norms is an interesting divergence worth examining across other endurance sports.',
    3,
    3,
    3,
    true
  ),
  (
    '41372730',
    'Iron Status, Muscle Oxygenation and Performance in Female Athletes During Repeated-Sprint Training in Hypoxia.',
    'Stein M, Peeling P, Girard O',
    'Sports medicine',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/41372730/',
    array['Iron Deficiency', 'Female Athlete Health'],
    'Iron deficiency is common in female athletes and impairs muscle oxygenation during high-intensity efforts, especially in hypoxic conditions. Because iron is essential for oxygen transport and mitochondrial energy production, compromised iron status can limit repeated sprint ability and endurance performance in ways that low-intensity testing may not reveal.',
    'Female athletes should monitor ferritin regularly and treat iron deficiency proactively, especially before altitude camps or high-intensity training blocks. Symptoms of low iron can masquerade as overtraining or poor fitness.',
    'Fills an important gap — most iron and sprint research has been done in males. The female-specific physiological challenges (menstruation, hormonal fluctuations) make proactive iron management non-negotiable.',
    4,
    4,
    4,
    true
  ),
  (
    '41440803',
    'Associations Between Nutritional Intake, Body Composition, Menstrual Health, and Performance in Elite Female Trail Runners.',
    'Pinol-Granadino N, Carrasco-Marginet M, Puigarnau S, Sole-Forto J',
    'Journal of functional morphology and kinesiology',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/41440803/',
    array['Female Athlete Health', 'Fueling & Nutrition'],
    'Among 35 elite female trail runners, 94.3% had clinically low energy availability (<30 kcal/kg FFM/day). Better performance correlated with higher complex carbohydrate, total energy, protein, and zinc intake, and negatively with simple sugar intake. Menstrual irregularities did not affect performance, but nutritional patterns strongly influenced both performance and health.',
    'If you are a female trail or ultra runner, track your energy availability — nearly all athletes in this study were under-fueling without realizing it. Prioritize complex carbs and adequate protein over simple sugars for both performance and long-term health.',
    'A sobering finding: near-universal low energy availability in elite female trail runners. This is an individual health issue, not just a performance one.',
    5,
    3,
    4,
    true
  ),
  (
    '41757674',
    'Post-exercise ketone supplementation improves endurance performance and mitochondrial adaptations during an 8-week endurance training intervention.',
    'Robberechts R, Bekhuis Y, Stalmans M, Poffe C',
    'The Journal of physiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41757674/',
    array['Ketone Supplementation', 'Training Adaptation'],
    'Trained male cyclists who consumed a ketone ester post-exercise and before sleep for 8 weeks showed a 4% improvement in 30-minute time trial power versus placebo, driven by increased mitochondrial content (14% higher citrate synthase activity) and improved peripheral oxygen utilization. Cardiac adaptations were not affected.',
    'If you are exploring ketone esters, the evidence points to post-exercise and pre-sleep timing rather than during exercise. The benefit appears to come from enhanced training adaptation over weeks, not acute performance.',
    'Strongest controlled evidence yet for ketone ester supplementation enhancing real endurance adaptations in trained athletes. The mechanism is mitochondrial, not acute fuel substitution.',
    4,
    4,
    4,
    true
  ),
  (
    '41755452',
    'Carbohydrate Storage and Supplementation Strategies for Peak Performance in Cross-Country Skiing.',
    'Ortenblad N, Holmberg HC, Nybo L, Gejl KD',
    'Scandinavian journal of medicine & science in sports',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41755452/',
    array['Glycogen', 'Cross-Country Skiing'],
    'Cross-country skiing has uniquely high whole-body energy demands due to varying loads on upper and lower body muscles plus fluctuating intensity from terrain and sub-technique changes. Glycogen depletion in both arms and legs can independently limit performance. Effective glycogen restoration requires both sufficient carbohydrate intake and adequate recovery time.',
    'For XC skiers and any athlete using both upper and lower body, fuel both muscle groups — total body glycogen demands are higher than in running or cycling alone. Plan carb intake around the specific muscles that will be depleted.',
    'Relevant beyond Nordic sports: any multi-muscle-group endurance effort (paddling, swimming, obstacle racing) faces the same dual-depletion challenge.',
    3,
    3,
    4,
    true
  ),
  (
    '42043082',
    'Energy Availability as a Neurocognitive Regulator of Endurance Performance: Integrating Metabolic, Perceptual, and Decision-Making Mechanisms-A Narrative Review.',
    'Grivas GV, Alkasasbeh WJ',
    'Sports',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42043082/',
    array['Mental Performance', 'Fueling & Nutrition'],
    'Low energy availability amplifies perceived exertion, impairs executive function, reduces effort tolerance, and alters decision-making during prolonged exercise — even before any overt physiological failure. Carbohydrate availability modulates these effects through both peripheral and central neurocognitive pathways. The brain''s perception of effort is metabolically gated.',
    'Under-fueling does not just slow you down physically — it degrades your ability to make good decisions, tolerate discomfort, and pace correctly. Maintaining energy availability is a cognitive performance strategy, not just a physiological one.',
    'Bridges the gap between sport nutrition and sport psychology. Changes the framing of fueling from "feed the muscles" to "feed the brain that controls the muscles."',
    5,
    4,
    4,
    true
  ),
  (
    '41762427',
    'Maximizing Adaptations in Concurrent Training: An Umbrella Review of Meta-analyses.',
    'Held S, Wolf L, Rappelt L, Isenmann E',
    'Sports medicine',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41762427/',
    array['Concurrent Training', 'Strength Training'],
    'This umbrella review of 17 meta-analyses found that combining resistance and endurance training improves both aerobic capacity and strength outcomes without meaningful interference for recreationally trained individuals. Performing strength training before endurance training may favor strength and hypertrophy gains, though no significant sequence effects were found.',
    'You can train both strength and endurance without one canceling the other, especially if you do strength work first in a combined session. The interference effect is less of a concern than traditionally feared for most athletes.',
    'Reassuring evidence for endurance athletes who also want to maintain or build strength. The practical implication is simple: lift first, then do your endurance work.',
    4,
    4,
    4,
    true
  ),
  (
    '41130458',
    'UCI Sports Nutrition Project: Nutritional Periodization: Strategies to Enhance Training Adaptation and Recovery.',
    'Morton JP, Hearris M, Fell MJ, Owens DJ, Halson S, Trommelen J',
    'International journal of sport nutrition and exercise metabolism',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/41130458/',
    array['Fueling & Nutrition', 'Periodization'],
    'A UCI-commissioned review of nutritional periodization: deliberately manipulating energy and macronutrient availability across training cycles to promote adaptation, support recovery, and optimize competition performance. Carbohydrate intake should be adjusted session-by-session based on training demands, and protein intake should be at least 1.6-2.1 g/kg/day.',
    'Match your carb intake to each specific session''s demands rather than eating the same every day. High-intensity or long sessions need more carbs; easy days and recovery sessions need less. Protein stays consistently high.',
    'The definitive current reference for periodized nutrition in cycling, directly applicable to all endurance sports. The session-by-session approach replaces the outdated "daily macro target" mindset.',
    4,
    5,
    5,
    true
  ),
  (
    '41900531',
    'A Systematic Review of the Factors Associated with Performance in Non-Elite Runners.',
    'Thuany M, Silva M, Knechtle B, Gomes TN, Rolim R',
    'Journal of functional morphology and kinesiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41900531/',
    array['Training Methodology', 'Running Performance'],
    'Across 66 studies of non-elite runners (5K to ultramarathon), the relevance of performance predictors shifts with race distance. Physiological factors like VO2max become less important at marathon and ultra distances, where training variables, body composition, and social/psychological factors gain influence. Smoking, BMI, alcohol, and weather also impact finish times.',
    'At shorter distances, focus on the classic physiological markers. As race distance increases toward marathon and ultra, shift more attention to training consistency, body composition management, and race-day execution skills.',
    'Useful reality check: for recreational and non-elite runners, the determinants of performance are more multifactorial than the lab-test focus of most exercise physiology suggests.',
    5,
    3,
    4,
    true
  ),
  (
    '41343201',
    'Sex differences in English Channel swimming performance: an experiment of nature.',
    'Lacambra LA, Senefeld JW, Joyner MJ, Kipp S',
    'Journal of applied physiology',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/41343201/',
    array['Open Water Swimming', 'Sex Differences'],
    'Analyzing 2,593 solo English Channel swims from 1875-2025, males were 7.2% faster among the top 100 swimmers. Sex differences increased with age and were smaller than those seen in ultra-endurance running, suggesting that open-water swimming''s thermoregulatory and buoyancy demands partially attenuate the typical male performance advantage. Optimal swim times occurred at 17-18°C water temperature.',
    'For open-water swimmers, water temperature matters more than you think — fastest performances cluster at 17-18°C. Female swimmers show a relatively smaller performance gap versus males compared to running, reinforcing that swimming rewards thermoregulatory and body composition traits differently.',
    'A beautiful use of 150 years of Channel swim data to study human performance limits. The shrinking sex gap in ultra-swimming is a genuine physiological finding, not just a participation effect.',
    3,
    1,
    4,
    true
  )
on conflict (pubmed_id) do update
set
  title = excluded.title,
  authors = excluded.authors,
  journal = excluded.journal,
  publication_year = excluded.publication_year,
  pubmed_url = excluded.pubmed_url,
  topic_tags = excluded.topic_tags,
  plain_english_summary = excluded.plain_english_summary,
  practical_takeaway = excluded.practical_takeaway,
  commentary = excluded.commentary,
  ultra_score = excluded.ultra_score,
  gravel_score = excluded.gravel_score,
  triathlon_score = excluded.triathlon_score,
  published = excluded.published,
  updated_at = now();
