insert into public.research_library_entries (
  pubmed_id,
  title,
  authors,
  journal,
  publication_year,
  publication_date,
  pubmed_url,
  topic_tags,
  plain_english_summary,
  practical_takeaway,
  commentary,
  ultra_score,
  gravel_score,
  triathlon_score,
  running_score,
  cycling_score,
  swimming_score,
  rowing_score,
  skating_score,
  ski_score,
  team_sport_score,
  published
)
values
  -- ===== ALTITUDE / HYPOXIC TRAINING =====
  (
    '42191840',
    'Comparative efficacy of intermittent hypoxic training modalities on athletes'' performance: a systematic review with pairwise and network meta-analyses.',
    'Jiang X, Sun Y, Huang J, Zhang Z, Baharudin FB, Pritama MAN, Naharudin MNB',
    'Scientific reports',
    2026,
    '2026-05-26',
    'https://pubmed.ncbi.nlm.nih.gov/42191840/',
    array['Altitude', 'Training Methodology'],
    'A network meta-analysis of 29 RCTs (603 trained athletes) compared three types of intermittent hypoxic training against intensity-matched normoxic training. For aerobic capacity, intermittent hypoxic training ranked highest, while repeated sprint in hypoxia was best for anaerobic capacity. Sprint-in-hypoxia without continuous exercise showed no significant aerobic benefit. Moderate simulated altitudes enhanced both aerobic and anaerobic capacity, while high altitudes only improved aerobic outcomes.',
    'If your goal is aerobic development for longer endurance events, prioritize traditional intermittent hypoxic training sessions over repeated-sprint-in-hypoxia protocols. For athletes needing both aerobic and anaerobic gains, repeated sprints in hypoxia are the most versatile option. Target moderate simulated altitudes for the broadest benefit.',
    'First network meta-analysis to directly rank all three major intermittent hypoxic training approaches head-to-head. The modality-specific hierarchy is immediately actionable for coaches prescribing altitude camps.',
    4,
    4,
    5,
    4,
    4,
    3,
    3,
    3,
    4,
    2,
    true
  ),
  (
    '42200179',
    'Live high, train smart: translating altitude physiology to best practice with mechanistic insights.',
    'Faiss R, Girard O',
    'Frontiers in physiology',
    2026,
    '2026-05-11',
    'https://pubmed.ncbi.nlm.nih.gov/42200179/',
    array['Altitude', 'Training Methodology'],
    'This perspective article reconceptualizes performance improvement vectors associated with altitude training. By mapping contemporary strategies (live-high-train-high, live-high-train-low, intermittent hypoxic exposure) alongside their physiological mechanisms, the authors propose a framework linking hypoxic dose, exposure timing, and individual variability to increases in total hemoglobin mass and oxygen delivery. Drawing on 60 years of research since the first altitude training symposium, the review consolidates 25 years of practical lessons.',
    'Use the total hemoglobin mass response as your primary metric for evaluating altitude camp effectiveness. Ensure adequate hypoxic dose by targeting at least 2000-2500 meters for 3-4 weeks minimum. Monitor individual response variation and adjust altitude severity and duration accordingly rather than applying a one-size-fits-all protocol.',
    'Published in Frontiers in Physiology by two leading altitude researchers, this synthesizes the most current evidence into a practical framework. The emphasis on individual response monitoring is critical for coaches planning altitude camps.',
    5,
    5,
    5,
    5,
    5,
    4,
    4,
    4,
    5,
    3,
    true
  ),
  (
    '42166208',
    'Glucose and fructose contributions to exogenous carbohydrate oxidation and performance at moderate altitude.',
    'Arjomandkhah NC, King AJ, Griffiths A, King RFGJ, Morrison DJ, Preston T, O''Hara JP',
    'The Journal of physiology',
    2026,
    '2026-05-21',
    'https://pubmed.ncbi.nlm.nih.gov/42166208/',
    array['Fueling & Nutrition', 'Altitude'],
    'This is the first study to compare glucose-fructose co-ingestion with glucose alone during prolonged running at 2500 m altitude. The combination significantly increased exogenous carbohydrate oxidation and spared endogenous stores compared to glucose alone, confirming the synergistic effect seen at sea level also operates at altitude. However, the improved fuel utilization did not translate into a 5 km time trial performance advantage over glucose alone, though both carbohydrate conditions were faster than placebo.',
    'Use glucose-fructose blends rather than glucose alone when training or racing at moderate altitude. While the performance edge over glucose-only was not detected in a 5 km effort, the glycogen-sparing effect could become meaningful in longer events at altitude where endogenous fuel preservation matters more.',
    'First demonstration of the glucose-fructose synergy on exogenous CHO oxidation at altitude. The practical takeaway for athletes at altitude training camps or competing in mountain events is clear: dual-transport carbs work at altitude too.',
    4,
    4,
    4,
    4,
    4,
    2,
    2,
    2,
    3,
    2,
    true
  ),

  -- ===== CYCLING / FUELING =====
  (
    '41962970',
    'Ketone monoester reduces blood glucose, exogenous CHO oxidation, and oxidation efficiency in trained male cyclists when fed 120 g/h of CHO during exercise.',
    'Martyn HJ, Cameron NE, Edmondson JA, Phelan MM, Gonzalez JT, Shepherd SO, Pugh JN, Owens DJ, Morton JP',
    'Journal of applied physiology',
    2026,
    '2026-04-10',
    'https://pubmed.ncbi.nlm.nih.gov/41962970/',
    array['Supplementation', 'Fueling & Nutrition'],
    'When trained male cyclists ingested ketone monoester alongside 120 grams per hour of carbohydrate during prolonged cycling, blood glucose dropped, exogenous CHO oxidation fell from 1.50 to 1.35 grams per minute, and oxidation efficiency decreased from 75% to 67% compared to carbohydrate alone. Despite these metabolic changes, exercise capacity was not different between the ketone-plus-carb and carb-only conditions. Metabolomics revealed ketones increased markers of altered carbohydrate metabolism and protein turnover.',
    'Adding ketone monoester to an already high carbohydrate fueling strategy (120 g/h) does not enhance cycling performance and actually reduces the efficiency of exogenous carbohydrate use. If you are already fueling optimally with carbohydrate, ketone esters may not provide additional benefit and could interfere with carb metabolism.',
    'Important negative finding from a leading sports nutrition lab. At the highest recommended carb intake rates, ketones appear to compete with rather than complement carbohydrate oxidation. This challenges marketing claims around stacking ketones on top of carbs.',
    2,
    5,
    4,
    2,
    5,
    1,
    1,
    1,
    1,
    1,
    true
  ),
  (
    '42208612',
    'Addressing the Evidence Gap: Ergogenic Effects of Caffeine on Cycling Performance in Females-A Systematic Review and Three-Level Meta-Analysis.',
    'Bittencourt de Santa Ritta G, Brito Soares LM, Abreu ACP, Mendes GF, Saunders B, Reis CEG',
    'International journal of sport nutrition and exercise metabolism',
    2026,
    '2026-05-27',
    'https://pubmed.ncbi.nlm.nih.gov/42208612/',
    array['Caffeine', 'Female Athletes'],
    'This meta-analysis of 19 randomized crossover trials in 235 female cyclists found a small but significant ergogenic effect of caffeine on cycling performance. The effect was consistent regardless of caffeine dose or training level. Notably, caffeine significantly improved performance during the mid-luteal menstrual phase but showed no significant effect in other phases, suggesting cycle-phase-dependent responsiveness.',
    'Female cyclists should consider timing caffeine use with menstrual cycle phase for maximum benefit, with the mid-luteal phase appearing most responsive. The effective dose range was broad, so even moderate caffeine intake may help. This supports including caffeine in race-day nutrition plans for female endurance athletes.',
    'Addresses a critical evidence gap since most caffeine research has been in males. The menstrual cycle phase finding is novel and has immediate practical implications for periodized supplementation strategies in female athletes.',
    2,
    5,
    4,
    3,
    5,
    2,
    2,
    2,
    2,
    2,
    true
  ),
  (
    '41911915',
    'UCI Sports Nutrition Project: Body Composition, Energy Requirements, and Energy Availability in Cycling.',
    'Burke LM, Gonzalez JT, Areta JL, Kuikman MA, Coates AM, Bailey DM, Moran J, Dolan E',
    'International journal of sport nutrition and exercise metabolism',
    2026,
    '2026-03-30',
    'https://pubmed.ncbi.nlm.nih.gov/41911915/',
    array['Fueling & Nutrition', 'Recovery'],
    'This UCI-commissioned review critically examines body composition, energy expenditure, and energy availability in competitive cyclists. Available evidence shows cyclists are a weight-conscious group that frequently engages in restrictive eating. The dual demands of fueling high training loads while maintaining low body mass places many riders at risk of low energy availability and its associated health and performance consequences.',
    'Do not sacrifice energy availability for body composition goals during high-volume training phases. Use periodized nutrition to manage body composition during lower training loads instead. Monitor for warning signs of low energy availability including declining performance, frequent illness, menstrual disturbances, and mood changes.',
    'Part of the UCI Sports Nutrition Project led by Louise Burke. This is the definitive current review on energy availability in cycling and should inform how coaches and athletes approach the weight-power trade-off.',
    2,
    5,
    4,
    3,
    5,
    1,
    1,
    1,
    2,
    1,
    true
  ),
  (
    '41468224',
    'UCI Sports Nutrition Project: Does Cycling Create a "Perfect Storm" for Bone Health? Cycling-Specific Challenges to Bone and Nutritional Strategies to Overcome These.',
    'Saffioti N, Takarabe LL, Perfeito LAM, Ribeiro WJD, Hilkens L, van Dijk JW, Dolan E',
    'International journal of sport nutrition and exercise metabolism',
    2026,
    '2025-12-17',
    'https://pubmed.ncbi.nlm.nih.gov/41468224/',
    array['Injury Prevention', 'Fueling & Nutrition'],
    'Cyclists tend to have lower bone mass than other athletes and non-athlete controls. This UCI review identifies cycling-specific factors that combine to create a perfect storm for bone health: low-impact repetitive loading that provides minimal bone stimulus, metabolic perturbations from prolonged cycling that transiently increase bone resorption, low energy availability, and the naturally lean physique of endurance cyclists.',
    'Incorporate brief bouts of high-impact loading like jumping or running into your weekly training. Ensure adequate calcium, vitamin D, protein, and overall energy intake. Do not rely on cycling alone for bone health. Periodically assess bone density, especially if you are a long-career cyclist or have other risk factors.',
    'Second key paper from the UCI Sports Nutrition Project. The perfect storm framing is useful: no single factor explains low bone mass in cyclists, but the combination is potent. Especially relevant for gravel and road cyclists who rarely run.',
    2,
    5,
    4,
    2,
    5,
    1,
    1,
    1,
    1,
    1,
    true
  ),

  -- ===== TRAINING PHYSIOLOGY =====
  (
    '42126053',
    'The increase in time to task failure following endurance training is associated with adjustments in motor unit firing properties.',
    'Martinez-Valdes E, Negro F, Falla D, Farina D',
    'Journal of applied physiology',
    2026,
    '2026-05-13',
    'https://pubmed.ncbi.nlm.nih.gov/42126053/',
    array['Training Methodology', 'VO2max'],
    'Two weeks of continuous endurance training, but not high-intensity interval training, improved time-to-task-failure during sustained submaximal contractions. The improvement was linked to specific motor unit adaptations: delayed onset of compensatory firing rate increases and reduced firing rate attenuation under fatigue. These neuromuscular changes explained approximately 50% of the performance gains, revealing a distinct mechanism by which steady-state endurance work builds fatigue resistance.',
    'Continuous moderate-intensity training provides fatigue resistance benefits that HIIT does not replicate, at least in the short term. For athletes whose events demand sustained submaximal effort, maintaining a base of moderate-intensity volume is critical and cannot be fully replaced by interval work.',
    'Landmark paper using high-density EMG to track individual motor units before and after training. Demonstrates a clear physiological mechanism separating the adaptations from continuous vs interval training, supporting the polarized training model.',
    4,
    5,
    5,
    4,
    5,
    4,
    4,
    3,
    4,
    3,
    true
  ),
  (
    '42188576',
    'Physiological, Metabolic, and Mitochondrial Adaptations to a One-Week Endurance Training Camp in Recreational Athletes: An Observational Study.',
    'Bizjak DA, John L, Munk M, Reiter M, Luders N, Kirsten J, Henze AS, Schulz SVW',
    'Sports',
    2026,
    '2026-05-13',
    'https://pubmed.ncbi.nlm.nih.gov/42188576/',
    array['Recovery', 'Training Methodology'],
    'A professionally guided one-week endurance training camp in recreational athletes produced measurable physiological, metabolic, and mitochondrial adaptations. Body mass and body fat decreased, plasma mitochondrial DNA and PGC-1-alpha expression increased indicating mitochondrial biogenesis, and systemic stress markers like cortisol and interferon-gamma decreased. However, muscle-damage and cell-stress markers also rose, indicating significant physiological load alongside the adaptations.',
    'A well-structured one-week training camp can produce detectable mitochondrial adaptations even in recreational athletes. Plan adequate recovery after a camp block as the concurrent rise in stress markers shows the body is under substantial load. The holiday-like setting of the camp may have contributed to reduced psychological stress despite high training volume.',
    'Practical evidence supporting the training camp model popular among recreational endurance athletes. The mitochondrial DNA and PGC-1-alpha findings provide molecular evidence for what coaches have long observed anecdotally about camp-based training blocks.',
    4,
    4,
    4,
    4,
    4,
    3,
    3,
    2,
    3,
    2,
    true
  ),
  (
    '42157436',
    'EPAS1 is associated with human muscle fiber composition and endurance phenotypes.',
    'Dautova AZ, Valeeva EV, Semenova EA, Mavliev FA, Zverev AA, Nazarenko AS, John G, Zhelankin AV, Larin AK, Kulemin NA, Sultanov RI, Generozov EV, Ahmetov II',
    'Physiological reports',
    2026,
    '2026-05-01',
    'https://pubmed.ncbi.nlm.nih.gov/42157436/',
    array['VO2max', 'Training Methodology'],
    'EPAS1 (hypoxia-inducible factor 2-alpha) gene expression was significantly higher in endurance athletes compared to power athletes and was positively associated with slow-twitch muscle fiber proportion. Analysis of 24 transcriptomic datasets showed EPAS1 expression increased significantly following aerobic training. A specific genetic variant predicted higher EPAS1 expression and was associated with endurance athlete status and higher VO2max in males, identifying EPAS1 as an important genetic factor in endurance adaptation.',
    'While you cannot change your genetics, this finding reinforces that aerobic training itself upregulates the molecular machinery for slow-twitch fiber development. Consistent aerobic training volume is the environmental signal that drives EPAS1 expression upward, regardless of your starting genetic endowment.',
    'Connects a well-known altitude-adaptation gene to endurance phenotypes in a large sample of over 1200 subjects. The training-induced upregulation finding is especially important: your training habits influence the same pathway that genetics sets the baseline for.',
    4,
    4,
    4,
    4,
    4,
    3,
    3,
    3,
    4,
    2,
    true
  ),

  -- ===== ULTRA-ENDURANCE =====
  (
    '42137885',
    'Experimental evidence of life history trade-offs during ultra-endurance physical activity.',
    'Longman DP, Murray A, Brown EL, Lewis C, Millis RM, Nowak TJ, Udquim KT, Muehlenbein MP, Wells JCK, Stock JT',
    'Evolutionary human sciences',
    2026,
    '2026-03-06',
    'https://pubmed.ncbi.nlm.nih.gov/42137885/',
    array['Ultra-Endurance', 'Recovery'],
    'Researchers recruited 147 ultra-endurance athletes across four multi-day ultramarathons and one multi-week ocean rowing event to test whether extreme energy demands force the body to prioritize some physiological functions over others. The study found evidence of trade-offs across multiple systems: investment in immune defense was broadly prioritized over storage, reproduction, and maintenance functions, suggesting the body has a hierarchy of resource allocation under extreme energetic stress.',
    'During ultra-endurance events, your body will prioritize immune function over reproductive hormones and tissue maintenance. This means recovery from multi-day events requires attention to all systems, not just muscle repair. Expect hormonal disruptions and accept that full recovery from extreme ultra events may take longer than the musculoskeletal timeline suggests.',
    'Novel application of life history theory from evolutionary biology to ultra-endurance sport. The multi-event design spanning ultramarathons AND ocean rowing makes this one of the most ecologically valid studies of human energy allocation under extreme stress.',
    5,
    3,
    3,
    4,
    2,
    2,
    4,
    2,
    2,
    1,
    true
  ),
  (
    '41601104',
    'Examining attention-deficit/hyperactivity disorder in endurance and ultra-endurance runners.',
    'Scheer V, Valero D, Valero E, Weiss K, Rosemann T, Knechtle B',
    'Acta psychologica',
    2026,
    '2026-01-06',
    'https://pubmed.ncbi.nlm.nih.gov/41601104/',
    array['Ultra-Endurance', 'Training Methodology'],
    'In a survey of 601 endurance and ultra-endurance runners, 9.7% screened positive for ADHD traits using the ASRS-5, exceeding rates found in both elite athletes and the general adult population. Half-marathon runners had the highest screening rate at 14.8%. No significant sex differences were found. Younger runners under 40 had significantly higher screening rates. This is the first study to provide ADHD screening data specifically for endurance and ultra-endurance populations.',
    'Be aware that nearly 1 in 10 endurance runners may have undiagnosed ADHD traits that could affect training adherence, focus during long events, and response to coaching. Runners who struggle with training consistency despite high motivation should consider ADHD screening. Structured training plans with clear daily targets may help athletes with ADHD traits stay on track.',
    'First ADHD prevalence data specific to the endurance running community. The higher-than-general-population rate is noteworthy and aligns with the hypothesis that endurance sport may attract individuals with ADHD traits who benefit from the structure and dopaminergic reward of running.',
    5,
    2,
    3,
    4,
    2,
    2,
    2,
    2,
    2,
    2,
    true
  ),
  (
    '41295769',
    'Real-Time Performance Prediction in Long-Distance Trail Running: A Practical Model Based on Terrain Difficulty and Pacing Variability.',
    'Gutierrez H, Piedrafita E, Bascuas PJ, Arbones I, Berzosa C, Bataller-Cervero AV',
    'Sports',
    2025,
    '2025-11-04',
    'https://pubmed.ncbi.nlm.nih.gov/41295769/',
    array['Pacing', 'Ultra-Endurance'],
    'A real-time predictive model for trail running races was developed using data from 947 runners. The model uses weighted time across terrain difficulty, pacing variability, and checkpoint percentile rank to predict total race time from just the first third of the race, achieving adjusted R-squared above 0.95. Runners who maintained more consistent pacing relative to terrain difficulty performed better overall, confirming that pacing discipline is a key performance determinant in trail racing.',
    'In trail ultras, track your pacing consistency against terrain difficulty rather than obsessing over absolute pace. A model like this could allow crew and coaches to project finish times early in a race and adjust strategy accordingly. Practice on varied terrain to develop an internal sense of appropriate effort relative to elevation and technical difficulty.',
    'Practical field-applicable model that does not require lab testing. The weighted time and pacing variability metrics could be operationalized through GPS watches for real-time strategy adjustment during trail races.',
    5,
    3,
    2,
    4,
    1,
    1,
    1,
    1,
    1,
    1,
    true
  ),

  -- ===== WINTER ENDURANCE SPORTS =====
  (
    '41665741',
    'Mind-Muscle-Environment Interactions: Psychophysiological Determinants of Optimal Pacing in Olympic Winter Endurance Sports.',
    'Edholm P, Bouten LJL, Holmberg HC, Losnegard T, Hettinga FJ',
    'Scandinavian journal of medicine & science in sports',
    2026,
    '2026-02-01',
    'https://pubmed.ncbi.nlm.nih.gov/41665741/',
    array['Pacing', 'Training Methodology'],
    'This review synthesizes psychophysiological determinants of pacing in cross-country skiing, biathlon, and speed skating. Pacing emerges as a continuous decision-making process driven by dynamic interactions between the physiological engine, the psychological operator, and environmental factors like head-to-head racing, variable weather, and undulating terrain. The affordance competition hypothesis is proposed as a unifying framework for understanding how athletes regulate effort across these complex conditions.',
    'Train pacing decisions in ecologically valid conditions, not just controlled environments. For winter endurance athletes, this means practicing race-pace efforts on variable terrain, in changing conditions, and ideally in head-to-head formats. Develop both physiological capacity and the cognitive skills to regulate effort under uncertainty.',
    'Written ahead of the Milano-Cortina 2026 Winter Olympics, this integrates the latest thinking on pacing science across three Olympic endurance disciplines. The integrated psychophysiological framework is applicable to any endurance sport where terrain and conditions vary.',
    3,
    3,
    3,
    3,
    2,
    1,
    1,
    5,
    5,
    2,
    true
  ),
  (
    '41653367',
    'Olympic Snow Sports: Current Insights and Future Directions for Milano Cortina 2026 and Beyond.',
    'Zoppirolli C, Fornasiero A, Sporri J, Losnegard T, Elfmark OA, Sandbakk O, Holmberg HC',
    'Scandinavian journal of medicine & science in sports',
    2026,
    '2026-02-01',
    'https://pubmed.ncbi.nlm.nih.gov/41653367/',
    array['Periodization', 'Training Methodology'],
    'This comprehensive review synthesizes performance determinants across all Olympic snow sports ahead of Milano Cortina 2026. Endurance-dominant disciplines like cross-country skiing, biathlon, and ski mountaineering rely on high aerobic capacity and movement efficiency, while gravity sports emphasize neuromuscular power. Elite training models combine endurance, strength-power, technical, tactical, and psychological preparation tailored to sport-specific demands.',
    'Cross-country skiers and biathletes should maintain a large aerobic base supplemented with sport-specific strength and technical work. The review highlights that sex-specific training research remains scarce across winter sports, which means current programs may not be optimally serving female athletes. Address this gap by monitoring individual responses rather than applying male-derived protocols.',
    'Most comprehensive pre-Olympic review of snow sport science to date, from a group of leading Scandinavian and European researchers. The identification of major knowledge gaps in sex-specific research and ski mountaineering science maps future research priorities.',
    2,
    2,
    2,
    2,
    1,
    1,
    1,
    4,
    5,
    1,
    true
  ),

  -- ===== SUPPLEMENTATION & RECOVERY =====
  (
    '41870601',
    'The emerging and evolving evidence supporting creatine as an ergogenic aid: history and applications.',
    'Kerksick C, Gonzalez D, Stout J, Forbes S, Candow D, Ziegenfuss T, Marshall R, Schwesig R, Kreider R',
    'Journal of the International Society of Sports Nutrition',
    2026,
    '2026-03-23',
    'https://pubmed.ncbi.nlm.nih.gov/41870601/',
    array['Supplementation', 'Recovery'],
    'This comprehensive narrative review covering three decades of creatine research confirms consistent benefits for high-intensity performance, training adaptations, lean body mass, and strength. Emerging evidence suggests benefits for endurance and team-sport athletes through enhanced glycogen resynthesis, calcium handling, oxidative stress mitigation, and repeated-sprint performance. In tactical populations, creatine may support hydration, thermoregulation, cognition, and sleep quality. Safety data from hundreds of clinical trials show no greater adverse events than placebo.',
    'Creatine is not just for strength athletes. Endurance athletes may benefit from its effects on glycogen resynthesis, recovery between sessions, and potentially improved heat tolerance. Consider a maintenance dose of 3-5 grams daily, especially during high training load periods. The established safety profile makes it one of the lowest-risk supplements available.',
    'Authoritative ISSN review that repositions creatine for endurance sport applications. The glycogen resynthesis and thermoregulation findings are particularly relevant for ultra and gravel athletes dealing with multi-day events or heat stress.',
    3,
    4,
    4,
    3,
    4,
    3,
    3,
    3,
    3,
    4,
    true
  ),
  (
    '42044038',
    'Stress-Associated Testosterone Suppression: Central Adaptation or Hypogonadism?',
    'Friedl KE, Nindl BC, Potter AW',
    'The Journal of clinical endocrinology and metabolism',
    2026,
    '2026-04-27',
    'https://pubmed.ncbi.nlm.nih.gov/42044038/',
    array['Recovery', 'Training Methodology'],
    'Low testosterone in physically stressed populations, including endurance athletes, is most commonly a centrally mediated, reversible adaptation rather than true gonadal dysfunction. Severe energy deficit, sleep disruption, and sustained psychological stress suppress the hypothalamic-pituitary axis, while the testes themselves remain responsive. Critically, energetic sufficiency, not exercise modality, is the principal determinant of testosterone levels. When energy balance and recovery are restored, testosterone normalizes.',
    'If your testosterone is low during heavy training, seek clinical evaluation to rule out conditions unrelated to training while simultaneously optimizing energy availability, sleep quality, and psychological recovery. In many endurance athletes the suppression reflects a reversible adaptation to energy deficit and stress rather than permanent damage, but only a clinician can distinguish functional suppression from pathological causes.',
    'Published in JCEM, this reframes the testosterone conversation away from clinical hypogonadism and toward functional energy management. Directly relevant to the relative energy deficiency in sport (REDs) framework that many endurance athletes unknowingly experience.',
    4,
    4,
    4,
    4,
    4,
    3,
    3,
    3,
    4,
    3,
    true
  ),

  -- ===== MARATHON / ROAD RUNNING =====
  (
    '41351755',
    'Toward a record-eligible sub-2-hour marathon: an updated integrative framework of Physiological, technological, and cognitive determinants.',
    'Grivas GV',
    'European journal of applied physiology',
    2025,
    '2025-12-06',
    'https://pubmed.ncbi.nlm.nih.gov/41351755/',
    array['Running Economy', 'VO2max', 'Pacing'],
    'Breaking the sub-2-hour marathon under record-eligible conditions requires a VO2max of 75-85 mL/kg/min, running economy at or below 190 mL/kg/km at 21 km/h, fractional utilization of 90-94% VO2max, and cognitive endurance to sustain near-threshold effort for approximately two hours. Carbon-fiber-plated shoes, carbohydrate intake of 60-100 g/h, caffeine at 3-6 mg/kg, and optimal conditions of about 10 degrees Celsius with low wind further narrow the remaining gap. AI-assisted training and real-time monitoring are expected to refine preparation further.',
    'The sub-2-hour framework provides benchmark targets for elite marathon runners: train toward both the physiological ceiling and the cognitive capacity to sustain near-maximal effort. For non-elite runners, the same principles apply at a scaled level: running economy, fueling, shoe technology, and environmental conditions each contribute independently to marathon performance.',
    'The most complete integrative model of marathon performance determinants published to date. Extends previous frameworks by incorporating cognitive endurance, thermoregulation, and AI-assisted training. Useful as a reference for understanding what each factor contributes to the final time.',
    2,
    2,
    3,
    5,
    1,
    1,
    1,
    1,
    1,
    1,
    true
  ),
  (
    '40913707',
    'Training Volume and Training Frequency Changes Associated with Boston Marathon Race Performance.',
    'DeJong Lempke AF, Ackerman KE, Stellingwerff T, Burke LM, Baggish AL, d''Hemecourt PA, Dyer S, Troyanos C, Saville GH, Adelzadeh K, Holtzman B, Hackney AC, Whitney KE',
    'Sports medicine',
    2025,
    '2025-09-06',
    'https://pubmed.ncbi.nlm.nih.gov/40913707/',
    array['Periodization', 'Training Methodology'],
    'Analysis of 917 Boston Marathon runners showed that higher habitual training distance, more weekly sessions, and more quality sessions in both the 12-4 and 4-0 month pre-race periods were associated with faster race times. Crucially, runners who decreased their training frequency in the final four months while maintaining intensity ran faster than those who maintained or increased frequency. More cross-training in the final four months was also associated with better performance.',
    'Build a strong training base with consistent high volume 12-4 months out, then strategically reduce session frequency while preserving quality in the final 4 months before a marathon. Incorporate cross-training during the final build to maintain fitness while reducing running-specific fatigue. This supports a taper strategy based on reducing frequency rather than just reducing volume.',
    'Large-sample Boston Marathon study with an author team including Stellingwerff, Burke, Ackerman, and Baggish. The finding that reduced frequency with maintained quality outperforms maintained or increased frequency is a strong endorsement of smart tapering and periodization.',
    3,
    3,
    4,
    5,
    2,
    1,
    1,
    1,
    1,
    1,
    true
  ),

  -- ===== SWIMMING =====
  (
    '42218755',
    'Selected immunoendocrine and performance adaptations to upper-body plyometric training and beta-alanine supplementation in male swimmers.',
    'Gao H, Yu X, Guo Z',
    'Journal of the International Society of Sports Nutrition',
    2026,
    '2026-05-31',
    'https://pubmed.ncbi.nlm.nih.gov/42218755/',
    array['Supplementation', 'Strength Training'],
    'Eight weeks of upper-body plyometric training significantly improved medicine ball throw distance, push-up endurance, bench press 1RM, swim ergometer power, and 50-200 m freestyle performance in 30 trained male swimmers. The addition of beta-alanine supplementation further amplified these gains and promoted a more favorable testosterone-to-cortisol ratio and higher immunoglobulin A levels compared to training with placebo.',
    'Incorporate upper-body plyometric exercises like medicine ball throws and plyometric push-ups into swim training to improve power transfer and race performance across sprint and middle-distance events. Beta-alanine supplementation at standard doses can enhance the training response and support recovery during intensified training blocks.',
    'Well-designed three-group RCT showing both the standalone benefit of plyometrics and the additive effect of beta-alanine in swimmers. The immunoendocrine improvements suggest beta-alanine may help swimmers tolerate higher training loads.',
    1,
    1,
    3,
    1,
    1,
    5,
    2,
    1,
    1,
    1,
    true
  )
on conflict (pubmed_id) do nothing;
