-- Seed new research library entries covering broad endurance disciplines:
-- ultra running, endurance cycling, triathlon, rowing, cross-country skiing,
-- speed skating, swimming, biathlon, heat acclimation, altitude training,
-- training methodology, nutrition, marathon performance, and pacing.
-- Sources retrieved from PubMed (National Library of Medicine).

insert into public.research_library_entries (
  pubmed_id,
  title,
  authors,
  journal,
  publication_year,
  publication_date,
  pubmed_url,
  topic_tags,
  plain_english_summary,
  practical_takeaway,
  commentary,
  ultra_score,
  gravel_score,
  triathlon_score,
  running_score,
  cycling_score,
  swimming_score,
  rowing_score,
  skating_score,
  ski_score,
  team_sport_score,
  published
)
values
  -- ===== ULTRA / TRAIL RUNNING =====
  (
    '41334713',
    'Physiological, nutritional, and thermoregulatory responses of a world-class mountain-ultramarathon athlete during the 2025 Western States Endurance Run 100.',
    'Mougin L, Jornet Burgada K, Ely BR, Morel B, Blagrove RC, Mix H, Svendahl E, Mears SA, Stennett R',
    'Journal of applied physiology',
    2025,
    '2025-12-03',
    'https://pubmed.ncbi.nlm.nih.gov/41334713/',
    array['Fueling & Nutrition', 'Pacing', 'Recovery'],
    'This case study documents the physiological, nutritional, and thermoregulatory responses of Kilian Jornet during the 2025 Western States Endurance Run, where he finished third in 14:19:22. Using doubly labeled water, the study measured total energy expenditure at 16,104 kcal, with carbohydrate intake of approximately 86 grams per hour. Core temperature peaked at 39.4 degrees Celsius, and pacing analysis showed a mean normalized speed of 84.8 percent of predicted critical speed with only a 15 percent decline across the race.',
    'For elite ultra efforts, target 80 to 90 grams of carbohydrate per hour to match the enormous energy demands. Even world-class athletes show only partial energy replacement, so accept a caloric deficit and focus on carbohydrate delivery rate. Use pacing data relative to critical speed to monitor fatigue resistance.',
    'The first comprehensive in-race assessment of a world-class ultra athlete using gold-standard doubly labeled water for energy expenditure. The 18.8 kcal per minute expenditure rate defines the upper boundary of what is physiologically possible in competitive ultra running.',
    5,
    3,
    2,
    5,
    2,
    0,
    0,
    0,
    0,
    0,
    true
  ),
  (
    '41343039',
    'Thermoregulation and Hydration Dynamics in a 160-km Ultra-Endurance Race in a Tropical Environment: A Field Study on 80 Runners.',
    'Bouscaren N, Berly L, Descombes G, Tounkara B, Lacroix E, Lemarchand B, Racinais S, Millet GY',
    'Sports medicine (Auckland, N.Z.)',
    2025,
    '2025-12-04',
    'https://pubmed.ncbi.nlm.nih.gov/41343039/',
    array['Heat Acclimation', 'Fueling & Nutrition', 'Injury Prevention'],
    'This field study tracked core temperature and hydration in 80 runners during a 160-km ultra-endurance race in a tropical environment with temperatures up to 28 degrees Celsius and humidity up to 100 percent. Mean core temperature was 37.9 degrees, peaking at 38.9. Average body mass loss was 4.8 percent, with 31 percent of runners losing more than 6 percent, yet body mass loss showed no correlation with core temperature or performance.',
    'Substantial body mass loss during ultra-endurance events appears to be a normal physiological adaptation rather than a risk factor for hyperthermia. Individualize hydration strategies rather than chasing a fixed body mass target. Monitor core temperature and perceived effort instead of relying on weight as the sole hydration metric.',
    'Challenges the longstanding dogma that large body mass losses during exercise are inherently dangerous. The 80-runner sample in extreme tropical conditions makes this one of the most ecologically valid thermoregulation studies in ultra running.',
    5,
    3,
    2,
    5,
    2,
    0,
    0,
    0,
    0,
    0,
    true
  ),
  (
    '41601104',
    'Examining attention-deficit/hyperactivity disorder in endurance and ultra-endurance runners.',
    'Scheer V, Valero D, Valero E, Weiss K, Rosemann T, Knechtle B',
    'Acta psychologica',
    2026,
    '2026-01-06',
    'https://pubmed.ncbi.nlm.nih.gov/41601104/',
    array['Female Athletes', 'Recovery', 'Pacing'],
    'This cross-sectional study screened 601 endurance and ultra-endurance runners for ADHD using the ASRS-5 scale. Overall, 9.7 percent returned screening results above the ADHD cutoff, exceeding reported rates in the general adult population of 3.1 percent and previous elite athlete studies of 7 to 8 percent. Half-marathon runners screened highest at 14.8 percent, while ultramarathon runners screened at 8.7 percent. Age was the only significant risk factor, with higher rates in runners under 40.',
    'Be aware that ADHD traits may be more common in the endurance running community than previously recognized. Athletes with attention difficulties may self-select into endurance sports as a form of self-regulation. Coaches should consider neurodivergent-friendly training approaches, including varied sessions and clear structure.',
    'First study to screen for ADHD specifically in endurance and ultra-endurance runners. The higher-than-population-average screening rate raises important questions about whether endurance sport attracts people with ADHD traits or whether the sport provides a beneficial outlet.',
    5,
    3,
    3,
    5,
    2,
    0,
    0,
    0,
    0,
    0,
    true
  ),
  (
    '40645404',
    'Untargeted metabolomics profiling of 24-h ultramarathon runners: new insights into the biochemical alterations and the identification of performance biomarkers.',
    'Benedetti S, Biancucci F, Menotta M, Nasoni MG, Luchetti F',
    'Life sciences',
    2025,
    '2025-07-09',
    'https://pubmed.ncbi.nlm.nih.gov/40645404/',
    array['Recovery', 'Supplementation', 'Fueling & Nutrition'],
    'This study applied untargeted metabolomics to plasma samples from 17 runners before and after a 24-hour ultramarathon. The major metabolic shifts involved lipid metabolism, with increases in medium- and long-chain fatty acids. Oxidized metabolites from linoleic and arachidonic acid accumulated, indicating significant oxidative and inflammatory stress. Higher pre-race levels of 5-methyltetrahydrofolic acid and higher post-race levels of beta-alanine and creatine were associated with greater distance covered.',
    'Consider supplementing with folate, beta-alanine, and creatine as part of an ultra-endurance nutrition strategy. These metabolites correlated with better performance in a 24-hour race. Manage the oxidative and inflammatory load through antioxidant-rich nutrition during extended events.',
    'First metabolomics study to identify potential performance biomarkers during a 24-hour timed ultra. The associations between specific metabolites and distance covered open the door to personalized supplementation strategies for ultra-endurance athletes.',
    5,
    3,
    2,
    5,
    2,
    0,
    0,
    0,
    0,
    0,
    true
  ),
  (
    '41295769',
    'Real-Time Performance Prediction in Long-Distance Trail Running: A Practical Model Based on Terrain Difficulty and Pacing Variability.',
    'Gutierrez H, Piedrafita E, Bascuas PJ, Arbones I, Berzosa C, Bataller-Cervero AV',
    'Sports (Basel, Switzerland)',
    2025,
    '2025-11-04',
    'https://pubmed.ncbi.nlm.nih.gov/41295769/',
    array['Pacing', 'Running Economy'],
    'This study developed a real-time predictive model for marathon and ultra-trail race performance using only in-race data. Analyzing 947 runners, the model uses weighted time, pacing variability, and checkpoint percentile rank from the first third of the race to predict total race time with strong accuracy. The model reflects a runner''s ability to overcome elevation and maintain consistent pacing, offering insights into fatigue management.',
    'Use the first third of your trail race as a diagnostic window. If your pacing variability is increasing relative to terrain difficulty, you are likely heading for a significant slowdown. Coaches and crew can use checkpoint data to adjust fueling and effort strategy in real time.',
    'Unlike most performance models that require pre-race lab testing, this one works entirely from in-race data. The adjusted R-squared above 0.95 across sexes and race modalities makes it a genuinely practical tool for race-day strategy.',
    5,
    4,
    2,
    5,
    2,
    0,
    0,
    0,
    0,
    0,
    true
  ),
  -- ===== ENDURANCE CYCLING =====
  (
    '41622427',
    'The Cognitive Costs of Sleep Deprivation in Ultra-Endurance Cycling: Insights From the Race Across France.',
    'Hurdiel R, Kurinec C, Peze T, Bonduelle C, Bourlois V',
    'Journal of sleep research',
    2026,
    '2026-02-01',
    'https://pubmed.ncbi.nlm.nih.gov/41622427/',
    array['Recovery', 'Pacing'],
    'This study tracked sleep strategies, subjective sleepiness, and cognitive performance in 23 ultracyclists during the Race Across France. Riders who slept more per 24-hour period finished with higher race rankings. Those averaging less than 5.29 hours of sleep per day showed significantly greater perceived sleepiness and distinct 24-hour rhythms. Cognitive performance and reaction times worsened progressively in sleep-deprived riders across the multi-day event.',
    'In multi-day ultra-endurance cycling events, strategic sleep is a performance tool, not a luxury. Aim for more than 5 hours of sleep per 24-hour period. Align sleep timing with your natural circadian rhythm to maximize cognitive function and overall race performance.',
    'Provides the first quantitative evidence that sleep duration predicts finishing position in ultra-cycling. The 5.29-hour threshold is a practical benchmark for race planning. Challenges the macho culture of sleep deprivation in ultra-endurance cycling.',
    4,
    5,
    3,
    3,
    5,
    0,
    0,
    0,
    0,
    0,
    true
  ),
  (
    '41829603',
    'Beyond Euglycemia: Case Studies Using Continuous Glucose Monitoring in Elite Athletes Without Diabetes During Record Athletic Events.',
    'Skroce K, Turner LV, Zignoli A, Lipman DJ, Zisser HC, Riddell MC',
    'Sensors (Basel, Switzerland)',
    2026,
    '2026-03-05',
    'https://pubmed.ncbi.nlm.nih.gov/41829603/',
    array['Fueling & Nutrition', 'Recovery'],
    'This case series characterized continuous glucose monitoring responses in three elite athletes across distinct events: an ultra-endurance relay cycling world record, a continuous Everesting Challenge cycling record attempt, and a maximal breath-hold dive. During the 44-hour cycling relay, mean glucose was 91 mg/dL with 9.15 percent time below range. The Everesting attempt showed persistently elevated glucose at 160 mg/dL with 100 percent time above 140. Substantial deviations from normal glycemic ranges were common during elite performance.',
    'Do not apply clinical glucose targets to athletic performance contexts. Sustained hyperglycemia during high-intensity efforts and episodic hypoglycemia during ultra-endurance are normal physiological responses, not problems to fix. Use CGM data to optimize fueling timing rather than chasing euglycemia.',
    'Reframes how athletes and coaches should interpret CGM data during competition. The finding that clinical glucose thresholds are irrelevant to athletic performance contexts is important as CGM adoption grows among non-diabetic athletes.',
    4,
    5,
    4,
    4,
    5,
    0,
    0,
    0,
    0,
    0,
    true
  ),
  (
    '40675563',
    'Could It Bee? Honey Ingestion Induces Comparable Metabolic Responses to Traditional Carbohydrate-Based Sports Nutrition Product During 3-Hr Steady-State Cycling and Subsequent Exercise Capacity Test.',
    'Fortis HO, Ravikanti S, Barrett JS, Lopez EM, Bampouras TM, Haworth JJ, Areta JL, Pugh JN',
    'International journal of sport nutrition and exercise metabolism',
    2025,
    '2025-07-15',
    'https://pubmed.ncbi.nlm.nih.gov/40675563/',
    array['Fueling & Nutrition', 'Gut Training'],
    'In a randomized crossover study, 12 trained male cyclists ingested 90 grams per hour of carbohydrate as either honey or a traditional sports nutrition product during 180 minutes of steady-state cycling followed by a capacity test. There were no differences in total carbohydrate oxidation, fat oxidation, gastrointestinal symptoms, time to fatigue, or breath hydrogen between conditions. Honey matched commercial sports products across all measured outcomes.',
    'Honey is a viable and potentially more affordable alternative to commercial sports nutrition products for endurance fueling at 90 grams per hour. The similar GI tolerance and metabolic responses suggest athletes can use it confidently during prolonged cycling without performance compromise.',
    'At 90 grams per hour, this is the first study to test honey at the high carbohydrate intake rates that modern endurance nutrition recommends. The practical and cost implications are significant for athletes spending heavily on commercial products.',
    3,
    5,
    4,
    4,
    5,
    0,
    0,
    0,
    0,
    0,
    true
  ),
  -- ===== TRIATHLON =====
  (
    '41288839',
    'Modeling Performance in IRONMAN70.3 Age Group Triathletes.',
    'Thuany M, Valero D, Villiger E, Forte P, Weiss K, Andrade MS, Nikolaidis PT, Cuk I, Rosemann T, Knechtle B',
    'Sports medicine - open',
    2025,
    '2025-11-25',
    'https://pubmed.ncbi.nlm.nih.gov/41288839/',
    array['Pacing', 'Periodization'],
    'This study used machine learning to model performance in 823,464 IRONMAN 70.3 finishers between 2004 and 2020. Using age, sex, country of origin, and race location as predictors, the Random Forest model identified that men under 30 from Switzerland or Denmark competing in events like IRONMAN 70.3 Austria or Switzerland presented the best performance profiles. The model captured complex non-linear interactions between demographic and environmental factors.',
    'Choose your IRONMAN 70.3 venue strategically. Certain courses consistently produce faster times due to terrain, climate, and competitive field composition. Understanding your own performance profile relative to course demands can inform venue selection for personal records.',
    'Largest IRONMAN 70.3 analysis ever conducted, spanning over 800,000 finisher records. The machine learning approach captures interactions that traditional statistical models miss, providing genuinely new insights for race planning.',
    3,
    3,
    5,
    4,
    4,
    4,
    0,
    0,
    0,
    0,
    true
  ),
  (
    '40901845',
    'Sex differences in performance and pacing in the greatest Quintuple Iron ultra-triathlon race in history: The IUTA World Championship 2024 in France.',
    'Knechtle B, Leite LB, Duric S, Cuk I, Andrade MS, Scheer V, Nikolaidis PT, Weiss K, Rosemann T, Forte P',
    'PloS one',
    2025,
    '2025-09-03',
    'https://pubmed.ncbi.nlm.nih.gov/40901845/',
    array['Pacing', 'Female Athletes'],
    'This study analyzed pacing in 11 female and 24 male finishers at the 2024 Quintuple Iron Ultra-Triathlon World Championship in Colmar, France, the fastest and largest such event in history. Women outperformed men in swimming and cycling, likely due to the elite nature of the highly selected female cohort with a high completion rate. Both sexes showed consistent pacing in cycling, but women exhibited greater variability in running, possibly due to more frequent breaks.',
    'In ultra-triathlon, women may have a relative advantage in the swimming and cycling legs. Female athletes should capitalize on these strengths while developing strategies to maintain running consistency. The pacing data suggest that break management in the run leg is a key differentiator for women.',
    'At five times the Ironman distance, this is about as extreme as organized multi-sport racing gets. The finding that women outperformed men in two of three disciplines at the world championship level challenges assumptions about sex differences at ultra distances.',
    5,
    3,
    5,
    4,
    4,
    4,
    0,
    0,
    0,
    0,
    true
  ),
  (
    '41630099',
    'High Test-Retest Reliability but Questionable Validity: Assessing a Step-Ramp-Step Protocol to Estimate Critical Power and W'' in Trained Triathletes.',
    'Rousseau Q, Rabita G, Brunet E, Dorel S, Siblot A, Morales-Artacho AJ',
    'Medicine and science in sports and exercise',
    2026,
    '2026-02-02',
    'https://pubmed.ncbi.nlm.nih.gov/41630099/',
    array['Lactate Threshold', 'VO2max', 'Periodization'],
    'This study evaluated a modified Step-Ramp-Step protocol for estimating critical power and W prime in 12 trained male triathletes. The protocol reliably measured VO2max, gas exchange threshold, and respiratory compensation point with high test-retest reliability. However, the corrected power at the respiratory compensation point systematically underestimated critical power, meaning athletes using this shortcut protocol may set training zones too low.',
    'If you use a ramp test to estimate critical power for training zones, be aware that the respiratory compensation point underestimates true critical power. Validate your CP against multiple time-trial efforts when precision matters. The Step-Ramp-Step is reliable for tracking fitness changes over time even if the absolute values are slightly low.',
    'Important validation study for the growing number of athletes and coaches using single-visit ramp protocols to set training zones. The reliability is encouraging for longitudinal tracking, but the validity gap means absolute zone boundaries may need correction.',
    3,
    4,
    5,
    3,
    5,
    2,
    0,
    0,
    0,
    0,
    true
  ),
  (
    '41305679',
    'Post-Exercise Nutrition Knowledge and Adherence to Recommendations Among Amateur Endurance Athletes.',
    'Csanaky L, Asztalos AC, Toth D, Polyak E, Figler M',
    'Nutrients',
    2025,
    '2025-11-20',
    'https://pubmed.ncbi.nlm.nih.gov/41305679/',
    array['Fueling & Nutrition', 'Recovery'],
    'This study assessed post-exercise nutrition knowledge and adherence in 113 amateur Hungarian endurance athletes. Only 1.8 percent correctly identified the optimal carbohydrate content for rapid glycogen resynthesis. More athletes prioritized protein over carbohydrate in post-exercise meals. Triathletes scored significantly higher than runners on the nutrition adherence scale. Consulting a dietitian was positively associated with better practices, while relying on online sources predicted worse knowledge.',
    'Prioritize carbohydrate over protein in your immediate post-exercise nutrition, especially after long sessions. Seek advice from qualified sports dietitians rather than social media. The knowledge gap around post-exercise carbohydrate needs is widespread even among experienced athletes.',
    'Highlights a critical blind spot in endurance athlete nutrition: the protein-obsessed culture has overshadowed the fundamental importance of post-exercise carbohydrate for glycogen resynthesis. The dietitian versus social media finding is a strong signal for where athletes should seek nutrition guidance.',
    4,
    4,
    5,
    4,
    4,
    3,
    3,
    0,
    0,
    0,
    true
  ),
  -- ===== ROWING =====
  (
    '42222289',
    'Hematological, inflammatory, and hypoxia-responsive adaptations to 18-day normobaric live high-train low training in elite rowers.',
    'Kasperska A, Dziewiecka H, Jankowski W, Mikulski T, Czerniec I, Skarpanska-Stejnborn A, Ostapiuk-Karolczuk J',
    'Frontiers in physiology',
    2026,
    '2026-05-13',
    'https://pubmed.ncbi.nlm.nih.gov/42222289/',
    array['VO2max', 'Periodization', 'Recovery'],
    'This study investigated the effects of an 18-day normobaric live high-train low protocol on hematological, inflammatory, and hypoxia-responsive biomarkers in 13 elite male rowers. EPO levels were higher in the hypoxic group after 18 days, reticulocyte counts increased early and remained elevated, and hematocrit was significantly higher by day 18. CRP levels increased transiently at days 6 and 18, indicating a mild inflammatory response without clinical signs of infection.',
    'An 18-day normobaric LH-TL protocol produces measurable erythropoietic responses in elite rowers. However, the transient inflammatory markers and immune modulation indicate this is an additional physiological stress that requires monitoring. Plan recovery carefully around altitude blocks.',
    'Demonstrates that normobaric hypoxic rooms can produce hematological adaptations similar to natural altitude in rowers. The detailed time-course sampling at six points across 18 days provides a more nuanced picture of adaptation than typical pre-post designs.',
    3,
    3,
    3,
    3,
    3,
    2,
    5,
    0,
    3,
    0,
    true
  ),
  -- ===== SWIMMING =====
  (
    '42218755',
    'Selected immunoendocrine and performance adaptations to upper-body plyometric training and beta-alanine supplementation in male swimmers.',
    'Gao H, Yu X, Guo Z',
    'Journal of the International Society of Sports Nutrition',
    2026,
    '2026-05-31',
    'https://pubmed.ncbi.nlm.nih.gov/42218755/',
    array['Strength Training', 'Supplementation'],
    'Thirty trained male swimmers were randomly assigned to upper-body plyometric training with beta-alanine, plyometric training with placebo, or a control group over eight weeks. Both plyometric groups improved across all performance outcomes including medicine ball throw, push-up endurance, bench press 1RM, swim ergometer power, and 50 to 200 meter freestyle times. Beta-alanine supplementation further amplified training adaptations and promoted a more favorable immunoendocrine profile.',
    'Add upper-body plyometric exercises to your swim training to improve power output and freestyle performance. Combining with beta-alanine supplementation at standard dosing may provide additional benefits beyond plyometrics alone, particularly for events from 50 to 200 meters.',
    'A clean three-group design with a genuine placebo control. The finding that plyometric training improved freestyle times across sprint to middle-distance events makes it applicable to a wide range of competitive swimmers.',
    1,
    1,
    4,
    1,
    1,
    5,
    2,
    0,
    0,
    0,
    true
  ),
  (
    '41903613',
    'Body position and immersion associate with lung function differently in healthy and asthmatic endurance athletes.',
    'Rodrigues J, Jesus B, Caseiro P, Rama L',
    'Respiratory medicine',
    2026,
    '2026-03-26',
    'https://pubmed.ncbi.nlm.nih.gov/41903613/',
    array['VO2max', 'Respiratory Training'],
    'This study measured spirometry in 45 male endurance athletes across four positions: seated on land, prone on land, seated immersed, and prone immersed. The group included swimmers, triathletes, and runners. All lung function variables decreased with immersion and prone position, except the FEV1/FVC ratio which remained unchanged. Athletes with asthma or allergies showed different patterns of respiratory change, with position and hydrostatic pressure effects accumulating in those with pre-existing respiratory conditions.',
    'If you have exercise-induced asthma or allergies, immersion and prone position compound your respiratory limitations. Swimmers and triathletes with these conditions should pay extra attention to breathing technique and may benefit from pre-swim bronchodilator use. Land-based athletes without respiratory conditions can largely ignore these effects.',
    'One of few studies to quantify the combined effects of body position and water immersion on lung function in endurance athletes. The clinical implications for asthmatic swimmers and triathletes are direct and actionable.',
    2,
    1,
    4,
    2,
    1,
    5,
    2,
    0,
    0,
    0,
    true
  ),
  -- ===== CROSS-COUNTRY SKIING =====
  (
    '41957792',
    'Oxidative stress and antioxidant enzyme activities in elite female Turkish cross-country skiers.',
    'Seyhan S, Bilici MF, Demir H, Bilici OF, Kahraman MZ, Sahin MF, Aglar S, Soylu C, Acar G, Kizilca S',
    'BMC sports science, medicine & rehabilitation',
    2026,
    '2026-04-09',
    'https://pubmed.ncbi.nlm.nih.gov/41957792/',
    array['Recovery', 'Female Athletes'],
    'This study compared resting oxidative stress biomarkers between 17 elite female cross-country skiers and 17 matched sedentary women. Skiers showed significantly higher catalase activity and glutathione concentrations, and lower malondialdehyde levels, indicating superior antioxidant defense at rest. Within the skier group, catalase and glutathione were correlated, suggesting a coordinated antioxidant system developed through chronic endurance training.',
    'Chronic endurance training builds a robust antioxidant defense system that protects against oxidative damage even at rest. This adaptation takes years of consistent training. Acute supplementation with high-dose antioxidants may interfere with this natural adaptation process.',
    'Rare data on elite female endurance athletes in a winter sport. The finding that trained athletes have fundamentally different resting redox profiles supports the concept that antioxidant supplementation during training may be counterproductive by blunting adaptive signaling.',
    3,
    3,
    3,
    3,
    3,
    2,
    2,
    2,
    5,
    0,
    true
  ),
  (
    '41901624',
    'Investigation of the Effects of Ski Ergometer-Based Training on Respiratory Functions and Isokinetic Muscle Strength in Cross-Country Skiers.',
    'Sevindik Aktas B, Akaras E, Polat M, Kara S, Kilic M',
    'Medicina (Kaunas, Lithuania)',
    2026,
    '2026-03-14',
    'https://pubmed.ncbi.nlm.nih.gov/41901624/',
    array['Strength Training', 'Respiratory Training', 'VO2max'],
    'An eight-week ski ergometer training program performed three times per week at 80 to 90 percent of maximal heart rate significantly improved forced vital capacity, FEV1, and upper-extremity isokinetic peak power in competitive cross-country skiers. Strong positive correlations between dominant and nondominant limb strength indicated balanced bilateral development and high neuromuscular coordination from the ergometer work.',
    'The ski ergometer is an effective tool for simultaneously improving upper-body power and respiratory capacity in cross-country skiers. Use it as a complement to on-snow training, especially during off-season or poor-weather periods. Target 80 to 90 percent of max heart rate for 2.5 km per session.',
    'Demonstrates that the SkiErg, widely available in commercial gyms, can produce measurable sport-specific adaptations in competitive skiers. The dual benefit to both respiratory capacity and upper-body power makes it a time-efficient training tool.',
    2,
    2,
    2,
    2,
    2,
    1,
    3,
    1,
    5,
    0,
    true
  ),
  (
    '41665741',
    'Mind-Muscle-Environment Interactions: Psychophysiological Determinants of Optimal Pacing in Olympic Winter Endurance Sports.',
    'Edholm P, Bouten LJL, Holmberg HC, Losnegard T, Hettinga FJ',
    'Scandinavian journal of medicine & science in sports',
    2026,
    '2026-02-01',
    'https://pubmed.ncbi.nlm.nih.gov/41665741/',
    array['Pacing', 'Periodization'],
    'This narrative review synthesizes psychophysiological determinants of pacing in cross-country skiing, biathlon, and speed skating. The physiological engine and psychological operator interact to shape pacing behavior, with environmental factors like head-to-head racing, variable weather, and undulating terrain adding complexity. The affordance competition hypothesis is proposed as a framework for understanding pacing as continuous decision-making driven by mind-muscle-environment interactions.',
    'Integrate psychological pacing skills into physical training. Practice decision-making under fatigue in variable conditions rather than only in steady-state environments. Build a phased training approach that develops physiological and psychological capacity together within ecologically valid settings.',
    'Provides a unifying framework for pacing across three distinct winter endurance sports. The affordance competition hypothesis offers coaches a concrete model for training pacing decisions, not just pacing execution.',
    3,
    3,
    3,
    3,
    3,
    1,
    1,
    4,
    5,
    0,
    true
  ),
  (
    '41653367',
    'Olympic Snow Sports: Current Insights and Future Directions for Milano Cortina 2026 and Beyond.',
    'Zoppirolli C, Fornasiero A, Sporri J, Losnegard T, Elfmark OA, Sandbakk O, Holmberg HC',
    'Scandinavian journal of medicine & science in sports',
    2026,
    '2026-02-01',
    'https://pubmed.ncbi.nlm.nih.gov/41653367/',
    array['Periodization', 'Strength Training', 'VO2max'],
    'This comprehensive narrative review synthesizes performance determinants across all Olympic snow sports, from cross-country skiing and biathlon to alpine skiing and freestyle. Endurance-dominant disciplines rely on high aerobic capacity and movement efficiency, while gravity and technical disciplines emphasize neuromuscular power. Nordic combined represents a hybrid. The review identifies critical knowledge gaps in sex-specific analyses, on-snow monitoring technologies, and energy availability.',
    'Training models in snow sports should reflect sport-specific demand profiles. Endurance-dominant disciplines need high-volume aerobic work with sport-specific strength. Technical disciplines need neuromuscular power and skill. Avoid applying a single training template across different snow sports.',
    'The most comprehensive snow sports review to date, covering disciplines from cross-country skiing to snowboarding. The identification of knowledge gaps, particularly around female athletes and energy availability, provides a clear research agenda.',
    3,
    3,
    2,
    3,
    2,
    1,
    1,
    3,
    5,
    0,
    true
  ),
  -- ===== SPEED SKATING =====
  (
    '41758881',
    'Effects of slide-board-based high-intensity interval versus moderate-intensity continuous training on aerobic and anaerobic capacity in young speed skaters.',
    'Zhang K, Qi J, Shi P, Xue X, Liu Y',
    'PloS one',
    2026,
    '2026-02-27',
    'https://pubmed.ncbi.nlm.nih.gov/41758881/',
    array['VO2max', 'Lactate Threshold', 'Strength Training'],
    'Twenty-seven youth speed skaters were randomly assigned to two HIIT protocols or moderate-intensity continuous training on a slide-board simulator for four weeks. Both HIIT protocols significantly improved VO2max, relative peak power, relative mean power, and reduced fatigue index, while MICT produced no significant changes. The 4-minute work to 1-minute rest protocol showed greater anaerobic improvements, while the 3-minute work to 2-minute rest protocol better enhanced fatigue resistance.',
    'For speed skaters, slide-board HIIT is superior to moderate-intensity continuous training for short-term fitness gains. Match the HIIT structure to your racing distance: longer rest intervals for middle- to long-distance skaters focused on fatigue resistance, shorter rest for sprinters developing explosive power.',
    'Sport-specific HIIT using a slide-board simulator transfers directly to skating biomechanics. The finding that four weeks of MICT alone produced no measurable adaptation challenges the value of moderate-intensity-only training blocks for youth skaters.',
    1,
    1,
    1,
    1,
    1,
    0,
    0,
    5,
    2,
    0,
    true
  ),
  (
    '41707040',
    'Olympic Ice Sports: A Narrative Review and Perspectives Toward Milano-Cortina 2026.',
    'Sperlich B, Zoppirolli C, Hettinga F, Hannigan LS, Colyer S, Vigh-Larsen JF, Fornasiero A, Holmberg HC',
    'Scandinavian journal of medicine & science in sports',
    2026,
    '2026-02-01',
    'https://pubmed.ncbi.nlm.nih.gov/41707040/',
    array['Periodization', 'Strength Training', 'VO2max'],
    'This review synthesizes performance determinants across all Olympic ice sports. Long- and short-track speed skating require 900 to 1100 hours of annual training with polarized, mixed-modal approaches. Bobsleigh and skeleton training mirrors sprint athletes with a focus on start velocity. Ice hockey demands managing high-intensity intermittent efforts at 40 to 50 percent of total distance at high speed. Figure skating hinges on rotational power for multi-rotation jumps.',
    'Speed skaters should adopt polarized training with 900 to 1100 annual training hours combining on-ice and cross-training modalities. For tactical sports like short-track and ice hockey, include decision-making components in training rather than just physiological conditioning.',
    'The most comprehensive review of performance determinants across all Olympic ice sports. Particularly valuable for coaches moving between disciplines or working with multi-sport athletes who need to understand the distinct demand profiles.',
    1,
    1,
    1,
    1,
    1,
    0,
    0,
    5,
    3,
    2,
    true
  ),
  (
    '40732429',
    'Characteristics of Post-Exercise Lower Limb Muscle Tremor Among Speed Skaters.',
    'Kulis S, Pietraszewski P, Callegari B',
    'Sensors (Basel, Switzerland)',
    2025,
    '2025-07-10',
    'https://pubmed.ncbi.nlm.nih.gov/40732429/',
    array['Recovery', 'Strength Training'],
    'This study examined post-exercise lower limb muscle tremor in 19 elite speed skaters from Poland''s national team compared to 19 non-athlete controls. Tremor amplitude and frequency increased significantly after both sprint and endurance training compared to rest. Sprint training produced greater high-frequency tremor increases than endurance training. No differences were observed between limbs, indicating symmetrical neuromuscular adaptation in trained skaters.',
    'Post-exercise tremor analysis using a simple accelerometer could serve as a practical tool for monitoring neuromuscular fatigue in speed skaters. Asymmetric tremor responses between legs may indicate imbalanced fatigue or injury risk. Sprint sessions produce distinct neuromuscular fatigue signatures compared to endurance sessions.',
    'Introduces tremor analysis as a practical, non-invasive monitoring tool for skating. The symmetrical adaptation between limbs is reassuring for a sport where bilateral power production is critical for skating technique.',
    1,
    1,
    1,
    1,
    1,
    0,
    0,
    5,
    1,
    0,
    true
  ),
  -- ===== BIATHLON =====
  (
    '41902078',
    'Quantitative Comparative Analysis of Annual Training Volume and Intensity Distribution of Male Biathlon National Team and University Athletes Using Global Positioning Systems and Wearable Devices.',
    'Zhang G, Hu Q, Kim Y, Choi Y',
    'Sensors (Basel, Switzerland)',
    2026,
    '2026-03-18',
    'https://pubmed.ncbi.nlm.nih.gov/41902078/',
    array['Periodization', 'HRV'],
    'This study compared annual training characteristics between Korean biathlon national team and university athletes using GPS and heart rate data over two years. National team athletes accumulated 812 versus 606 hours and 6359 versus 4130 km annually. They spent proportionally less time at low intensity and more at mid and high intensities. During high-intensity training, national team athletes maintained 78.5 percent ski-specific work versus only 46.4 percent for university athletes.',
    'Progression from university to national team level in biathlon requires not just more volume but a shift toward higher-intensity and more sport-specific training. University athletes should gradually increase ski-specific high-intensity work rather than relying on running as a substitute for on-snow intensity.',
    'One of the first studies to quantify the structural training differences between development and elite levels in biathlon using objective GPS and heart rate data. The specificity gap in high-intensity training is a clear target for developmental programs.',
    2,
    2,
    2,
    2,
    1,
    0,
    0,
    2,
    5,
    0,
    true
  ),
  -- ===== HEAT ACCLIMATION =====
  (
    '41267396',
    'Long-term passive heat acclimation enhances maximal oxygen consumption via haematological and cardiac adaptation in endurance runners.',
    'Jenkins EJ, Killick JA, Zerilli O, Douglas AJM, Corr L, Hughes MG, Tremblay JC, Stembridge M',
    'The Journal of physiology',
    2025,
    '2025-11-20',
    'https://pubmed.ncbi.nlm.nih.gov/41267396/',
    array['Heat Acclimation', 'VO2max'],
    'Ten well-trained runners completed five weeks of hot-water immersion alongside normal training in a within-subject crossover design. Passive heating increased hemoglobin mass by 33 grams, blood volume by 284 mL, and left ventricular end-diastolic volume by 10 mL. These coordinated hematological and cardiac adaptations produced a 2.7 mL per kg per minute improvement in VO2max and a 0.8 km per hour increase in treadmill speed at VO2max.',
    'Five weeks of daily 45-minute hot-water immersion at 40 degrees Celsius or higher, done alongside normal training, can meaningfully increase VO2max through both blood volume expansion and cardiac remodeling. This passive approach lets athletes maintain training intensity while adding a potent physiological stimulus.',
    'Landmark study demonstrating that passive heat, not just exercise-induced heat stress, can produce coordinated adaptations across the entire oxygen transport chain. The crossover design with 10 well-trained runners and the R-squared of 0.96 for the full model make the evidence compelling.',
    5,
    5,
    5,
    5,
    5,
    3,
    3,
    2,
    3,
    0,
    true
  ),
  (
    '41548048',
    'Assessing passive heat acclimation as a dual stimulus for erythropoiesis and central cardiovascular adaptation in well-trained runners.',
    'Dunn RA, Bellini DP, McCollum TB, Ky AT, Brojanac AP, Hernandez MI, Keefe MS',
    'The Journal of physiology',
    2026,
    '2026-01-17',
    'https://pubmed.ncbi.nlm.nih.gov/41548048/',
    array['Heat Acclimation', 'VO2max'],
    'This study assessed passive heat acclimation via hot water immersion as a dual stimulus for erythropoiesis and central cardiovascular adaptation in well-trained runners. The findings complement the growing evidence that passive heat exposure can simultaneously stimulate red blood cell production and cardiac remodeling, offering endurance athletes a practical way to enhance oxygen-carrying capacity without additional training load.',
    'Use passive heat acclimation as a dual-purpose intervention targeting both blood volume expansion and cardiac adaptation. This approach adds minimal training stress while providing a potent physiological stimulus for endurance performance.',
    'Extends the passive heat acclimation literature by examining the dual mechanisms simultaneously. Supports the practical integration of heat interventions into endurance training programs.',
    5,
    5,
    5,
    5,
    5,
    3,
    3,
    2,
    3,
    0,
    true
  ),
  -- ===== ALTITUDE TRAINING =====
  (
    '42200179',
    'Live high, train smart: translating altitude physiology to best practice with mechanistic insights.',
    'Faiss R, Girard O',
    'Frontiers in physiology',
    2026,
    '2026-05-11',
    'https://pubmed.ncbi.nlm.nih.gov/42200179/',
    array['VO2max', 'Periodization'],
    'Sixty years after the first altitude training symposium, this perspective article reconceptualizes the performance improvement vectors associated with altitude training. Beyond the traditional focus on hemoglobin mass and erythropoiesis, the authors map contemporary altitude strategies alongside their physiological mechanisms and propose a framework for evidence-informed practice. Key lessons from 25 years of research include optimal hypoxic dose, exposure timing, and the importance of accounting for inter-individual variability.',
    'When planning altitude training, target hemoglobin mass increases as the primary goal but recognize that non-hematological adaptations also contribute to performance. Personalize altitude protocols based on individual response patterns and use the 25-year evidence base to guide duration, severity, and timing of exposure.',
    'A timely synthesis from leading altitude researchers that moves beyond the simplistic view of altitude training as purely an erythropoietic stimulus. The framework for mapping strategy to mechanism helps coaches and athletes make more informed altitude training decisions.',
    4,
    4,
    4,
    4,
    4,
    3,
    3,
    3,
    4,
    0,
    true
  ),
  (
    '41351754',
    'Biomarkers predicting the effectiveness of normobaric altitude training.',
    'Klugel S, Nolte S, Hacker S, Kastner T, Walter N, Fleckenstein D, Maier C, Gebhardt K, Relogio A, Malhan D, Klemmer A, Stauber T, Hollander K, Kruger K',
    'European journal of applied physiology',
    2025,
    '2025-12-06',
    'https://pubmed.ncbi.nlm.nih.gov/41351754/',
    array['VO2max', 'Recovery'],
    'Fifteen highly trained athletes completed a 21-day live high-train low program in normobaric hypoxia. VO2max increased by an average of 3.1 percent, but individual responses ranged from minus 1.7 to plus 4.5 mL per kg per minute. Baseline blood biomarkers predicted responder status: monocyte percentage above 10 percent and neutrophil percentage above 50 percent were the strongest predictors. High-responders consistently displayed lower neutrophil-to-lymphocyte ratio and higher hematocrit before the altitude block.',
    'Get a comprehensive blood panel before starting an altitude training block. If your neutrophil-to-lymphocyte ratio is below 1.5 and hematocrit is above 42.5 percent, you are more likely to be a high responder. If your baseline immune profile suggests you are a low responder, consider alternative strategies like heat acclimation instead.',
    'First study to identify pre-altitude biomarkers that predict individual responsiveness. The practical implications are significant: rather than sending every athlete to altitude and hoping for the best, coaches can now make data-informed decisions about who will benefit most.',
    4,
    4,
    4,
    4,
    4,
    3,
    4,
    3,
    4,
    0,
    true
  ),
  (
    '41527186',
    'Effect of live-high, train-low strategy induced by chronic low-dose carbon monoxide exposure on haematological parameters and performance in trained individuals.',
    'Villanova S, Porcelli S, Ekstrom L, Cardinale DA',
    'Experimental physiology',
    2026,
    '2026-01-12',
    'https://pubmed.ncbi.nlm.nih.gov/41527186/',
    array['VO2max', 'Supplementation'],
    'Eight well-trained individuals completed a randomized crossover study comparing four weeks of daily low-dose carbon monoxide inhalation to simulate live-high, train-low versus ambient air, separated by a six-month washout. CO exposure significantly increased hemoglobin mass by 53.6 grams, red blood cell volume by 156.6 mL, and blood volume by 240.4 mL compared to the air-only control. However, muscle oxidative capacity and performance metrics remained unchanged.',
    'Low-dose CO inhalation can stimulate erythropoiesis at sea level without requiring altitude camps, but the hematological gains did not translate to measurable performance improvements in this four-week protocol. The approach may need longer duration or combination with other stimuli to produce performance benefits.',
    'A provocative study that raises both scientific and ethical questions about using CO inhalation as an altitude substitute. The hematological adaptations are clear, but the performance gap is a reminder that hemoglobin mass alone does not guarantee improved endurance capacity.',
    3,
    3,
    3,
    3,
    3,
    2,
    3,
    2,
    3,
    0,
    true
  ),
  -- ===== TRAINING METHODOLOGY =====
  (
    '41286008',
    'Machine learning-based personalized training models for optimizing marathon performance through pyramidal and polarized training intensity distributions.',
    'Qin G, Lee S, Kim S',
    'Scientific reports',
    2025,
    '2025-11-24',
    'https://pubmed.ncbi.nlm.nih.gov/41286008/',
    array['Periodization', 'Lactate Threshold', 'VO2max'],
    'One hundred twenty recreational marathon runners were randomly assigned to 16-week pyramidal or polarized training programs. Polarized training produced 30 percent greater marathon time improvements despite reduced training volume. Machine learning identified four response clusters: polarized responders at 31.5 percent, pyramidal responders at 31.9 percent, dual responders at 18.7 percent, and non-responders at 17.9 percent. Training experience was the strongest predictor: novice athletes favored pyramidal approaches while experienced athletes responded better to polarized training.',
    'If you have significant endurance training experience, polarized training is likely your best approach. If you are relatively new to endurance sport, a pyramidal distribution with gradual intensity progression may work better. There is no universal best approach, so track your individual response and adjust accordingly.',
    'The first large RCT to directly compare pyramidal and polarized training using machine learning to identify individual response patterns. The finding that training history predicts optimal methodology resolves much of the ongoing debate about which approach is superior: the answer is that it depends on the athlete.',
    5,
    5,
    5,
    5,
    5,
    3,
    3,
    3,
    4,
    2,
    true
  ),
  (
    '41169886',
    'Recent advances in training intensity distribution theory for cyclic endurance sports: theoretical foundations, model comparisons, and periodization characteristics.',
    'Sun Q, Yu Y, Cui J, Lin S, Wang X, Zhou T',
    'Frontiers in physiology',
    2025,
    '2025-10-15',
    'https://pubmed.ncbi.nlm.nih.gov/41169886/',
    array['Periodization', 'Lactate Threshold'],
    'This comprehensive review examines the theoretical foundations and practical applications of three training intensity distribution models: pyramidal, threshold, and polarized. Each model shows distinct structural advantages at different training phases and for different sports. The review demonstrates that phased adaptation and strategic integration of multiple models across a season may enhance cumulative training adaptations and competitive performance better than committing to a single model year-round.',
    'Do not commit to one training intensity distribution model for the entire season. Use pyramidal distribution during general preparation, shift toward threshold work during specific preparation, and employ polarized distribution approaching competition. The optimal model depends on your sport, training phase, and individual characteristics.',
    'The most thorough review of training intensity distribution theory to date. The periodization angle, showing how different TID models fit different training phases, is the most practically useful contribution and moves beyond the stale pyramidal-versus-polarized debate.',
    5,
    5,
    5,
    5,
    5,
    4,
    4,
    4,
    5,
    2,
    true
  ),
  (
    '40623686',
    'Substituting Low-Intensity Endurance Exercise With High-Intensity Microintervals: Responses to Acute Exercise.',
    'Matomaki P, Iivari M, Nuuttila OP, Malinen T',
    'International journal of sports physiology and performance',
    2025,
    '2025-07-07',
    'https://pubmed.ncbi.nlm.nih.gov/40623686/',
    array['VO2max', 'Lactate Threshold', 'HRV'],
    'Thirteen endurance athletes completed 45-minute cycling sessions comparing continuous low-intensity exercise with three microinterval protocols alternating very short bursts at VO2max intensity with recovery. The microinterval protocols maintained heart rate, VO2, blood lactate, and fat oxidation responses equivalent to continuous low-intensity exercise despite including efforts at 111 percent of VO2max-associated power. The researchers classify microintervals as oscillating low-intensity exercise.',
    'Microintervals of 4 to 10 seconds at VO2max power alternating with 6 to 20 seconds of easy spinning can replace continuous low-intensity rides while adding neuromuscular stimulus without metabolic cost. This is a genuine low-intensity alternative that maintains aerobic training benefits while breaking monotony.',
    'This challenges the assumption that any high-power effort is automatically high-intensity training. The metabolic responses clearly show these ultra-short bursts do not accumulate lactate or elevate heart rate beyond the low-intensity zone, creating a new exercise classification between traditional easy riding and intervals.',
    3,
    5,
    4,
    3,
    5,
    2,
    2,
    2,
    3,
    0,
    true
  ),
  -- ===== MARATHON / RUNNING =====
  (
    '41351755',
    'Toward a record-eligible sub-2-hour marathon: an updated integrative framework of Physiological, technological, and cognitive determinants.',
    'Grivas GV',
    'European journal of applied physiology',
    2025,
    '2025-12-06',
    'https://pubmed.ncbi.nlm.nih.gov/41351755/',
    array['VO2max', 'Running Economy', 'Pacing', 'Fueling & Nutrition'],
    'This narrative review synthesizes the physiological, technological, and cognitive requirements for an officially ratified sub-2-hour marathon. The required profile includes VO2max of 75 to 85 mL per kg per minute, running economy of 190 mL per kg per km or better at 21 km per hour, fractional utilization of 90 to 94 percent VO2max, carbohydrate intake of 60 to 100 grams per hour, temperature around 10 degrees Celsius, and the cognitive endurance to sustain near-threshold effort for two hours.',
    'Even for recreational runners, the sub-2-hour framework identifies the key performance determinants worth training: running economy, fractional utilization, and cognitive durability under fatigue. Focus training on the limiters specific to your level. Carbon-plated shoes, race nutrition, and environmental conditions all matter at every level.',
    'The most comprehensive and current analysis of the sub-2-hour marathon barrier. The inclusion of cognitive endurance alongside traditional physiological determinants reflects growing recognition that the brain is a key performance limiter in marathon running.',
    3,
    2,
    4,
    5,
    2,
    1,
    0,
    0,
    0,
    0,
    true
  ),
  (
    '41179514',
    'Early marathon running metrics from inertial measurement units predict significant pace reduction.',
    'Miyazaki Y, Matsui H, Zushi K, Fukui T',
    'Frontiers in sports and active living',
    2025,
    '2025-10-17',
    'https://pubmed.ncbi.nlm.nih.gov/41179514/',
    array['Running Economy', 'Pacing'],
    'Analyzing data from 1,437 marathon runners using lower-back inertial measurement units, this study developed a model to predict hitting the wall from first-half biomechanical data. The model achieved 73.9 percent accuracy, 75.8 percent recall, and 70.1 percent precision. Step length, ground contact time, and vertical stiffness were the strongest predictors of subsequent performance decline, outperforming pace-based predictions alone.',
    'If you have access to running biomechanics data from an IMU, monitor step length decay, increasing ground contact time, and decreasing vertical stiffness during the first half of a marathon. These signals predict a second-half collapse before pace deterioration becomes obvious, giving you an earlier warning window to adjust effort.',
    'Practical application of functional data analysis to marathon racing. The 1,437-runner dataset from real races and the use of consumer-grade IMU data make this immediately applicable. A step beyond traditional pace-based pacing tools.',
    3,
    2,
    3,
    5,
    1,
    0,
    0,
    0,
    0,
    0,
    true
  ),
  -- ===== SUPPLEMENTATION & NUTRITION =====
  (
    '41590651',
    'The Effect of Acute Supplementation of Branched Chain Amino Acids on Serum Metabolites During Endurance Exercise in Healthy Young Males: An Integrative Metabolomics and Correlation Analysis Based on a Randomized Crossover Study.',
    'Zhang X, Wang X, Luan C, Wang Y, Li J, Shan W, Ni Z, Xu C, Gong L',
    'Metabolites',
    2026,
    '2026-01-02',
    'https://pubmed.ncbi.nlm.nih.gov/41590651/',
    array['Supplementation', 'Fueling & Nutrition', 'Recovery'],
    'In a randomized crossover trial, eight healthy active males received either BCAA or placebo supplementation for three days before a high-intensity cycling test. BCAA supplementation enhanced fat oxidation, attenuated post-exercise increases in plasma ammonia, creatine kinase, and lactate dehydrogenase, and promoted coordinated regulation of fatty acid oxidation and tryptophan-related pathways. The metabolomics analysis revealed BCAA intake improved membrane stability and energy supply.',
    'Short-term BCAA supplementation before intense endurance sessions may enhance fat oxidation and reduce markers of muscle damage. Consider using BCAAs in the three days leading into key training sessions or competitions. The benefits appear to work through improved lipid and amino acid metabolism.',
    'Uses untargeted metabolomics to reveal mechanisms behind BCAA supplementation that previous studies using single biomarkers could not detect. The coordinated regulation of fatty acid oxidation and tryptophan pathways provides mechanistic support for subjective reports of reduced fatigue with BCAA use.',
    3,
    4,
    4,
    3,
    4,
    2,
    2,
    2,
    3,
    2,
    true
  ),
  -- ===== CONCURRENT / STRENGTH TRAINING =====
  (
    '41576259',
    'The Effectiveness of a 10-Week Concurrent Strength and Endurance Training Program on the Physical Readiness of Trained British Army Soldiers.',
    'Nevin J, Suffield C, Mutch S, Glass M, Sadler S, Mclay W, Coonan L, Penver R, Beckingham J',
    'Journal of strength and conditioning research',
    2026,
    '2026-02-01',
    'https://pubmed.ncbi.nlm.nih.gov/41576259/',
    array['Strength Training', 'Periodization'],
    'Forty-eight trained British Army soldiers were randomly assigned to a 10-week concurrent strength and endurance program based on block periodization or traditional military PT. The concurrent program produced significantly greater improvements in hex bar deadlift and pull-up performance with superior effect sizes across all measures. However, neither group improved aerobic capacity, suggesting that additional endurance-specific volume may be needed alongside strength work.',
    'A concurrent training program using block periodization is more effective than traditional circuit-based training for developing strength and power while maintaining endurance. But if aerobic capacity improvement is a priority, ensure at least two dedicated endurance sessions per week on top of strength work.',
    'Clean RCT in trained military personnel, not untrained subjects. The finding that block periodization-based concurrent training outperformed traditional military PT has direct implications for how endurance athletes should structure concurrent strength programs.',
    3,
    3,
    3,
    3,
    3,
    2,
    2,
    2,
    3,
    3,
    true
  ),
  -- ===== FATIGUE & PERFORMANCE =====
  (
    '42099913',
    'Fatigue protocols and athletic performance: a systematic review with a focus on ecological relevance.',
    'Yu Y, Zhang X, Zhang N, Qu Y, Wang X, He K',
    'Frontiers in physiology',
    2026,
    '2026-04-22',
    'https://pubmed.ncbi.nlm.nih.gov/42099913/',
    array['Recovery', 'Pacing'],
    'This systematic review of 56 studies examined how physical and mental fatigue affect athletic performance. Physical fatigue generally impaired physical performance but had mixed effects on cognitive performance. Mental fatigue impaired endurance, motor skill, and cognitive performance but showed less consistent effects on strength and power. Dual fatigue combining physical and mental stress showed negative effects on endurance and cognitive performance, with limited evidence available.',
    'Train both physical and mental fatigue resistance. Mental fatigue impairs endurance performance even when physical capacity is unaffected. Include cognitively demanding tasks during training sessions to build resilience against the dual fatigue experienced in competition.',
    'The most comprehensive systematic review of fatigue effects on performance to date. The distinction between physical, mental, and dual fatigue has direct practical implications for how athletes and coaches structure training to build fatigue resistance.',
    4,
    4,
    4,
    4,
    4,
    3,
    3,
    3,
    3,
    3,
    true
  )
on conflict (pubmed_id) do nothing;
