insert into public.research_library_entries (
  pubmed_id,
  title,
  authors,
  journal,
  publication_year,
  publication_date,
  pubmed_url,
  topic_tags,
  plain_english_summary,
  practical_takeaway,
  commentary,
  ultra_score,
  gravel_score,
  triathlon_score,
  published
)
values
  -- ===== ULTRA / TRAIL RUNNING =====
  (
    '42258036',
    'Fuelled or Fooled? Examining the Evidence and Mechanisms Behind Ultra-High Carbohydrate Intake in Endurance Athletes.',
    'Plews DJ, Booth PD, Krieger T, Mündel T, Mears SA',
    'Sports medicine',
    2026,
    '2026-06-05',
    'https://pubmed.ncbi.nlm.nih.gov/42258036/',
    array['Fueling & Nutrition', 'Carbohydrate'],
    'This review critically examines the science behind ultra-high carbohydrate ingestion strategies (above 90 g per hour) that have become widespread among elite endurance athletes. The authors find a disconnect between metabolic data and real-world adoption: current oxidation ceilings cannot fully explain the performance benefits athletes report. Emerging mechanisms including substrate selection shifts, enhanced lactate shuttling, and central nervous system effects may play a role.',
    'Do not blindly chase the highest carb intake numbers. The evidence for going above 90 g/h is weaker than marketing suggests. Focus on training the gut with glucose-fructose blends at tolerable rates, and recognize that individual variation in carbohydrate oxidation capacity is large. Test your fueling strategy in training before racing.',
    'A much-needed reality check from a credible author group. This paper questions whether the carb arms race has outpaced the science, while still acknowledging that high carb intake during endurance exercise is clearly beneficial. Essential reading for anyone advising athletes on race nutrition.',
    5,
    5,
    5,
    true
  ),
  (
    '42097589',
    'Durability in Trail Running: Coupled Physiological and Biomechanical Responses to Prolonged Submaximal and Repeated Uphill Time Trials in Trained Trail Runners.',
    'Jaén-Carrillo D, Bruce CD, Gobbo C, Howe C, Lawley JS',
    'International journal of sports physiology and performance',
    2026,
    '2026-05-07',
    'https://pubmed.ncbi.nlm.nih.gov/42097589/',
    array['Running Economy', 'Training Structure'],
    'Twenty-three trail runners completed a 180-minute treadmill protocol with repeated uphill time trials every 60 minutes. Heart rate and perceived effort drifted upward, and a metabolic shift toward fat reliance occurred, but oxygen cost and leg stiffness were preserved throughout. Trail runners showed high durability, maintaining biomechanical stability and running efficiency despite increasing fatigue.',
    'Trained trail runners can rely on their durability to hold form during long efforts. To build this resilience, include long runs with repeated climbs that train both the metabolic shift toward fat and the biomechanical maintenance under fatigue. The fact that perceived effort rises while actual efficiency holds suggests mental preparation is as important as physical.',
    'This is among the first studies to simultaneously track physiological and biomechanical durability in trail runners. The coupled analysis of both systems during repeated uphill time trials adds unique value compared to flat running studies.',
    5,
    3,
    3,
    true
  ),
  (
    '42085607',
    'Long-distance trail running induces functional iron deficiency driven by inflammation.',
    'Tobiasch AK, Dünnwald T, Adami PE, Garrandes F, Bermon S, Brunelli L, Griesmacher A, Irsara C, Koeck A, Seifert M, Bösch J, Fries D, Schobersberger W, Weiss G',
    'Blood advances',
    2026,
    '2026-05-05',
    'https://pubmed.ncbi.nlm.nih.gov/42085607/',
    array['Recovery', 'Injury Prevention', 'Supplementation'],
    'Seven elite athletes were tested before and after an 87-km World Championship trail race. The race triggered an inflammatory response that elevated hepcidin and ferritin while serum iron and transferrin saturation dropped, creating a state of functional iron deficiency. Blood cells showed gene expression changes consistent with restricted iron availability, and signs of intravascular hemolysis were also present.',
    'Ultra-distance racing creates temporary functional iron deficiency even when total iron stores are adequate. Athletes should monitor ferritin and transferrin saturation, not just hemoglobin, especially after major events. Allow adequate recovery before resuming intense training. Consider iron status testing as part of routine post-race bloodwork.',
    'Published in Blood Advances, this gives the cellular and molecular detail behind what endurance coaches have long suspected. The real-time gene expression data from immune cells during extreme exercise is cutting-edge and has direct implications for post-race recovery protocols.',
    5,
    3,
    3,
    true
  ),
  (
    '42061829',
    'Running Power Analysis of a World Champion: A Case Study From the Spanish Vertical, European Ultra, and World Trail Championships.',
    'Rodríguez-Medina J, Rodríguez-Marroyo JA',
    'International journal of sports physiology and performance',
    2026,
    '2026-04-29',
    'https://pubmed.ncbi.nlm.nih.gov/42061829/',
    array['Pacing', 'Training Structure'],
    'A world champion mountain runner was monitored using a Stryd power meter across three championship races of different formats: a 2.4-km vertical race, a 38-km sky race, and a 62-km sky ultra. Exercise intensity declined with increasing race duration, with the vertical race averaging 5.1 W/kg compared to 2.8 W/kg in the ultra. The athlete showed very large power advantages over sub-elite runners in shorter formats.',
    'Running power data can help quantify the specific demands of different mountain race formats and guide training prescription. Use power zones to structure workouts that match your target event. Vertical races demand sustained high-intensity output, while ultras require efficient low-to-moderate power over many hours.',
    'A rare inside look at world-class mountain running performance quantified with power data. The Z-score comparisons against sub-elite reference data clearly show where elite talent separates and can help ambitious athletes benchmark their own training.',
    5,
    3,
    2,
    true
  ),
  (
    '41664965',
    'Running kinematics, spatiotemporal variation and lower limb strength at different stages of a 156-km ultra-trail race.',
    'Nguyen AP, Esculier JF, Dubois B, VAN Cant J, Roy-Baillargeon O, Hebert-Losier K, Francisco B, Hingrand C, Delaunay PL, Mauvieux B, Pairot DE Fontenay B',
    'The Journal of sports medicine and physical fitness',
    2026,
    '2026-02-01',
    'https://pubmed.ncbi.nlm.nih.gov/41664965/',
    array['Running Economy', 'Injury Prevention'],
    'Fifty-five runners were tracked biomechanically during a 156-km ultra-trail race with 6000 meters of elevation gain. Foot strike pattern remained consistent throughout. Speed declined 14.2% and step length shortened 12.6%, while ground contact time increased 12.9%. Hip abductor and ankle plantar flexor strength decreased only late in the race.',
    'Experienced ultra-trail runners naturally adapt their biomechanics to manage fatigue without changing foot strike. Train hip abductor and calf strength specifically, as these are the muscle groups that decline in the final stages. Shortened step length is a normal fatigue adaptation, not a problem to fight.',
    'One of the largest biomechanical studies conducted during an actual ultra-trail race. The finding that foot strike pattern is remarkably stable across 156 km challenges the idea that fatigue causes dramatic gait changes in experienced runners.',
    5,
    2,
    2,
    true
  ),
  (
    '42232809',
    'The Comrades Marathon: a narrative review of physiological responses and health implications in the world''s oldest ultra-marathon.',
    'Knechtle B, Scheer V, Nikolaidis PT, Thuany M, Chlíbková D, Forte P, Leite LB, Weiss K, Rosemann T, Duric S',
    'Frontiers in physiology',
    2026,
    '2026-05-18',
    'https://pubmed.ncbi.nlm.nih.gov/42232809/',
    array['Hydration', 'Recovery', 'Injury Prevention'],
    'This comprehensive review synthesizes 42 published studies on the Comrades Marathon (roughly 89 km), held annually since 1921. Dehydration and hypernatremia were far more common than hyponatremia. Medical encounters occurred at rates up to 20 per 1000 starters. Faster, well-trained runners showed higher rates of post-race upper respiratory infection than slower runners. Peak performance occurred at roughly 30 years for men and 36 for women.',
    'At the Comrades and similar ultras, the risk of over-drinking and hyponatremia is lower than the risk of dehydration and hypernatremia. Drink to thirst rather than forcing fluid. Plan for immune suppression post-race, especially if you are a fast finisher who pushes hard. Allow at least 2 to 3 weeks of genuine recovery.',
    'The Comrades provides the longest continuous dataset in ultra-marathon research. The unusually high prevalence of acute kidney injury and hypernatremia compared to other ultras makes this review especially valuable for hydration strategy.',
    5,
    2,
    2,
    true
  ),
  (
    '42127094',
    'Screening for eating disorders and low energy availability in female trail runners: A cross-sectional study.',
    'Hill C, Vigne C, Basset P, Scheer V, Baud D',
    'PloS one',
    2026,
    '2026-05-13',
    'https://pubmed.ncbi.nlm.nih.gov/42127094/',
    array['Female Athletes', 'Fueling & Nutrition', 'Weight Management'],
    'A survey of 276 female trail runners found that 53.6% screened positive for eating disorder risk and 55.1% showed indicators of low energy availability. Risk factors for eating disorders included higher BMI and depression, while more than 3 years of trail running experience was an independent risk factor for low energy availability. The two conditions were significantly associated with each other.',
    'Low energy availability is alarmingly common in female trail runners, even among those who do not appear underweight. Coaches and athletes should proactively screen for it using validated tools. Training volume that increases over years can silently outpace caloric intake. Addressing fueling adequacy is not just about performance; it protects long-term health.',
    'The sample size and focused population make this one of the strongest studies on RED-S in trail running specifically. The finding that longer sport participation is itself a risk factor for low energy availability is a wake-up call for experienced female runners.',
    5,
    3,
    4,
    true
  ),
  (
    '42222487',
    'Electrolyte imbalance markers and acid-base disturbances in Brazilian male runners during a 45-km mountain ultramarathon.',
    'Ribas MR, Ribas DIR, Badicu G, Ferreira S, Matta MAT, Legnani E, Ardigò LP, Bassan JC',
    'PeerJ',
    2026,
    '2026-05-27',
    'https://pubmed.ncbi.nlm.nih.gov/42222487/',
    array['Hydration', 'Fueling & Nutrition'],
    'Forty runners were tracked during a 45-km mountain ultramarathon. Potassium dropped significantly in all performance groups, while lactate rose. Slower runners showed more acid-base disruption with lower pH and calcium. Faster runners maintained better electrolyte and acid-base homeostasis throughout the event.',
    'Electrolyte management matters beyond just sodium. Potassium depletion is universal in mountain ultras and may contribute to muscle cramping and fatigue. Include potassium-rich foods or supplements in your race nutrition plan. The ability to maintain acid-base balance appears to distinguish faster from slower finishers.',
    'Adds important detail about potassium and acid-base disturbances that are often overlooked in favor of sodium-focused hydration research. The performance-group stratification reveals patterns that whole-group averages would miss.',
    5,
    3,
    3,
    true
  ),
  (
    '42224084',
    'Effects of Advanced Footwear Technology in Trail Running Shoes on Running Economy.',
    'Joubert DP, Sanders J',
    'Journal of strength and conditioning research',
    2026,
    '2026-06-02',
    'https://pubmed.ncbi.nlm.nih.gov/42224084/',
    array['Running Economy'],
    'Eight trail runners completed outdoor 1500-meter trials wearing advanced footwear technology (AFT) trail shoes versus control trail shoes at 50-km race effort. The AFT shoes provided a 1.1% improvement in running economy measured as cost of transport. The benefit was smaller than what has been observed with AFT road racing shoes at faster speeds on treadmills.',
    'Carbon-plated trail shoes do improve running economy on trails, but the benefit is smaller than on the road, roughly 1% versus 2 to 4%. This still translates to meaningful time savings over ultra distances. Use them if your target course allows, but do not expect the same dramatic gains as road super shoes.',
    'The first published study specifically measuring AFT effects in trail running shoes on actual trail surfaces. The smaller benefit compared to road shoes likely reflects the varied terrain and slower speeds reducing the mechanical advantage of the plate-foam system.',
    5,
    2,
    2,
    true
  ),
  (
    '42050344',
    'Test-Retest Reliability of Physiological Resilience During and After Prolonged Moderate-Intensity Running in Well-Trained Runners.',
    'Malinen T, Nuuttila OP, Matomäki P, Uusitalo A, Kyröläinen H',
    'European journal of sport science',
    2026,
    '2026-05-01',
    'https://pubmed.ncbi.nlm.nih.gov/42050344/',
    array['Running Economy', 'VO2max', 'Training Structure'],
    'Twenty-six well-trained runners completed two identical 2.5-hour durability tests. Changes in peak speed and drifts in running economy and heart rate showed moderate to good reliability as measures of physiological resilience. Changes in VO2max and ventilatory thresholds showed poor reliability. Absolute physiological values remained reliable even in a fatigued state.',
    'If you want to test your durability, track heart rate drift, running economy drift, and change in peak speed after a long effort. These are the most reliable markers. Do not rely on single VO2max or threshold measurements taken in a fatigued state to track durability improvements over time.',
    'This is the first study to establish which durability metrics are actually reproducible enough to use for tracking training progress. Coaches now have evidence-based guidance on what to measure during long-run assessments.',
    5,
    4,
    4,
    true
  ),

  -- ===== CYCLING =====
  (
    '42234539',
    'An extract from whole coffee cherry improves time trial performance, but not muscle glycogen resynthesis, in trained cyclists.',
    'Pavis GF, Kingma RL, Nemzer BV, Abshiru N, Wall BT, Stephens FB',
    'Journal of the International Society of Sports Nutrition',
    2026,
    '2026-06-01',
    'https://pubmed.ncbi.nlm.nih.gov/42234539/',
    array['Supplementation', 'Fueling & Nutrition'],
    'Twelve trained cyclists received a whole coffee cherry extract concentrated in caffeine and polyphenols or a control during a time trial protocol. The coffee cherry extract significantly improved time trial performance, but did not enhance muscle glycogen resynthesis during recovery. The performance benefit appeared to come from the caffeine and polyphenol combination rather than glycogen effects.',
    'Whole-fruit coffee cherry supplements with both caffeine and polyphenols may offer a performance edge during cycling time trials. However, do not count on them to speed up glycogen recovery between efforts. Stick to proven carbohydrate-rich recovery nutrition for glycogen replenishment.',
    'An interesting twist on caffeine supplementation research by testing a whole-fruit extract rather than pure caffeine. The separation of performance benefit from glycogen effects helps clarify mechanism.',
    3,
    5,
    4,
    true
  ),
  (
    '42228164',
    'Low carbohydrate availability reduces power output at the moderate-to-heavy transition, impairs efficiency, and increases median power frequency during cycling in females.',
    'Main E, Yoon S, James SL, Mellor KM, Brick MJ, Leigh WB, Maunder E',
    'European journal of applied physiology',
    2026,
    '2026-06-01',
    'https://pubmed.ncbi.nlm.nih.gov/42228164/',
    array['Fueling & Nutrition', 'Carbohydrate', 'Female Athletes'],
    'Female cyclists performed tests in both normal and low carbohydrate availability states. Low carb availability reduced the power output at which the moderate-to-heavy intensity transition occurred, impaired cycling efficiency, and altered neuromuscular recruitment patterns indicated by increased median power frequency.',
    'Riding with low carbohydrate availability genuinely reduces the power you can sustain at threshold, not just how it feels. For female athletes especially, fasted or low-carb training sessions lower the ceiling of productive training intensity. If the goal is quality work, ensure adequate fueling.',
    'Important female-specific data in a field dominated by male studies. The finding that low carb availability actually shifts intensity domain boundaries, not just perception, has real implications for train-low strategies in women.',
    3,
    5,
    4,
    true
  ),
  (
    '42223297',
    'Acute Sleep Deprivation Shifts Substrate Utilization Toward Greater Fat Oxidation During Incremental Exercise in Recreationally Trained Adults.',
    'Del Val-Manzano M, Montalvo-Alonso JJ, Gonzalo-Encabo P, Valades D, Ferragut C, Perez-Lopez A',
    'Scandinavian journal of medicine & science in sports',
    2026,
    '2026-06-01',
    'https://pubmed.ncbi.nlm.nih.gov/42223297/',
    array['Sleep', 'Fueling & Nutrition'],
    'After one night of total sleep deprivation, recreationally trained adults shifted their exercise metabolism toward greater fat oxidation and reduced carbohydrate utilization during incremental exercise. This metabolic shift occurred without changes in perceived exertion.',
    'A poor night of sleep before a race or hard workout shifts your body away from carbohydrate use. This may impair high-intensity efforts that rely on carb oxidation. Prioritize sleep before key sessions and events. If sleep was poor, consider increasing carbohydrate intake during exercise to compensate.',
    'Adds metabolic evidence to the growing case that sleep is a performance variable, not just a recovery one. The substrate shift toward fat after sleep loss may partly explain why sleep-deprived efforts feel harder at threshold.',
    4,
    4,
    4,
    true
  ),

  -- ===== TRIATHLON =====
  (
    '42245827',
    'Dose-response to endurance training: a longitudinal study of training load and biomarkers in elite triathletes.',
    'Cejuela R, Arévalo-Chico H, Sellés-Pérez S',
    'Frontiers in physiology',
    2026,
    '2026-05-20',
    'https://pubmed.ncbi.nlm.nih.gov/42245827/',
    array['Training Structure', 'Recovery'],
    'Twenty elite triathletes were monitored across a full training season. Blood urea rose significantly during heavy and moderate training weeks but not during light weeks. Greater subjective training load correlated with larger urea increases, while athletes who perceived training as easier relative to the actual load showed smaller urea elevations. Improvements in power at VO2max were negatively associated with urea increases.',
    'Monitor blood urea as part of your regular bloodwork during heavy training blocks. Rising urea that does not come down during recovery weeks may signal excessive training load. The disconnect between how hard training feels and what blood markers show reinforces the need for combined subjective and objective monitoring.',
    'One of the few longitudinal studies in elite triathletes linking training load distribution, biomarkers, and performance outcomes across a full season. The finding that perceived exertion relative to load predicts urea response is practically useful for coaches.',
    3,
    4,
    5,
    true
  ),
  (
    '42075028',
    'Effect of Beetroot Nitrate Supplementation on Nitric Oxide Pathways and Oxy-Inflammatory Biomarkers in Amateur Triathletes: A Randomized Cross-Over Pilot Study.',
    'Mrakic-Sposta S, Vezzoli A, Parenza M, Magno M, D''Angelo G, Nannipieri F, Battaglia S, Solfanelli L, Tacconi E, Dellanoce C, Montorsi M, Pratali L',
    'Nutrients',
    2026,
    '2026-04-12',
    'https://pubmed.ncbi.nlm.nih.gov/42075028/',
    array['Supplementation'],
    'Ten male triathletes took a beetroot-based nitrate supplement for 7 days in a randomized crossover design. Supplementation significantly increased nitric oxide metabolites by 155%, along with increases in iNOS and peroxynitrite. These changes occurred without evidence of lipid oxidative damage, suggesting the nitric oxide pathway was enhanced without harmful oxidative stress.',
    'Seven days of beetroot supplementation meaningfully activates nitric oxide pathways in endurance athletes. The lack of oxidative damage is reassuring. Consider a week-long loading protocol with beetroot juice before key races, rather than single-dose race-day strategies alone.',
    'Adds biochemical depth to the beetroot supplementation literature. The 155% increase in nitric oxide metabolites without lipid damage supports the safety and efficacy of short-term loading protocols.',
    3,
    4,
    5,
    true
  ),
  (
    '41956949',
    'Comparison of haemoglobin mass across elite endurance sports and within-subject reliability using the optimised CO re-breathing method.',
    'Green DJ, Lobb C, Scott BE, Turner G',
    'Journal of science and medicine in sport',
    2026,
    '2026-03-26',
    'https://pubmed.ncbi.nlm.nih.gov/41956949/',
    array['VO2max', 'Altitude Training'],
    'Ninety-nine male and seventy-five female elite athletes from athletics, swimming, and triathlon were compared for total hemoglobin mass. After adjusting for body mass, age, and sex, distance runners and triathletes had approximately 9% greater hemoglobin mass than swimmers and roughly 6% greater than shorter-distance track athletes. Within-subject measurement error was 23 grams.',
    'Hemoglobin mass is sport-specific even among elite endurance athletes. Distance runners and triathletes develop the highest values, likely reflecting their greater training volumes at sustained intensities. When monitoring hemoglobin mass for altitude camp responses, a change must exceed roughly 23 grams to be considered real rather than measurement noise.',
    'Published from the UK Sports Institute with data from genuine elite athletes, giving this study real-world authority. The reliability data is critical for practitioners using CO rebreathing to track altitude training effects.',
    4,
    4,
    5,
    true
  ),
  (
    '42188550',
    '"Every Woman Has a Different Cycle and Feels Differently": A Qualitative Study of Athlete-Centred Perspectives on Menstrual Cycle Symptoms and Management in Female Endurance Sports.',
    'Liebrenz E, Smith A, Liebrenz M, Colangelo J, Buadze A',
    'Sports (Basel, Switzerland)',
    2026,
    '2026-04-24',
    'https://pubmed.ncbi.nlm.nih.gov/42188550/',
    array['Female Athletes'],
    'Twelve female endurance athletes across triathlon, running, swimming, cycling, and skiing were interviewed about menstrual cycle experiences. Six themes emerged including body awareness, the influence of expectations on perceived performance, inconsistent approaches to cycle-based training, and communication barriers. Cycle-based training served more as a framework for interpreting symptoms than as a means of optimizing performance.',
    'Avoid rigid menstrual-cycle-based training prescriptions. Each athlete responds differently, and expectations can shape perceived performance as much as physiology does. Create an environment where female athletes can openly discuss cycle-related symptoms and adjust training flexibly rather than following a one-size-fits-all model.',
    'A qualitative counterpoint to the quantitative menstrual cycle research. The finding that rigid cycle-based training may reinforce negative expectancies is important for coaches implementing these approaches.',
    4,
    4,
    5,
    true
  ),
  (
    '42131935',
    'Prospective Assessment of Swimming-Induced Pulmonary Edema in Open-Water Athletes at Moderate Elevations: Incidence and Diagnostic Utility of Point-of-Care Ultrasound.',
    'Steins H, Patterson B, Payton M, Vidlock K',
    'Wilderness & environmental medicine',
    2026,
    '2026-05-14',
    'https://pubmed.ncbi.nlm.nih.gov/42131935/',
    array['Injury Prevention'],
    'Among 7,866 endurance athletes at half-Ironman triathlons and open-water swims at moderate elevations (771 to 1665 meters), 29 athletes (0.37%) had ultrasound-confirmed swimming-induced pulmonary edema (SIPE). Male incidence at altitude was significantly higher than previously reported at sea level. Nontraditional symptoms like anxiety, tachycardia, and wetsuit tightness were associated with positive cases.',
    'SIPE is uncommon but real, and risk increases at elevation. Athletes swimming in races above 750 meters should be aware of symptoms beyond classic cough and breathlessness: anxiety, rapid heart rate, and unusual wetsuit pressure can be warning signs. Race medical teams should consider point-of-care lung ultrasound in their toolkit.',
    'The first large prospective SIPE study at moderate elevations. The finding that standard oxygen saturation cutoffs overestimate SIPE at altitude has immediate practical implications for race medical protocols.',
    2,
    2,
    5,
    true
  ),

  -- ===== ROWING =====
  (
    '41918248',
    'Comparative effects of caffeine and paraxanthine on rowing performance and sleep quality: a randomized crossover study.',
    'Bingol Diedhiou A, Yildirim UC, Ozdenk S, Erkan D, Karakulak I, Yildirim Tuncer S, Turgut M, Gundem MC, Bora MV, Akca F',
    'Journal of the International Society of Sports Nutrition',
    2026,
    '2026-03-31',
    'https://pubmed.ncbi.nlm.nih.gov/41918248/',
    array['Supplementation', 'Sleep'],
    'Fourteen male rowers completed 2000-meter time trials under four conditions: caffeine plus paraxanthine, caffeine alone, paraxanthine alone, and placebo. The combination of caffeine and paraxanthine produced the fastest times and highest power output. Paraxanthine alone showed better subjective sleep outcomes than caffeine, suggesting it may be preferable for evening training.',
    'Combining caffeine with its metabolite paraxanthine may boost rowing performance more than either alone. For athletes who train in the evening and are sensitive to caffeine-related sleep disruption, paraxanthine supplements could be worth exploring as an alternative that is gentler on sleep quality.',
    'Novel study comparing caffeine to its primary metabolite paraxanthine in a sport-specific performance test. The sleep quality angle makes it especially relevant for athletes juggling evening training and recovery.',
    3,
    3,
    4,
    true
  ),
  (
    '42223158',
    'Associations of 2000 m Rowing Ergometer Performance With Load-Velocity Relationship Variables Obtained During Bilateral and Unilateral Prone Bench Pull and Leg Press.',
    'Pérez-Castilla A, Quidel-Catrilelbún MEL, Baena-Raya A, Miras-Moreno S, Conceição F, Fernandes JFT, Ramirez-Campillo R',
    'Journal of strength and conditioning research',
    2026,
    '2026-06-01',
    'https://pubmed.ncbi.nlm.nih.gov/42223158/',
    array['Strength Training'],
    'Twenty-one competitive rowers completed 2000-meter time trials and strength assessments. Load-velocity profiles from both bench pull and leg press showed moderate to very large correlations with rowing performance. Bilateral exercises more closely reflected rowing performance than unilateral variants. Interlimb asymmetries generally did not predict rowing performance.',
    'For rowers, bilateral strength exercises like prone bench pull and leg press provide the most transferable strength assessments. Load-velocity profiling during these exercises can help predict and track 2000-meter performance. Do not overemphasize correcting asymmetries at the expense of bilateral strength development.',
    'Provides clear guidance on which strength tests are most relevant for rowing performance. The load-velocity approach is more practical than 1RM testing for ongoing monitoring in competitive rowers.',
    2,
    2,
    3,
    true
  ),
  (
    '42222289',
    'Hematological, inflammatory, and hypoxia-responsive adaptations to 18-day normobaric live high-train low training in elite rowers.',
    'Kasperska A, Dziewiecka H, Jankowski W, Mikulski T, Czerniec I, Skarpańska-Stejnborn A, Ostapiuk-Karolczuk J',
    'Frontiers in physiology',
    2026,
    '2026-05-13',
    'https://pubmed.ncbi.nlm.nih.gov/42222289/',
    array['Altitude Training', 'Recovery'],
    'Thirteen national-level male rowers completed an 18-day normobaric live high-train low protocol. EPO levels and reticulocyte counts increased, with hematocrit significantly higher after 18 days in the hypoxic group. CRP levels also rose, indicating a transient inflammatory response. The protocol induced moderate hematological adaptations but represented an additional physiological load.',
    'An 18-day normobaric altitude block can stimulate erythropoiesis in rowers, but comes with an inflammatory cost that should be monitored. Plan altitude camps carefully within the training calendar and track inflammatory markers alongside hematological ones to avoid overloading athletes.',
    'Adds rowing-specific altitude training data to a literature dominated by running and cycling studies. The dual finding of hematological benefit alongside inflammatory stress is a useful reminder that altitude is not free physiological adaptation.',
    3,
    3,
    4,
    true
  ),

  -- ===== SWIMMING =====
  (
    '42218755',
    'Selected immunoendocrine and performance adaptations to upper-body plyometric training and beta-alanine supplementation in male swimmers.',
    'Gao H, Yu X, Guo Z',
    'Journal of the International Society of Sports Nutrition',
    2026,
    '2026-05-31',
    'https://pubmed.ncbi.nlm.nih.gov/42218755/',
    array['Strength Training', 'Supplementation'],
    'Thirty trained male swimmers were assigned to plyometric training plus beta-alanine, plyometric training plus placebo, or control for eight weeks. Both plyometric groups improved upper-body power, bench press strength, and 50-to-200-meter freestyle performance. Beta-alanine supplementation further amplified these training-induced adaptations and promoted a more favorable hormonal profile.',
    'Upper-body plyometric training effectively translates to faster swimming times across sprint and middle distances. Adding beta-alanine supplementation may provide an additional edge by enhancing the training response and supporting a more favorable testosterone-to-cortisol ratio. Include medicine ball throws and explosive push-up variants in swim training.',
    'One of the few studies to combine plyometric training with beta-alanine supplementation in competitive swimmers. The dose-response pattern between plyometrics alone and plyometrics plus beta-alanine is practically relevant for periodized swim programs.',
    2,
    2,
    4,
    true
  ),

  -- ===== CROSS-COUNTRY SKIING & WINTER SPORTS =====
  (
    '41723749',
    'Seasonal changes in energy intake and emerging indicators of energy availability in young elite Nordic skiers.',
    'Lundberg HE, Larsen S, Sundgot-Borgen J, Mathisen TF',
    'Journal of the International Society of Sports Nutrition',
    2026,
    '2026-02-22',
    'https://pubmed.ncbi.nlm.nih.gov/41723749/',
    array['Fueling & Nutrition', 'Female Athletes', 'Weight Management'],
    'Thirty female and thirty male elite Nordic skiers were tracked for 24 weeks. Energy intake increased by 25% and carbohydrate by 14.5% over the study, but training volume increased by 41% for females and 83% for males. Skiers were unable to increase food intake enough to match rising training demands. Lean mass emerged as a key predictor of multiple health markers related to relative energy deficiency.',
    'Young endurance athletes, especially Nordic skiers with high training volumes, consistently under-eat relative to their energy expenditure as training ramps up. Proactively increase calories during preparation periods rather than waiting for symptoms. Monitor lean body mass as a key health indicator alongside training metrics.',
    'A well-designed longitudinal study showing the energy availability gap in real-time during a competitive season. The practical implication is clear: coaches must actively manage nutrition as training volume increases, not assume athletes will self-regulate.',
    4,
    3,
    4,
    true
  ),
  (
    '41674117',
    'Agreement between muscle saturation breakpoints and lactate thresholds: Muscles comparison and sex difference in world-class Nordic skiers.',
    'Forot J, Schorderet F, Burdet C, Brocherie F, Millet GP',
    'Experimental physiology',
    2026,
    '2026-02-11',
    'https://pubmed.ncbi.nlm.nih.gov/41674117/',
    array['VO2max', 'Training Structure'],
    'Near-infrared spectroscopy (NIRS) muscle oxygen saturation breakpoints were compared against lactate thresholds in world-class Nordic skiers. The study found varying levels of agreement between NIRS breakpoints and lactate thresholds depending on which muscle was measured. Sex differences in the agreement were also identified, with females showing different patterns than males.',
    'NIRS-based training zone prescriptions should use sport-specific and sex-specific reference muscles for the most accurate threshold estimation. Do not assume that a NIRS sensor on the vastus lateralis gives equivalent zone information as one on the arm in upper-body-dominant sports like Nordic skiing.',
    'From a world-class athletic population, this study adds important nuance to the growing use of NIRS devices for training prescription. The sex differences identified here should inform how coaches interpret NIRS data in male versus female athletes.',
    3,
    4,
    4,
    true
  ),
  (
    '41665741',
    'Mind-Muscle-Environment Interactions: Psychophysiological Determinants of Optimal Pacing in Olympic Winter Endurance Sports.',
    'Edholm P, Bouten LJL, Holmberg HC, Losnegard T, Hettinga FJ',
    'Scandinavian journal of medicine & science in sports',
    2026,
    '2026-02-01',
    'https://pubmed.ncbi.nlm.nih.gov/41665741/',
    array['Pacing', 'Mental Performance'],
    'This review examines pacing in Olympic winter endurance sports including cross-country skiing, biathlon, and speed skating. While pacing is a critical performance determinant, optimal strategies depend on the interaction between psychological factors, physiological state, and environmental conditions. Course profile, snow conditions, altitude, and competitor behavior all modulate pacing decisions.',
    'Effective pacing in winter endurance sports cannot be based on physiology alone. Train decision-making under variable conditions. Practice adjusting effort in response to environmental changes like wind and snow quality. Mental preparation for handling competitor tactics during mass-start events is as important as fitness.',
    'Bridges the gap between laboratory pacing research and the complex reality of winter endurance competition. The mind-muscle-environment framework could be applied to many endurance sports beyond winter disciplines.',
    4,
    4,
    4,
    true
  ),

  -- ===== TRAINING THEORY & PERIODIZATION =====
  (
    '41169886',
    'Recent advances in training intensity distribution theory for cyclic endurance sports: theoretical foundations, model comparisons, and periodization characteristics.',
    'Sun Q, Yu Y, Cui J, Lin S, Wang X, Zhou T',
    'Frontiers in physiology',
    2025,
    '2025-10-15',
    'https://pubmed.ncbi.nlm.nih.gov/41169886/',
    array['Polarized Training', 'Training Structure', 'Periodization'],
    'This systematic review compares three major training intensity distribution models: pyramidal, threshold, and polarized. Each model has distinct strengths depending on the sport, the training phase, and individual athlete characteristics. The review shows that no single model is universally superior, and that strategic integration of multiple models across periodization phases may enhance cumulative adaptations.',
    'Do not commit dogmatically to one training intensity distribution model. Use a pyramidal base during general preparation, shift toward polarized during specific preparation, and consider threshold blocks before competition. Match the model to the training phase and sport demands rather than following a single philosophy year-round.',
    'The most comprehensive recent review of training intensity distribution theory across endurance sports. Provides a framework for understanding when and why to shift between polarized, pyramidal, and threshold approaches, which is more nuanced than the polarized-versus-everything debate.',
    5,
    5,
    5,
    true
  ),
  (
    '40851900',
    'Effects of protein supplementation on body composition, physiological adaptations, and performance during endurance training: a systematic review and meta-analysis.',
    'Xiao Y, Deng Z, Sun W, Li J, Gao W',
    'Frontiers in nutrition',
    2025,
    '2025-08-07',
    'https://pubmed.ncbi.nlm.nih.gov/40851900/',
    array['Fueling & Nutrition', 'Supplementation'],
    'This meta-analysis of 23 randomized trials involving 1,146 participants found that protein supplementation during endurance training significantly improved time to exhaustion but had a small, non-significant effect on lean body mass. Protein supplementation did not significantly affect VO2max, body weight, or body fat in the general population, though untrained individuals may see greater VO2max benefit.',
    'Adding protein to your endurance nutrition can help you last longer in extended efforts, but do not expect it to dramatically change body composition or VO2max. The time-to-exhaustion benefit suggests protein may help with fatigue resistance. Prioritize adequate total protein intake rather than specific supplementation protocols.',
    'A large and well-conducted meta-analysis that helps set realistic expectations for protein supplementation in endurance athletes. The performance benefit on time-to-exhaustion without VO2max changes suggests a fatigue-resistance mechanism rather than an aerobic capacity one.',
    4,
    4,
    4,
    true
  ),

  -- ===== SUPPLEMENTATION =====
  (
    '41870601',
    'The emerging and evolving evidence supporting creatine as an ergogenic aid: history and applications.',
    'Kerksick C, Gonzalez D, Stout J, Forbes S, Candow D, Ziegenfuss T, Marshall R, Schwesig R, Kreider R',
    'Journal of the International Society of Sports Nutrition',
    2026,
    '2026-03-23',
    'https://pubmed.ncbi.nlm.nih.gov/41870601/',
    array['Supplementation', 'Recovery', 'Strength Training'],
    'This comprehensive narrative review covers three decades of creatine research. Beyond the established benefits for strength and power, emerging evidence shows creatine may benefit endurance and team-sport athletes through enhanced glycogen resynthesis, calcium handling, oxidative stress mitigation, and repeated-sprint performance. Pooled safety analyses show no greater adverse events than placebo.',
    'Creatine is not just for strength athletes. Endurance athletes may benefit from enhanced glycogen resynthesis, better recovery, and improved repeated-sprint ability during interval training. The safety profile is well-established across hundreds of clinical trials. Consider 3 to 5 grams daily as a baseline supplementation strategy.',
    'The most thorough recent review of creatine from the ISSN author group. The extension of evidence into endurance and team sports makes this relevant beyond the traditional strength and power audience. The safety data summary is especially useful for athletes concerned about supplement risks.',
    3,
    4,
    4,
    true
  ),

  -- ===== NUTRITION AT ALTITUDE =====
  (
    '42166208',
    'Glucose and fructose contributions to exogenous carbohydrate oxidation and performance at moderate altitude.',
    'Arjomandkhah NC, King AJ, Griffiths A, King RFGJ, Morrison DJ, Preston T, O''Hara JP',
    'The Journal of physiology',
    2026,
    '2026-05-21',
    'https://pubmed.ncbi.nlm.nih.gov/42166208/',
    array['Fueling & Nutrition', 'Carbohydrate', 'Altitude Training'],
    'Eight male runners ingested glucose-fructose, glucose alone, or placebo during 120 minutes of running at 70% VO2max at 2500 meters altitude followed by a 5-km time trial. Glucose-fructose co-ingestion increased exogenous carbohydrate oxidation and spared endogenous stores compared to glucose alone. However, this metabolic advantage did not translate into a faster 5-km time trial compared to glucose alone, though both carbohydrate conditions were faster than placebo.',
    'At altitude, glucose-fructose mixtures still offer a metabolic advantage over glucose alone by sparing your internal carb stores. Always fuel with carbohydrate during prolonged altitude exercise. However, for shorter time-trial performance at altitude, the type of carb may matter less than simply having enough carbohydrate on board.',
    'The first study to demonstrate the synergistic exogenous carbohydrate oxidation effect of glucose-fructose co-ingestion at altitude. Published in the Journal of Physiology, this high-quality study fills a gap in altitude nutrition research.',
    4,
    4,
    5,
    true
  ),

  -- ===== ALTITUDE TRAINING =====
  (
    '42191840',
    'Comparative efficacy of intermittent hypoxic training modalities on athletes'' performance: a systematic review with pairwise and network meta-analyses.',
    'Jiang X, Sun Y, Huang J, Zhang Z, Baharudin FB, Pritama MAN, Naharudin MNB',
    'Scientific reports',
    2026,
    '2026-05-26',
    'https://pubmed.ncbi.nlm.nih.gov/42191840/',
    array['Altitude Training', 'VO2max'],
    'A network meta-analysis of 29 trials with 603 trained athletes compared three hypoxic training methods. Intermittent hypoxic training (IHT) ranked highest for aerobic capacity improvement. Repeated sprint training in hypoxia (RSH) was most effective for anaerobic capacity and showed consistent benefits across both aerobic and anaerobic domains. Sprint interval training in hypoxia (SIH) showed no significant benefits.',
    'Choose your hypoxic training method based on your primary goal. For aerobic development, traditional intermittent hypoxic training is most effective. For combined aerobic and anaerobic gains, repeated sprint training in hypoxia offers the most versatile benefits. Sprint interval training in hypoxia does not appear to provide clear advantages over normoxic equivalents.',
    'The network meta-analysis design allows direct comparison between hypoxic modalities that have rarely been studied head-to-head. The clear hierarchy of IHT for aerobic and RSH for anaerobic outcomes gives coaches actionable guidance.',
    4,
    4,
    4,
    true
  ),
  (
    '42200179',
    'Live high, train smart: translating altitude physiology to best practice with mechanistic insights.',
    'Faiss R, Girard O',
    'Frontiers in physiology',
    2026,
    '2026-05-11',
    'https://pubmed.ncbi.nlm.nih.gov/42200179/',
    array['Altitude Training', 'Training Structure'],
    'This perspective article reconceptualizes altitude training strategies by mapping contemporary approaches alongside their physiological mechanisms. The traditional goal of increasing total hemoglobin mass remains the primary performance target, but the authors propose a broader framework that includes non-hematological adaptation vectors. Key lessons from 25 years of research on hypoxic dose, exposure timing, and inter-individual variability are synthesized.',
    'Altitude training works through more than just red blood cell production. Consider the full spectrum of adaptations including mitochondrial, muscular, and ventilatory changes. Plan altitude camps with sufficient duration at the right elevation, typically 2000 to 2500 meters for at least 3 weeks. Expect substantial individual variation in response and monitor accordingly.',
    'From two of the most respected altitude training researchers, this paper provides a practical framework that goes beyond the traditional hemoglobin mass focus. The reconceptualization of multiple adaptation vectors is useful for planning altitude training blocks.',
    4,
    5,
    5,
    true
  ),
  (
    '41885723',
    'Hematological and performance enhancements using live high-train low in cycling, a review with meta-analysis.',
    'Torres-Pérez J, Fernández-Peña E, Pinedo-Jauregi A',
    'The Journal of sports medicine and physical fitness',
    2026,
    '2026-04-01',
    'https://pubmed.ncbi.nlm.nih.gov/41885723/',
    array['Altitude Training', 'VO2max'],
    'This meta-analysis reviewed live high-train low protocols specifically in cyclists. The protocol consistently produced hematological adaptations including increases in hemoglobin mass and hematocrit. Performance improvements were also observed, though with considerable variability between studies and individuals.',
    'Live high-train low remains an effective strategy for cyclists seeking hematological and performance gains. The variability in response means coaches should track individual hemoglobin mass changes to confirm each athlete is responding. Non-responders may need adjustments in altitude dose or duration.',
    'A cycling-specific meta-analysis of LHTL fills a gap, as most altitude training reviews mix data from multiple sports. The consistent hematological finding alongside variable performance effects highlights the complexity of translating physiological changes into race results.',
    3,
    5,
    4,
    true
  ),

  -- ===== RECOVERY & SLEEP =====
  (
    '42184272',
    'The effect of probiotic and synbiotic supplementation on sleep parameters in exercised population: a systematic review and synthesis without meta-analysis (SWiM) of randomized controlled trials.',
    'Salehi Asl M, Ahmadi F, Ershadmanesh M, Mortezapour E, Torki F, Danandeh A, Dehghani E, Danandeh K',
    'Journal of the International Society of Sports Nutrition',
    2026,
    '2026-05-25',
    'https://pubmed.ncbi.nlm.nih.gov/42184272/',
    array['Supplementation', 'Sleep', 'Recovery'],
    'This systematic review examined the effects of probiotic and synbiotic supplements on sleep in exercising populations. The evidence suggests that certain probiotic strains may improve subjective sleep quality during intensive training or competition periods. The gut-brain axis appears to mediate these effects through modulation of inflammatory and neurotransmitter pathways.',
    'Probiotic supplementation may support sleep quality during heavy training blocks, adding to their established gut health benefits. While not a replacement for good sleep hygiene, a quality multi-strain probiotic could be a worthwhile addition to the supplement toolkit for athletes struggling with sleep during intense training periods.',
    'Extends the probiotic conversation beyond gut comfort into sleep quality, which is increasingly recognized as a key recovery variable. The gut-brain axis mechanism is biologically plausible and supported by emerging evidence.',
    4,
    4,
    4,
    true
  ),
  (
    '42188576',
    'Physiological, Metabolic, and Mitochondrial Adaptations to a One-Week Endurance Training Camp in Recreational Athletes: An Observational Study.',
    'Bizjak DA, John L, Munk M, Reiter M, Lüders N, Kirsten J, Henze AS, Schulz SVW',
    'Sports (Basel, Switzerland)',
    2026,
    '2026-05-13',
    'https://pubmed.ncbi.nlm.nih.gov/42188576/',
    array['Training Structure', 'Recovery'],
    'Thirty-five recreational endurance athletes completed a professionally guided one-week training camp. Body mass and body fat decreased. Mitochondrial DNA abundance and PGC1-alpha expression increased, indicating mitochondrial biogenesis. However, muscle stress markers also rose alongside psychological stress reductions, showing that concentrated training blocks are a potent but stressful stimulus.',
    'A one-week training camp can trigger measurable mitochondrial adaptations even in recreational athletes. However, the concurrent rise in muscle stress markers means adequate recovery afterward is essential. Plan a reduced training week following any concentrated training block to allow the adaptations to consolidate.',
    'Rare data on the cellular-level effects of real-world training camps in recreational athletes. The combination of mitochondrial biogenesis markers with reduced psychological stress in a holiday-like camp setting is an interesting finding that supports the popular practice of training vacations.',
    4,
    4,
    4,
    true
  ),

  -- ===== GENERAL ENDURANCE =====
  (
    '42254834',
    'Lifetime Endurance Physical Activity Is Related to Better Cardiometabolic Profile but May Be Insufficient to Preserve Muscle Strength and Power in Middle Aged and Older Men.',
    'Pigłowska M, Kwaśniewska M, Kostka J, Kostka T',
    'Clinical interventions in aging',
    2026,
    '2026-06-01',
    'https://pubmed.ncbi.nlm.nih.gov/42254834/',
    array['Strength Training', 'Recovery'],
    'A study of 545 middle-aged and older men found that lifetime endurance physical activity was associated with better cardiometabolic profiles including lower blood pressure, better lipid profiles, and lower fasting glucose. However, endurance activity alone was insufficient to preserve muscle strength and power, which declined with age regardless of activity history.',
    'Endurance training alone is not enough to maintain strength and power as you age. Lifelong runners and cyclists must incorporate resistance training to preserve muscle function. The cardiometabolic benefits of endurance exercise are clear, but they do not protect against age-related strength loss.',
    'An important reminder for aging endurance athletes who may resist adding strength training. The data clearly shows that decades of endurance exercise protect the heart and metabolism but not the muscles. Concurrent training is essential for long-term athletic longevity.',
    4,
    4,
    4,
    true
  ),
  (
    '42258354',
    'Endurance exercise elicits temporal and sexual dimorphic multi-omics remodeling of liver metabolism revealed by MoTrPAC.',
    'Kelty TJ, Franczak E, Gay NR, MoTrPAC Study Group',
    'Cell reports',
    2026,
    '2026-06-01',
    'https://pubmed.ncbi.nlm.nih.gov/42258354/',
    array['Fueling & Nutrition'],
    'Using data from the Molecular Transducers of Physical Activity Consortium (MoTrPAC), this study analyzed how endurance exercise remodels liver metabolism at the molecular level. The adaptations showed clear differences between sexes and changed over time, with distinct metabolic pathways activated at different training stages. The findings reveal how the liver adapts its metabolic machinery to support sustained exercise.',
    'Liver metabolism adapts to endurance training in sex-specific ways and across different timeframes. This supports the idea that men and women may benefit from different nutritional strategies during training. The temporal aspect suggests that metabolic adaptations are progressive and benefit from consistent long-term training.',
    'From the landmark MoTrPAC consortium, this represents the most comprehensive molecular analysis of liver adaptation to exercise. While the practical applications are still emerging, the sex-dimorphic findings reinforce that training and nutrition recommendations should not be blindly applied across sexes.',
    4,
    4,
    4,
    true
  ),
  (
    '41957792',
    'Oxidative stress and antioxidant enzyme activities in elite female Turkish cross-country skiers.',
    'Seyhan S, Bilici MF, Demir H, Bilici OF, Kahraman MZ, Sahin MF, Aglar S, Soylu C, Acar G, Kizilca S',
    'BMC sports science, medicine & rehabilitation',
    2026,
    '2026-04-09',
    'https://pubmed.ncbi.nlm.nih.gov/41957792/',
    array['Recovery', 'Female Athletes'],
    'Elite female cross-country skiers showed significant oxidative stress responses during training, with redox-sensitive signaling contributing to exercise physiology. When oxidant production exceeded antioxidant defenses, oxidative stress markers increased. Antioxidant enzyme activities were measured to characterize the balance between stress and adaptation.',
    'Female endurance athletes in high-volume sports like cross-country skiing should pay attention to oxidative stress management. Ensure adequate dietary antioxidant intake through colorful fruits and vegetables rather than mega-dose supplements, which may blunt training adaptations. Periodize antioxidant intake relative to training load.',
    'Adds female-specific oxidative stress data from an underrepresented sport. The tension between oxidative stress as a training signal and as a harmful stressor remains an active area of research.',
    3,
    3,
    3,
    true
  )
on conflict (pubmed_id) do update
set
  title = excluded.title,
  authors = excluded.authors,
  journal = excluded.journal,
  publication_year = excluded.publication_year,
  publication_date = excluded.publication_date,
  pubmed_url = excluded.pubmed_url,
  topic_tags = excluded.topic_tags,
  plain_english_summary = excluded.plain_english_summary,
  practical_takeaway = excluded.practical_takeaway,
  commentary = excluded.commentary,
  ultra_score = excluded.ultra_score,
  gravel_score = excluded.gravel_score,
  triathlon_score = excluded.triathlon_score,
  published = excluded.published,
  updated_at = now();
