insert into public.research_library_entries (
  pubmed_id,
  title,
  authors,
  journal,
  publication_year,
  publication_date,
  pubmed_url,
  topic_tags,
  plain_english_summary,
  practical_takeaway,
  commentary,
  ultra_score,
  gravel_score,
  triathlon_score,
  published
)
values
  -- 1. Norwegian coaches best practices across Olympic endurance sports
  (
    '40278987',
    'Best-Practice Training Characteristics Within Olympic Endurance Sports as Described by Norwegian World-Class Coaches.',
    'Sandbakk Ø, Tønnessen E, Sandbakk SB, Losnegard T, Seiler S, Haugen T',
    'Sports medicine - open',
    2025,
    '2025-04-25',
    'https://pubmed.ncbi.nlm.nih.gov/40278987/',
    array['Training Periodization', 'Intensity Distribution', 'Coaching'],
    'Twelve Norwegian coaches responsible for over 380 international medals across running, biathlon, rowing, XC skiing, speed skating, cycling, swimming, and triathlon describe what actually works at the world-class level. The common thread is high volume of low-intensity training combined with two to three weekly key workout days containing three to five hard sessions. All coaches follow traditional periodization with a shift toward competition-specific work as racing approaches. The sport-specific differences in volume, frequency, and strength training are large and driven by mechanical loading and competition demands rather than ideology.',
    'Build most of the week around low-intensity volume, then concentrate quality into two or three key workout days. Use sport-specific constraints to determine how much strength and cross-training belongs in the plan rather than copying another sport''s template.',
    'This is the most comprehensive coaching-practice paper in endurance sport to date, spanning eight Olympic disciplines from a single nation with consistent medal production.',
    5,
    5,
    5,
    true
  ),
  -- 2. Norwegian session models across intensities
  (
    '39012575',
    'Training Session Models in Endurance Sports: A Norwegian Perspective on Best Practice Recommendations.',
    'Tønnessen E, Sandbakk Ø, Sandbakk SB, Seiler S, Haugen T',
    'Sports medicine (Auckland, N.Z.)',
    2024,
    '2024-07-16',
    'https://pubmed.ncbi.nlm.nih.gov/39012575/',
    array['Interval Training', 'Intensity Distribution', 'Coaching'],
    'This companion paper to the Norwegian coaches study describes the actual session structures used across Olympic endurance sports. The key finding is that real-world interval sessions used by world-class athletes are more voluminous, more controlled, and less exhaustive than most interval prescriptions found in research literature. Moderate-intensity training accounts for more total annual sessions than high-intensity training in most sports, and intervals feature a progressive intensity build within the session rather than an all-out start.',
    'Design interval sessions with more accumulated volume and less exhaustion than you probably think is necessary. Let intensity build progressively through the session rather than going to the well on the first rep.',
    'A direct challenge to the lab-driven HIIT culture that dominates social media training advice.',
    5,
    5,
    5,
    true
  ),
  -- 3. Nutritional periodization for training adaptation
  (
    '41130458',
    'UCI Sports Nutrition Project: Nutritional Periodization: Strategies to Enhance Training Adaptation and Recovery.',
    'Morton JP, Hearris M, Fell MJ, Owens DJ, Halson S, Trommelen J',
    'International journal of sport nutrition and exercise metabolism',
    2025,
    '2025-10-22',
    'https://pubmed.ncbi.nlm.nih.gov/41130458/',
    array['Fueling & Nutrition', 'Carbohydrate Periodization', 'Recovery'],
    'Nutrient availability does more than fuel workouts. It modulates the cell signaling pathways that drive both endurance and strength adaptations. This UCI-commissioned review makes the case that elite athletes should adjust carbohydrate intake meal-by-meal and day-by-day based on session demands, not just daily totals. Protein needs sit at 1.6 to 2.1 grams per kilogram of fat-free mass per day, and emerging evidence supports nutraceuticals for recovery and sleep, though some may blunt training adaptations if used carelessly.',
    'Match carbohydrate intake to session demand on a per-meal basis, not just a daily average. Keep protein at or above 1.6 grams per kilogram and be cautious with anti-inflammatory supplements that might dampen the training signal.',
    'Essential reading for any athlete or coach trying to integrate nutrition into the training plan rather than treating it as a separate department.',
    5,
    5,
    4,
    true
  ),
  -- 4. Concurrent training umbrella review
  (
    '41762427',
    'Maximizing Adaptations in Concurrent Training: An Umbrella Review of Meta-analyses.',
    'Held S, Wolf L, Rappelt L, Bloch W, Donath L, Micke F, Geisler S, Isenmann E',
    'Sports medicine (Auckland, N.Z.)',
    2026,
    '2026-02-28',
    'https://pubmed.ncbi.nlm.nih.gov/41762427/',
    array['Strength Training', 'Concurrent Training', 'Interference Effect'],
    'This umbrella review of 17 meta-analyses and 144 studies settles a long-running debate: combining strength and endurance training improves aerobic capacity without meaningfully compromising strength, power, or hypertrophy in recreationally trained individuals. There is a trend suggesting that performing resistance training before endurance training may favor strength and hypertrophy gains, but the effect is not statistically decisive yet. The interference effect appears less dramatic than commonly feared.',
    'Do not skip strength work because you are afraid it will hurt your endurance. If anything, do your strength session first when both are on the same day, and accept that the interference effect is smaller than most athletes assume.',
    'Directly relevant for endurance athletes who have been avoiding the gym based on outdated concerns about interference.',
    4,
    5,
    5,
    true
  ),
  -- 5. Sprint intervals don't cause interference
  (
    '41734815',
    'Does Sprint Interval Training Cause Interference in Concurrent Training? A Meta-Analysis Study.',
    'Ferraro-Farro D, Bandeira-Guimarães M, Blanco-Rambo E, Vieira AF, Cadore EL, Benítez-Flores S',
    'International journal of sports medicine',
    2026,
    '2026-03-17',
    'https://pubmed.ncbi.nlm.nih.gov/41734815/',
    array['Sprint Training', 'Concurrent Training', 'VO2max'],
    'When sprint interval training replaces traditional endurance work as the cardio component in a concurrent program, it does not compromise strength, power, or hypertrophy gains. It does, however, significantly improve VO2max compared to resistance training alone. Short sprint protocols of ten seconds or less may even potentiate jump performance. This makes sprint intervals a time-efficient way to maintain or build aerobic fitness alongside strength work without the volume-driven interference that longer endurance sessions can create.',
    'If time is limited and you need both strength and aerobic fitness, short sprint intervals are a better pairing with resistance training than longer steady-state or threshold sessions.',
    'Useful reframe for time-crunched athletes who need to compress concurrent training into fewer weekly hours.',
    3,
    4,
    4,
    true
  ),
  -- 6. Comprehensive supplement review for cycling
  (
    '41685663',
    'A comprehensive review of the physiology and evidence base to guide the use of ergogenic and medical supplements for enhanced cycling performance.',
    'Rowland A, Edwards S, Prieto-Bellver G, Menz B, Rowland A, Cornelisse E, Karapetis CS, Wallen MP, Hopkins AM',
    'Journal of the International Society of Sports Nutrition',
    2026,
    '2026-02-13',
    'https://pubmed.ncbi.nlm.nih.gov/41685663/',
    array['Supplementation', 'Fueling & Nutrition', 'Ergogenic Aids'],
    'This review maps every major ergogenic and medical supplement against the energy systems they target in cycling: phosphagen, glycolysis, oxidative phosphorylation, and beta-oxidation. The strongest evidence supports beta-alanine, caffeine, carbohydrates, creatine, dietary nitrates, electrolytes, and sodium bicarbonate. Medical supplements including iron, vitamin D, omega-3s, collagen, and probiotics play an indirect role by supporting recovery, immune function, and connective tissue health. Evidence quality varies widely and the strongest support is for AIS Group A compounds.',
    'Start with the well-supported ergogenic aids that match your event demands, then layer in medical supplements based on individual blood work and recovery needs. Do not stack everything at once without understanding which systems each targets.',
    'Applies well beyond cycling to any endurance sport where energy system management and recovery support matter.',
    4,
    5,
    4,
    true
  ),
  -- 7. Caffeine mouth rinse meta-analysis
  (
    '41774525',
    'Revisiting the evidence on caffeine mouth rinse: effects on exercise and cognitive performance: a meta-analytic review.',
    'Deng H, Fan X, Song T, Bin Mohd Nasiruddin NJ, Ahmad Fuaad AA, Bin Naharudin MN',
    'Journal of the International Society of Sports Nutrition',
    2026,
    '2026-03-03',
    'https://pubmed.ncbi.nlm.nih.gov/41774525/',
    array['Caffeine', 'Supplementation', 'Cognitive Performance'],
    'Caffeine mouth rinsing activates oral receptors and engages central networks for motivation and pacing without systemic absorption. A meta-analysis of 31 studies found trivial-to-small but significant performance improvements, most consistent for aerobic endurance. Brief rinses of around five seconds outperformed longer durations, and the effect was clearest in the fed state. The optimal dosing window appears to be 32 to 133 milligrams, though this finding was sensitive to outlier removal.',
    'If GI tolerance is a concern with caffeine ingestion during long events, a five-second mouth rinse with a moderate dose is a low-risk alternative that still provides a measurable aerobic endurance benefit.',
    'A practical option for athletes who want the CNS boost from caffeine without the stomach risk during racing.',
    4,
    4,
    4,
    true
  ),
  -- 8. Short energy restriction without performance loss
  (
    '36940222',
    'Short Severe Energy Restriction with Refueling Reduces Body Mass without Altering Training-Associated Performance Improvement.',
    'Burke LM, Whitfield J, Ross MLR, Tee N, Sharma AP, King AJ, Heikura IA, Morabito A, McKay AKA',
    'Medicine and science in sports and exercise',
    2023,
    '2023-03-20',
    'https://pubmed.ncbi.nlm.nih.gov/36940222/',
    array['Weight Management', 'Fueling & Nutrition', 'Body Composition'],
    'Elite race walkers underwent nine days of severe energy restriction at 15 kilocalories per kilogram of fat-free mass per day during intensified training, then refueled. They lost two kilograms, mostly fat, without losing the performance gains they were making during the training camp. Stress and recovery scores were worse during the restriction phase, but race times improved at the same rate as the control group that ate normally throughout. This suggests that brief, strategic energy restriction phases may achieve race weight goals without sacrificing the training block.',
    'If you need to cut weight, a short and deliberate restriction phase followed by full refueling may be safer than chronic underfueling. But monitor stress and recovery closely during the cut, and never stack it on top of the hardest training days.',
    'An important counterpoint to the fear-based messaging around any energy restriction in endurance sport, provided the timing is strategic and the restriction is brief.',
    4,
    4,
    4,
    true
  ),
  -- 9. Hydration in ultra-trail events
  (
    '40001904',
    'Impact of Ad Libitum Hydration on Muscle and Liver Damage and Electrolyte Balance in Ultra-Trail Events: A Heatmap Analysis of Biomarkers and Event Characteristics.',
    'García-Giménez A, Pradas F, Lecina M, Ochiana N, Castellar-Otín C',
    'Biology',
    2025,
    '2025-01-28',
    'https://pubmed.ncbi.nlm.nih.gov/40001904/',
    array['Hydration', 'Electrolytes', 'Ultra-Endurance'],
    'Four athletes were tracked across a nine-stage ultra-trail event covering 635 kilometers and over 40,000 meters of elevation gain. Drinking to thirst prevented hyponatremia and hypernatremia, but it did not prevent significant dehydration in early stages or the progressive muscle and liver damage that accumulated across stages. Body weight loss correlated with worse muscle damage markers and lower calcium levels. Elevation gain and loss amplified both fluid loss and muscle injury.',
    'Drinking to thirst protects against dangerous sodium imbalances, but it does not solve everything. In multi-stage ultra events, proactive attention to early-stage hydration and cumulative muscle damage markers matters more than a single-stage fueling plan.',
    'Directly applicable to multi-day ultra racing and any event where cumulative damage compounds stage over stage.',
    5,
    3,
    3,
    true
  ),
  -- 10. Female trail runners nutrition and RED-S
  (
    '41440803',
    'Associations Between Nutritional Intake, Body Composition, Menstrual Health, and Performance in Elite Female Trail Runners.',
    'Piñol-Granadino N, Carrasco-Marginet M, Puigarnau S, Espasa-Labrador J, Cebrián-Ponce Á, Gravina-Cognetti F, Darder-Terradas M, Solé-Fortó J',
    'Journal of functional morphology and kinesiology',
    2025,
    '2025-12-17',
    'https://pubmed.ncbi.nlm.nih.gov/41440803/',
    array['Female Athletes', 'Fueling & Nutrition', 'RED-S'],
    'Among 35 elite female trail runners, 94.3 percent had clinically low energy availability below 30 kilocalories per kilogram of fat-free mass per day. Menstrual irregularities did not directly predict worse race performance, but nutritional patterns strongly did. Higher complex carbohydrate intake and total energy correlated with better performance, while higher simple carbohydrate intake correlated with worse results. Both groups had inadequate calcium and iron intake regardless of menstrual status.',
    'For female trail and ultra runners, the priority is getting enough total energy and complex carbohydrates to support training, rather than restricting intake. Screen for iron and calcium deficiencies regardless of whether menstrual cycles appear normal.',
    'The near-universal low energy availability in this elite cohort is a red flag that warrants proactive nutritional intervention in female endurance athletes.',
    5,
    3,
    3,
    true
  ),
  -- 11. HRV orthostatic testing for monitoring
  (
    '39259398',
    'Orthostatic testing for heart rate and heart rate variability monitoring in exercise science and practice.',
    'Gronwald T, Schaffarczyk M, Hoos O',
    'European journal of applied physiology',
    2024,
    '2024-09-11',
    'https://pubmed.ncbi.nlm.nih.gov/39259398/',
    array['Recovery', 'HRV Monitoring', 'Overtraining'],
    'A simple lying-to-standing test captures how the autonomic nervous system responds to a positional challenge, and this response shifts meaningfully in overtrained athletes. In overtrained endurance athletes, both parasympathetic and sympathetic activity are blunted and the heart rate response to standing is weaker. Standing HRV measurement also avoids the parasympathetic saturation problem that makes supine HRV readings unreliable in well-trained athletes. The key is tracking intra-individual trends over time, not comparing absolute numbers between athletes.',
    'Add a standardized standing HRV measurement to your morning routine. Track your own trend line over weeks, and flag any sustained blunting of the response as a sign that the load-recovery balance may be off.',
    'A low-tech, free monitoring tool that gives coaches an early warning signal before overtraining symptoms become obvious in performance data.',
    4,
    4,
    4,
    true
  ),
  -- 12. XC ski training periodization
  (
    '42072223',
    'Quantitative Analysis of Annual Training Volume and Periodization Patterns in Elite Female Cross-Country Skiers Using GPS Monitoring: A Three-Athlete Case Study.',
    'Xiao X, Moon S, Kim Y, Choi Y',
    'Bioengineering (Basel, Switzerland)',
    2026,
    '2026-04-07',
    'https://pubmed.ncbi.nlm.nih.gov/42072223/',
    array['Cross-Country Skiing', 'Training Periodization', 'Polarized Training'],
    'GPS and heart rate monitoring of the entire Korean women''s national XC ski team across a full season showed 668 training hours annually, split between roller and on-snow skiing (54 percent), running (23 percent), and strength training (23 percent). The endurance intensity distribution was clearly polarized with over 91 percent in zones one and two. The strength training allocation at 23 percent was notably higher than world-class Scandinavian benchmarks of 10 to 15 percent, while total volume was 18 to 30 percent lower than world-class standards.',
    'Polarized intensity distribution works across endurance sports, not just running and cycling. When total training volume is lower than competitors, a higher strength training allocation may partially compensate, but volume gaps in sport-specific work still matter for race performance.',
    'Useful benchmark for any endurance athlete or coach thinking about how cross-training and strength work fit into a polarized framework.',
    3,
    3,
    3,
    true
  ),
  -- 13. Importance of ultra-marathon research
  (
    '41759081',
    'On the importance of studying ultra-marathon.',
    'Vernillo G, Millet GY',
    'Applied physiology, nutrition, and metabolism',
    2026,
    '2026-01-01',
    'https://pubmed.ncbi.nlm.nih.gov/41759081/',
    array['Ultra-Endurance', 'Research Methodology', 'Injury Prevention'],
    'This editorial by two leading ultra-endurance researchers argues that ultra-marathon is a uniquely valuable model for studying the boundaries of human performance because it exposes athletes to physiological stresses that shorter events never reach. The three key reasons to invest in ultra research are understanding adaptive responses to extreme loads, identifying detrimental physiological variations that could signal health risks, and developing evidence-based training methods and injury prevention strategies specific to these demands.',
    'Take ultra-marathon research seriously as a source of training insight, not just as extreme-sport curiosity. The physiological signals that emerge under ultra-distance stress often reveal vulnerabilities that shorter events hide.',
    'A call to action from Vernillo and Millet, two of the most published researchers in the ultra space, arguing the field deserves dedicated scientific investment.',
    5,
    2,
    2,
    true
  ),
  -- 14. Polarized training with lower load = same gains
  (
    '39619091',
    'Six weeks of polarized functional interval training with large training load reductions does not affect performance gains compared to traditional workouts.',
    'Held S, Isenmann E, Rappelt L, Wiedenmann T, Kutschki D, Harbrecht J, Kirchner K, Geisler S, Donath L',
    'Frontiers in physiology',
    2024,
    '2024-11-15',
    'https://pubmed.ncbi.nlm.nih.gov/39619091/',
    array['Polarized Training', 'Training Load', 'Intensity Distribution'],
    'When functional interval training athletes switched from a traditional high-intensity-dominant approach to a polarized model with 78 percent low intensity, they completed 38 percent less total training load but achieved the same strength, endurance, and workout performance gains over six weeks. Both groups improved deadlift, overhead press, and benchmark workout times at similar rates. This suggests that a large portion of the training load athletes accumulate in threshold-heavy programs may not be driving additional adaptation.',
    'If you are doing most of your training at moderate or threshold intensity, try shifting to a polarized approach with more low-intensity work and fewer but harder key sessions. You may get the same results with substantially less accumulated fatigue.',
    'Adds to the growing evidence that training harder is not the same as training better, and that polarized approaches transfer across sport modalities.',
    4,
    4,
    4,
    true
  ),
  -- 15. U23 female triathlete season
  (
    '38393273',
    'Training Characteristics, Performance, and Body Composition of Three U23 Elite Female Triathletes throughout a Season.',
    'Sellés-Pérez S, Arévalo-Chico H, Fernández-Sáez J, Cejuela R',
    'Sports (Basel, Switzerland)',
    2024,
    '2024-02-07',
    'https://pubmed.ncbi.nlm.nih.gov/38393273/',
    array['Triathlon', 'Female Athletes', 'Training Periodization'],
    'Three elite U23 female triathletes were tracked across an entire season, showing improvements of 7 to 10 percent in cycling VO2max and 5 to 9 percent in running VO2max with average weekly training of over 10 hours and peak weeks exceeding 15 hours. The training intensity distribution was polarized at 82 percent zone one, 6 percent zone two, and 12 percent zone three. Body composition improved through the season but stagnated or slightly reversed at the end, suggesting that the late-season load may have outpaced recovery.',
    'For developing triathletes, a polarized intensity distribution with traditional block periodization produces measurable physiological gains across all three disciplines. Watch for late-season body composition stagnation as a signal that the recovery-load balance may be slipping.',
    'One of very few longitudinal female triathlon studies that shows the full-season arc of training, performance, and body composition together.',
    3,
    3,
    5,
    true
  ),
  -- 16. Power and endurance: complementary not opposing
  (
    '40577381',
    'Power and Endurance: Polar Opposites or Willing Partners?',
    'Ferguson C, Furrer R, Murach KA, Hepple RT, Rossiter HB',
    'Medicine and science in sports and exercise',
    2025,
    '2025-06-23',
    'https://pubmed.ncbi.nlm.nih.gov/40577381/',
    array['Strength Training', 'Concurrent Training', 'Physiological Resilience'],
    'This review challenges the assumption that peak neuromuscular power and endurance capacity are mutually exclusive adaptations. The evidence shows that the molecular signaling pathways for strength and endurance are less antagonistic than the textbook model suggests. In sport, aging, and clinical populations, power and endurance show meaningful reciprocation. The authors propose a combined musculo-cardio-pulmonary exercise test that captures both qualities simultaneously, reinforcing that these are willing partners rather than polar opposites.',
    'Stop treating strength and endurance as a zero-sum tradeoff. Both qualities support each other, especially as athletes age, and training both concurrently builds physiological resilience that neither alone provides.',
    'A paradigm-shifting review that should change how endurance athletes think about the role of power training in their programs.',
    4,
    4,
    4,
    true
  ),
  -- 17. Iron status in female athletes
  (
    '41372730',
    'Iron Status, Muscle Oxygenation and Performance in Female Athletes During Repeated-Sprint Training in Hypoxia.',
    'Stein M, Peeling P, Girard O',
    'Sports medicine (Auckland, N.Z.)',
    2025,
    '2025-12-10',
    'https://pubmed.ncbi.nlm.nih.gov/41372730/',
    array['Iron Deficiency', 'Female Athletes', 'Altitude'],
    'Iron deficiency is common in female athletes and it directly impairs the oxygen transport and mitochondrial energy production that repeated-sprint ability depends on. Because repeated-sprint ability relies on rapid reoxygenation of active muscles between efforts, compromised iron status hits harder in hypoxic conditions where oxygen availability is already limited. Hormonal fluctuations and menstruation increase iron demands in ways that male-derived research often underestimates.',
    'Screen female athletes for iron status regularly, especially before altitude camps or hypoxic training blocks. If iron is low, the training stimulus is compromised before the athlete even starts the session.',
    'Iron deficiency is one of the most correctable limiters in female endurance sport, yet it remains chronically under-screened.',
    4,
    3,
    4,
    true
  ),
  -- 18. Open water vs pool swimming for triathletes
  (
    '39044665',
    'Swimming Performance in Elite Triathletes: Comparison Between Open Water and Pool Conditions.',
    'López-Belmonte Ó, Ruiz-Navarro JJ, Gay A, Cuenca-Fernández F, Arellano R, Cejuela R',
    'Scandinavian journal of medicine & science in sports',
    2024,
    '2024-08-01',
    'https://pubmed.ncbi.nlm.nih.gov/39044665/',
    array['Triathlon', 'Swimming', 'Open Water'],
    'Elite triathletes swim with a higher stroke rate and shorter stroke length in open water compared to the pool, even though the physiological cost is similar. The fastest pool swimmers were also the fastest open water swimmers, but the kinematic adjustments required in open water are specific and must be trained. Respiratory exchange ratio was lower in open water, suggesting a different metabolic profile, and the oxygen kinetics took longer to stabilize.',
    'Pool speed predicts open water speed, but the stroke mechanics are different enough that dedicated open water sessions are essential for triathletes. Train both environments rather than assuming pool fitness transfers directly.',
    'Quantifies what most triathlon coaches already suspect: open water demands different technique, and it needs its own training time.',
    2,
    1,
    5,
    true
  ),
  -- 19. Concurrent training sequence effects
  (
    '41669271',
    'The effects, mechanisms, and influencing factors of concurrent strength and endurance training with different sequences: a semi-systematic review.',
    'Feng Z, Wang Y, Wang J',
    'Frontiers in sports and active living',
    2026,
    '2026-01-23',
    'https://pubmed.ncbi.nlm.nih.gov/41669271/',
    array['Strength Training', 'Concurrent Training', 'Training Sequence'],
    'A review of 42 studies on concurrent training sequence found that while training order does not consistently change long-term gains in endurance, hypertrophy, or maximal strength, a strength-first approach optimizes neuromuscular adaptations that enhance relative strength and explosive power. Acute molecular responses like mTOR and AMPK phosphorylation do vary by sequence, but these acute signals do not translate linearly into long-term outcomes. If the endurance-first order is chosen, spacing sessions by more than three hours reduces molecular interference.',
    'Default to strength before endurance when both are on the same day, especially if power or relative strength matters for your event. If you must reverse the order, space the sessions by at least three hours.',
    'Practical training-order guidance for the athlete who is trying to fit both strength and endurance work into limited weekly slots.',
    4,
    4,
    4,
    true
  ),
  -- 20. Cardiac remodeling across endurance sports
  (
    '40419828',
    'The spectrum of eccentric left ventricular hypertrophy in endurance sports disciplines.',
    'Di Gioia G, Ferrera A, Mango F, Maestrini V, Monosilio S, Pelliccia A, Squeo MR',
    'The international journal of cardiovascular imaging',
    2025,
    '2025-05-26',
    'https://pubmed.ncbi.nlm.nih.gov/40419828/',
    array['Cardiac Health', 'Sport-Specific Adaptation', 'Screening'],
    'A study of 282 Olympic athletes across six endurance disciplines found that cardiac remodeling varies dramatically by sport. Triathletes and cyclists showed the highest rates of eccentric left ventricular hypertrophy at 94 and 88 percent, with the largest left ventricular volumes. Rowers and canoeists, despite enormous training loads, had the lowest degree of chamber enlargement but the greatest increase in wall mass. Among cyclists, the most eccentric remodeling correlated with both more training hours and better exercise test performance.',
    'Do not assume all endurance hearts look the same. Sport-specific demands drive different remodeling patterns, and understanding what is normal for your sport matters for both screening and interpreting cardiac imaging results.',
    'Important context for clinicians interpreting athlete ECGs and echocardiograms, and for coaches understanding that cardiac adaptation is sport-specific, not generic.',
    4,
    5,
    5,
    true
  )
on conflict (pubmed_id) do update
set
  title = excluded.title,
  authors = excluded.authors,
  journal = excluded.journal,
  publication_year = excluded.publication_year,
  publication_date = excluded.publication_date,
  pubmed_url = excluded.pubmed_url,
  topic_tags = excluded.topic_tags,
  plain_english_summary = excluded.plain_english_summary,
  practical_takeaway = excluded.practical_takeaway,
  commentary = excluded.commentary,
  ultra_score = excluded.ultra_score,
  gravel_score = excluded.gravel_score,
  triathlon_score = excluded.triathlon_score,
  published = excluded.published,
  updated_at = now();
