insert into public.research_library_entries (
  pubmed_id,
  title,
  authors,
  journal,
  publication_year,
  pubmed_url,
  topic_tags,
  plain_english_summary,
  practical_takeaway,
  commentary,
  ultra_score,
  gravel_score,
  triathlon_score,
  published
)
values
  -- 1. Carbohydrate fueling guidelines update (running, cycling, ultra)
  (
    '41759826',
    'From Metabolism to Medals: Contemporary Perspectives and Revisiting Carbohydrate Guidelines for Fueling Endurance Athletes during Exercise.',
    'Morton JP, Fell JM, Gonzalez JT, Hearris MA, Podlogar T, Pugh JN, Wallis GA',
    'The Journal of nutrition',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41759826/',
    array['Fueling & Nutrition', 'Carbohydrate'],
    'The long-standing cap of 90 g/h of carbohydrate during exercise is being revised upward. Contemporary data support pushing toward 120 g/h in trained athletes using glucose-fructose blends, with evidence that this higher dose improves exogenous oxidation rates, durability, and economy across cycling, marathon, and ultra-endurance events. Field reports of 120-200 g/h are ahead of published science, so the practical ceiling is still being established.',
    'Use glucose-fructose blends and work progressively toward 120 g/h in long sessions and races. The dose must be rehearsed and personalized, not copied from elite field reports. Format, environmental heat, and individual tolerance all matter.',
    'The definitive 2026 update to carbohydrate fueling guidelines. Essential reading for any coach managing nutrition in events over 2.5 hours.',
    5,
    5,
    5,
    true
  ),
  -- 2. Long runs and running economy durability
  (
    '40878015',
    'Regular Long Runs and Higher Training Volumes Are Associated with Better Running Economy Durability in Performance Matched Well-Trained Male Runners.',
    'Zanini M, Folland JP, Blagrove RC',
    'Medicine and science in sports and exercise',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40878015/',
    array['Training Structure', 'Running Economy'],
    'Running economy deteriorates during prolonged running, and this study is the first to show that runners who include regular long runs and accumulate higher weekly volume are measurably more durable. Performance-matched athletes who trained with shorter runs saw running economy degrade twice as fast over 90 minutes at lactate threshold, and they lost more neuromuscular capability afterward.',
    'Long runs are not just mental preparation. They build physiological durability that directly protects running economy late in a race. Runners cutting long-run frequency or capping distance may be trading late-race efficiency for short-term freshness.',
    'Strong evidence that the long run earns its place in the program for reasons beyond glycogen depletion or mental toughness.',
    5,
    3,
    4,
    true
  ),
  -- 3. Norwegian training session models across Olympic endurance sports
  (
    '39012575',
    'Training Session Models in Endurance Sports: A Norwegian Perspective on Best Practice Recommendations.',
    'Tønnessen E, Sandbakk Ø, Sandbakk SB, Seiler S, Haugen T',
    'Sports medicine',
    2024,
    'https://pubmed.ncbi.nlm.nih.gov/39012575/',
    array['Training Structure', 'Polarized Training'],
    'Twelve Norwegian coaches responsible for over 370 international championship medals described their actual interval and session models across biathlon, cross-country skiing, running, cycling, rowing, swimming, speed skating, and triathlon. The sessions are more voluminous, more controlled, and less exhaustive than what the research literature typically recommends. Moderate-intensity work accounts for a larger share of annual high-intensity training than expected.',
    'High-intensity sessions should be controlled rather than exhaustive. Interval design should progress intensity within the session and use high accumulated volume. Competition serves as a major source of high-intensity stimulus across almost all Olympic endurance sports.',
    'A landmark multi-sport coaching study. The controlled-execution theme challenges the "go harder" default in many training cultures.',
    5,
    5,
    5,
    true
  ),
  -- 4. Comprehensive cycling supplements review
  (
    '41685663',
    'A comprehensive review of the physiology and evidence base to guide the use of ergogenic and medical supplements for enhanced cycling performance.',
    'Rowland A, Edwards S, Prieto-Bellver G, Menz B, Rowland A, Cornelisse E, Karapetis CS, Wallen MP, Hopkins AM',
    'Journal of the International Society of Sports Nutrition',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41685663/',
    array['Supplementation', 'Recovery'],
    'This review maps every major ergogenic and medical supplement against the energy systems they support in cycling: phosphagen, glycolysis, oxidative phosphorylation, and beta-oxidation. Beta-alanine, caffeine, carbohydrates, creatine, nitrates, electrolytes, and sodium bicarbonate have the strongest direct performance evidence. Medical supplements like iron, vitamin D, omega-3, and probiotics support recovery and long-term adaptation indirectly.',
    'Prioritize AIS Group A supplements with proven ergogenic benefit. Layer medical supplements based on individual blood biomarker and metabolic testing rather than blanket protocols.',
    'Comprehensive reference for any cycling-focused athlete or coach building a supplement strategy from the evidence up.',
    3,
    5,
    4,
    true
  ),
  -- 5. Carbohydrate mouth rinsing enhances cycling performance
  (
    '42118778',
    'Oral carbohydrate sensing enhances prefrontal cortex oxygenation, reduces perceived exertion, and improves high-intensity cycling performance: A randomized crossover trial.',
    'Park SB, Oh K, Yang G, Kim T, Lee JW, Jeon HJ, Han DH',
    'PLoS one',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42118778/',
    array['Fueling & Nutrition', 'Cognitive Performance'],
    'Simply rinsing the mouth with a carbohydrate solution, without swallowing, improved 4-km cycling time trial performance, increased prefrontal cortex oxygenation, preserved executive function, and reduced perceived exertion compared to placebo and music. The effect is central and neurocognitive, not metabolic. Blood lactate and heart rate did not differ between conditions.',
    'Carbohydrate mouth rinsing is a legitimate ergogenic tool for efforts under an hour where full fueling is not practical. It works through the brain, not the gut, making it useful when GI tolerance is a limiter.',
    'Relevant for short-course racing, time trials, and any situation where the gut is already under pressure.',
    2,
    4,
    4,
    true
  ),
  -- 6. Torque training in cyclists
  (
    '42076918',
    'The Role of Pedaling Intensity During Torque Training in Cyclists: A Three-Arm Randomized Controlled Trial.',
    'de Pablos R, Valenzuela PL, Martínez-Cava A, Alejo LB, Revuelta C, Sánchez-Redondo IR, Barranco-Gil D, Pallares JG',
    'Scandinavian journal of medicine & science in sports',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42076918/',
    array['Strength Training', 'Cycling Performance'],
    'High-load torque training (all-out pedaling at 70% of max dynamic force) improved both sprint power and endurance indicators including VO2max and ventilatory thresholds in well-trained male cyclists over 10 weeks. Low-load torque training showed no significant within-group gains. High-load also increased quadriceps cross-sectional area, suggesting a genuine hypertrophic stimulus.',
    'If adding torque work to a cycling program, load matters. Short, high-load efforts twice a week produced meaningful gains in both power and aerobic capacity. Low-load big-gear grinding did not.',
    'Directly relevant for gravel and road cyclists looking to add targeted strength work on the bike.',
    2,
    5,
    3,
    true
  ),
  -- 7. Low-carb diet and endurance: the debate
  (
    '42070892',
    'Does a low-carbohydrate diet impede endurance sports performance? No.',
    'Noakes TD, Burke LM',
    'The American journal of clinical nutrition',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42070892/',
    array['Fueling & Nutrition', 'Fat Adaptation'],
    'After 4-6 weeks of adaptation, low-carbohydrate high-fat diets did not impair VO2max test performance, 5-km or 1.6-km time trials, or interval sessions in trained athletes compared to high-carb diets. Some subjects achieved fat oxidation rates of 2 g/min. Minimal carbohydrate ingestion during exercise (10 g/h) improved prolonged cycling by 22% equally on either diet, suggesting exercise-induced hypoglycemia from liver glycogen depletion, not muscle glycogen per se, is the key fatigue driver.',
    'Fat adaptation does not automatically wreck performance in well-adapted athletes, but the practical question is whether the athlete can still hit the intensities their program demands. Minimal carbohydrate during exercise protects against the main fatigue mechanism regardless of background diet.',
    'A provocative contribution from Noakes and Burke. Coaches should read both sides of this debate rather than defaulting to ideology.',
    4,
    4,
    3,
    true
  ),
  -- 8. Pacing in Double Deca ultra-triathlon
  (
    '42056382',
    'Pacing profiles and slowdown patterns in ultra-triathlon performance.',
    'Marković S, Cuk I, Duric S, Forte P, Leite LB, Andrade MS, Nikolaidis PT, Weiss K, Rosemann T, Knechtle B',
    'Scientific reports',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42056382/',
    array['Pacing', 'Ultra-Endurance'],
    'In the Double Deca Iron ultra-triathlon (76 km swim, 3600 km bike, 844 km run), higher performers maintained a fast and relatively steady baseline pace punctuated by occasional large slowdowns, rather than moving at a continuously slower, more variable pace. Running showed the most consistent pacing, while cycling had the greatest variability.',
    'In extreme ultra events, the winning strategy is to hold a high sustainable pace and accept periodic deep slowdowns rather than smoothing out the effort into a conservative, highly variable crawl. Pacing discipline in the bike and run legs is the differentiator.',
    'Extreme-distance data but the pacing principle translates: protect baseline pace and manage the inevitable dips rather than trying to eliminate them.',
    5,
    3,
    5,
    true
  ),
  -- 9. Cold open-water marathon swim thermoregulation
  (
    '41564305',
    'Prolonged stable hypothermia during a 10-hour cold open-water marathon swim.',
    'Roxburgh BH, Edgar DT, Cotter JD',
    'Experimental physiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41564305/',
    array['Thermoregulation', 'Open Water Swimming'],
    'A 52-year-old cold-adapted swimmer completed a 37-km crossing of New Zealand''s Foveaux Strait in 13-14°C water over nearly 10 hours, with core temperature below 35°C for over 6 hours and a nadir of 33.88°C. Despite profound hypothermia, he showed no cognitive or motor impairment, completed the swim unaided, and had no afterdrop post-immersion.',
    'Cold adaptation is trainable and remarkably powerful. For open-water endurance athletes in cold conditions, progressive cold exposure builds thermoregulatory tolerance that lab-based thresholds may underestimate. Individual variability in cold tolerance is far wider than most safety protocols assume.',
    'Rare real-world thermoregulation data from an extreme open-water event. Relevant for any athlete racing in cold water.',
    3,
    1,
    4,
    true
  ),
  -- 10. 10-year cardiac effects of marathon running (JAMA Cardiology)
  (
    '41370052',
    'Long-Term Changes in Ventricular Function in Recreational Marathon Runners.',
    'Schindler MJ, Schoenfeld J, Trommler A, Haller B, Nieman DC, Halle M, Scherr J',
    'JAMA cardiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41370052/',
    array['Cardiac Health', 'Recovery'],
    'In a 10-year longitudinal study of 152 male marathon runners, the acute troponin rise seen after a marathon was not associated with long-term right ventricular deterioration. Left ventricular ejection fraction decreased slightly but remained normal. Right ventricular function recovered fully within days and remained normal at 10-year follow-up. Repetitive strenuous endurance training did not induce chronic cardiac damage in this cohort.',
    'Post-race troponin elevation is transient and does not predict long-term cardiac harm in recreational male runners. Athletes and coaches should not panic about elevated biomarkers in isolation after a hard race.',
    'The longest follow-up study of its kind. Reassuring data for marathon and ultra athletes concerned about cumulative cardiac risk.',
    5,
    3,
    4,
    true
  ),
  -- 11. Kidney injury risk in endurance running
  (
    '41615405',
    'Kidney injury risk during prolonged endurance running: lessons from the field.',
    'McKenna ZJ, Atkins WC, Babcock MC, Grosicki GJ, Linder BA, McDermott BP, Robinson AT',
    'Journal of applied physiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41615405/',
    array['Kidney Health', 'Hydration'],
    'Marathon and ultramarathon runners commonly show postrace rises in kidney injury biomarkers. These are usually transient, but clinically significant cases do occur. The main drivers are hemodynamic stress, muscle damage, gastrointestinal permeability, and hydration status. Elevation gain, temperature, humidity, fitness, biological sex, age, and race-day hydration practices all modulate individual risk.',
    'Athletes racing in heat, at altitude, or over very long distances should treat hydration as a performance and safety variable, not an afterthought. Coaches should monitor athletes with known risk factors and build individualized hydration plans into the race strategy.',
    'Practical mini-review with clear guidance for coaches managing athletes in long-distance events.',
    5,
    3,
    3,
    true
  ),
  -- 12. Concurrent training umbrella review
  (
    '41762427',
    'Maximizing Adaptations in Concurrent Training: An Umbrella Review of Meta-analyses.',
    'Held S, Wolf L, Rappelt L, Bloch W, Donath L, Micke F, Geisler S, Isenmann E',
    'Sports medicine',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41762427/',
    array['Strength Training', 'Training Structure'],
    'This umbrella review of 17 meta-analyses found that combining resistance and endurance training improves both aerobic capacity and strength without meaningful interference in recreationally trained individuals. Compared to endurance-only training, concurrent training added significant strength. Compared to resistance-only training, it added aerobic capacity without compromising strength, power, or hypertrophy. Performing resistance work before endurance work showed a non-significant trend toward better strength and hypertrophy gains.',
    'Endurance athletes should not fear strength training. The interference effect is smaller than commonly assumed for most athletes. When sequencing matters, do the strength work first. Data from elite populations remains limited.',
    'The most comprehensive concurrent training review to date. Directly addresses a common coaching concern across all endurance sports.',
    4,
    5,
    5,
    true
  ),
  -- 13. Carbohydrate strategies for cross-country skiing
  (
    '41755452',
    'Carbohydrate Storage and Supplementation Strategies for Peak Performance in Cross-Country Skiing.',
    'Ørtenblad N, Holmberg HC, Nybo L, Gejl KD',
    'Scandinavian journal of medicine & science in sports',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41755452/',
    array['Fueling & Nutrition', 'Cross-Country Skiing'],
    'Cross-country skiing has exceptionally high whole-body energy turnover with varying loads on upper and lower body muscles. Glycogen depletion patterns depend on course profile, snow conditions, sub-technique, and race format. Adequate carbohydrate intake between sessions is essential to restore both liver and muscle glycogen, and supplementation during prolonged workouts delays depletion in the working muscles.',
    'Skiing athletes need to match carbohydrate replenishment to the specific demands of their discipline, including the unique upper-body glycogen demands that distinguish skiing from running or cycling. Recovery windows between sessions are critical when training volume is high.',
    'Directly applicable to biathlon, Nordic combined, and any athlete cross-training on ski-based modalities.',
    3,
    3,
    3,
    true
  ),
  -- 14. Multi-timescale power tracking in professional cyclists
  (
    '42145217',
    'Tracking Performance Limits Using Multi-Timescale Maximal Mean Power Ratios.',
    'Zignoli A, Giorgi A, Kolodziej F, Martinez-Gonzalez B, Leo P, Laursen PB',
    'European journal of sport science',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42145217/',
    array['Performance Monitoring', 'Cycling Performance'],
    'A new framework uses rolling maximal mean power ratios across multiple time scales to track how close a cyclist is to their performance limits in real time. When tested on 21 professional cyclists, the model converged to 98-101% of historical capacity at the end of maximal time trials. The dominant constraint was often a slower time scale than the nominal effort duration, meaning performance limits emerge from the interaction of multiple energy systems, not just the one matching the effort.',
    'Power data analysis should look at multiple time scales simultaneously, not just the duration of the target effort. A rider''s limit in a 3-minute effort may actually be constrained by a 1-hour capacity component. This reframes how coaches interpret record power profiles.',
    'Advanced analytics for power-based training. Most applicable to coached cyclists and triathletes using power meters.',
    2,
    5,
    4,
    true
  ),
  -- 15. Ultra-endurance tetrathlon fueling and CGM
  (
    '41868981',
    'Case Report: Stage-by-stage fueling, glucose dynamics, and next-day metabolism and biomarker responses after baseline testing in an 18.5-hour Swedish classic tetrathlon.',
    'Trinh J, Edin F, Andersson-Hall U, Pettersson S',
    'Frontiers in sports and active living',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41868981/',
    array['Fueling & Nutrition', 'Ultra-Endurance'],
    'An amateur athlete completed the Swedish Classic tetrathlon (316 km cycling, 3 km swimming, 84 km roller-skiing, 30 km trail running) in 18.5 hours with continuous glucose monitoring. Total intake was 5825 kcal with 1051 g carbohydrate. Glucose remained stable across cycling, swimming, and skiing, but transient hypoglycemia appeared only during the final run. Discipline-specific feeding opportunities, not generic hourly targets, determined achievable carbohydrate delivery.',
    'In multi-discipline ultra events, fueling plans should be built around the logistics of each discipline rather than a flat hourly target. The terminal stage is where glycemic control breaks down, so front-loading fuel during stages with better access matters.',
    'Rare integrated dataset combining weighed-back nutrition, CGM, and next-day metabolic testing in a condensed multi-sport event.',
    5,
    3,
    5,
    true
  ),
  -- 16. Ultramarathon metabolic challenges by distance
  (
    '41374091',
    'Does Distance Matter? Metabolic and Muscular Challenges of a Non-Stop Ultramarathon with Sub-Analysis Depending on Running Distance.',
    'John L, Munk M, Bizjak R, Schulz SVW, Witzel J, Engler H, Siebers C, Siebers M, Kirsten J, Grau M, Bizjak DA',
    'Nutrients',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/41374091/',
    array['Fueling & Nutrition', 'Ultra-Endurance'],
    'In a non-stop ultramarathon with 100 km, 160.9 km, and 230 km distances, the mean energy deficit was nearly 6800 kcal with carbohydrate-dominant fueling at 79%. Significant drops in leptin and insulin, and rises in ghrelin, glucagon, and muscle damage markers occurred across all distances, with the 230 km group showing the greatest disruption. Energy homeostasis broke down regardless of distance.',
    'Even well-fueled ultramarathon runners accumulate massive energy deficits. Nutritional strategies should aim to minimize the deficit rather than eliminate it, and recovery nutrition after the event is as important as race-day fueling.',
    'Valuable metabolic data across three ultra distances using CGM and hormonal panels.',
    5,
    3,
    3,
    true
  ),
  -- 17. Race-day carbohydrate intake discrepancies
  (
    '41054247',
    'Under Consumed and Overestimated: Discrepancies in Race-Day Carbohydrate Intake Among Endurance Athletes.',
    'Lanpir AD, Eroğlu MN, Özyıldırım M, Louis J',
    'European journal of sport science',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/41054247/',
    array['Fueling & Nutrition', 'Race Execution'],
    'Across 60 endurance athletes in official marathon and cycling races, actual carbohydrate intake during competition averaged only 31.7 g/h, well below the 38 g/h they planned. Athletes consistently overestimated how much they consumed. Better sleep behavior and lower pre-race cognitive anxiety predicted higher actual intake. Cyclists achieved higher absolute intake than marathoners but both groups fell short by a similar proportion.',
    'Plan your fuel, then verify what actually goes in. Most athletes consume less than they think during a race. Pre-race sleep quality and anxiety management directly affect fueling execution, making them legitimate performance variables.',
    'Bridges the gap between nutrition guidelines and real-world execution. Coaches should weigh-back sports products in training to calibrate intake perception.',
    5,
    5,
    5,
    true
  ),
  -- 18. Exercise-associated hyponatremia
  (
    '40913680',
    'Pathophysiology and treatment of exercise-associated hyponatremia.',
    'Altieri B, Aini I, Cannavale G, Magnelli C, Mancini C, Zamponi V, Isidori AM, Colao A, Faggiano A, Peri A',
    'Journal of endocrinological investigation',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40913680/',
    array['Hydration', 'Race Safety'],
    'Exercise-associated hyponatremia occurs not just in ultramarathons and Ironman triathlons but also in team sports and shorter events. The main driver is excessive fluid intake combined with non-osmotic vasopressin secretion during exercise, not primarily sodium loss through sweat. Symptoms range from nausea and headache to seizures, coma, and death. The old advice to drink ahead of thirst should be replaced by drinking when thirsty.',
    'Replace the "drink before you are thirsty" mantra with a thirst-driven hydration strategy. Over-drinking is more dangerous than mild under-drinking in most endurance settings. Athletes and crew need to know the early signs of hyponatremia.',
    'Critically important safety review. Every race crew and ultra athlete should understand this condition.',
    5,
    3,
    5,
    true
  ),
  -- 19. Caffeine enhances performance regardless of diet (Burke)
  (
    '40964913',
    'Caffeine enhances performance regardless of fueling strategy; however, high carbohydrate availability is associated with improved training speeds compared with ketogenic diet.',
    'Burke LM, Merrell L, Heikura IA, Civil R, Sharma AP, Leckey JJ, McKay AKA',
    'The British journal of nutrition',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40964913/',
    array['Caffeine', 'Fueling & Nutrition'],
    'In elite race walkers, a ketogenic low-carb high-fat diet reduced training speeds compared to high-carb availability over 3 weeks. Caffeine (3 mg/kg) improved performance equally in both dietary groups but could not fully compensate for the keto-related decrement. Athletes on high carbohydrate availability plus caffeine achieved the best training quality overall.',
    'Caffeine is a reliable ergogenic aid regardless of dietary approach, but it does not erase the performance cost of low carbohydrate availability for high-intensity training. If training quality matters, carbohydrate availability should be protected.',
    'From Louise Burke''s elite athlete research camp. Clean crossover design in a real-world training setting.',
    4,
    4,
    4,
    true
  ),
  -- 20. Carbohydrate dose and exercise intensity domains
  (
    '42018708',
    'Recommended but Not High Carbohydrate Dose Improves Performance After Heavy- but Not Moderate-Intensity Exercise in Recreationally Trained Participants.',
    'Fleitas-Paniagua PR, Rasica L, Azevedo RA, Iannetta D, Alvares TS, Zagatto AM, Murias JM',
    'Scandinavian journal of medicine & science in sports',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42018708/',
    array['Fueling & Nutrition', 'Training Structure'],
    'Recommended-dose carbohydrate supplementation (40 g/h) improved 4-km time trial performance after heavy-intensity exercise but not after moderate-intensity exercise. Doubling the dose to 90 g/h provided no additional benefit at any intensity. The ergogenic effect of mid-session fueling depends on both the dose and the intensity domain of the preceding work.',
    'More carbohydrate is not always better. Match the fueling dose to the session demands. After moderate work, supplementation may not matter. After heavy work, the standard recommended dose helps, but mega-dosing does not add further benefit.',
    'Useful nuance for coaches programming fueling around different session types.',
    3,
    4,
    4,
    true
  )
on conflict (pubmed_id) do update
set
  title = excluded.title,
  authors = excluded.authors,
  journal = excluded.journal,
  publication_year = excluded.publication_year,
  pubmed_url = excluded.pubmed_url,
  topic_tags = excluded.topic_tags,
  plain_english_summary = excluded.plain_english_summary,
  practical_takeaway = excluded.practical_takeaway,
  commentary = excluded.commentary,
  ultra_score = excluded.ultra_score,
  gravel_score = excluded.gravel_score,
  triathlon_score = excluded.triathlon_score,
  published = excluded.published,
  updated_at = now();
