-- Seed 20 new research library entries covering broad endurance disciplines:
-- ultra cycling, rowing, paddling, biathlon, cross-country skiing, open-water
-- swimming, triathlon durability, cardiac health, recovery, sex differences,
-- chronotype, and pacing.
-- Sources retrieved from PubMed (National Library of Medicine).

insert into public.research_library_entries (
  pubmed_id,
  title,
  authors,
  journal,
  publication_year,
  publication_date,
  pubmed_url,
  topic_tags,
  plain_english_summary,
  practical_takeaway,
  commentary,
  ultra_score,
  gravel_score,
  triathlon_score,
  published
)
values
  -- 1. 24-hour ultra cycling world record: exercise-induced heart failure
  (
    '42126136',
    'From Healthy to Heart Failure in 24 Hours: Defining the upper limit of exercise induced cardiac fatigue.',
    'Foulkes SJ, Anderson M, Janssens K, Beaudry R, Carey A, Mitchell A, Spencer L, Angus D, Haykowsky MJ, La Gerche A',
    'Journal of applied physiology',
    2026,
    '2026-05-13',
    'https://pubmed.ncbi.nlm.nih.gov/42126136/',
    array['Cardiac Health', 'Ultra-Endurance'],
    'A former professional ultra-endurance cyclist was comprehensively evaluated before and after two world-record attempts at 12 and 24 hours of continuous cycling. After 12 hours, cardiac biomarkers and ventricular function were moderately impaired but recovered within 14 days. After 24 hours, the athlete developed acute respiratory distress and pulmonary edema with profoundly elevated biomarkers and bi-ventricular ejection fractions of 37 percent and 32 percent. Function only partially recovered at 18 days but fully normalized by 5 months. This is the most definitive evidence of an exercise dose threshold that triggers acute heart failure.',
    'There is a real upper limit to how long the heart can sustain maximal output. Athletes and crews in 24-hour-plus events should be aware that acute cardiac failure is possible even in highly trained individuals. Full recovery took months, not days. Post-event cardiac screening after extreme efforts is warranted.',
    'Landmark case study with CMR imaging data. The 12-hour versus 24-hour comparison within the same athlete provides the clearest dose-response evidence of exercise-induced cardiac fatigue ever published.',
    5,
    4,
    4,
    true
  ),
  -- 2. 866 km ultra-trail race: oxidative/inflammatory profile of finishers vs DNFs
  (
    '42196277',
    'Oxy-Inflammatory Profile of Finishers and No-Finishers in an Extreme Ultra-Endurance Trail Race: The 866 km Transpyrénéa.',
    'Mrakic-Sposta S, Gussoni M, Mrakic-Sposta F, Giardini G, Pratali L, Montorsi M, Tonacci A, Dellanoce C, Martinelli M, Vezzoli A',
    'International journal of molecular sciences',
    2026,
    '2026-05-12',
    'https://pubmed.ncbi.nlm.nih.gov/42196277/',
    array['Recovery', 'Ultra-Endurance'],
    'Thirty-nine ultra-runners were tracked during the 866-km Transpyrénéa across the French Pyrenees with 52,900 meters of climbing. Both finishers and DNF athletes showed massive increases in reactive oxygen species, oxidative damage, inflammation, and transient immune-renal dysfunction. Finishers differed from non-finishers in baseline oxidative stress levels before the race even started, and in perceived exertion at the midpoint. This suggests that better-adapted athletes entered the race with lower baseline oxidative burden and tolerated extreme physiological stress more efficiently.',
    'Pre-race oxidative and inflammatory status may predict who finishes extreme ultra events. Athletes preparing for multi-day efforts should consider antioxidant status and training that builds oxidative stress tolerance as part of their preparation, not just aerobic fitness and fueling.',
    'Rare biomarker data from one of the longest trail races in existence. The pre-race difference between finishers and non-finishers is the standout finding for coaches and athletes.',
    5,
    3,
    2,
    true
  ),
  -- 3. Sex differences in endurance performance: comprehensive review
  (
    '42057283',
    'Physiological Basis of Sex Differences in Human Performance and Exercise-Associated Pathology.',
    'Holdsworth DA, O''Leary TJ, Doig CL, Taylor N, Dosanjh J, Woods DR, Stacey MJ, Gifford RM',
    'Clinical endocrinology',
    2026,
    '2026-04-29',
    'https://pubmed.ncbi.nlm.nih.gov/42057283/',
    array['Female Athletes', 'Training Methodology'],
    'This review examines the hormonal and physiological mechanisms driving sex differences in exercise performance. Higher testosterone in men leads to greater muscle mass, hemoglobin, bone size, and cardiac output, explaining most of the 10 to 15 percent performance gap. Female physiology confers advantages during prolonged submaximal exercise through greater fat oxidation, lower carbohydrate dependence, and improved fatigue resistance, which may explain the narrowing performance gap in ultra-endurance events. Sex differences also influence injury risk, reproductive dysfunction, and thermoregulation.',
    'Female athletes have genuine physiological advantages in ultra-distance events that coaches should leverage, not ignore. Training programs and fueling strategies should account for sex-specific metabolic profiles. Male-derived training models applied universally miss these differences.',
    'A comprehensive bridge between endocrinology and sport science. Directly relevant for any coach working with mixed-sex rosters in ultra, gravel, or triathlon.',
    5,
    4,
    5,
    true
  ),
  -- 4. Endurance training in Olympic winter sports: dual framework
  (
    '41673933',
    'Endurance Training in Olympic Winter Sports: A Narrative Review of the Current Literature and Future Research Priorities.',
    'Sperlich B, Holmberg HC',
    'Scandinavian journal of medicine & science in sports',
    2026,
    '2026-02-01',
    'https://pubmed.ncbi.nlm.nih.gov/41673933/',
    array['Periodization', 'Training Methodology'],
    'This review proposes two models for endurance training in winter sports. An endurance-limited model for sports like cross-country skiing and biathlon where aerobic capacity is the primary performance limiter, and a feeder-function model where endurance primarily supports recovery, training tolerance, and resilience in sports like freestyle skiing and snowboarding. The review integrates emerging concepts of durability, fatigability, resilience, and repeatability, and argues for individualized volume-intensity prescriptions informed by multimodal stress stacking using hypoxia and heat.',
    'Not all endurance training serves the same purpose. In some sports and phases, endurance work is the goal; in others, it feeds recovery and training tolerance. Match your endurance prescription to whether it is the limiter or the enabler.',
    'A paradigm-organizing paper that gives coaches a framework for deciding how much endurance work belongs in any sport. The tier system for when endurance is a limiter versus a support function is immediately applicable.',
    4,
    4,
    4,
    true
  ),
  -- 6. Caffeine in biathlon: endurance benefit vs shooting cost
  (
    '41666907',
    'Effects of Acute Caffeine Supplementation on Integrated Biathlon Performance in Elite Male Athletes.',
    'Engel H, Yilmaz C, Appelhans D, Staunton CA, Kock H, Mathieu J, Leitlauf T, Brandl R, Waibel K, Koehler K',
    'International journal of sport nutrition and exercise metabolism',
    2026,
    '2026-02-09',
    'https://pubmed.ncbi.nlm.nih.gov/41666907/',
    array['Caffeine', 'Supplementation'],
    'Seven elite male biathletes consumed caffeine at 3 mg/kg or placebo before a simulated biathlon competition. Caffeine increased skiing distance in the first two laps and raised blood lactate and ventilation. However, it impaired standing shooting accuracy from 83 to 73 percent and reduced precision shooting in the prone position after exercise. When integrated across all race formats, the net effect on overall race time was zero because the skiing gains were offset by the shooting penalties.',
    'In sports requiring both endurance output and fine motor precision, caffeine is not a free lunch. The endurance benefit is real but the accuracy cost can cancel it out. Athletes in any sport combining effort with skill, such as adventure racing or orienteering, should test caffeine effects on both dimensions.',
    'First study to quantify the caffeine trade-off in a real integrated biathlon simulation with elite athletes. The finding that net race time was unchanged despite faster skiing is a powerful cautionary result.',
    3,
    3,
    3,
    true
  ),
  -- 7. VO2peak as predictor of rowing performance
  (
    '42112935',
    'Peak Oxygen Uptake Provides a Better Predictor of Rowing Ergometer Mean Maximal Power Than Maximal Oxygen Extraction in Trained Rowers.',
    'Lanigan BJO, Tinely ZL, Binnie MJ, Peeling P, Scott BR, Peiffer JJ, Galna B, Dennis MC, Billaut F, Goods PSR',
    'Journal of strength and conditioning research',
    2026,
    '2026-05-07',
    'https://pubmed.ncbi.nlm.nih.gov/42112935/',
    array['VO2max', 'Rowing'],
    'In 22 trained rowers, peak oxygen uptake explained 74 percent of the variance in mean maximal power on an ergometer. Adding near-infrared spectroscopy measurements of muscle oxygen extraction improved prediction only marginally. Muscle oxygen extraction alone had no association with maximal power output. The gastrocnemius showed the greatest increase in oxygen extraction at high intensities, suggesting it becomes a limiting muscle during maximal rowing.',
    'For rowers and coaches, VO2peak remains the gold standard predictor of ergometer performance. Muscle oxygen monitors like NIRS provide interesting supplementary data but should not replace traditional metabolic testing. The gastrocnemius finding suggests calf-specific conditioning may have underappreciated value.',
    'Practical guidance for rowing coaches deciding where to invest in testing technology. VO2peak testing remains the priority over NIRS-based approaches.',
    2,
    2,
    3,
    true
  ),
  -- 8. Anaerobic power reserve framework in rowing (1500m Olympic format)
  (
    '41348913',
    'Performance Prediction and Athlete Categorization using the Anaerobic Power Reserve Framework in Rowing.',
    'Rappelt L, Donath L, Wiedenmann T, Micke F, Mühlenhoff S, Held S',
    'Medicine and science in sports and exercise',
    2026,
    '2026-03-05',
    'https://pubmed.ncbi.nlm.nih.gov/41348913/',
    array['Rowing', 'Training Methodology'],
    'With the Olympic rowing distance changing from 2000 to 1500 meters for 2028, this study used the anaerobic power reserve framework to predict 2000-meter performance and categorize rowers. Power at 4 mmol/L lactate and peak power output were the strongest predictors of ergometer performance in both sexes. K-means clustering identified distinct sprint-type and endurance-type rowers along the power reserve ratio continuum, even among athletes with similar overall performance.',
    'The shortened Olympic distance rewards athletes with a higher anaerobic power reserve. Coaches should use the power reserve ratio to identify whether an athlete is sprint-type or endurance-type and tailor training accordingly. Two rowers with identical 2000-meter times may need very different approaches to optimize 1500-meter performance.',
    'Directly relevant as rowing transitions to the shorter Olympic format. The sprint-endurance categorization framework has applications beyond rowing for any endurance sport with varying distance formats.',
    2,
    2,
    3,
    true
  ),
  -- 9. Cold water immersion protocol optimization across exercise modalities
  (
    '41845491',
    'Cold water immersion protocol optimization across exercise modalities: a systematic review and network meta-analysis of resistance training, endurance exercise, and team sport applications.',
    'Yu T, Liu Y, Ding C, Wang S, Wan Y, Fei X, Guan D, Wang J, Hao L',
    'BMC sports science, medicine & rehabilitation',
    2026,
    '2026-03-18',
    'https://pubmed.ncbi.nlm.nih.gov/41845491/',
    array['Recovery', 'Training Methodology'],
    'This network meta-analysis of 87 studies and 2,313 athletes found that optimal cold water immersion protocols vary dramatically by exercise type. For strength training, passive recovery actually outperformed CWI for strength outcomes. For endurance exercise, moderate-temperature protocols at 9 to 12 degrees Celsius for 10 to 15 minutes showed the most promise for recovery. The strongest effects across all modalities were for reducing perceived fatigue and muscle damage biomarkers, not for directly improving next-session performance.',
    'Stop using the same ice bath protocol for everything. After endurance sessions, use moderate cold at 9 to 12 degrees for 10 to 15 minutes. After strength work aimed at building strength, skip the ice bath entirely. CWI is a recovery perception tool more than a performance tool.',
    'The most comprehensive CWI analysis to date. The finding that passive recovery beats CWI for strength adaptation should change how multi-sport athletes plan their recovery.',
    4,
    4,
    4,
    true
  ),
  -- 10. CWI after HIIT does not impair endurance adaptations
  (
    '41742004',
    'Regular Cold-Water Immersion Following HIIT Does Not Affect Intramuscular Adaptation Markers, Inflammatory Profile or Endurance Performance.',
    'Malta ES, Neto JCR, Beck WR, Cornachione AS, de Poli RAB, Sigoli E, Zagatto AM',
    'Scandinavian journal of medicine & science in sports',
    2026,
    '2026-03-01',
    'https://pubmed.ncbi.nlm.nih.gov/41742004/',
    array['Recovery', 'VO2max'],
    'Sixteen males completed 5 weeks of HIIT with or without post-session cold water immersion at 11 degrees Celsius for 15 minutes. Both groups improved VO2max, time to exhaustion, satellite cell pool, and PGC-1-alpha content equally. CWI did not blunt any intramuscular adaptation marker, inflammatory response, or performance gain. This contradicts the common fear that ice baths after hard endurance sessions will impair training adaptations.',
    'If you use cold water immersion after high-intensity endurance sessions for recovery comfort, the evidence suggests it will not compromise your aerobic adaptations over a 5-week block. The adaptation concern applies more to strength and hypertrophy goals than to endurance goals.',
    'Addresses a common coaching concern with direct experimental evidence. The distinction between strength adaptation interference and endurance adaptation interference from CWI is clinically important.',
    4,
    4,
    4,
    true
  ),
  -- 11. Durability profiling in junior triathletes
  (
    '42097586',
    'Durability of International and National Junior and U23 Triathletes: A Simulated Stochastic Sprint Triathlon Cycle Elicits Significant Declines in Running Physiology and Performance Indices.',
    'Langley JO, Knight M, Bloom W, O''Brien H',
    'International journal of sports physiology and performance',
    2026,
    '2026-05-07',
    'https://pubmed.ncbi.nlm.nih.gov/42097586/',
    array['Running Economy', 'Pacing'],
    'Eight elite junior triathletes completed a stochastic sprint-triathlon cycling simulation followed by running assessments. In the fatigued state, VO2peak dropped significantly, velocity at VO2peak declined, and time to task failure was reduced. The gas exchange threshold shifted upward as a percentage of VO2peak, meaning the relative intensity of running at the same pace increased after cycling. Critically, the individual responses varied enormously between athletes.',
    'Fresh running tests tell you what an athlete can do; fatigued running tests tell you what they will do in a race. Test durability specifically by assessing running physiology after hard cycling. The massive individual variation means each athlete needs their own durability profile.',
    'Durability is the emerging frontier in triathlon science. This study provides a practical protocol for measuring it in developing athletes.',
    3,
    3,
    5,
    true
  ),
  -- 12. Chronotype affects cycling time-trial performance
  (
    '41402031',
    'Influence of Chronotype on Cycling Performance in Simulated 20-km Time Trials-A Pilot Study.',
    'Forster S, Schwindling S, Abbiss C, Döringer F, Klütsch A, Hecksteden A, Meyer T',
    'Journal of sleep research',
    2025,
    '2025-12-16',
    'https://pubmed.ncbi.nlm.nih.gov/41402031/',
    array['Sleep', 'Pacing'],
    'Competitive cyclists and triathletes categorized as definite evening types performed significantly better later in the day, finishing 40 seconds faster at 18:00 compared to 06:00 in a 20-km time trial. Evening types also reported lower mental readiness in the early morning. Morning types showed no significant time-of-day variation. Overall, all participants were faster in the evening than the morning by about 2 percent.',
    'If you are a confirmed evening chronotype, schedule your key training sessions and races later in the day when possible. A 2 percent performance difference is meaningful in competitive endurance sport. If your race starts early, consider chronotype-specific warm-up and preparation strategies.',
    'Connects circadian biology to real competitive performance. The 40-second difference in a 20-km TT is the kind of margin that decides races.',
    3,
    5,
    5,
    true
  ),
  -- 13. Female Triple Deca ultra-triathlon pacing (first woman to finish)
  (
    '41630831',
    'Pacing of the first and only female finisher in the world''s longest triathlon: The 2024 Triple Deca ultra triathlon.',
    'Duric S, Andrade MS, Leite LB, Forte P, Nikolaidis PT, Cuk I, Weiss K, Rosemann T, Knechtle B',
    'Journal of exercise science and fitness',
    2026,
    '2026-01-19',
    'https://pubmed.ncbi.nlm.nih.gov/41630831/',
    array['Pacing', 'Female Athletes'],
    'This case study analyzes the pacing of the first and only woman to complete 30 consecutive long-distance triathlons in 30 days. She maintained relatively even pacing throughout, with cycling speed gradually decreasing and running speed increasing over the 30 days. Cycling performance was the strongest predictor of daily total race time. Energy expenditure and heart rate were significant predictors for cycling pace, while only average heart rate predicted running performance.',
    'In extreme multi-day events, protect cycling output above all else because it has the strongest correlation with total time. Running pace may actually improve over weeks as the body adapts. Pacing strategy should be built around the discipline that most influences total time, not the one that feels hardest.',
    'First scientific analysis of female performance in the world''s longest triathlon format. The improving run speed over 30 days is a fascinating adaptation finding.',
    5,
    3,
    5,
    true
  ),
  -- 14. Outrigger canoe: predicting on-water performance
  (
    '41958824',
    'Prediction of on-water performance in outrigger canoeing using laboratory tests: the influence of sex and anthropometric characteristics.',
    'Estácio Costa F, Kons RL, Caputo F, Dal Pupo J',
    'Frontiers in sports and active living',
    2026,
    '2026-03-25',
    'https://pubmed.ncbi.nlm.nih.gov/41958824/',
    array['Paddling', 'Training Methodology'],
    'In 38 competitive outrigger canoe paddlers, the relationship between lab-based ergometer performance and on-water racing was strongly sex-dependent. In males, incremental peak power best predicted on-water speed. In females, 1000-meter mean power allometrically adjusted for body mass was the strongest predictor. Body mass and lean body mass were moderately to strongly associated with ergometer power in females but not in males. No anthropometric variables predicted on-water performance directly in either sex.',
    'For paddling athletes, ergometer testing predicts on-water performance but only when interpreted through a sex-specific lens. Female paddlers benefit more from body composition optimization, while male paddlers should focus on peak power development. On-water testing remains essential for both.',
    'One of the few studies on a paddling-based endurance sport. The sex-specific findings are relevant for any coach working with kayakers, canoeists, or stand-up paddlers.',
    3,
    2,
    3,
    true
  ),
  -- 15. All-female Atlantic rowing: mood, sleep, fatigue across 3000 miles
  (
    '41698792',
    'Mood, sleep, fatigue and recovery profiles from the first all-female UK military team rowing 3000 miles across the Atlantic.',
    'Scheer V, de Sá Souza H, Mendes PHV, O''Brien I, Glover R, Morris G, Kaulback K',
    'BMJ military health',
    2026,
    '2026-02-16',
    'https://pubmed.ncbi.nlm.nih.gov/41698792/',
    array['Sleep', 'Ultra-Endurance'],
    'Four female British Army personnel completed a 3000-mile unsupported Atlantic rowing race in 46 days. Mean sleep was only 3.8 hours per night. They lost an average of 15.5 percent of body mass. Tension and fatigue decreased toward mid-race, suggesting psychological adaptation. Depressive mood appeared only on days 16 and 40. Recovery perception was strongly negatively correlated with fatigue when sleep dropped below 3.5 hours, identifying a critical sleep threshold.',
    'In extreme multi-day endurance events, a sleep floor of approximately 3.5 hours appears to be the threshold below which recovery perception collapses. The mid-race psychological adaptation, where tension and fatigue decrease, suggests the early days are the hardest mentally. Crew and support strategies should front-load psychological support.',
    'Rare longitudinal data from an extreme female endurance event. The 3.5-hour sleep threshold and the mid-race mood adaptation pattern are directly applicable to multi-day ultra racing.',
    5,
    2,
    3,
    true
  ),
  -- 16. Block vs even periodization of low-intensity training in XC skiing
  (
    '42177035',
    'No Additional Effects of Block- Compared to Even-Periodization of Low-Intensity Training in Junior Cross-Country Skiers.',
    'Walther J, Hänel L, Krohn R, Großmann S, Schumann M',
    'International journal of sports physiology and performance',
    2026,
    '2026-05-23',
    'https://pubmed.ncbi.nlm.nih.gov/42177035/',
    array['Periodization', 'Training Methodology'],
    'Twenty junior cross-country skiers completed a crossover study comparing block periodization of low-intensity training at 160 percent of normal volume in one week followed by reduced volume, versus evenly distributed volume-matched training. Neither VO2max, maximal aerobic speed, nor submaximal performance differed between approaches. The block group reported significantly lower mood and perceived recovery during and after the high-volume week. Consistent application of low-intensity training produced the same gains without the mood cost.',
    'For low-intensity training, consistency beats concentration. Block periodization did not provide an additional stimulus compared to even distribution when total volume was matched. Save the block approach for high-intensity work where the concentrated stimulus may matter more.',
    'Challenges the assumption that block periodization is universally superior. For the large low-intensity base that dominates most endurance programs, steady distribution appears equally effective and more sustainable.',
    4,
    4,
    4,
    true
  ),
  -- 17. Cardiac changes across half-marathon, marathon, and ultramarathon
  (
    '41732747',
    'Exercise-induced ventricular changes in recreational half-marathon runners compared with marathon/ultramarathon runners.',
    'Blachut D, Janik M, Mazurkiewicz M, Cieśla J, Wojciechowski P, Krawiec M, Schulz M, Kurczyński D, Kosowski M, Wojciechowska C, Tomasik A, Kukulski T',
    'International journal of cardiology. Heart & vasculature',
    2026,
    '2026-02-14',
    'https://pubmed.ncbi.nlm.nih.gov/41732747/',
    array['Cardiac Health', 'Recovery'],
    'In 105 amateur runners across half-marathon, marathon, and ultramarathon distances, left ventricular global longitudinal strain was reduced after marathon and ultra distances but not after the half-marathon. Right ventricular parameters showed smaller, non-significant declines. All changes normalized within two weeks. Critically, the cardiac response did not differ significantly between marathon and ultramarathon distances, and no simple demographic or training variable reliably predicted who would show the greatest decline.',
    'Post-race cardiac changes in recreational runners are mild, transient, and fully reversible within two weeks regardless of distance. Higher weekly training volume may offer some protection. There is no need to panic about cardiac biomarkers after a long race, but allow at least two weeks of reduced intensity before the next hard effort.',
    'Reassuring data for the growing population of recreational ultra runners. The lack of distance-dependent cardiac effects beyond the half-marathon threshold is a notable finding.',
    5,
    3,
    4,
    true
  ),
  -- 18. Nutritional strategies for Olympic biathletes
  (
    '41228458',
    'Nutritional Strategies for Olympic Biathletes: A Practical Review.',
    'Gawelczyk M, Kaszuba M, Petr M',
    'Nutrients',
    2025,
    '2025-10-28',
    'https://pubmed.ncbi.nlm.nih.gov/41228458/',
    array['Fueling & Nutrition', 'Supplementation'],
    'This review synthesizes nutrition recommendations specific to biathlon, where daily energy expenditure can exceed 7000 kcal during intensive training. Carbohydrate intake should match session intensity at 6 to 12 grams per kilogram per day, and protein should reach at least 1.6 grams per kilogram per day distributed every 3 to 4 hours. Iron and vitamin D deficiencies are common risks. Race-day meals should be timed to meet both endurance and precision demands, as some performance supplements like caffeine may impair shooting accuracy.',
    'For athletes in dual-demand sports combining endurance and precision, nutrition planning must account for both. Standard endurance fueling advice may be incomplete if the sport also requires fine motor skills. Time meals and supplements around both the physical and technical demands of the event.',
    'The first comprehensive nutrition review specific to biathlon. The dual-performance framework of fueling for both endurance and shooting accuracy has applications for adventure racing, orienteering, and multi-sport events.',
    3,
    3,
    3,
    true
  ),
  -- 19. Critical swimming speed as pacing metric in 10 km open-water racing
  (
    '40843832',
    'Evaluation of Race Pace Using Critical Swimming Speed During 10 km Open-Water Swimming Competition.',
    'Fujito Y, Fujimoto T, Hara R, Yoshida R, Funato K',
    'Journal of functional morphology and kinesiology',
    2025,
    '2025-08-03',
    'https://pubmed.ncbi.nlm.nih.gov/40843832/',
    array['Pacing', 'Open Water Swimming'],
    'In the 2023 World Championship men''s 10-km open-water swim, the top 10 finishers maintained pace at about 93 percent of their pool-derived critical swimming speed from start to finish, with longer strokes and lower stroke frequency. Swimmers finishing 31st and below started at 96 to 98 percent of critical speed and faded dramatically to 85 to 88 percent by the final lap. The ability to maintain a conservative, sustainable percentage of critical speed was the defining characteristic of top performers.',
    'In open-water endurance events, the winners pace at about 92 to 93 percent of critical speed throughout. Do not start at or above critical speed. Calculate your critical speed from pool tests and use it as a ceiling, not a target, for open-water race pacing.',
    'Clean pacing data from a world championship event. The 92 percent critical speed guideline provides a concrete, testable target for open-water swimmers and triathletes.',
    3,
    2,
    5,
    true
  ),
  -- 20. Advanced echocardiography reveals training-specific cardiac adaptations
  (
    '42138932',
    'Echocardiographic Parameters and Athlete Performance: Associations and Training Profile Comparisons.',
    'Guerra E, Segreti A, Carpenito M, Ciancio M, Guarino L, Ricciardi D, Fossati C, Suma S, Gaibazzi N, Rosiello R, Lettieri C, Papalia R, Pigozzi F, Boriani G, Grigioni F',
    'Echocardiography',
    2026,
    '2026-05-01',
    'https://pubmed.ncbi.nlm.nih.gov/42138932/',
    array['Cardiac Health', 'Training Methodology'],
    'Long-distance runners had the highest stroke volume index and lowest global longitudinal strain compared to mid-distance runners and detrained athletes, but their myocardial work efficiency was the highest. Stroke volume index and global work efficiency were independently associated with peak VO2, while global longitudinal strain was not. This means a lower resting strain value in an ultra or marathon runner is not a sign of dysfunction but reflects a more efficient cardiac work pattern.',
    'Clinicians interpreting echocardiograms in endurance athletes should use myocardial work indices, not just strain, to assess cardiac health. Lower global longitudinal strain in long-distance athletes reflects efficient adaptation, not pathology. Athletes and coaches should understand that screening results must be interpreted in the context of sport-specific cardiac remodeling.',
    'Reframes how cardiac imaging should be interpreted in endurance athletes. The finding that work efficiency, not strain, predicts VO2peak has direct implications for athlete screening programs.',
    5,
    4,
    4,
    true
  )
on conflict (pubmed_id) do update
set
  title = excluded.title,
  authors = excluded.authors,
  journal = excluded.journal,
  publication_year = excluded.publication_year,
  publication_date = excluded.publication_date,
  pubmed_url = excluded.pubmed_url,
  topic_tags = excluded.topic_tags,
  plain_english_summary = excluded.plain_english_summary,
  practical_takeaway = excluded.practical_takeaway,
  commentary = excluded.commentary,
  ultra_score = excluded.ultra_score,
  gravel_score = excluded.gravel_score,
  triathlon_score = excluded.triathlon_score,
  published = excluded.published,
  updated_at = now();
