insert into public.research_library_entries (
  pubmed_id,
  title,
  authors,
  journal,
  publication_year,
  pubmed_url,
  topic_tags,
  plain_english_summary,
  practical_takeaway,
  commentary,
  ultra_score,
  gravel_score,
  triathlon_score,
  published
)
values
  (
    '42070893',
    'Does a low-carbohydrate diet impede endurance sports performance? Debate Consensus.',
    'Burke LM, Noakes TD',
    'The American journal of clinical nutrition',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42070893/',
    array['Fueling & Nutrition', 'Carbohydrate Loading'],
    'This debate between two of the field''s biggest voices lands on a nuanced middle ground: carbohydrate availability clearly supports high-intensity endurance work, but fat-adapted athletes can sustain prolonged moderate efforts better than older models predicted. The real performance risk from low-carb approaches is exercise-induced hypoglycemia from liver glycogen depletion, not muscle glycogen per se. Even small amounts of carbohydrate during exercise can prevent that crash.',
    'Match fuel strategy to the event demands. For races with sustained high-intensity surges, prioritize carbohydrate availability. For long, steady efforts, metabolic flexibility matters more. Either way, taking in some carbohydrate during exercise prevents the bonk.',
    'This is the Burke vs. Noakes debate athletes have been waiting for. Both sides agree the old all-or-nothing framing is wrong. Directly relevant to any athlete choosing between high-carb and low-carb race fueling.',
    5,
    5,
    4,
    true
  ),
  (
    '41130458',
    'UCI Sports Nutrition Project: Nutritional Periodization: Strategies to Enhance Training Adaptation and Recovery.',
    'Morton JP, Hearris M, Fell MJ, Owens DJ, Halson S, Trommelen J',
    'International journal of sport nutrition and exercise metabolism',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/41130458/',
    array['Fueling & Nutrition', 'Carbohydrate Loading', 'Recovery'],
    'Nutritional periodization means adjusting energy and macros meal-by-meal and day-by-day to match the specific training objective of each session, not just hitting a daily average. Carbohydrate availability modulates the cell signaling that drives adaptation, so what you eat around each session shapes what the body learns from that session. Protein needs for endurance athletes are higher than many assume, at 1.6 to 2.1 grams per kilogram per day.',
    'Fuel key sessions fully, consider lower carbohydrate availability on easy days to drive metabolic adaptation, and keep daily protein at 1.6 to 2.1 grams per kilogram. The sport nutritionist should be as integrated as the coach.',
    'This is the UCI''s official position on periodized nutrition for cycling, but the principles apply across all endurance sports. The meal-by-meal framing is more actionable than daily averages.',
    4,
    5,
    5,
    true
  ),
  (
    '41569815',
    'UCI Sports Nutrition Project: Nutrition for the Emerging Cycling Disciplines of Esports and Gravel.',
    'Whitfield J, Mujika I, Burke LM',
    'International journal of sport nutrition and exercise metabolism',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41569815/',
    array['Fueling & Nutrition', 'Hydration'],
    'Gravel racing presents unique fueling challenges compared to road cycling: limited support, variable terrain, and long self-supported stretches mean the athlete must carry and manage nutrition independently. Caffeine, creatine, buffering agents, and glycerol all have evidence-based use cases, but the logistics of consumption during gravel events differ from road racing and need to be rehearsed.',
    'Practice the full fueling logistics of gravel racing, not just the nutrition plan on paper. Train carrying and consuming food at race intensity on mixed terrain. Test supplements like caffeine and glycerol in conditions that simulate the event.',
    'This is the first major review to address gravel-specific nutrition. Directly relevant to the gravel community and a useful bridge to road and ultra fueling strategies.',
    3,
    5,
    3,
    true
  ),
  (
    '41651468',
    'Energy and fluid balance during a 214-km winter ultraendurance race: a case study.',
    'Wehmanen KW, Ruby BC, Shriver TC, Ravelli MN, Kipp S, McDaniel J, Petushek EJ, Elmer SJ',
    'Journal of applied physiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41651468/',
    array['Fueling & Nutrition', 'Hydration'],
    'The winner of the 2025 Arrowhead Ultra burned over 15,000 calories in 18 hours of cold-weather cycling, hitting 9.6 times his basal metabolic rate. Despite temperatures well below freezing, his water turnover was comparable to athletes racing in warm conditions, meaning cold-weather hydration demands are far higher than most athletes expect. He consumed 88 grams of carbohydrate per hour and still finished in massive energy deficit.',
    'Do not underestimate hydration needs in cold weather. Water turnover can match warm-weather racing. Target high carbohydrate intake rates even in the cold, and plan for a significant energy deficit in events of this duration.',
    'Remarkable case study with doubly labeled water data. The hydration finding alone should change how athletes prepare for cold-weather ultras and gravel events.',
    5,
    4,
    3,
    true
  ),
  (
    '42056382',
    'Pacing profiles and slowdown patterns in ultra-triathlon performance.',
    'Markovic S, Cuk I, Duric S, Forte P, Leite LB, Andrade MS, Nikolaidis PT, Weiss K, Rosemann T, Knechtle B',
    'Scientific reports',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42056382/',
    array['Pacing', 'Running Economy'],
    'In the Double Deca Iron ultra-triathlon, the best performers maintained a fast baseline pace with occasional large slowdowns rather than moving at a slower but more consistent speed. Faster athletes had fewer moderate speed drops but tolerated bigger ones, suggesting that strategic rest or slowdown periods are a feature of good ultra pacing, not a failure of it.',
    'In ultra-distance events, plan for deliberate significant slowdowns rather than trying to hold a perfectly even pace. The better strategy is a fast baseline with planned recovery dips, not a conservative crawl.',
    'This is the first study to analyze pacing across all three disciplines in a Double Deca Iron. The finding that big intentional slowdowns beat constant moderate slowdowns is directly applicable to ultra racing strategy.',
    5,
    3,
    5,
    true
  ),
  (
    '40947642',
    'The prevalence and perceptions of non-steroidal anti-inflammatory drug use among ultra-endurance runners.',
    'Cole PL, Bontemps B, Pugh J, Owens DJ',
    'Research in sports medicine',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40947642/',
    array['Recovery', 'Injury Prevention'],
    'Over half of ultra-endurance runners surveyed use NSAIDs like ibuprofen, despite most being aware of the kidney and GI risks. World-class athletes tend to use them strategically and sparingly, while less experienced runners use them more reactively. Female athletes often link use to menstrual or menopause-related discomfort. Most athletes get their information informally rather than from medical professionals.',
    'If you are using NSAIDs during ultras, know the renal and GI risks are real, especially during prolonged exercise when kidneys are already stressed. Seek medical guidance for a pain management strategy rather than relying on informal norms.',
    'Important health study for the ultra community. The finding that 53 percent of ultra runners use NSAIDs despite knowing the risks highlights a gap between knowledge and behavior.',
    5,
    3,
    3,
    true
  ),
  (
    '42047663',
    'Sky''s the limit: A comprehensive narrative review on the epidemiology of injuries and illnesses in ultra trail running.',
    'Basile GC, Alito A, de Sire A, Cova A, Filardi V, Ferioli D, Maccarone MC, Capodaglio P, Fontana JM',
    'Journal of back and musculoskeletal rehabilitation',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42047663/',
    array['Injury Prevention', 'Recovery'],
    'Ultra trail running injuries are overwhelmingly lower-limb and overuse-related, but the medical complications like acute kidney injury, GI distress, and exercise-associated hyponatremia are what actually pull athletes from races. Skin issues like blisters are underrated contributors to performance decline. The unique combination of prolonged exertion, uneven terrain, and environmental exposure makes injury prevention inherently multifactorial.',
    'Build an injury prevention plan that addresses not just muscles and joints, but also kidney stress from dehydration, GI tolerance through gut training, sodium balance, and skin care including blister prevention. Train on the terrain you will race on.',
    'Comprehensive overview that connects the dots between training load, terrain adaptation, and the medical risks specific to ultra trail events.',
    5,
    3,
    3,
    true
  ),
  (
    '40646069',
    'Change in elevation predicts 100 km ultra marathon performance.',
    'Knechtle B, Weiss K, Valero D, Scheer V, Villiger E, Nikolaidis PT, Andrade M, Cuk I, Gajda R, Rosemann T, Thuany M',
    'Scientific reports',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40646069/',
    array['Pacing', 'Running Economy'],
    'In the largest analysis of 100-km ultra-marathon data ever conducted, elevation was the single most important course variable affecting performance, far outweighing surface type, country, or age group. Flat track courses produced the fastest times, road was next, then trail, then mountain. Individual athlete ability still matters 3 to 4 times more than any course factor, but choosing the right course profile matters more than most athletes realize.',
    'When targeting a time goal at 100 km, choose your course deliberately. Elevation profile has a larger impact on your finishing time than any other external factor. Train specifically for the elevation demands of your target race.',
    'Massive dataset of over 858,000 race records. The clear hierarchy of track, road, trail, and mountain performance reinforces the importance of course-specific preparation.',
    5,
    3,
    3,
    true
  ),
  (
    '41855389',
    'Velocity Loss During Resistance Training: Implications for Concurrent Training Adaptations.',
    'Tundidor-Duque RM, Loturco I, Paez-Malddonado JA, Asin-Izquierdo I, Lovillo-Fuentes F, Sanchez-Valdepenas J, Cornejo-Daza PJ, Pereira LA, de Villarreal ES, Pareja-Blanco F',
    'Scandinavian journal of medicine & science in sports',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41855389/',
    array['Strength Training'],
    'When combining strength and endurance training, the degree of fatigue accumulated during the strength session matters for endurance adaptation. Stopping sets before significant velocity loss preserves the endurance gains from the running that follows. Pushing sets to high fatigue builds more muscle mass but can blunt aerobic improvements. Endurance-only training improved aerobic speed the most but caused neuromuscular decline.',
    'If your primary goal is endurance performance, keep strength sets short of failure. Stop when bar speed drops 15 percent or less. If you need muscle mass, accept some aerobic trade-off with higher fatigue sets. Never skip strength entirely.',
    'Practical guidance for the concurrent training puzzle. The velocity-loss threshold gives athletes and coaches a concrete tool for balancing strength and endurance goals.',
    5,
    5,
    5,
    true
  ),
  (
    '41734815',
    'Does Sprint Interval Training Cause Interference in Concurrent Training? A Meta-Analysis Study.',
    'Ferraro-Farro D, Bandeira-Guimaraes M, Blanco-Rambo E, Vieira AF, Cadore EL, Benitez-Flores S',
    'International journal of sports medicine',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41734815/',
    array['Strength Training', 'VO2max'],
    'Adding sprint interval training to a resistance training program improves VO2max without compromising strength, power, or jump performance. When sprints are kept short, at 10 seconds or less, jump performance may actually improve. This makes sprint intervals a time-efficient way to build aerobic fitness alongside strength work without the interference effect seen with traditional endurance training.',
    'Use short sprint intervals as the endurance component when doing concurrent training. Sprints under 10 seconds paired with strength training can improve both aerobic capacity and explosive power simultaneously.',
    'Strong evidence that sprints can replace steady-state cardio in concurrent programs without the interference penalty. Relevant for any endurance athlete adding strength work.',
    4,
    4,
    4,
    true
  ),
  (
    '42171506',
    'Effects of Different Training-Intensity Distribution Models on Maximal Oxygen Uptake and Time-Trial Performance in Endurance Athletes: A Bayesian Network Meta-Analysis.',
    'Li H, Yang Q, Wang B',
    'Journal of strength and conditioning research',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42171506/',
    array['VO2max', 'Lactate Threshold'],
    'This network meta-analysis compared polarized, threshold, and high-intensity interval training models head-to-head. No single model showed a definitive advantage over polarized training, but the probability rankings suggest threshold training may be best for improving VO2max while high-intensity interval training may be best for time-trial performance. Age, training status, and intervention duration all moderate the results.',
    'Do not default to one training model year-round. Use threshold training blocks when VO2max development is the priority, and shift toward high-intensity intervals when race-specific time-trial fitness matters most. Polarized training remains a strong baseline.',
    'The most comprehensive comparison of training intensity distribution models to date. The Bayesian approach gives probability rankings rather than just pass-fail significance, which is more useful for real-world coaching decisions.',
    5,
    5,
    5,
    true
  ),
  (
    '41624183',
    'Periodized carbohydrate intake influences metabolic flexibility and indices of running economy during endurance training in recreationally active males.',
    'Kripp AM, Feichter A, Konig D',
    'Frontiers in nutrition',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41624183/',
    array['Fueling & Nutrition', 'Carbohydrate Loading', 'Running Economy'],
    'An eight-week study found that periodizing carbohydrate intake, four weeks low-carb followed by four weeks high-carb, improved running economy at lactate threshold while maintaining performance. The low-carb phase boosted fat oxidation, and reintroducing carbs restored the ability to burn both fuels efficiently. Continuous low-carb produced good fat burning but did not improve running economy the same way.',
    'Consider a periodized approach: use lower carbohydrate phases during base training to build metabolic flexibility, then reintroduce carbohydrates before key race-specific blocks. The combination may yield better running economy than either approach alone.',
    'Practical evidence for the periodized carbohydrate approach that many coaches already use intuitively. The running economy improvement in the periodized group is the standout finding.',
    5,
    4,
    4,
    true
  ),
  (
    '41564305',
    'Prolonged stable hypothermia during a 10-hour cold open-water marathon swim.',
    'Roxburgh BH, Edgar DT, Cotter JD',
    'Experimental physiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41564305/',
    array['Heat Acclimation', 'Recovery'],
    'A 52-year-old swimmer completed a 37-km cold-water strait crossing in under 10 hours with core temperature below 35 degrees Celsius for over 6 hours, including a low of 33.9 degrees. Despite prolonged hypothermia, he showed no cognitive or motor impairment and completed the swim without assistance. This demonstrates remarkable thermoregulatory tolerance in a cold-adapted endurance athlete.',
    'Cold-water endurance is trainable, and experienced athletes can tolerate core temperatures that would incapacitate most people. If your event involves cold water, progressive cold exposure in training builds tolerance that cannot be replicated by theory alone.',
    'Extraordinary case study with continuous core temperature monitoring. Relevant to open-water swimmers, winter ultra athletes, and anyone racing in cold conditions.',
    4,
    2,
    4,
    true
  ),
  (
    '40962298',
    'Associations Between Body Composition and Performance in Elite Endurance Athletes.',
    'Kettunen O, Mikkola J, Ihalainen JK',
    'International journal of sports physiology and performance',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40962298/',
    array['Recovery', 'Running Economy'],
    'In 52 elite endurance athletes across skiing, biathlon, running, and orienteering, reductions in body fat percentage correlated with improved peak running speed and VO2max. Critically, in female athletes, increases in lean mass were also associated with better endurance performance. This means body composition strategies that sacrifice lean mass to get lighter may be counterproductive, especially for women.',
    'Focus on reducing body fat without losing lean mass. For female athletes especially, gaining lean mass appears to support endurance performance rather than hinder it. Do not chase scale weight at the expense of muscle.',
    'Strong evidence against the lighter-is-always-better mindset. The female athlete finding is particularly important given the prevalence of relative energy deficiency in endurance sport.',
    5,
    4,
    4,
    true
  ),
  (
    '40054482',
    'Training Characteristics Related to (the Changes in) Durability in Semiprofessional Cyclists.',
    'Voet JG, van Erp T, Viribay A, de Koning JJ, Lamberts RP',
    'International journal of sports physiology and performance',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40054482/',
    array['Lactate Threshold', 'Pacing'],
    'Durability, the ability to maintain performance when fatigued, responds differently to training than fresh performance does. The same training block can improve fresh time-trial power while having a different or even opposite effect on fatigued performance. Time spent below lactate threshold intensity was specifically linked to carbohydrate oxidation in the fatigued state, suggesting that volume at low intensity supports durability.',
    'Test performance in both fresh and fatigued states to get the full picture. Do not assume that improving your fresh FTP means your race performance will also improve. Low-intensity volume appears to specifically support the ability to perform when fatigued.',
    'Durability is one of the most important emerging concepts in endurance sport. This study makes the case that fresh testing alone misses half the picture.',
    4,
    5,
    5,
    true
  ),
  (
    '39591960',
    'Sodium Hyperhydration Improves Performance With No Change in Thermal and Cardiovascular Strain in Female Cyclists Exercising in the Heat Across the Menstrual Cycle.',
    'Convit L, Orellana L, Periard JD, Carr AJ, Warmington S, Beaugeois M, Abraham A, Snipe RMJ',
    'International journal of sport nutrition and exercise metabolism',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/39591960/',
    array['Hydration', 'Supplementation'],
    'Sodium-loaded hyperhydration improved 200-kJ cycling time-trial performance in the heat by about 1.5 minutes in female cyclists, with an even larger benefit during the high-progesterone phase of the menstrual cycle. The protocol did not change core temperature or heart rate, suggesting the benefit comes through fluid-balance mechanisms rather than thermal regulation.',
    'For female athletes racing in the heat, a sodium hyperhydration protocol two hours before the start is worth testing. The benefit may be larger during the luteal phase of the menstrual cycle. Test the protocol in training first to confirm GI tolerance.',
    'One of the few studies specifically testing heat mitigation in female athletes across the menstrual cycle. The phase-dependent finding has direct implications for race-day planning.',
    3,
    5,
    5,
    true
  ),
  (
    '41584794',
    'A periodized winter training block enhances anaerobic capacity in elite female rowers during 30-second maximal rowing.',
    'Liu X, Ding Y, Gong Z, Guo P',
    'Frontiers in physiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41584794/',
    array['Strength Training', 'VO2max'],
    'A 16-week structured winter training block in elite female rowers produced a 14 percent increase in mean power output and a 22 percent increase in anaerobic energy contribution during a 30-second all-out test, without any loss in VO2max. The gains came from a metabolic shift toward anaerobic pathways rather than changes in technique or body composition.',
    'Periodized off-season blocks that emphasize strength and power alongside endurance base can meaningfully build anaerobic capacity without sacrificing aerobic fitness. The off-season is the time to invest in top-end power.',
    'Directly relevant to any endurance athlete who wants to build race-ending kick or surge capacity during the off-season. The preservation of VO2max while gaining anaerobic power is the key finding.',
    3,
    4,
    4,
    true
  ),
  (
    '41343068',
    'Effect of swimming intensity on performance in subsequent sprint triathlon: a sex-based analysis in amateur athletes.',
    'Vivan L, Dos Anjos Souza VR, Engelke P, de Lira CAB, Vancini RL, Weiss K, Knechtle B, Andrade MS',
    'European journal of applied physiology',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/41343068/',
    array['Pacing', 'Running Economy'],
    'In sprint triathlon, the intensity of the swim leg affects overall race time differently for men and women. For women, swimming too conservatively below critical velocity produced worse overall times than swimming at or above critical velocity. For men, swim intensity did not significantly change total race time. This suggests women may benefit more from an aggressive swim start.',
    'Female triathletes should not hold back in the swim leg. Swimming at or above critical velocity improved overall race time. Male triathletes showed more tolerance to varying swim intensities without affecting total performance.',
    'Important sex-based finding for triathlon pacing. Challenges the conservative-swim advice that is often given universally. Relevant for sprint and Olympic distance race planning.',
    3,
    3,
    5,
    true
  ),
  (
    '42167359',
    'Dietary Intake of Endurance Athletes During 12 Weeks of Self-Selected Training: An Observational Study.',
    'Rothschild JA, Morton JP, Stewart T, Kilding AE, Plews DJ',
    'International journal of sport nutrition and exercise metabolism',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42167359/',
    array['Fueling & Nutrition', 'Carbohydrate Loading'],
    'Over 12 weeks of real-world training, most endurance athletes do adjust carbohydrate intake based on training volume, but many do so with minimal variation or not at all. Average daily carbohydrate intake ranged from just 1.2 to 7.2 grams per kilogram. Sixty-five percent of athletes regularly trained fasted, and men did so twice as often as women. The gap between recommended and actual periodization is wide.',
    'Track your actual carbohydrate intake relative to training load for a few weeks. Most athletes think they periodize their nutrition but the data shows the adjustments are often too small to matter. Align high-carb days with hard or long sessions.',
    'Real-world observational data from the Plews lab. The gap between what athletes believe they do and what they actually do with nutrition is the practical takeaway.',
    5,
    5,
    5,
    true
  ),
  (
    '41829910',
    'Effects of Low-Carbohydrate and Ketogenic Diets on Aerobic Performance in Trained Athletes: A Systematic Review and Meta-Analysis.',
    'Gawelczyk M, Kaszuba M, Zajac A, Maszczyk A',
    'Nutrients',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41829910/',
    array['Fueling & Nutrition', 'Carbohydrate Loading'],
    'This meta-analysis found that low-carb and ketogenic diets reliably increase fat oxidation capacity in trained athletes, but the performance picture is nuanced. VO2max is preserved in most cases, time to exhaustion holds up in about 70 percent of studies, but submaximal exercise economy is impaired in half. Critically, performance measured within the first week is almost always worse, while studies lasting longer than a week show maintained or improved results.',
    'If you experiment with a low-carb approach, commit to at least two weeks before judging performance effects. The first week will feel terrible and the data confirms it. After adaptation, most performance metrics recover, but exercise economy may remain slightly impaired.',
    'The one-week adaptation threshold is the most actionable finding. Athletes who tried keto for a few days and quit may have been right at the worst point. The periodized approach, using low-carb phases strategically, gets the best of both worlds.',
    5,
    4,
    4,
    true
  )
on conflict (pubmed_id) do update
set
  title = excluded.title,
  authors = excluded.authors,
  journal = excluded.journal,
  publication_year = excluded.publication_year,
  pubmed_url = excluded.pubmed_url,
  topic_tags = excluded.topic_tags,
  plain_english_summary = excluded.plain_english_summary,
  practical_takeaway = excluded.practical_takeaway,
  commentary = excluded.commentary,
  ultra_score = excluded.ultra_score,
  gravel_score = excluded.gravel_score,
  triathlon_score = excluded.triathlon_score,
  published = excluded.published,
  updated_at = now();
