insert into public.research_library_entries (
  pubmed_id,
  title,
  authors,
  journal,
  publication_year,
  pubmed_url,
  topic_tags,
  plain_english_summary,
  practical_takeaway,
  commentary,
  ultra_score,
  gravel_score,
  triathlon_score,
  published
)
values
  -- ===== ULTRA RUNNING / CARDIOVASCULAR =====
  (
    '40739070',
    'Central blood pressure and arterial stiffness among ultramarathon runners across the lifespan.',
    'Vondrasek JD, Jeong S, El-Kurd OB, Linder BA, Stute NL, Domeier C, Bissen TG, Bagley JR, Robinson AT, Babcock MC, Grosicki GJ, Watso JC',
    'European journal of applied physiology',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40739070/',
    array['Cardiac Health', 'Aging'],
    'Researchers measured central blood pressure and arterial stiffness in 71 ultramarathon runners aged 26-69 preparing for the 161 km Western States Endurance Run. Brachial systolic BP rose only 1.4 mmHg per decade, and 86% of athletes had arterial stiffness below age-predicted norms. Central BP showed a curvilinear relationship with age, suggesting that high-volume endurance training across the lifespan is associated with favorable vascular health rather than harm.',
    'These data push back against the extreme-exercise-is-bad-for-your-heart hypothesis. Ultramarathon runners maintain excellent arterial compliance well into their 60s. Continue training with confidence that long-term ultra running appears to protect, not damage, cardiovascular health.',
    'Among the first studies to measure central blood pressure (not just brachial) and carotid-femoral pulse wave velocity across a wide age range of ultramarathon runners. The Western States cohort adds ecological validity. Reassuring data for aging endurance athletes.',
    5,
    3,
    3,
    true
  ),
  (
    '41192397',
    'The association between screening questions of anxiety and depression symptoms among endurance athletes.',
    'Thuany M, Viljoen C, Gomes TN, Valero D, Rosemann T, Weiss K, Knechtle B, Scheer V',
    'Acta psychologica',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/41192397/',
    array['Mental Health', 'Recovery'],
    'A network analysis of 382 endurance runners competing in events from half-marathon to ultra-marathon found that anxiety and depression symptoms form tightly connected clusters. Difficulty relaxing and psychomotor agitation emerged as the key bridge nodes linking anxiety to depression. The finding suggests that interventions targeting relaxation capacity, body awareness, and recovery regulation could simultaneously reduce both anxiety and depressive symptoms.',
    'If you notice persistent anxiety or trouble relaxing, address it proactively rather than just pushing through. Breathing work, mindfulness, and structured recovery practices can be protective against a cascade into depressive symptoms. Coaches should check in on athletes'' mental state, not just their training logs.',
    'Important mental health data specific to the endurance community. The network analysis approach is more informative than simple prevalence stats because it reveals which symptoms are the leverage points for intervention.',
    5,
    3,
    3,
    true
  ),
  -- ===== ROWING =====
  (
    '41468203',
    'From Underperformance to Olympic Finals in a World-Class Male Single Sculler: A Case Study.',
    'Mujika I, Nakamura M, Dorfman X, Yamashita D',
    'International journal of sports physiology and performance',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/41468203/',
    array['Training Periodization', 'Recovery', 'Overtraining'],
    'A world-class single sculler experienced a 5-7% drop in power output due to overtraining, illness, and travel stress. A 22-week recovery program built on 95% low-intensity training with only 5% high-intensity intervals, combined with direct coaching supervision and holistic attention to recovery, nutrition, sleep, and confidence, brought the athlete from underperformance to a 9th-place finish at the Paris 2024 Olympic finals, just 0.57% off the bronze-medal time.',
    'When recovering from overtraining or a deep performance slump, resist the urge to claw back fitness with high-intensity work. A prolonged period of low-intensity training with very gradual reintroduction of intensity, combined with sleep, nutrition, and psychological support, is the evidence-based approach. Patience and holistic care produce results.',
    'A landmark case study from Inigo Mujika. The 95/5 intensity distribution during recovery from overtraining mirrors the polarized model but taken to an extreme. The level of detail about the week-by-week progression is invaluable for coaches managing similar situations.',
    4,
    4,
    4,
    true
  ),
  (
    '41253133',
    'The Protective Effect of High-Pressure Ischemic Preconditioning on Rowing Performance During Consecutive 2000-m Efforts.',
    'Weng MC, Lee PC, Dai X, Chiu CH, Ho CC, Hsu SM, Chen CH',
    'International journal of sports physiology and performance',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/41253133/',
    array['Performance Aids', 'Blood Flow Restriction'],
    'Eleven elite rowers were tested across three warm-up conditions before performing two consecutive 2000 m rowing trials: traditional warm-up, low-pressure ischemic preconditioning (100-190 mmHg), and high-pressure ischemic preconditioning (210-300 mmHg). While first-trial performance was similar across conditions, the high-pressure group significantly outperformed the others on the second trial. The control group showed performance decline between trials, while both ischemic preconditioning groups maintained output.',
    'Ischemic preconditioning applied to the legs before warm-up may protect performance in repeated high-intensity efforts such as heats and finals on the same day. High-pressure occlusion (210-300 mmHg) appears most effective. This is a practical and legal pre-competition strategy.',
    'Strong applied study with an elite rowing cohort. The finding that IPC protects against performance decline in the second effort, rather than boosting the first, has clear implications for any endurance sport with multiple rounds on the same day.',
    3,
    3,
    4,
    true
  ),
  -- ===== SPEED SKATING =====
  (
    '41758881',
    'Effects of slide-board-based high-intensity interval versus moderate-intensity continuous training on aerobic and anaerobic capacity in young speed skaters.',
    'Zhang K, Qi J, Shi P, Xue X, Liu Y',
    'PloS one',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41758881/',
    array['HIIT', 'Training Periodization'],
    'Twenty-seven youth speed skaters were randomly assigned to two different HIIT protocols (3 min work/2 min rest or 4 min work/1 min rest) or a moderate-intensity continuous protocol on a slide board. After four weeks, both HIIT groups improved VO2max, peak power, and mean power and reduced their fatigue index, while the MICT group showed no changes. The longer-interval HIIT (4+1) produced greater anaerobic power gains, while the shorter-interval HIIT (3+2) better improved fatigue resistance.',
    'For endurance athletes doing cross-training: short-duration HIIT blocks (even 4 weeks) can produce meaningful aerobic and anaerobic gains that moderate-intensity continuous training cannot match. Choose your interval structure based on your event demands: longer intervals for explosive power, shorter intervals for fatigue resistance.',
    'Sport-specific HIIT on a slide board is a novel modality that translates to skating biomechanics. The finding that different HIIT structures target different adaptations is directly relevant to periodization design across any endurance sport.',
    2,
    2,
    2,
    true
  ),
  -- ===== WINTER ENDURANCE SPORTS =====
  (
    '41665741',
    'Mind-Muscle-Environment Interactions: Psychophysiological Determinants of Optimal Pacing in Olympic Winter Endurance Sports.',
    'Edholm P, Bouten LJL, Holmberg HC, Losnegard T, Hettinga FJ',
    'Scandinavian journal of medicine & science in sports',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41665741/',
    array['Pacing', 'Mental Performance', 'Cross-Country Skiing'],
    'This review synthesizes how pacing in cross-country skiing, biathlon, and speed skating is governed by an interaction between the physiological engine (energy systems, fatigue, afferent feedback), the psychological operator (self-regulation, expectations, affect), and environmental factors (head-to-head racing, weather, terrain). The affordance competition hypothesis is proposed as a framework where pacing is a continuous decision-making process driven by dynamic mind-muscle-environment interactions.',
    'Optimal pacing is not just about fitness. Practice pacing under race-like conditions: variable terrain, head-to-head competition, and weather extremes. Train the decision-making process, not just the engine. A phased approach that integrates physiological and psychological preparation in realistic settings produces the best race execution.',
    'The most comprehensive integration of pacing science for winter endurance sports to date. The mind-muscle-environment framework applies equally well to ultra running, gravel racing, and triathlon, where terrain and conditions constantly shift.',
    4,
    4,
    4,
    true
  ),
  (
    '41653367',
    'Olympic Snow Sports: Current Insights and Future Directions for Milano Cortina 2026 and Beyond.',
    'Zoppirolli C, Fornasiero A, Sporri J, Losnegard T, Elfmark OA, Sandbakk O, Holmberg HC',
    'Scandinavian journal of medicine & science in sports',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41653367/',
    array['Cross-Country Skiing', 'Training Periodization'],
    'This narrative review categorizes Olympic snow sports into endurance-dominant disciplines (cross-country skiing, biathlon, ski mountaineering) relying on high aerobic capacity and movement efficiency, and gravity/technical disciplines emphasizing neuromuscular power. It synthesizes performance determinants, training characteristics, and knowledge gaps across all winter Olympic snow disciplines, including the newly added ski mountaineering.',
    'For endurance athletes who cross-train in winter: the training principles that make elite cross-country skiers fast (high aerobic capacity, tailored strength-power work, and technical/tactical preparation) transfer directly to off-season development. Ski mountaineering, with its mix of climbing and descending, offers a particularly good cross-training model for ultra and trail runners.',
    'Authoritative review from the top researchers in winter sports. The identification of sex-specific gaps in research and the standardization recommendations for training documentation are relevant far beyond winter sports.',
    3,
    3,
    3,
    true
  ),
  (
    '40555413',
    'The Making of a Biathlete: Insights From 2 Decades of Training Data From Junior, World, and Olympic Champions.',
    'Kock H, Wick J, Gronwald T, Laaksonen MS, Hanstock H',
    'International journal of sports physiology and performance',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40555413/',
    array['Training Periodization', 'Cross-Country Skiing'],
    'Analysis of 20 years of self-documented training diaries from 18 elite biathletes revealed that male athletes increased total training volume by 34% from junior to senior level, while female athletes did not show increasing volume with age. Both sexes increased endurance training volume from junior to senior level (35% for men, 23% for women), primarily by increasing the proportion of low-intensity training while reducing moderate-intensity work and maintaining high-intensity training.',
    'The path to elite endurance performance involves progressively increasing training volume from junior to senior level, with that extra volume coming almost entirely at low intensity. Do not increase moderate-intensity work as you mature. Instead, add more easy volume while keeping the absolute amount of high-intensity training stable.',
    'Twenty years of training diary data from Olympic and World Champions is an extraordinary dataset. The sex-specific finding that female biathletes do not increase total volume the same way males do has implications for coaching female endurance athletes across all disciplines.',
    3,
    3,
    3,
    true
  ),
  (
    '40945928',
    'The Effect of an Educational Session to Improve Knowledge About the Menstrual Cycle and Hormonal Contraceptives in Junior Endurance Athletes and Their Coaches.',
    'Solli GS, De Martin Topranin V, Svantorp-Tveiten KME, Noordhof DA',
    'International journal of sports physiology and performance',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40945928/',
    array['Female Athletes', 'Recovery'],
    'Junior female cross-country skiers and biathletes (n=36) and their coaches (n=12) participated in a tailored educational session about the menstrual cycle and hormonal contraceptives. The intervention significantly improved perceived knowledge and satisfaction with that knowledge for both athletes and coaches. It also improved peer communication among athletes, though it did not increase athlete-coach communication about menstrual health.',
    'A single structured educational session can meaningfully improve menstrual health literacy in female endurance athletes and their coaches. Teams should build these sessions into their annual programs. Peer communication improved most, suggesting group education formats are particularly effective.',
    'Addresses a critical gap in endurance sport: most female athletes and coaches lack adequate menstrual health knowledge. The finding that peer communication improved but coach-athlete communication did not highlights the need for follow-up interventions that specifically normalize these discussions across the coaching relationship.',
    3,
    3,
    3,
    true
  ),
  (
    '41651736',
    'Thinking outside the box: comparing age at performance milestones of swimmers to cross-country skiers and biathletes.',
    'Jonsson Karstrom M, Ruiz-Navarro JJ, Romann M, Born DP',
    'Journal of science and medicine in sport',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41651736/',
    array['Aging', 'Training Periodization'],
    'Comparing 1,569 World Championship athletes across swimming, cross-country skiing, and biathlon, researchers found that swimmers reach performance milestones 2-4 years earlier than skiers and biathletes. Only 40% of WC swimmers had competed at Junior World Championships versus 90% of skiers and biathletes. In all three sports, there was a 3-4 year gap between peak junior performance and adult WC debut, suggesting development cannot be rushed.',
    'Long-term athlete development timelines are sport-specific. Early specialization and peak may be necessary in swimming, while winter endurance sports allow for later development. Regardless of sport, there is a consistent 3-4 year transition period from junior peak to adult competitiveness that coaches should plan for rather than fight.',
    'Valuable longitudinal data challenging one-size-fits-all development models. The finding that female swimmers reach milestones one year earlier than males, with no sex difference in skiing and biathlon, has implications for sex-specific training periodization.',
    2,
    2,
    3,
    true
  ),
  -- ===== OPEN-WATER SWIMMING =====
  (
    '39788117',
    'Lactate Threshold and Swimming Performance in World-Class Open-Water Swimmers.',
    'Lopez-Belmonte O, Baldassarre R, Ruiz-Navarro JJ, Bonifazi M, Arellano R, Piacentini MF',
    'International journal of sports physiology and performance',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/39788117/',
    array['Lactate Threshold', 'Swimming'],
    'Twenty world-class open-water swimmers completed incremental 7x400 m pool tests. Their swimming speed at lactate threshold corresponded to 97% of the peak speed reached in testing, indicating an extraordinarily developed aerobic capacity. The commonly used 4 mmol/L fixed lactate reference was a reasonable proxy for lactate threshold in male swimmers but significantly overestimated aerobic capacity in female swimmers.',
    'World-class open-water swimmers race at an intensity very close to their lactate threshold. Training should target raising the speed at threshold rather than VO2max ceiling. For female swimmers, coaches should use individualized lactate threshold testing rather than the standard 4 mmol/L cutoff, which overestimates true aerobic capacity in women.',
    'First study to characterize lactate threshold specifically in world-class open-water swimmers. The sex difference in threshold estimation has direct implications for training prescription and is likely relevant to female endurance athletes in other sports as well.',
    2,
    2,
    5,
    true
  ),
  (
    '39599736',
    'Endurance in Long-Distance Swimming and the Use of Nutritional Aids.',
    'Miguel-Ortega A, Calleja-Gonzalez J, Mielgo-Ayuso J',
    'Nutrients',
    2024,
    'https://pubmed.ncbi.nlm.nih.gov/39599736/',
    array['Fueling & Nutrition', 'Swimming'],
    'This comprehensive review covers the energetic, physiological, and nutritional demands of long-distance swimming. The nutritional needs of open-water swimmers during competition differ substantially from pool swimmers due to longer duration, cold exposure, and limited feeding opportunities. Body composition optimization, hydration strategies, and carbohydrate delivery methods all require sport-specific approaches that account for the aquatic environment.',
    'Open-water swimmers need different fueling strategies than land-based endurance athletes. Cold-water exposure increases energy expenditure and carbohydrate oxidation. Practice feeding during training swims to minimize time lost at feed stations. Higher body fat percentages may be advantageous for insulation and buoyancy at longer distances.',
    'The most complete review to date on long-distance swimming nutrition. Particularly useful for triathletes looking to optimize their swim-leg fueling and for coaches working with athletes transitioning from pool to open-water events.',
    2,
    2,
    5,
    true
  ),
  -- ===== TRIATHLON =====
  (
    '40770400',
    'Sex-specific differences in performance and pacing in the world''s longest triathlon in history.',
    'Knechtle B, Leite LB, Forte P, Andrade MS, Nikolaidis PT, Scheer V, Duric S, Cuk I, Rosemann T',
    'Scientific reports',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40770400/',
    array['Pacing', 'Female Athletes', 'Ultra-Endurance'],
    'Researchers analyzed the 2024 Triple Deca Ultra Triathlon, covering 114 km of swimming, 5,400 km of cycling, and 1,266 km of running. Men were faster in all three disciplines (8.5-24.8%), with the largest sex difference in cycling and the smallest in running. More consistent athletes performed better overall, and cycling and running variability strongly predicted final rankings.',
    'In extreme ultra-endurance events, pacing consistency is king. Cycling variability predicted overall outcomes more than any single discipline''s speed. Athletes targeting events beyond Ironman distance should prioritize even pacing across days, especially on the bike, and accept that the running sex gap narrows substantially at extreme distances.',
    'At 114 km of swimming, 5,400 km of cycling, and 1,266 km of running, this is the longest triathlon ever studied. The finding that the sex gap in running shrinks to 8.5% at this extreme distance further supports the growing evidence for female durability advantages in ultra-endurance.',
    5,
    4,
    5,
    true
  ),
  (
    '40901845',
    'Sex differences in performance and pacing in the greatest Quintuple Iron ultra-triathlon race in history: The IUTA World Championship 2024 in France.',
    'Knechtle B, Leite LB, Duric S, Cuk I, Andrade MS, Scheer V, Nikolaidis PT, Weiss K, Rosemann T, Forte P',
    'PloS one',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40901845/',
    array['Pacing', 'Female Athletes', 'Ultra-Endurance'],
    'At the 2024 Quintuple Iron Ultra Triathlon World Championship (19 km swim, 900 km bike, 211 km run), women outperformed men in swimming and cycling, while men were faster in running and overall. Cycling pacing variability was similar between sexes, but women showed greater variability in running, possibly due to more frequent breaks. The elite female cohort had a high completion rate.',
    'At extreme ultra-triathlon distances, the traditional sex-based performance gaps narrow dramatically and can even reverse in individual disciplines. Female athletes should not apply traditional IRONMAN pacing models to ultra-distance events. The finding that women outperformed men in swimming and cycling at the World Championship level challenges assumptions about sex differences.',
    'The first analysis of a Quintuple Iron World Championship. The reversal of sex differences in swimming and cycling at the world-championship level suggests that the female talent pool at extreme distances is deep when the sample is elite and self-selected.',
    5,
    4,
    5,
    true
  ),
  (
    '40642658',
    'Case Report: Case study of 100 consecutive IRONMAN-distance triathlons-impact of race splits and sleep on the performance of an elite athlete.',
    'Knechtle B, Leite LB, Forte P, Andrade MS, Cuk I, Nikolaidis PT, Scheer V, Weiss K, Rosemann T',
    'Frontiers in sports and active living',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40642658/',
    array['Ultra-Endurance', 'Sleep', 'Pacing'],
    'An elite triathlete completed 100 consecutive IRONMAN-distance triathlons in 100 days, averaging approximately 15 hours per race. Cycling and running split times had the strongest correlation with overall performance, while swimming contributed least to daily variability. Sleep quality significantly influenced cycling but not swimming performance. Swimming times degraded faster over the 100 days than cycling or running times.',
    'In multi-day ultra-endurance events, cycling and running performance are the key levers for overall results, and both are sensitive to sleep quality. Prioritize sleep hygiene over training optimization when competing across consecutive days. Athletes planning extreme endurance records should focus pre-event preparation on cycling and running, not swimming.',
    'The longest documented continuous IRONMAN effort in history. The autocorrelation analysis showing day-to-day dependency in performance and the sleep-cycling connection provide rare longitudinal insights into human ultra-endurance limits.',
    5,
    4,
    5,
    true
  ),
  (
    '40546782',
    'Women in the triathlon-the differences between female and male triathletes: a narrative review.',
    'Loosli M, Nikolaidis PT, Scheer V, Wilhelm M, Forte P, Andrade M, Rosemann T, Duric S, Cuk I, Knechtle B',
    'Frontiers in sports and active living',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40546782/',
    array['Female Athletes', 'Training Periodization'],
    'This comprehensive review of 147 studies found that female triathlete participation, especially among masters athletes, has increased substantially. Women show significantly lower VO2max and higher lactate thresholds compared to men, with higher body fat and lower body mass. Sex differences in performance vary across distances and disciplines. The age for peak IRONMAN performance is 25-39 years for both sexes.',
    'Female triathletes should not simply copy male training programs. The higher lactate threshold relative to VO2max in women suggests that threshold-based training may be more productive than VO2max-focused work. Personal best times in marathon and previous triathlon races are the strongest predictors of IRONMAN performance for both sexes.',
    'The most comprehensive review of sex differences in triathlon to date. Highlights critical research gaps around menstruation, hormonal contraceptives, pregnancy, and childbirth effects on triathlon performance that remain largely unstudied.',
    3,
    3,
    5,
    true
  ),
  (
    '41630099',
    'High Test-Retest Reliability but Questionable Validity: Assessing a Step-Ramp-Step Protocol to Estimate Critical Power and W'' in Trained Triathletes.',
    'Rousseau Q, Rabita G, Brunet E, Dorel S, Siblot A, Morales-Artacho AJ',
    'Medicine and science in sports and exercise',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41630099/',
    array['Testing & Monitoring', 'Critical Power'],
    'Twelve trained male triathletes (VO2max 67.9 ml/kg/min) performed a modified Step-Ramp-Step protocol and compared it to traditional critical power testing from 4-5 severe-intensity trials. The protocol reliably measured VO2max, gas exchange threshold, and respiratory compensation point, but the corrected power at RCP systematically underestimated critical power by approximately 17-19 watts.',
    'A single Step-Ramp-Step test can reliably identify VO2max and ventilatory thresholds in one session, making it practical for regular monitoring. However, do not use the respiratory compensation point as a direct substitute for critical power when setting training zones. Traditional multi-session critical power testing remains the gold standard for that specific metric.',
    'Important validation study for coaches and athletes using single-session testing protocols. The reliability data are encouraging for threshold measures, but the critical power underestimation is a meaningful limitation that coaches should understand.',
    3,
    4,
    5,
    true
  ),
  (
    '39762336',
    'The fastest nonprofessional age group IRONMAN triathletes in the world originate from Europe.',
    'Knechtle B, Villiger E, Weiss K, Valero D, Rosemann T, Nikolaidis PT, Vancini RL, Andrade MS, Thuany M',
    'Scientific reports',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/39762336/',
    array['Pacing', 'Race Selection'],
    'Analysis of 677,320 IRONMAN age group finishers from 150 countries competing in 443 races between 2002 and 2022 revealed that the fastest age-groupers consistently come from European countries including Germany, Austria, Denmark, Belgium, Switzerland, Norway, Czechia, Estonia, and Slovenia. Optimal race conditions include water temperatures of 23-25 C, air temperatures of 19-28 C, and flat to rolling courses. IRONMAN Hawaii, Vitoria-Gasteiz, and Hamburg are the fastest races.',
    'If you want a fast IRONMAN time, choose your race carefully. Flat courses, moderate temperatures (19-28 C air, 23-25 C water), and ocean swimming lead to faster times. Hilly running and cycling courses slow times significantly. European races tend to attract the fastest age-group fields.',
    'The largest IRONMAN performance dataset ever analyzed. The race-course and environmental data give athletes an evidence-based framework for selecting events aligned with their performance goals. The nationality trends likely reflect both cycling culture and structured training environments.',
    3,
    4,
    5,
    true
  ),
  (
    '39287585',
    'Reoccurrence of adverse medical incidents in repeat ultraendurance triathlon competitors.',
    'Cho SP, Connolly CP, Hiller DB, Miller TK',
    'The Journal of sports medicine and physical fitness',
    2024,
    'https://pubmed.ncbi.nlm.nih.gov/39287585/',
    array['Injury Prevention', 'Hydration'],
    'Analysis of 427 repeat IRONMAN-distance competitors evaluated medically over a 30-year period (1989-2019) found that athletes diagnosed with hyponatremia, nausea, dizziness, or muscle cramps in their first race were significantly more likely to return with the same issue in subsequent years. Hyponatremia had the highest reoccurrence risk (2.42x). Interestingly, athletes who vomited in their first race were less likely to return with vomiting.',
    'If you have experienced hyponatremia, nausea, dizziness, or cramping in an IRONMAN, you are at elevated risk for the same problem in future races. Do not assume you have outgrown these issues. Proactively address the root causes: sodium intake strategy, pacing, heat management, and fueling protocols need deliberate adjustment between races.',
    'Thirty years of medical data from the same event is a remarkable dataset. The finding that medical issues follow athletes across years suggests these are not random bad days but reflect underlying individual vulnerabilities in physiology or race strategy.',
    4,
    3,
    5,
    true
  ),
  -- ===== NUTRITION & FUELING =====
  (
    '41493790',
    'Running Performance in Response to Different Forms of Carbohydrate Through Cephalic-Phase Responses.',
    'Guadagni AJ, Ward CA, Cooper JA',
    'International journal of sports physiology and performance',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41493790/',
    array['Fueling & Nutrition', 'Running Economy'],
    'Eighteen endurance-trained runners completed 12.87 km treadmill time trials under three conditions: a carbohydrate dissolvable strip, a carbohydrate mouth rinse, and a water control. Both carbohydrate interventions improved performance versus water, but the dissolvable strip produced stronger and more consistent improvements (3.0% faster) than the mouth rinse (1.9% faster), likely through enhanced cephalic-phase responses triggered by longer oral exposure to carbohydrate.',
    'For races under 90 minutes where full carbohydrate ingestion is not practical or causes GI distress, a carbohydrate dissolvable strip placed on the tongue may offer a stronger ergogenic effect than a traditional mouth rinse. The key mechanism is tricking the brain through oral carbohydrate sensing rather than actual fuel delivery.',
    'Elegant study separating oral carbohydrate sensing from actual fuel absorption. The dissolvable strip approach is novel and practical for shorter endurance events where athletes want a performance edge without the GI risk of full ingestion.',
    4,
    3,
    4,
    true
  ),
  (
    '41570812',
    'No Effect of High-Amylose Maize Starch on Pre- or Postexercise Hydration Status, Thermophysiological Strain, or Exhaustive Exercise Performance During Exertional Heat Stress in Endurance Runners.',
    'McCubbin AJ, Leng SD, Young KJ, Demeo JL, Costa RJS',
    'International journal of sport nutrition and exercise metabolism',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41570812/',
    array['Hydration', 'Heat Acclimation'],
    'Ten endurance runners consumed either a resistant starch beverage or placebo as part of hyperhydration and rehydration protocols around a 2-hour heat stress running test. Resistant starch had no effect on fluid retention, hydration status, core temperature, or time-to-exhaustion performance. Gastrointestinal symptoms were similar between conditions.',
    'Despite marketing claims, resistant starch from high-amylose maize does not improve fluid retention during hyperhydration or rehydration around exercise in the heat. Stick with established hydration strategies: sodium-containing drinks and gradual fluid intake. Do not add resistant starch to your pre-race hydration protocol expecting improved fluid balance.',
    'Important null finding that saves athletes from wasting time and money on unsubstantiated hydration products. Well-designed study from Ricardo Costa''s group at Monash, who are among the leading researchers in exercise-heat-gut interactions.',
    4,
    4,
    4,
    true
  ),
  (
    '40675563',
    'Could It Bee? Honey Ingestion Induces Comparable Metabolic Responses to Traditional Carbohydrate-Based Sports Nutrition Product During 3-Hr Steady-State Cycling and Subsequent Exercise Capacity Test.',
    'Fortis HO, Ravikanti S, Barrett JS, Lopez EM, Bampouras TM, Haworth JJ, Areta JL, Pugh JN',
    'International journal of sport nutrition and exercise metabolism',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40675563/',
    array['Fueling & Nutrition', 'Carbohydrate'],
    'Twelve trained male cyclists ingested 90 g/hr of carbohydrate from either honey or a traditional sports nutrition product during 3 hours of steady-state cycling at 90% lactate threshold, followed by a time-to-fatigue test. Total carbohydrate oxidation, fat oxidation, gastrointestinal symptoms, breath hydrogen, and exercise capacity were all similar between conditions.',
    'Honey at 90 g/hr is a viable alternative to commercial sports nutrition products for long endurance sessions. It provides equivalent metabolic and performance outcomes with no increase in GI distress. Athletes looking for a natural, affordable, or more palatable fuel source can confidently use honey during training and racing.',
    'From Jamie Pugh and colleagues at Liverpool John Moores, this is the first study to test honey at the current recommended high carbohydrate intake rates (90 g/hr). The equivalence finding opens up a genuinely practical and affordable fueling option.',
    4,
    5,
    5,
    true
  ),
  (
    '39914376',
    'Repetitive Feeding-Challenge With Different Nutritional Densities on Markers of Gastrointestinal Function, Substrate Oxidation, and Endurance Exercise Performance.',
    'Martinez IG, Biesiekierski JR, Rauch CE, Costa RJS',
    'International journal of sport nutrition and exercise metabolism',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/39914376/',
    array['Fueling & Nutrition', 'Gut Training'],
    'Forty-four endurance athletes completed a 7-day repetitive feeding challenge using either a fat-based (nut butter, 11g fat) or carbohydrate-based (29g CHO gel) supplement during exercise. Both groups showed similar reductions in gastrointestinal symptom severity (26-40% improvement) and similar feeding tolerance at retest. The fat group did not worsen fueling outcomes and covered more distance in a post-test, though the difference between groups was not significant.',
    'Gut training works regardless of whether you train with carbohydrate or fat. If you experience GI distress during racing, a 7-day feeding challenge protocol, practicing ingestion during exercise sessions, can reduce symptoms by 26-40%. This improvement comes from gut adaptation, not just familiarity with a specific product.',
    'Important contribution from the Monash group showing that the gut-training effect is about consistent feeding practice rather than the specific macronutrient. This has practical implications for athletes who struggle with carbohydrate-only fueling strategies.',
    5,
    5,
    5,
    true
  ),
  (
    '40528157',
    'Beta-alanine supplementation improves time to exhaustion, but not aerobic capacity, in competitive middle- and long-distance runners.',
    'Marko D, Snarr RL, Bahensky P, Bunc V, Krajcigr M, Maly T',
    'Journal of the International Society of Sports Nutrition',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40528157/',
    array['Supplements', 'Running Economy'],
    'Twenty-seven competitive middle- and long-distance runners (average age 17) took either beta-alanine or placebo for 28 days. The beta-alanine group improved time to exhaustion by 6.5% compared to 1.4% for placebo, with small favorable effects on heart rate, ventilation, and lactate. However, VO2max did not change. Submaximal heart rate and respiratory exchange ratio both decreased by 4% in the beta-alanine group.',
    'Beta-alanine supplementation over 4 weeks can improve how long you can sustain effort at high intensity without increasing your VO2max ceiling. It appears to work by buffering acidosis, letting you tolerate discomfort longer. Consider a 28-day loading phase before key competition blocks, particularly for events from the mile to half marathon.',
    'One of the few beta-alanine studies in competitive adolescent runners rather than recreational adults. The 6.5% TTE improvement is meaningful and aligns with the broader meta-analytic evidence. The null VO2max finding confirms that beta-alanine is a capacity extender, not a ceiling raiser.',
    3,
    2,
    3,
    true
  ),
  -- ===== HEAT & THERMOREGULATION =====
  (
    '40605605',
    'The impact of temperature and skeletal muscle oxygen saturation on 40 km cycling time trial performance of male cyclists.',
    'Faulkner SH, Jobling P, Wilson N, James R, Martin E, Griggs K',
    'Physiological reports',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40605605/',
    array['Heat Acclimation', 'Pacing'],
    'Ten well-trained cyclists completed simulated 40 km time trials at 10, 20, and 30 degrees C with ecologically valid wind speeds matching real-world cycling speeds (~40 km/h). Performance was significantly impaired at 30 degrees C compared to both cooler conditions, with a 3.7-3.9% time loss. Skeletal muscle oxygen saturation was impaired in the heat, correlating with reduced power output and elevated heart rate.',
    'Cycling time trial performance degrades significantly above 20 degrees C, even with realistic wind cooling. The mechanism involves reduced muscle oxygenation, not just thermoregulatory strain. For hot races, pre-cooling strategies and pacing adjustments should account for this muscle-level impairment, not just perceived heat stress.',
    'Novel contribution from the Great Britain Cycling Team showing that heat impairs performance through muscle oxygenation changes, not just core temperature rises. Using real-world wind speeds makes this more applicable than typical lab studies with still air.',
    3,
    5,
    4,
    true
  ),
  (
    '40566470',
    'Passive Heat Stimuli as a Systemic Training in Elite Endurance Athletes: A New Strategy to Promote Greater Metabolic Flexibility.',
    'Cinca-Morros S, Burtscher M, Benito-Lopez F, Alvarez-Herms J',
    'Journal of functional morphology and kinesiology',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40566470/',
    array['Heat Acclimation', 'Recovery'],
    'Twelve professional trail runners were tested before and after passive dry sauna exposure (80-90 C) and a maximal endurance test. Sauna produced cardiovascular and metabolic responses similar to exercise but at a much lower physiological level. Athletes who mobilized more total substrate (glucose + HDL) during sauna also performed the exercise test faster. Individual variability was notable, suggesting responders and non-responders to heat stimuli.',
    'Sauna use may serve as a low-cost complementary training stimulus that promotes metabolic flexibility in endurance athletes. The correlation between substrate mobilization during sauna and endurance performance suggests that sauna responders may gain more benefit. Consider adding regular sauna sessions and tracking whether your metabolic markers respond.',
    'Bridges the gap between the popular interest in sauna for athletes and the actual physiological mechanisms. The responder/non-responder distinction is important. This is not a one-size-fits-all intervention.',
    5,
    4,
    4,
    true
  ),
  (
    '40956767',
    'Acute Effects of Caffeine and Taurine Co-Ingestion on Time to Exhaustion and Thermoregulatory Responses to Cycling in the Heat.',
    'Aggett J, Page J, Peel J, John K, Matta G, Tallent J, Heffernan S, Jeffries O, Waldron M',
    'European journal of sport science',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40956767/',
    array['Supplements', 'Heat Acclimation'],
    'Ten non-heat-acclimated participants completed time-to-exhaustion cycling tests at the gas exchange threshold in 35 C heat after ingesting caffeine (5 mg/kg) plus taurine (50 mg/kg) or placebo. Despite increasing oxygen consumption, ventilation, and metabolic heat production, the caffeine-taurine combination did not improve time to exhaustion and had minimal effects on thermoregulation, skin temperature, core temperature, or sweat rate.',
    'Combining caffeine with taurine before exercising in the heat does not provide an ergogenic advantage and actually increases metabolic heat production. In hot conditions, caffeine alone at a lower dose may be more appropriate, and taurine co-ingestion should not be relied upon for heat performance benefits.',
    'Important null finding that challenges the common practice of combining caffeine and taurine in energy drinks before hot-weather training or racing. The increased metabolic demand without performance benefit is a cautionary finding.',
    3,
    4,
    4,
    true
  ),
  -- ===== ULTRA CYCLING =====
  (
    '40627664',
    'Exploratory analysis of critical event phases and the impact of team size and performance levels in 24 hour ultra cycling.',
    'Dindorf C, Dully J, Maurer L, Becker S, Simon S, Bartaguiz E, Frohlich M',
    'PloS one',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40627664/',
    array['Pacing', 'Ultra-Endurance'],
    'Researchers analyzed rank stability across four years (2019-2022) of a 24-hour cycling race on a 17.9 km repetitive course. As the race progressed, final standings became increasingly predictable. Solo riders showed the least clarity in their final standing throughout, while larger teams settled into positions earlier. Medium-performance teams, especially solo riders, showed the highest rank instability.',
    'In 24-hour solo cycling, your position relative to competitors remains volatile much longer than in team events. The critical phase where final rankings crystallize comes later for solo riders. Pacing conservatively in the first half and saving tactical moves for the second half is more important for solo competitors than for team members.',
    'Unique pacing research from ultra-cycling that applies to any time-based ultra-endurance event. The finding that medium-performers have the most volatile rankings suggests that mid-pack athletes face the most strategic decision-making pressure during the race.',
    5,
    5,
    3,
    true
  ),
  -- ===== TESTING & PERFORMANCE =====
  (
    '40259411',
    'Continuous vertical jump test is a reliable alternative to wingate anaerobic test and isokinetic fatigue tests in evaluation of muscular fatigue resistance in endurance runners.',
    'Acar NE, Umutlu G, Ersoz Y, Akarsu Tasman G, Guven E, Sinar Ulutas DS, Kamis O, Erdogan M, Aslan YE',
    'BMC sports science, medicine & rehabilitation',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40259411/',
    array['Testing & Monitoring', 'Strength Training'],
    'Twenty-two recreational distance runners performed the continuous vertical jump test, Wingate anaerobic test, and isokinetic fatigue test before and after half-marathon and ultra-marathon races. All three tests showed strong internal consistency and reproducibility in measuring muscular fatigue resistance, with the vertical jump test producing highly correlated results to the lab-based tests.',
    'A simple continuous vertical jump test can replace expensive Wingate or isokinetic testing for tracking muscular fatigue resistance in runners. This makes regular fatigue monitoring accessible for self-coached athletes and small teams without lab equipment. Use it pre- and post-race or after heavy training blocks to quantify fatigue.',
    'Practical validation study that democratizes fatigue testing for endurance runners. The field-based vertical jump test requires minimal equipment and can be deployed anywhere, making it ideal for real-world training monitoring.',
    4,
    3,
    3,
    true
  ),
  -- ===== RACEWALKING =====
  (
    '40102451',
    'Plasma metabolomics dataset of race-walking athletes illuminating systemic metabolic reaction of exercise.',
    'He Y, Zhang Y, Lai J, Ma S, Yin P, Wu Z, Zhou J',
    'Scientific data',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40102451/',
    array['Recovery', 'Biomarkers'],
    'Blood samples from 19 race-walking athletes were analyzed at four time points: pre-exercise, immediately post-exercise, 3 hours into recovery, and 22 hours post-exercise. Using untargeted and targeted metabolomics, 859 metabolites and 411 lipids were identified, revealing the systemic metabolic shifts triggered by endurance exercise. The comprehensive dataset is publicly available for future research.',
    'Endurance exercise produces widespread metabolic changes that persist well beyond the exercise itself, with many metabolites still altered at 22 hours post-exercise. This reinforces the importance of a full recovery day after hard sessions. The publicly available dataset opens opportunities for coaches and researchers to identify biomarkers of training adaptation and recovery.',
    'The first comprehensive plasma metabolomics dataset from competitive race-walking athletes. While the practical applications are still emerging, the 22-hour metabolite persistence data has immediate implications for understanding recovery timelines.',
    3,
    3,
    3,
    true
  )
on conflict (pubmed_id) do nothing;
