insert into public.research_library_entries (
  pubmed_id,
  title,
  authors,
  journal,
  publication_year,
  pubmed_url,
  topic_tags,
  plain_english_summary,
  practical_takeaway,
  commentary,
  ultra_score,
  gravel_score,
  triathlon_score,
  published
)
values
  (
    '42070893',
    'Does a low-carbohydrate diet impede endurance sports performance? Debate Consensus.',
    'Burke LM, Noakes TD',
    'The American journal of clinical nutrition',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42070893/',
    array['Carbohydrate Loading', 'Fueling & Nutrition'],
    'The debate between high-carbohydrate and low-carbohydrate approaches for endurance athletes is more nuanced than either camp admits. Carbohydrate availability clearly supports high-intensity efforts and race situations where top-end output matters, but fat-adapted athletes can sustain prolonged submaximal work with less reliance on glycogen. The practical answer depends on the event demands and the intensity profile the athlete actually faces.',
    'Match fueling strategy to the intensity profile of the target event. High-carb availability matters most when the race includes sustained threshold work or surges. Low-carb training phases may have a role in building metabolic flexibility during base periods, but they should not replace carb-supported quality sessions.',
    'Directly relevant to athletes choosing between fueling philosophies across ultra, gravel, and triathlon events.',
    5,
    4,
    4,
    true
  ),
  (
    '41130458',
    'UCI Sports Nutrition Project: Nutritional Periodization: Strategies to Enhance Training Adaptation and Recovery.',
    'Morton JP, Hearris M, Fell MJ, Owens DJ, Halson S, Trommelen J',
    'International journal of sport nutrition and exercise metabolism',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/41130458/',
    array['Fueling & Nutrition', 'Carbohydrate Loading'],
    'Nutrition for endurance athletes should not be a fixed daily plan but a variable prescription that changes session by session. Carbohydrate intake in particular should be scaled to the energetic demands and training objectives of each workout, not averaged across the week. Protein needs are higher than general recommendations suggest, and the timing and dose across meals matters for tissue repair and adaptation.',
    'Adjust carbohydrate intake meal by meal to match each session''s purpose. Target at least 1.6 to 2.1 grams of protein per kilogram per day, distributed evenly, to support both recovery and adaptation alongside the endurance work.',
    'Strong framework for any endurance athlete trying to periodize nutrition across a mixed training week.',
    5,
    5,
    5,
    true
  ),
  (
    '41934470',
    'Heat training augments hemoglobin mass during a moderate-altitude training camp in well-trained endurance athletes.',
    'Rønnestad BR, Urianstad Odden T, Blindheim PM, Hansen J, Hamarsland H, Ellefsen S, Urianstad Odden I, Mølmen KS',
    'Journal of applied physiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41934470/',
    array['Altitude', 'Heat Acclimation'],
    'Adding three weekly heat training sessions to a moderate-altitude camp produced a meaningful increase in hemoglobin mass that altitude alone at the same elevation did not achieve. The combination works because heat and hypoxia stimulate red blood cell production through complementary pathways, allowing athletes to get altitude-like hematological gains even at locations below the traditional 2,300-meter threshold.',
    'If the only available altitude camp is at moderate elevation, adding structured heat sessions can close the gap on hemoglobin adaptation. Three heat-suit cycling sessions per week alongside normal training is enough to move the needle without wrecking session quality.',
    'Practical solution for athletes who cannot access high-altitude facilities but want hematological benefits.',
    5,
    5,
    5,
    true
  ),
  (
    '41651468',
    'Energy and fluid balance during a 214-km winter ultraendurance race: a case study.',
    'Wehmanen KW, Ruby BC, Shriver TC, Ravelli MN, Kipp S, McDaniel J, Petushek EJ, Elmer SJ',
    'Journal of applied physiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41651468/',
    array['Fueling & Nutrition', 'Hydration'],
    'A 214-km winter ultra-endurance cycling race showed energy expenditure at nearly 10 times basal metabolic rate and water turnover comparable to hot-weather events, despite temperatures well below freezing. The athlete consumed 88 grams of carbohydrate per hour and still finished in substantial energy deficit. Cold does not eliminate the need for aggressive fueling and hydration; it may even increase fluid needs beyond what athletes expect.',
    'Do not assume cold racing conditions reduce fueling or hydration demands. Target the same carbohydrate and fluid intake strategy you would use in warm conditions, and monitor for cold-masked dehydration.',
    'Critical data for winter ultra events and cold-weather gravel races where athletes commonly under-fuel.',
    5,
    5,
    3,
    true
  ),
  (
    '40016936',
    'Strength Training Improves Running Economy Durability and Fatigued High-Intensity Performance in Well-Trained Male Runners: A Randomized Control Trial.',
    'Zanini M, Folland JP, Wu H, Blagrove RC',
    'Medicine and science in sports and exercise',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40016936/',
    array['Strength Training', 'Running Economy'],
    'Ten weeks of maximal strength and plyometric training preserved running economy over a 90-minute run and dramatically improved time to exhaustion at high intensity afterward. The runners who added strength work were able to maintain efficiency deep into the run when the running-only group was already losing it, and then still had more to give at the finish.',
    'Add maximal strength and plyometric sessions twice weekly to protect running economy late in races. The payoff shows up not in fresh legs but in fatigued ones, which is where races are decided.',
    'Directly applicable to the final miles of any marathon, ultra, or long triathlon run leg.',
    5,
    3,
    5,
    true
  ),
  (
    '41028151',
    'Individual training prescribed by heart rate variability, heart rate and well-being scores in experienced cyclists.',
    'Alfonso C, Clarke DC, Capdevila L',
    'Scientific reports',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/41028151/',
    array['HRV', 'Recovery'],
    'Combining heart rate variability with resting heart rate and subjective well-being scores to guide training decisions produced better cycling performance outcomes than using HRV alone. The athletes who used all three signals improved the most in sustained power efforts, suggesting that no single recovery marker captures the full picture of readiness.',
    'Do not rely on HRV alone to decide training load. Combine it with resting heart rate and a simple daily well-being check. The combined signal gives a more honest picture of whether the athlete is ready for quality work.',
    'Practical guidance for any endurance athlete already tracking HRV and looking for better load management.',
    4,
    5,
    5,
    true
  ),
  (
    '40087377',
    'Pacing in ultra-marathon running: the Western States 100-mile endurance run 2006-2023.',
    'Markovic S, Cuk I, Nikolaidis PT, Weiss K, Rosemann T, Scheer V, Thuany M, Knechtle B',
    'Scientific reports',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40087377/',
    array['Pacing'],
    'Analysis of nearly 4,000 finishers at the Western States 100 revealed that pacing is overwhelmingly positive, meaning runners slow down as the race progresses, and this pattern is driven heavily by elevation changes. Men start faster and slow down more than women, while both the fastest and slowest runners show less pace variability than mid-pack athletes, suggesting that extreme performance groups are better at matching effort to terrain.',
    'Plan for positive pacing in long ultras and anchor early pace to terrain rather than target splits. Women and experienced runners tend to pace more evenly, so aggressively conservative starts remain the strongest strategy for most athletes.',
    'Large-sample pacing data that directly informs race strategy for mountain ultras.',
    5,
    3,
    2,
    true
  ),
  (
    '41564305',
    'Prolonged stable hypothermia during a 10-hour cold open-water marathon swim.',
    'Roxburgh BH, Edgar DT, Cotter JD',
    'Experimental physiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41564305/',
    array['Recovery'],
    'A solo open-water swimmer completed a 37-km cold-water crossing while hypothermic for over six hours, maintaining cognitive and motor function throughout despite a core temperature below 35 degrees for most of the swim. This case highlights remarkable thermoregulatory tolerance in a cold-adapted endurance swimmer and challenges assumptions about the performance limits of hypothermia.',
    'Cold-water endurance athletes can function well below typical hypothermia thresholds if they have built progressive cold adaptation. Training in cold water is itself the preparation, and monitoring core temperature during long open-water events is essential for safety decisions.',
    'Relevant for open-water swimmers, winter triathletes, and any endurance athlete training in cold environments.',
    3,
    2,
    4,
    true
  ),
  (
    '41584794',
    'A periodized winter training block enhances anaerobic capacity in elite female rowers during 30-second maximal rowing.',
    'Liu X, Ding Y, Gong Z, Guo P',
    'Frontiers in physiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41584794/',
    array['Taper', 'Strength Training'],
    'A 16-week periodized winter training block in elite female rowers produced a 14 percent increase in mean power output and a 22 percent increase in anaerobic energy contribution, while maintaining VO2max. The block progressed through aerobic endurance, anaerobic threshold, and race-pace phases, showing that structured periodization can build anaerobic capacity on top of an endurance base without sacrificing aerobic fitness.',
    'Structure off-season training in progressive phases that build from aerobic base to anaerobic capacity. The aerobic engine does not have to suffer when the block is designed to layer anaerobic work on top of it rather than replace it.',
    'Applicable to any endurance athlete looking to build race-day power during an off-season or base phase.',
    3,
    4,
    4,
    true
  ),
  (
    '42134780',
    'Embracing the Diversity of Race Characteristics: Association Between Muscular Strength and Cross-Country Skiing Performance.',
    'Walther J, Tomavo A, Schumann M',
    'International journal of sports physiology and performance',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42134780/',
    array['Strength Training'],
    'Upper-body maximal strength explained up to 57 percent of sprint performance variance in elite cross-country skiers and remained significant in shorter distance races on flat terrain. The association weakened in longer races and hilly courses, where aerobic capacity plays a larger role. This confirms that strength is a foundational capacity for endurance sports where propulsion involves the upper body.',
    'Upper-body strength matters more than many endurance athletes assume, especially in sports that use arms for propulsion. Invest in maximal strength for the upper body during the off-season and maintain it through the competitive season.',
    'Extends the strength-endurance conversation beyond running to skiing, paddling, and swimming.',
    2,
    3,
    4,
    true
  ),
  (
    '41569815',
    'UCI Sports Nutrition Project: Nutrition for the Emerging Cycling Disciplines of Esports and Gravel.',
    'Whitfield J, Mujika I, Burke LM',
    'International journal of sport nutrition and exercise metabolism',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41569815/',
    array['Fueling & Nutrition', 'Supplementation'],
    'Gravel racing presents unique nutritional challenges because access to in-race food and drink is more limited than in road cycling, and the terrain demands make consuming calories more difficult. Caffeine, creatine, buffering agents, and glycerol-based hyperhydration strategies may all have a role depending on the specific race format and conditions.',
    'Plan race nutrition for gravel around access constraints, not just caloric targets. Test supplement protocols like caffeine and glycerol in race-simulated training because the logistics of eating and drinking mid-race are harder than in road events.',
    'The first evidence-based nutrition review specifically addressing gravel racing.',
    3,
    5,
    3,
    true
  ),
  (
    '41343068',
    'Effect of swimming intensity on performance in subsequent sprint triathlon: a sex-based analysis in amateur athletes.',
    'Vivan L, Dos Anjos Souza VR, Engelke P, de Lira CAB, Vancini RL, Weiss K, Knechtle B, Andrade MS',
    'European journal of applied physiology',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/41343068/',
    array['Pacing'],
    'In sprint triathlon, swimming at or above critical velocity did not impair overall race time in men, while women who swam at lower intensity actually performed worse overall. The data suggests that conservative swimming pacing may not protect performance in subsequent legs and could cost time, particularly for women.',
    'Do not default to an easy swim to save energy for the bike and run. For most sprint-distance athletes, swimming at or near race pace produces the best overall finish time without the feared carryover fatigue.',
    'Challenges the common triathlon advice to hold back in the swim leg, especially for female athletes.',
    2,
    1,
    5,
    true
  ),
  (
    '41280657',
    'Exercise-Associated Hyponatremia: Serum Sodium, Symptomatology, Severity, and Sport Specificity.',
    'Armstrong LE, McDermott BP, Young SL, Casa DJ',
    'Open access journal of sports medicine',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/41280657/',
    array['Hydration'],
    'Exercise-associated hyponatremia remains a preventable cause of serious illness and death in endurance sports, with running and hiking accounting for far more cases than cycling, swimming, or triathlon. The absolute sodium level is not a reliable predictor of symptom severity, and no reported cases were asymptomatic below 130 mmol per liter. Women are disproportionately affected.',
    'Drink to thirst rather than on a fixed schedule, especially in events longer than five hours. Know the early warning signs of hyponatremia, which include nausea, weakness, dizziness, and headache, and do not assume more water is the fix when these appear.',
    'Essential safety knowledge for ultrarunners and any endurance athlete racing in hot or extended events.',
    5,
    3,
    4,
    true
  ),
  (
    '39619091',
    'Six weeks of polarized functional interval training with large training load reductions does not affect performance gains compared to traditional workouts.',
    'Held S, Isenmann E, Rappelt L, Wiedenmann T, Kutschki D, Harbrecht J, Kirchner K, Geisler S, Donath L',
    'Frontiers in physiology',
    2024,
    'https://pubmed.ncbi.nlm.nih.gov/39619091/',
    array['Recovery'],
    'A polarized training approach that used 78 percent low-intensity and 22 percent high-intensity work produced the same performance gains as a traditional high-intensity-dominant approach, despite a dramatically lower total training load. The polarized group accumulated significantly less internal stress while improving strength and endurance markers equally.',
    'Reducing total training load through a polarized approach does not cost performance gains. Athletes concerned about overtraining or injury can shift more volume to low intensity without losing the fitness benefits of high-intensity work.',
    'Supports polarized training as a sustainable model for athletes managing fatigue or injury risk.',
    4,
    4,
    4,
    true
  ),
  (
    '42135915',
    'Combined effects of inspiratory and core muscle training on respiratory and core muscle function, limb muscle oxygenation and swimming performance.',
    'Pratama AB, Chidnok W, Yimlamai T',
    'Journal of sports sciences',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42135915/',
    array['Respiratory Training'],
    'Combining inspiratory muscle training with core stability work improved swimming performance by nearly five percent in competitive swimmers, outperforming either intervention alone. The combined approach increased oxygen extraction in locomotor muscles during swimming, suggesting that respiratory and core strength work together to improve how the body uses oxygen under load.',
    'For swimmers and triathletes, pair inspiratory muscle training with core work rather than treating them as separate interventions. Six weeks of combined training is enough to see measurable performance gains in the water.',
    'Practical application for swim-focused athletes and triathletes looking for marginal gains.',
    2,
    1,
    5,
    true
  )
on conflict (pubmed_id) do update
set
  title = excluded.title,
  authors = excluded.authors,
  journal = excluded.journal,
  publication_year = excluded.publication_year,
  pubmed_url = excluded.pubmed_url,
  topic_tags = excluded.topic_tags,
  plain_english_summary = excluded.plain_english_summary,
  practical_takeaway = excluded.practical_takeaway,
  commentary = excluded.commentary,
  ultra_score = excluded.ultra_score,
  gravel_score = excluded.gravel_score,
  triathlon_score = excluded.triathlon_score,
  published = excluded.published,
  updated_at = now();
