-- Seed 20 new research library entries covering broad endurance disciplines:
-- ultrarunning, road cycling, mountain biking, triathlon, cross-country skiing,
-- swimming, and general endurance physiology.
-- Sources retrieved from PubMed (National Library of Medicine).

insert into public.research_library_entries (
  pubmed_id,
  title,
  authors,
  journal,
  publication_year,
  pubmed_url,
  topic_tags,
  plain_english_summary,
  practical_takeaway,
  commentary,
  ultra_score,
  gravel_score,
  triathlon_score,
  published
)
values
  -- 1. Ultra-endurance energy/fluid balance in extreme cold (cycling)
  (
    '41651468',
    'Energy and fluid balance during a 214-km winter ultraendurance race: a case study.',
    'Wehmanen KW, Ruby BC, Shriver TC, Ravelli MN, Kipp S, McDaniel J, Petushek EJ, Elmer SJ',
    'Journal of applied physiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41651468/',
    array['Fueling & Nutrition', 'Hydration'],
    'This case study tracked the winner of a 214-km snow-covered bike race in temperatures as low as -13C. Total energy expenditure reached 15,273 kcal (9.6x basal metabolic rate) and water turnover was 17.7 liters, comparable to warm-weather ultra events. Carbohydrate intake averaged 88 g/hr. The energy deficit was roughly 7,300 kcal despite aggressive fueling.',
    'Cold-weather ultra events demand the same fueling and hydration intensity as hot-weather ones. Do not underestimate fluid loss just because conditions feel cold. Practice high carbohydrate intake rates in cold training to build tolerance.',
    'One of the first studies to quantify upper limits of energy expenditure and water turnover during continuous single-day exercise in the cold. Directly relevant to winter ultras, bikepacking, and cold-weather gravel events.',
    5,
    4,
    3,
    true
  ),
  -- 2. Metabolic challenges of non-stop ultramarathon (100-230 km)
  (
    '41374091',
    'Does Distance Matter? Metabolic and Muscular Challenges of a Non-Stop Ultramarathon with Sub-Analysis Depending on Running Distance.',
    'John L, Munk M, Bizjak R, Schulz SVW, Witzel J, Engler H, Siebers C, Siebers M, Kirsten J, Grau M, Bizjak DA',
    'Nutrients',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/41374091/',
    array['Fueling & Nutrition', 'Recovery'],
    'Forty-three ultra runners across 100, 160, and 230 km distances showed mean energy deficits of ~6,800 kcal despite carbohydrate-dominant fueling (79% of intake). Significant drops in leptin and insulin and spikes in muscle damage markers (CK, LDH) occurred across all distances, with the 230 km group hit hardest. GI and musculoskeletal symptoms rose sharply post-race.',
    'Even with aggressive fueling, large energy deficits are inevitable in ultra events. Pre-race carbohydrate loading and individualized recovery protocols matter more than trying to match expenditure in real time. Monitor muscle damage markers if racing back-to-back.',
    'Reinforces that ultra athletes should focus on damage limitation rather than energy balance during the event itself. The distance-dependent sub-analysis gives useful calibration for 100-mile athletes.',
    5,
    3,
    3,
    true
  ),
  -- 3. Comprehensive supplement review for cycling
  (
    '41685663',
    'A comprehensive review of the physiology and evidence base to guide the use of ergogenic and medical supplements for enhanced cycling performance.',
    'Rowland A, Edwards S, Prieto-Bellver G, Menz B, Rowland A, Cornelisse E, Karapetis CS, Wallen MP, Hopkins AM',
    'Journal of the International Society of Sports Nutrition',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41685663/',
    array['Supplementation', 'Fueling & Nutrition'],
    'This review maps the full landscape of ergogenic and medical supplements for cycling. Direct performance enhancers include caffeine, beta-alanine, carbohydrates, dietary nitrates, creatine, and sodium bicarbonate. Recovery-oriented supplements include collagen, omega-3, probiotics, and vitamin D. Evidence quality varies widely, with AIS Group A compounds having the strongest support.',
    'Build a supplement strategy around well-supported compounds first: caffeine, carbohydrate, and nitrates for race day; collagen and omega-3 for connective tissue and recovery windows. Use metabolic testing to personalize rather than adopting a one-size-fits-all stack.',
    'The most complete single-source supplement guide for endurance cyclists published to date. Directly useful for gravel, ultra cycling, and triathlon bike legs.',
    4,
    5,
    4,
    true
  ),
  -- 4. Torque training in well-trained cyclists
  (
    '42076918',
    'The Role of Pedaling Intensity During Torque Training in Cyclists: A Three-Arm Randomized Controlled Trial.',
    'de Pablos R, Valenzuela PL, Martinez-Cava A, Alejo LB, Revuelta C, Sanchez-Redondo IR, Barranco-Gil D, Pallares JG',
    'Scandinavian journal of medicine & science in sports',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42076918/',
    array['Strength Training', 'VO2max'],
    'Forty-six well-trained cyclists (VO2max ~63 mL/kg/min) were randomized to control, low-load torque, or high-load torque training for 10 weeks. Only the high-load group improved both Wingate peak/mean power AND endurance markers (MAP, ventilatory thresholds). Quadriceps cross-sectional area also increased in the high-load group.',
    'If you are going to do big-gear torque work on the bike, go heavy. All-out pedaling cycles against high resistance (~70% max dynamic force) produced the broadest performance gains. Low-load grinding did not move the needle meaningfully.',
    'Settles a practical debate for gravel and ultra cyclists about whether low-cadence grinding has real training value. The answer: only if the intensity is genuinely high.',
    3,
    5,
    4,
    true
  ),
  -- 5. Pacing strategy in Monument cycling races
  (
    '41489924',
    'Pacing Strategy and Workload Distribution as Determinants of Success in One-Day Monument Cycling Races.',
    'Sanchez-Jimenez JL, Javaloyes A, Pena-Gonzalez I, Moya-Ramon M, Mateo-March M',
    'Journal of strength and conditioning research',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41489924/',
    array['Pacing', 'VO2max'],
    'Power data from 30 professional cyclists across the five Monument one-day classics (Milan-San Remo, Tour of Flanders, Paris-Roubaix, Liege-Bastogne-Liege, Il Lombardia) showed that top-5 finishers spent significantly more energy in zone 4 (submaximal threshold) compared to 6th-30th finishers, especially in the third quarter of the race. Zone 4 workload was the primary discriminator between top finishers and the rest.',
    'The decisive factor in long one-day races is the ability to sustain threshold-level efforts in the second half, not maximal sprint power at the end. Train durability at zone 4 rather than short peak efforts to excel in long single-day events.',
    'Directly maps to gravel racing, century rides, and any one-day endurance event where fatigue resistance at threshold determines the outcome.',
    3,
    5,
    3,
    true
  ),
  -- 6. Physiology of Olympic XCO mountain biking
  (
    '41739301',
    'The Physiology of Contemporary Olympic Cross-Country Mountain Biking: A Systematic Review.',
    'Protzen G, Inoue A, Buzzachera C, Doma K, Devantier-Thomas B, Herrero-Molleda A, Garcia-Lopez J, Boullosa D',
    'Sports medicine - open',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41739301/',
    array['VO2max', 'Pacing'],
    'This systematic review of 53 studies shows that modern XCO mountain biking demands exceptional aerobic capacity paired with frequent high-intensity surges. Athletes spend about a quarter of race time above maximal aerobic power, interspersed with technical sections that still keep oxygen uptake elevated. A fast-start pacing strategy is common.',
    'Mountain bike race preparation should blend sustained aerobic capacity with repeated short maximal efforts. Technical riding sections are not rest periods physiologically. Include race-simulation intervals that mix threshold work with above-VO2max surges.',
    'Highly relevant for gravel racers facing technical terrain. The shift toward more intermittent demands in modern XCO mirrors what happens in technical gravel events.',
    3,
    5,
    3,
    true
  ),
  -- 7. FTP vs RCP equivalence in triathletes
  (
    '42060964',
    'Equivalence between FTP and RCP: Assessment of association, agreement and sex effect.',
    'Engelke P, Vivan L, Dos Anjos Souza VR, de Lira CAB, Weiss K, Rosemann T, Knechtle B, Andrade MS',
    'Clinics (Sao Paulo, Brazil)',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42060964/',
    array['Lactate Threshold', 'VO2max'],
    'FTP and respiratory compensation point (RCP) were strongly correlated (r = 0.916) in amateur triathletes, and the relationship held equally for men and women. However, Bland-Altman analysis showed wide limits of agreement, meaning FTP and RCP are not interchangeable at the individual level.',
    'Use FTP as a convenient field metric but do not treat it as a direct substitute for lab-based threshold testing. If you are setting race-day intensity targets, confirm with at least one lab test. The good news: the FTP-RCP relationship is sex-independent.',
    'Practical for triathletes and cyclists who use FTP for daily training but need precision for race pacing. Validates FTP as a trend tracker, not an absolute threshold marker.',
    2,
    4,
    5,
    true
  ),
  -- 8. Swimming intensity and sprint triathlon performance
  (
    '41343068',
    'Effect of swimming intensity on performance in subsequent sprint triathlon: a sex-based analysis in amateur athletes.',
    'Vivan L, Dos Anjos Souza VR, Engelke P, de Lira CAB, Vancini RL, Weiss K, Knechtle B, Andrade MS',
    'European journal of applied physiology',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/41343068/',
    array['Pacing', 'Recovery'],
    'Twenty amateur triathletes swam 750 m at three intensities (below, at, and above critical velocity) before cycling 20 km and running 5 km. For women, swimming below critical velocity produced the slowest overall race times. For men, swim intensity did not significantly alter total race time.',
    'Female triathletes should not hold back excessively on the swim to save energy. Swimming at or slightly above critical velocity appears optimal for overall race time. Male triathletes have more flexibility to push the swim without paying a penalty on the bike and run.',
    'One of the few studies examining sex-specific pacing across all three triathlon disciplines. Directly applicable to sprint and Olympic distance racing.',
    2,
    2,
    5,
    true
  ),
  -- 9. Triathlon-specific fatigued running test protocol
  (
    '41493796',
    'Reliability of a Triathlon-Specific Test Protocol to Assess Physiological Determinants of Fatigued Running Performance.',
    'Keller S, Rohrs G, Wahl P',
    'International journal of sports physiology and performance',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41493796/',
    array['Running Economy', 'Lactate Threshold'],
    'A triathlon-specific protocol that stacks a cycling test to exhaustion followed by a constant-load bike segment and then an incremental run showed excellent reliability (ICC >= 0.845) for key fatigued running metrics including VO2peak, oxygen cost, and lactate thresholds. Substrate oxidation measurements during fatigued running were less reliable.',
    'If you want to measure how your run holds up after hard cycling, this standardized protocol gives repeatable data. Use it to track durability improvements across a season rather than relying on fresh-legs testing alone.',
    'Durability is the emerging metric in triathlon and this gives coaches a reliable way to quantify it. The protocol could be adapted for ultra and gravel athletes who need to run or hike after long bike efforts.',
    3,
    3,
    5,
    true
  ),
  -- 10. Heat training augments hemoglobin mass at moderate altitude
  (
    '41934470',
    'Heat training augments hemoglobin mass during a moderate-altitude training camp in well-trained endurance athletes.',
    'Ronnestad BR, Urianstad Odden T, Blindheim PM, Hansen J, Hamarsland H, Ellefsen S, Urianstad Odden I, Molmen KS',
    'Journal of applied physiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41934470/',
    array['Heat Acclimation', 'Altitude'],
    'Forty-six cross-country skiers and biathletes (VO2max ~69 mL/kg/min) were split into three groups: moderate altitude + heat-suit cycling, moderate altitude alone, or sea-level control. The heat + altitude group gained 2.9% hemoglobin mass versus 1.2% for altitude-only and -0.2% for control. However, performance differences on roller-ski testing were not significant between groups.',
    'Adding three heat-suit cycling sessions per week to a moderate-altitude camp (~1,865 m) boosts red blood cell production more than altitude alone. This is a practical option when access to high altitude (>2,300 m) is limited. Monitor for the gap between hematological gains and immediate performance changes.',
    'Bridges two popular interventions (heat and altitude) for endurance athletes. Relevant across all endurance sports, especially for athletes who camp at moderate altitudes.',
    5,
    4,
    4,
    true
  ),
  -- 11. Carbohydrate strategies for cross-country skiing
  (
    '41755452',
    'Carbohydrate Storage and Supplementation Strategies for Peak Performance in Cross-Country Skiing.',
    'Ortenblad N, Holmberg HC, Nybo L, Gejl KD',
    'Scandinavian journal of medicine & science in sports',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41755452/',
    array['Fueling & Nutrition', 'Carbohydrate Loading'],
    'This narrative review examines glycogen metabolism and carbohydrate fueling specifically in cross-country skiing, biathlon, and Nordic combined. These sports feature exceptionally high whole-body energy turnover with shifting upper and lower-body demands based on sub-technique, terrain, and snow conditions. Glycogen depletion patterns differ from running or cycling due to the distributed muscular load.',
    'Fueling strategies from running and cycling do not directly transfer to skiing or other whole-body endurance sports. Account for both upper and lower body glycogen stores, and adjust intake timing around the unique intensity fluctuations of course profiles and sub-technique changes.',
    'The first comprehensive carbohydrate review specific to Nordic sport. Highly relevant for any endurance athlete whose sport involves variable upper/lower body loading, including paddling, rowing, and adventure racing.',
    4,
    3,
    4,
    true
  ),
  -- 12. Combined inspiratory and core training for swimmers
  (
    '42135915',
    'Combined effects of inspiratory and core muscle training on respiratory and core muscle function, limb muscle oxygenation and swimming performance.',
    'Pratama AB, Chidnok W, Yimlamai T',
    'Journal of sports sciences',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42135915/',
    array['Respiratory Training', 'Strength Training'],
    'Twenty-five competitive swimmers were randomized to core training, inspiratory muscle training (IMT), or combined core + IMT for 6 weeks. Only the combined group improved swim time (-4.7%), along with increased locomotor muscle deoxygenation post-swim, indicating better oxygen extraction. Core-only training did not improve swim performance alone.',
    'If you are going to add respiratory or core work for swimming, do both together. The combination produced meaningfully faster swim times, while either intervention alone fell short. Six weeks of 3x/week sessions was sufficient to see results.',
    'Relevant for triathletes and open-water swimmers looking for marginal gains. The oxygen extraction finding suggests the mechanism is peripheral, not just ventilatory.',
    2,
    2,
    5,
    true
  ),
  -- 13. Sex differences in cycling durability
  (
    '41954088',
    'Sex Differences in Durability Following Heavy Intensity Cycling Exercise in Trained Athletes.',
    'Pastorio E, Spillane P, Squires E, Benyahia L, Wilson HK, Swain P, Colosio M, Felles C, Menditto A, Clarke S, Minion B, Pearmain W, Brownstein CG, Porcelli S, Ansdell P',
    'Scandinavian journal of medicine & science in sports',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41954088/',
    array['VO2max', 'Pacing'],
    'After 90 minutes of heavy-intensity cycling, female athletes showed smaller declines in gas exchange threshold (-2% vs -16%) and respiratory compensation point (-6% vs -13%) compared to males. Females also exhibited less cardiovascular drift, lower lactate, and better muscle oxygen status during the fatiguing ride, though neuromuscular fatigue was similar between sexes.',
    'Female athletes may have inherently better durability at submaximal thresholds during prolonged endurance efforts. Training and pacing prescriptions should account for these sex differences rather than applying male-derived models universally.',
    'One of the strongest studies on sex-specific durability in cycling. Directly relevant for coaches programming long-course triathlon, gravel, and ultra events for mixed-sex rosters.',
    4,
    5,
    5,
    true
  ),
  -- 14. Concurrent training umbrella review
  (
    '41762427',
    'Maximizing Adaptations in Concurrent Training: An Umbrella Review of Meta-analyses.',
    'Held S, Wolf L, Rappelt L, Bloch W, Donath L, Micke F, Geisler S, Isenmann E',
    'Sports medicine (Auckland, N.Z.)',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41762427/',
    array['Strength Training', 'Running Economy'],
    'This umbrella review of 17 meta-analyses (144 studies, 1492 participants) found that concurrent training (resistance + endurance) improves aerobic capacity comparably to endurance training alone while adding meaningful strength gains. Strength, power, and hypertrophy outcomes were similar to resistance-only training. Trends suggest performing resistance before endurance may favor strength and hypertrophy adaptations.',
    'Endurance athletes can add strength training without compromising aerobic development. When scheduling both in one day, do the strength work first. The interference effect is smaller than commonly feared for recreationally trained athletes.',
    'Settles a long-running debate with the most comprehensive evidence synthesis to date. Essential reading for any endurance athlete debating whether to add gym work.',
    4,
    4,
    5,
    true
  ),
  -- 15. Caffeine mouth rinse meta-analysis
  (
    '41774525',
    'Revisiting the evidence on caffeine mouth rinse: effects on exercise and cognitive performance: a meta-analytic review.',
    'Deng H, Fan X, Song T, Bin Mohd Nasiruddin NJ, Ahmad Fuaad AA, Bin Naharudin MN',
    'Journal of the International Society of Sports Nutrition',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41774525/',
    array['Supplementation'],
    'This meta-analysis of 31 studies found that caffeine mouth rinsing (swish and spit, no swallowing) produced small but significant improvements in exercise performance, particularly aerobic endurance. Benefits were most consistent in the fed state with brief (~5 second) rinses. The ingestion-free approach activates oropharyngeal receptors to engage central motivation and pacing networks.',
    'For athletes who get GI distress from caffeine pills or gels late in a race, mouth rinsing is a viable alternative. Keep rinse duration to about 5 seconds for best results. This works best as a complement to earlier caffeine ingestion, not a full replacement.',
    'A practical tool for the late stages of ultra and gravel events when the gut is already stressed. Low-risk, easy to test in training.',
    5,
    4,
    4,
    true
  ),
  -- 16. HIIT vs MICT for running economy
  (
    '41766811',
    'High-Intensity Interval Training and Moderate-Intensity Continuous Training Affect Running Economy in Endurance Runners: A Systematic Review and Meta-Analysis of Randomized Controlled Trials.',
    'Feng Y, Li D, Liu Y, Tang D',
    'Journal of human kinetics',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/41766811/',
    array['Running Economy', 'Lactate Threshold'],
    'This meta-analysis of randomized controlled trials found HIIT was more effective than moderate-intensity continuous training (MICT) at improving running economy and delaying lactate accumulation in endurance runners. MICT produced greater VO2max gains. HIIT was most effective for running economy when performed at or below lactate threshold intensity.',
    'For runners looking to improve efficiency and economy, high-intensity intervals are more effective than steady-state mileage. For raw aerobic ceiling (VO2max), longer moderate-intensity runs still have an edge. A mixed approach targeting both adaptations is optimal.',
    'Useful calibration for coaches programming training blocks. The finding that sub-threshold HIIT best improves running economy has direct implications for marathon, ultra, and triathlon run training.',
    5,
    3,
    4,
    true
  ),
  -- 17. Glucose ingestion and blood flow redistribution during exercise
  (
    '41926638',
    'Effects of glucose ingestion on blood flow in the small intestine and exercising limbs during endurance exercise.',
    'Endo MY, Kashima H, Miura A, Fukuba Y',
    'Journal of applied physiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41926638/',
    array['Fueling & Nutrition', 'Gut Training'],
    'This study measured regional blood flow after glucose ingestion during high-intensity cycling. Glucose increased blood flow to the small intestine while reducing flow to working limbs, with no compensatory increase in cardiac output. This means digestion and working muscles compete for the same limited circulatory resources during exercise.',
    'There is a real physiological cost to eating during hard efforts: blood flow shifts to the gut and away from working muscles. Time nutrition intake during lower-intensity windows when possible. Gut training may help minimize this redistribution penalty over time.',
    'Provides the mechanistic explanation for why athletes feel worse when fueling during hard efforts. Directly relevant to pacing nutrition intake in ultra, gravel, and triathlon racing.',
    5,
    5,
    5,
    true
  ),
  -- 18. Hydration and muscle damage in ultra-trail events
  (
    '40001904',
    'Impact of Ad Libitum Hydration on Muscle and Liver Damage and Electrolyte Balance in Ultra-Trail Events: A Heatmap Analysis of Biomarkers and Event Characteristics-A Pilot Study.',
    'Garcia-Gimenez A, Pradas F, Lecina M, Ochiana N, Castellar-Otin C',
    'Biology',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40001904/',
    array['Hydration', 'Recovery'],
    'Four athletes were tracked across a 9-stage ultra-trail (635 km, 40,586 m elevation gain) using ad libitum hydration. No cases of dangerous hyponatremia occurred, but dehydration exceeded the 2% threshold in early stages. Body weight loss correlated with worse muscle damage (r=0.47 with CK) and lower calcium levels. LDH and CK remained elevated for 48 hours post-event.',
    'Drink-to-thirst strategies appear to protect against hyponatremia in multi-stage ultras, but they do not prevent dehydration in early stages when effort outpaces intake habits. Pay extra attention to fluid intake in the first stage or two. Expect muscle damage markers to persist for at least 48 hours.',
    'One of the few studies to track biomarkers across a multi-stage ultra-trail. The correlation between dehydration and muscle damage suggests hydration strategy is also a recovery strategy.',
    5,
    4,
    3,
    true
  ),
  -- 19. Exercise-associated hyponatremia review
  (
    '40913680',
    'Pathophysiology and treatment of exercise-associated hyponatremia.',
    'Altieri B, Aini I, Cannavale G, Magnelli C, Mancini C, Zamponi V, Isidori AM, Colao A, Faggiano A, Peri A',
    'Journal of endocrinological investigation',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40913680/',
    array['Hydration'],
    'Exercise-associated hyponatremia (EAH) is driven primarily by overdrinking and non-osmotic vasopressin secretion during exercise, not by sodium loss through sweat. It can occur in any sport duration, not just ultra events. Symptoms range from nausea and confusion to seizures and death. The key prevention strategy is to replace ''drink ahead of thirst'' advice with ''drink when thirsty.''',
    'Stop drinking on a schedule. Drink when thirsty. EAH is more dangerous than mild dehydration and is caused by overconsumption, not under-salting. Carry sodium supplements as backup, not as a license to overdrink. Know the warning signs: nausea, confusion, and headache after heavy fluid intake.',
    'Critical safety knowledge for any endurance athlete or race medical crew. The shift from scheduled hydration to thirst-driven drinking is one of the most important practical changes in endurance sport medicine.',
    5,
    4,
    5,
    true
  ),
  -- 20. Sleep quality and nutrition in ultramarathon runners
  (
    '42123923',
    'Sleep Quality, Dietary Patterns, and Nutrition Knowledge in Ultramarathon Runners and American Football Players: A Comparative Cross-Sectional Study.',
    'Kosendiak AA, Colinso B, Kuznik Z, Makles S, Bazan H, Hariasz W, Biernat E',
    'Nutrients',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42123923/',
    array['Sleep', 'Fueling & Nutrition'],
    'Comparing 43 ultramarathon runners with 43 American football players, ultramarathon runners demonstrated significantly better sleep quality and higher nutritional knowledge. The athletic discipline itself was the primary predictor of sleep quality, more so than any individual dietary factor. Higher BMI was independently associated with better sleep scores.',
    'The demands and culture of endurance sport appear to drive better sleep habits compared to power-sport athletes. Treat sleep as a trainable skill that responds to the consistency and structure of endurance training. Nutritional knowledge alone did not predict sleep quality.',
    'Reinforces that sleep quality in ultra athletes is shaped by the discipline itself, not just diet optimization. Useful context for coaches building holistic recovery programs.',
    5,
    3,
    3,
    true
  )
on conflict (pubmed_id) do update
set
  title = excluded.title,
  authors = excluded.authors,
  journal = excluded.journal,
  publication_year = excluded.publication_year,
  pubmed_url = excluded.pubmed_url,
  topic_tags = excluded.topic_tags,
  plain_english_summary = excluded.plain_english_summary,
  practical_takeaway = excluded.practical_takeaway,
  commentary = excluded.commentary,
  ultra_score = excluded.ultra_score,
  gravel_score = excluded.gravel_score,
  triathlon_score = excluded.triathlon_score,
  published = excluded.published,
  updated_at = now();
