insert into public.research_library_entries (
  pubmed_id,
  title,
  authors,
  journal,
  publication_year,
  pubmed_url,
  topic_tags,
  plain_english_summary,
  practical_takeaway,
  commentary,
  ultra_score,
  gravel_score,
  triathlon_score,
  published
)
values
  -- ===== FUELING & CARBOHYDRATE SCIENCE =====
  (
    '42258036',
    'Fuelled or Fooled? Examining the Evidence and Mechanisms Behind Ultra-High Carbohydrate Intake in Endurance Athletes.',
    'Plews DJ, Booth PD, Krieger T, Maunder E',
    'Sports medicine (Auckland, N.Z.)',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42258036/',
    array['Fueling & Nutrition', 'Carbohydrate Loading'],
    'This opinion paper from Dan Plews and colleagues critically examines whether ultra-high carbohydrate intake strategies above 90 grams per hour during endurance exercise are truly supported by evidence or driven by anecdotal hype. The authors find a disconnect between metabolic data and real-world adoption, noting that traditional mechanisms like glycogen sparing and maximal exogenous oxidation do not fully explain why athletes report benefits at intakes far beyond established oxidation ceilings. Emerging mechanisms including substrate selection shifts, enhanced lactate shuttling, and central nervous system effects are proposed but remain untested.',
    'Do not blindly chase ultra-high carb intake rates above 90 grams per hour without first confirming your individual gut tolerance and oxidation capacity. Focus on progressive gut training and use race rehearsals to find your personal ceiling. The performance gains from going above 90 grams per hour may be real for some athletes but are not yet proven in controlled research.',
    'This is the most balanced critical take on the 100-plus grams per hour trend that has swept endurance sport. Coming from Plews, who coaches elite Ironman athletes, the paper carries practical credibility alongside its scientific rigor.',
    5,
    5,
    5,
    true
  ),
  (
    '42228164',
    'Low carbohydrate availability reduces power output at the moderate-to-heavy transition, impairs efficiency, and increases median power frequency during cycling in females.',
    'Main E, Yoon S, James SL, Mellor KM, Brick MJ, Leigh WB, Maunder E',
    'European journal of applied physiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42228164/',
    array['Fueling & Nutrition', 'Female Athletes'],
    'In well-trained female cyclists, reducing carbohydrate availability by restricting intake to one gram per kilogram after a glycogen-depleting session lowered power output at the first ventilatory threshold by 19 watts and impaired gross cycling efficiency compared to a high-carbohydrate condition. EMG data suggested that the body recruited higher-threshold motor units to compensate for glycogen-depleted fibers, increasing the energy cost of cycling at the same power. Critical power was not affected, indicating that the durability of the moderate-to-heavy transition is particularly sensitive to fuel status.',
    'For female athletes especially, carbohydrate availability the day before and morning of key sessions directly affects the power you can sustain at threshold-adjacent intensities. Fuel properly before quality sessions; save low-carb approaches only for deliberately easy training days.',
    'A strong addition to the durability literature, with the finding that carb availability specifically impairs the moderate-to-heavy boundary adding a practical dimension beyond the usual advice to eat enough.',
    3,
    5,
    4,
    true
  ),
  (
    '41962970',
    'Ketone monoester reduces blood glucose, exogenous CHO oxidation, and oxidation efficiency in trained male cyclists when fed 120 g/h of CHO during exercise.',
    'Martyn HJ, Cameron NE, Edmondson JA, Phelan MM, Gonzalez JT, Shepherd SO, Pugh JN, Owens DJ, Morton JP',
    'Journal of applied physiology (Bethesda, Md. : 1985)',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41962970/',
    array['Fueling & Nutrition', 'Supplementation'],
    'When trained cyclists consumed 120 grams per hour of carbohydrate with an added ketone monoester, their blood glucose dropped lower, they oxidized less of the ingested carbohydrate, and oxidation efficiency fell from 75 percent to 67 percent compared to carbohydrate alone. Despite these metabolic differences, exercise capacity in the time-to-exhaustion test was not different between the ketone-plus-carb and carb-only conditions. Both carbohydrate conditions vastly outperformed the placebo.',
    'Adding ketone esters on top of already aggressive carbohydrate fueling does not improve performance and actually impairs your ability to oxidize the carbs you are consuming. For most endurance athletes, the money is better spent on optimizing carbohydrate delivery rather than adding ketones.',
    'This is the first study to measure exogenous carbohydrate oxidation at 120 grams per hour with and without ketones. It provides hard data against the growing trend of stacking ketones on top of high-carb fueling.',
    4,
    5,
    4,
    true
  ),
  (
    '41468185',
    'No Performance Effects of Altered Carbohydrate Distribution During Intense Cycling.',
    'Podlogar T, Grmek B, Pungercar L, Cirnski S, Gorsek Sparovec T, Rowlands DS',
    'International journal of sport nutrition and exercise metabolism',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/41468185/',
    array['Fueling & Nutrition', 'Carbohydrate Loading'],
    'Trained male cyclists consumed 90 grams per hour of carbohydrate in increasing, decreasing, or constant patterns during 180 minutes of intermittent cycling followed by a 15-minute all-out test and a sprint to exhaustion. Carbohydrate distribution had no clear effect on performance, though a decreasing pattern supported slightly higher carbohydrate oxidation and better gut comfort later in exercise. Nausea and stomach fullness increased over time with the increasing pattern.',
    'If you struggle with GI issues late in races, consider front-loading your carbohydrate intake slightly rather than ramping up. But do not overthink the pattern: total intake matters more than how you distribute it across the hours.',
    'A reassuring finding for athletes who find their fueling rhythm disrupted mid-race. The data suggest you can recover from uneven fueling without meaningful performance cost.',
    5,
    5,
    5,
    true
  ),
  (
    '41749472',
    'Menstrual Cycle Phase Does Not Affect Carbohydrate Supplementation Ergogenic Effect After Heavy Intensity Cycling.',
    'Fleitas-Paniagua PR, Rasica L, Azevedo RA, Alvares TS, Zagatto AM, Murias JM',
    'Scandinavian journal of medicine & science in sports',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41749472/',
    array['Female Athletes', 'Fueling & Nutrition'],
    'In recreationally trained female cyclists, carbohydrate supplementation during 90 minutes of heavy-intensity cycling improved subsequent 4-kilometer time trial performance equally during both the mid-follicular and mid-luteal phases of the menstrual cycle. No differences in endurance performance or fatigue markers were observed between cycle phases when carbohydrate was provided. The ergogenic benefit of carbohydrate during exercise was consistent regardless of hormonal status.',
    'Female athletes should fuel during prolonged sessions with the same carbohydrate strategy throughout the menstrual cycle. There is no need to adjust in-exercise carbohydrate intake based on cycle phase. The performance benefit of fueling properly is consistent across the month.',
    'An important paper for female-specific sport science. It simplifies one piece of the puzzle: whatever cycle phase you are in, fuel the same way during long efforts.',
    3,
    4,
    4,
    true
  ),

  -- ===== CYCLING PERFORMANCE & TRAINING =====
  (
    '41934371',
    'The Record Power Profile of Male Under-23 Cyclists: Normative Values and Fatigue Effects.',
    'Mateo-March M, Sanchez-Jimenez JL, Zabala M, Moya-Ramon M, Javaloyes A',
    'Scandinavian journal of medicine & science in sports',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41934371/',
    array['Pacing', 'VO2max'],
    'Researchers analyzed race power data from 90 elite U23 cyclists across major 2025 stage races to establish normative record power profiles and quantify how fatigue erodes power output. In fresh conditions, 20-minute relative power averaged 5.5 watts per kilogram. Fatigue reduced short-duration power most dramatically, with 5-second power dropping 54 percent after 60 kilojoules per kilogram of accumulated work. Longer-duration power was more resilient, with 20-minute power declining only 14 percent even after heavy supra-threshold work.',
    'Use fresh record power profiles as benchmarks, but train and race with the understanding that real-world power is always diminished by prior work. Durability, the ability to minimize power loss after fatigue, is a trainable and important performance marker especially for stage racing.',
    'This is the first comprehensive record power profile dataset for U23 cyclists using real race data. The fatigue decay curves are immediately applicable for pacing strategies and talent identification.',
    2,
    5,
    3,
    true
  ),
  (
    '41696846',
    'Similar performance and muscle adaptations between intervals with and without blood flow restriction in well-trained cyclists.',
    'Zambolin F, Vikmoen O, Cumming KT, Skattebo O, Odemark HN, Ofsteng SF, Hammarstrom D, Hansen J, Ronnestad BR, Raastad T',
    'Journal of applied physiology (Bethesda, Md. : 1985)',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41696846/',
    array['Strength Training', 'VO2max'],
    'Well-trained cyclists with a VO2max of 67 milliliters per kilogram per minute performed five high-intensity interval sessions in six days either with or without blood flow restriction applied to the thighs via inflatable cuffs. The BFR group trained at 42 percent lower power output but matched heart rate and perceived exertion. Both groups improved 5-minute maximal power output by approximately 4 percent with no differences in lactate threshold, VO2max, or hemoglobin mass. BFR preserved type 2 fiber cross-sectional area while traditional HIIT did not.',
    'Blood flow restriction during intervals could be a useful tool during periods when you need to reduce mechanical load while maintaining physiological stimulus, such as when managing knee tendon issues or during a deload block that still needs a cardiovascular hit.',
    'The Norwegian School of Sport Sciences team behind this study includes some of the top cycling physiology researchers. The finding that BFR can match traditional HIIT gains at nearly half the power opens practical applications for load management in competitive cyclists.',
    2,
    4,
    3,
    true
  ),
  (
    '41482961',
    'Strength training in the gym versus specific strength training on the bike in young off-road cyclists.',
    'Vicari DSS, Filipas L, Giustino V, Drid P, Bianco A',
    'British medical bulletin',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41482961/',
    array['Strength Training', 'Concurrent Training'],
    'Young off-road cyclists were assigned to either 12 weeks of gym-based heavy strength training combined with endurance training, or on-bike specific strength training combined with endurance. The gym group showed significant improvements in Wingate mean power output and maximum power achieved in incremental testing, while the on-bike strength group showed no significant changes in these measures. Neither group improved countermovement jump height.',
    'For off-road and gravel cyclists looking to boost power, traditional heavy strength training in the gym appears more effective than doing strength work exclusively on the bike. Integrate two gym sessions per week into your endurance program during the base and build phases.',
    'Adds to the evidence that sport-specific strength work on the bike, while intuitive, does not replicate the neuromuscular stimulus of heavy external loading. A practical paper for cyclists still debating whether gym time is worth it.',
    2,
    5,
    3,
    true
  ),
  (
    '41845935',
    'Performance, cardioventilatory and perceptual responses to perceived opponent ability during head-to-head cycling competition.',
    'Matta G, Edwards A, Roelands B, Hettinga F, Hurst P',
    'Experimental physiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41845935/',
    array['Pacing'],
    'Twelve male cyclists completed 20-minute time trials alone, against a virtual opponent matching their previous performance, and against an opponent described as 2 percent stronger, with either accurate or deceptive information about the opponent. Power output increased significantly only in the condition where cyclists were told accurately that the opponent was 2 percent stronger. The mere presence of a virtual competitor did not improve performance. The competitive framing and belief in a genuine challenge, rather than just having an opponent present, drove the performance gains.',
    'Racing or training alongside someone you believe is slightly better than you produces a real and measurable performance boost. Use this in training by pairing with slightly faster training partners or using virtual racing platforms with calibrated competitors during key sessions.',
    'A well-controlled study on the psychology of competition in cycling. The finding that accurate competitive framing matters more than deception has practical implications for how coaches set up race simulations.',
    3,
    4,
    3,
    true
  ),

  -- ===== ENDURANCE TRAINING ADAPTATION =====
  (
    '42126053',
    'The increase in time to task failure following endurance training is associated with adjustments in motor unit firing properties.',
    'Martinez-Valdes E, Negro F, Falla D, Farina D',
    'Journal of applied physiology (Bethesda, Md. : 1985)',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42126053/',
    array['Running Economy', 'Lactate Threshold'],
    'After just two weeks of moderate-intensity continuous endurance training, previously untrained men significantly increased their time to task failure during a sustained 30-percent maximal voluntary contraction, while a matched high-intensity interval training group did not. The endurance training group showed delayed onset of compensatory motor unit firing rate increases during fatigue, and less attenuation of firing rates at task failure. These motor unit adaptations explained approximately 50 percent of the performance gains.',
    'Short-term continuous endurance training builds fatigue resistance through neuromuscular adaptations that allow the brain to more efficiently manage motor unit recruitment under sustained load. This supports including steady-state aerobic work even in programs focused on higher-intensity training.',
    'A mechanistic study that explains why easy aerobic volume builds durability in ways that interval training alone cannot replicate. The motor unit tracking methodology using high-density surface EMG is cutting-edge.',
    4,
    4,
    4,
    true
  ),

  -- ===== HEAT ACCLIMATION =====
  (
    '41267396',
    'Long-term passive heat acclimation enhances maximal oxygen consumption via haematological and cardiac adaptation in endurance runners.',
    'Jenkins EJ, Killick JA, Zerilli O, Douglas AJM, Corr L, Hughes MG, Tremblay JC, Stembridge M',
    'The Journal of physiology',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/41267396/',
    array['Heat Acclimation', 'VO2max'],
    'Ten well-trained runners with a VO2max of 64.5 completed five weeks of hot water immersion at 40-plus degrees Celsius for 45 minutes five times per week alongside their normal training, in a counterbalanced crossover design with a control period. Hot water immersion increased hemoglobin mass by 33 grams, blood volume by 284 milliliters, and left ventricular end-diastolic volume by 10 milliliters. These coordinated adaptations produced a 2.7 milliliter per kilogram per minute improvement in VO2max and a 0.8 kilometer per hour increase in speed at VO2max.',
    'Five weeks of daily hot water immersion after training can meaningfully boost VO2max in already well-trained runners. This passive approach lets you maintain training quality since the heat stress comes outside of workouts. Target water temperature above 40 degrees Celsius and at least 45 minutes of soaking.',
    'The first study to show that passive heat exposure alone, without exercise in the heat, drives both hemoglobin mass and cardiac adaptations in well-trained runners. The 2.7 unit improvement in VO2max is practically significant for competitive athletes.',
    5,
    4,
    5,
    true
  ),
  (
    '40929090',
    'Haematological adaptations to high-altitude and heat acclimation training in elite male cyclists.',
    'Cubel C, Klaris MB, Larsen JV, Faiss R, Nybo L, Lundby C',
    'Experimental physiology',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40929090/',
    array['Heat Acclimation', 'Altitude'],
    'Twelve elite cyclists completed an in-season 21-day altitude camp at 3000 meters immediately after their national championships. Total hemoglobin mass increased by 3.5 percent, but this decayed back to pre-altitude levels within 10 days of returning to sea level. Exercise performance was not improved at any post-altitude time point. In a subset of seven cyclists followed for nine months, the hemoglobin mass gain from altitude was comparable to a 5-week off-season heat acclimation protocol, and baseline hemoglobin mass before both interventions was nearly identical.',
    'For elite cyclists with already high hemoglobin mass, the gains from altitude are real but fleeting, decaying within days. Off-season heat acclimation may produce comparable hemoglobin gains with less disruption to training. Time your return from altitude carefully and consider whether heat protocols offer a more sustainable alternative.',
    'A sobering look at the reality of altitude camps for athletes who are already near their physiological ceiling. The direct comparison with heat acclimation within the same athletes is valuable and rarely done.',
    3,
    5,
    4,
    true
  ),

  -- ===== CAFFEINE & SUPPLEMENTATION =====
  (
    '41248625',
    'Effects of Caffeine on Durability After a Simulated Race in Trained Cyclists: A Field-Based Cross-Over Randomized Controlled Trial.',
    'Alejo LB, Sanchez-Redondo IR, Revuelta C, de Pablos R, Ibanez M, Valenzuela PL, Barranco-Gil D',
    'International journal of sport nutrition and exercise metabolism',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/41248625/',
    array['Caffeine', 'Pacing'],
    'Thirteen well-trained junior cyclists performed an 8-minute time trial under fresh conditions and after two sessions simulating a short cycling race totaling about 90 minutes and 20 kilojoules per kilogram. Placebo led to a significant decline in time trial power from fresh conditions, while the caffeine condition at 6 milligrams per kilogram maintained power output at a level not significantly different from the fresh baseline. The 3.1 percent performance difference between caffeine and placebo exceeded the estimated smallest worthwhile change of 2 percent.',
    'Caffeine consumed during a race may help preserve your finishing kick. If you race for 90 minutes or more, consider dosing caffeine around 60 minutes before the decisive final effort rather than only before the start. A dose of 6 milligrams per kilogram is effective but high, so practice this in training first.',
    'One of the first field-based studies to specifically test caffeine for durability rather than fresh performance. The practical design mimicking real race conditions makes the findings immediately applicable.',
    3,
    5,
    4,
    true
  ),
  (
    '41261949',
    'Caffeine exacerbates exercise-induced gut cell damage and is influenced by ADORA2A genotype but not CYP1A2 genotype: A preliminary study.',
    'Davison G, Carswell AT, Baron P, Martinez-Gonzalez B',
    'Physiological reports',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/41261949/',
    array['Caffeine', 'Gut Training'],
    'Eighteen men and women consumed caffeine at 3 milligrams per kilogram or placebo before a cycling protocol including a 15-minute performance time trial. Caffeine significantly increased post-exercise intestinal fatty acid binding protein, a marker of gut cell damage, compared to placebo. Athletes with the ADORA2A TT genotype, indicating higher caffeine sensitivity, showed a 109 percent increase in gut damage markers with caffeine versus a non-significant 48 percent increase in low-sensitivity genotypes. CYP1A2 genotype had no influence.',
    'If you experience GI distress during races despite gut training, caffeine may be part of the problem, especially if you are a caffeine-sensitive individual. Consider genetic testing for ADORA2A to identify your sensitivity profile, and trial lower caffeine doses or caffeine-free strategies in training to see if gut symptoms improve.',
    'This connects two major practical concerns in endurance sport: caffeine as an ergogenic aid and exercise-induced gut damage. The genotype-specific response is a step toward personalized supplementation.',
    5,
    4,
    4,
    true
  ),

  -- ===== PROTEIN & RECOVERY =====
  (
    '41556283',
    'Whey protein intakes up to 0.4g/kg body mass are well tolerated before a 10km run at 85% of race pace: a clinical trial.',
    'Shaw K, Lindstrom B, Moss A, Parnell JA',
    'Journal of the International Society of Sports Nutrition',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41556283/',
    array['Fueling & Nutrition'],
    'Thirteen recreational runners consumed either a low-protein or moderate-protein shake one hour before a 10-kilometer treadmill run at 85 percent of race pace. The moderate protein dose of 0.4 grams per kilogram was associated with slightly increased bloating during the run but no meaningful differences in total GI symptoms, blood glucose, or perceived exertion compared to the low-protein condition. Both conditions saw increased GI symptoms during running versus at rest, but protein content did not make things worse overall.',
    'You do not need to avoid protein before running. A pre-exercise shake with up to 0.4 grams per kilogram of easily digestible whey protein one hour before running is generally well tolerated, though individual testing is recommended before race day.',
    'Challenges the common runner belief that protein before running causes GI distress. The clinical trial design provides stronger evidence than typical survey-based studies on pre-exercise nutrition.',
    4,
    3,
    4,
    true
  ),
  (
    '41433039',
    'The effectiveness of protein supplements on athletic performance and post-exercise recovery - a Bayesian multilevel meta-analysis of randomized controlled trials.',
    'Zhao S, Zhang X, Liang T, Ng S, Liu Y, Ning Z',
    'Journal of the International Society of Sports Nutrition',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/41433039/',
    array['Fueling & Nutrition', 'Recovery'],
    'This meta-analysis of 75 randomized controlled trials involving 1206 athletes found that protein-carbohydrate supplements improved endurance performance compared to placebo, and pure protein supplements enhanced both endurance performance and muscle strength. However, all statistically significant results came from studies where total energy intake was not matched between groups, meaning the benefits may stem from extra calories rather than protein specifically. An additional 1 gram per kilogram per day from supplements, reaching a total daily intake of approximately 2 grams per kilogram, appeared most effective.',
    'Aim for a total daily protein intake of around 2 grams per kilogram from food and supplements combined. But recognize that the ergogenic effect of protein supplements may largely be an energy effect. Prioritize getting enough total calories and protein from whole foods before adding shakes.',
    'A methodologically sophisticated meta-analysis that raises an uncomfortable question for the supplement industry: are protein supplements working because of protein, or because of extra calories?',
    4,
    4,
    4,
    true
  ),

  -- ===== CROSS-COUNTRY SKIING & BIATHLON =====
  (
    '40400090',
    'Day-To-Day Endurance Training Periodization of World-Class Cross-Country Skiers.',
    'Walther J, Kocbach J, Sandbakk O',
    'European journal of sport science',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40400090/',
    array['Periodization'],
    'Session-by-session training data from 17 world-class cross-country skiers revealed that during the general preparation period, training volume was distributed as 18 percent very low days, 22 percent low, 32 percent moderate, and 28 percent high volume days. During competition, high volume days dropped to 10 percent and low volume days increased to 35 percent. Intensive sessions occurred every 3.6 days during preparation and every 3.0 days during competition. The day before a hard session averaged 127 percent of normal volume in preparation, dropping to 99 percent in competition.',
    'World-class endurance athletes do not follow a rigid weekly structure. Instead, they alternate training loads in a wave pattern with hard sessions every 3 to 4 days, reduced loading every 8 to 9 days, and rarely combine high volume with high intensity on the same day. Apply this flexible periodization approach to your own training.',
    'This study finally documents the day-to-day training architecture that coaches have discussed anecdotally for years. The finding that only 5 percent of training days combine both volume and intensity challenges the common approach of doing long hard sessions.',
    5,
    5,
    5,
    true
  ),
  (
    '40555413',
    'The Making of a Biathlete: Insights From 2 Decades of Training Data From Junior, World, and Olympic Champions.',
    'Kock H, Wick J, Gronwald T, Laaksonen MS, Hanstock H',
    'International journal of sports physiology and performance',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40555413/',
    array['Periodization', 'Altitude'],
    'Two decades of training diary data from 18 elite biathletes including junior, world, and Olympic champions revealed that male athletes increased total training volume by 34 percent from junior to senior level, while females did not. Both sexes increased endurance volume by 23 to 35 percent across career stages, primarily by increasing low-intensity training while reducing moderate-intensity work and maintaining high-intensity volume. The proportion of low-intensity training grew from junior to senior level, supporting the polarized model of training intensity distribution.',
    'Long-term athletic development in endurance sport involves progressively increasing total volume, with the added volume coming almost entirely from low-intensity work. If you are progressing from age-group to elite level, the path is more volume at easy intensity, not more hard sessions.',
    'One of the most comprehensive longitudinal training studies in endurance sport, covering actual careers from junior to Olympic champion level. The sex-specific differences in volume progression deserve attention from coaches working with female athletes.',
    5,
    4,
    4,
    true
  ),
  (
    '41665741',
    'Mind-Muscle-Environment Interactions: Psychophysiological Determinants of Optimal Pacing in Olympic Winter Endurance Sports.',
    'Edholm P, Bouten LJL, Holmberg HC, Losnegard T, Hettinga FJ',
    'Scandinavian journal of medicine & science in sports',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41665741/',
    array['Pacing'],
    'This review synthesizes how physiological capacity, psychological self-regulation, and environmental factors interact to determine pacing behavior in cross-country skiing, biathlon, and speed skating. The authors propose the affordance competition hypothesis as a framework where pacing emerges from continuous decision-making driven by dynamic interactions between the body, mind, and racing environment. Head-to-head racing formats, variable terrain, and weather conditions create a more complex pacing challenge than in time-trial-based sports.',
    'Pacing in endurance sport is not just about managing energy. Train the psychological and environmental components of pacing by practicing race-pace efforts in variable conditions, against competitors, and on unfamiliar courses. The ability to make good pacing decisions under fatigue is itself a trainable skill.',
    'A well-constructed framework for understanding pacing beyond the traditional physiological models. Especially relevant for athletes competing in mass-start or head-to-head racing formats.',
    5,
    4,
    4,
    true
  ),

  -- ===== SPEED SKATING =====
  (
    '41758881',
    'Effects of slide-board-based high-intensity interval versus moderate-intensity continuous training on aerobic and anaerobic capacity in young speed skaters.',
    'Zhang K, Qi J, Shi P, Xue X, Liu Y',
    'PloS one',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41758881/',
    array['VO2max'],
    'Twenty-seven youth speed skaters were randomized to two different slide-board high-intensity interval protocols or moderate-intensity continuous training for four weeks. Both HIIT protocols significantly improved VO2max, relative peak power, and relative mean power while reducing fatigue index. The moderate-intensity group showed no significant improvements in any variable. A 4-minute work to 1-minute rest structure produced slightly greater anaerobic power improvements, while a 3-minute work to 2-minute rest structure was better for fatigue resistance.',
    'For speed skaters and other athletes using sport-specific ergometers, short HIIT blocks of just four weeks can produce meaningful aerobic and anaerobic gains that moderate-intensity continuous training cannot match in the same timeframe. Tailor the work-to-rest ratio to your event demands.',
    'A practical comparison of HIIT structures within a sport-specific context. The finding that different interval architectures develop different capacities supports individualized interval prescription.',
    2,
    3,
    2,
    true
  ),

  -- ===== ROWING =====
  (
    '40827333',
    'Amateur Rowers to Transatlantic Trio Race Winners: A Case Study Describing the Physiological and Psychological Characteristics, Training Adaptations and Race Responses to Ultra-Endurance Rowing.',
    'Willmott AGB, Lillis J, Pinto JM, Jewiss M, Turner G, Roberts J',
    'European journal of sport science',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40827333/',
    array['Recovery', 'Periodization'],
    'Three amateur male rowers trained for 10 months and then completed a 38-day transatlantic rowing race, rowing approximately 12 hours per day in 4-hour blocks. Lactate threshold improved by 28 watts after training, but dropped 29 watts one month after the race, demonstrating prolonged cumulative fatigue. Body mass decreased by 12.7 kilograms during the race. Medical issues were near-universal: all three experienced skin and musculoskeletal problems, two had seasickness, and one reported mental health concerns. Psychological resilience and mental toughness increased after the race.',
    'Ultra-endurance events of this magnitude cause profound and prolonged physiological damage that takes well beyond one month to recover from. The psychological growth is real but should not mask the physical cost. For multi-day endurance events, plan for extended recovery and monitor return to training with objective markers.',
    'A rare window into the demands of multi-week continuous endurance competition. The training preparation details and the post-race performance decrements provide useful reference points for any ultra-endurance athlete.',
    5,
    3,
    3,
    true
  ),
  (
    '40603565',
    'Effect of baseline ferritin levels on post-exercise iron metabolism in male elite youth rowers.',
    'Cichon-Wozniak J, Dziewiecka H, Ostapiuk-Karolczuk J, Kasperska A, Gruszka W, Basta P, Skarpanska-Stejnborn A',
    'Scientific reports',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40603565/',
    array['Iron Deficiency', 'Recovery'],
    'Sixteen trained male youth rowers were divided by baseline serum ferritin levels into low and high groups before performing a 2000-meter ergometer test. The low-ferritin group showed a temporary spike in serum iron immediately after exercise followed by a sharp decline during the first hour of recovery, while the high-ferritin group showed only a gradual iron decline. Ferritin levels remained stable in the low group but increased in the high group. The findings suggest that baseline iron stores determine how the body manages free iron after intense exercise.',
    'Athletes with lower iron stores may be more vulnerable to exercise-induced iron dysregulation, reinforcing the importance of maintaining adequate ferritin levels before heavy training blocks. Regular ferritin monitoring and proactive supplementation when levels drop below 75 micrograms per liter can prevent the downward spiral.',
    'A novel mechanistic look at why iron-deficient athletes may compound their problem with training. The distinction in iron handling between low and high ferritin groups has direct implications for screening and supplementation protocols.',
    4,
    4,
    4,
    true
  ),

  -- ===== TRIATHLON =====
  (
    '40802655',
    'Effects of concurrent training on the Chinese female elite triathletes.',
    'Liu C, Zhang Z, Mao R, Xia L, Xie Y',
    'PloS one',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40802655/',
    array['Concurrent Training', 'Strength Training'],
    'Twelve elite female Chinese triathletes completed an 8-week concurrent strength and endurance training program with three strength sessions and three endurance sessions per week. One-rep-max squat increased by 4.2 percent, static jump improved by 3.7 percent, 400-meter swim improved by 0.85 percent, 2000-meter run improved by 0.47 percent, and short-distance triathlon performance improved by 3.6 percent. Maximum power output increased but VO2max did not change, suggesting the improvements came through neuromuscular rather than aerobic adaptations.',
    'For female triathletes, adding structured heavy strength training three times per week alongside endurance work can produce meaningful performance gains within eight weeks without compromising aerobic fitness. The gains likely come from improved economy and neuromuscular power rather than increased VO2max.',
    'A practical concurrent training study in a population where the interference effect is a constant concern. The 3.6 percent improvement in overall short-distance race performance is substantial at the elite level.',
    2,
    3,
    5,
    true
  ),
  (
    '40368324',
    'Durability in Youth Squad Triathletes-Influence of Strenuous Cycling on Subsequent Running Performance, Economy, and Substrate Utilization.',
    'Rohrs G, Keller S, Wahl P',
    'International journal of sports physiology and performance',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40368324/',
    array['Running Economy', 'Fueling & Nutrition'],
    'Nineteen junior squad triathletes ran under fresh and fatigued conditions following an exhaustive cycling bout. While oxygen cost of running changed only trivially from fresh to fatigued, carbohydrate oxidation dropped dramatically and fat oxidation increased, indicating a pronounced substrate shift. VO2max, oxygen cost of running, and the change in fat oxidation together explained 88 percent of the variance in fatigued running performance. The ability to maintain carbohydrate oxidation under fatigue was strongly associated with better time to exhaustion.',
    'For triathletes, the capacity to sustain carbohydrate oxidation during the run leg after cycling is a critical performance determinant. Train this with brick sessions and practice race-intensity fueling during the bike-to-run transition. Your run economy may hold up under fatigue, but your fuel mix will shift against you unless you manage it.',
    'An elegantly designed study that explains why some triathletes fade on the run while their economy numbers look fine. The substrate utilization data adds a layer beyond traditional economy and VO2 assessments.',
    3,
    3,
    5,
    true
  ),

  -- ===== IRON & ATHLETE HEALTH =====
  (
    '40681409',
    'Blood test findings in a large cohort of Olympic athletes: a cross-sectional study.',
    'Ferrera A, Di Gioia G, Spinelli A, Fiore R, Zampaglione D, Serdoz A, Squeo MR',
    'Journal of science and medicine in sport',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/40681409/',
    array['Iron Deficiency', 'Cardiac Health'],
    'Blood test results from 2525 Olympic athletes evaluated over a decade from London 2012 to Paris 2024 revealed that 62.6 percent had at least one biochemical abnormality. The most common findings were dyslipidemia at 20.4 percent, elevated cortisol at 15 percent, iron deficiency at 9.7 percent, and glucose intolerance at 8.4 percent. Female athletes had significantly higher rates of iron deficiency at 16.5 percent versus 4.2 percent in males and higher cortisol, while males showed more dyslipidemia and glucose intolerance.',
    'Even Olympic-level athletes commonly present with blood test abnormalities. All endurance athletes should have annual blood panels including a full iron panel, lipids, fasting glucose, and cortisol. Female athletes need especially close monitoring of iron status given the 16.5 percent deficiency rate found even at the Olympic level.',
    'The largest study of blood test findings in Olympic athletes to date. The high prevalence of abnormalities challenges the assumption that elite athletes are uniformly healthy and reinforces the case for routine screening.',
    4,
    4,
    4,
    true
  )
on conflict (pubmed_id) do nothing;
