insert into public.research_library_entries (
  pubmed_id,
  title,
  authors,
  journal,
  publication_year,
  pubmed_url,
  topic_tags,
  plain_english_summary,
  practical_takeaway,
  commentary,
  ultra_score,
  gravel_score,
  triathlon_score,
  published
)
values
  (
    '31749712',
    'Prolonged Heat Acclimation and Aerobic Performance in Endurance Trained Athletes.',
    'Mikkelsen CJ, Junge N, Piil JF, Morris NB',
    'Frontiers in physiology',
    2019,
    'https://pubmed.ncbi.nlm.nih.gov/31749712/',
    array['Heat Acclimation', 'Recovery'],
    'Longer heat-acclimation blocks appear to improve performance most when they are layered onto normal endurance training instead of replacing the core work. The usable signal is repeated exposure, not one-off suffering sessions.',
    'Use heat in a controlled block and keep the key endurance work intact. The intervention is most useful when it supports the race build rather than becoming the race build.',
    'Strong fit for hot ultramarathons and hard summer gravel blocks.',
    5,
    4,
    4,
    true
  ),
  (
    '34503527',
    'International Society of Sports Nutrition position stand: sodium bicarbonate and exercise performance.',
    'Grgic J, Pedisic Z, Saunders B, Artioli GG',
    'Journal of the International Society of Sports Nutrition',
    2021,
    'https://pubmed.ncbi.nlm.nih.gov/34503527/',
    array['Sodium Bicarbonate', 'Supplementation'],
    'Bicarbonate can help when the workout or race includes meaningful high-intensity stress, but tolerance is the gatekeeper. The performance upside is real only if the athlete can absorb the protocol without GI fallout.',
    'Test bicarbonate in race-specific intensity sessions first. If the gut cannot handle it in training, it is not a race-day solution.',
    'High relevance for aggressive bike surges, late-race climbs, and any athlete experimenting with buffering support.',
    4,
    5,
    4,
    true
  ),
  (
    '28177715',
    'Gut-training: the impact of two weeks repetitive gut-challenge during exercise on gastrointestinal status, glucose availability, fuel kinetics, and running performance.',
    'Costa RJS, Miall A, Khoo A, Rauch C',
    'Applied physiology, nutrition, and metabolism',
    2017,
    'https://pubmed.ncbi.nlm.nih.gov/28177715/',
    array['Gut Training', 'Fueling & Nutrition'],
    'Repeated fueling exposure during real training sessions improves tolerance better than treating race fueling like a one-day event. The gut adapts when the athlete rehearses the demand in motion.',
    'Train the exact carbohydrate load you want to race with, repeatedly, during the kinds of sessions where it will actually matter.',
    'This is one of the clearest practical bridges between research and what ultra athletes do every week.',
    5,
    5,
    4,
    true
  ),
  (
    '41753086',
    'The Role of Sleep on Physical and Cognitive Performance of Ultra-Endurance Athletes: A Systematic Review.',
    'Guilherme LQ, Rodrigues BO, Rosa COB, Leite LB',
    'Journal of clinical medicine',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41753086/',
    array['Sleep', 'Recovery'],
    'Sleep influences more than pace. In long-endurance settings it also affects decision quality, perceived effort, and the athlete''s ability to stay composed late in the event.',
    'Treat sleep as part of the performance plan, not just recovery hygiene. If a build compresses sleep too hard, the cost can show up before the athlete sees it in splits.',
    'High relevance for ultra racing where pacing and cognition deteriorate together.',
    5,
    3,
    3,
    true
  ),
  (
    '38107789',
    'Physiological and performance effects of live high train low altitude training for elite endurance athletes: A narrative review.',
    'Bonato G, Goodman SPJ, Tjh L',
    'Current research in physiology',
    2023,
    'https://pubmed.ncbi.nlm.nih.gov/38107789/',
    array['Altitude', 'Recovery'],
    'Altitude strategies work best when the athlete separates the hypoxic exposure from the quality training stress. The main benefit comes from preserving training quality while still accumulating meaningful altitude time.',
    'If altitude is the intervention, protect the quality sessions. The goal is not just more exposure; it is more useful exposure without flattening the legs.',
    'Useful anchor for altitude camp planning and for interpreting altitude-tent blocks.',
    5,
    4,
    4,
    true
  )
on conflict (pubmed_id) do update
set
  title = excluded.title,
  authors = excluded.authors,
  journal = excluded.journal,
  publication_year = excluded.publication_year,
  pubmed_url = excluded.pubmed_url,
  topic_tags = excluded.topic_tags,
  plain_english_summary = excluded.plain_english_summary,
  practical_takeaway = excluded.practical_takeaway,
  commentary = excluded.commentary,
  ultra_score = excluded.ultra_score,
  gravel_score = excluded.gravel_score,
  triathlon_score = excluded.triathlon_score,
  published = excluded.published,
  updated_at = now();
