insert into public.research_library_entries (
  pubmed_id,
  title,
  authors,
  journal,
  publication_year,
  pubmed_url,
  topic_tags,
  plain_english_summary,
  practical_takeaway,
  commentary,
  ultra_score,
  gravel_score,
  triathlon_score,
  published
)
values
  -- ===== ULTRA / TRAIL RUNNING =====
  (
    '42200900',
    'Hematological and Biochemical Responses During and After a 12-h Track Ultra-Marathon Race.',
    'Chatzakis P, Paradisis G, Patas K, Chatzipanagiotou S, Nikolaou C, Zacharogiannis E',
    'Journal of functional morphology and kinesiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42200900/',
    array['Recovery', 'Injury Prevention'],
    'Researchers tracked blood markers in athletes during and after a 12-hour track ultra-marathon, finding significant acute changes in hematological, inflammatory, muscular, myocardial, liver, and immune biomarkers. The inflammatory and muscle-damage markers spiked sharply during the race and remained elevated well after the finish, while some immune markers were suppressed, indicating a window of vulnerability post-race.',
    'Plan for a genuine recovery period after ultra events lasting 12 hours or more. The immune suppression and organ stress markers show that jumping back into hard training too soon adds risk. Monitor for signs of illness in the days following a major ultra effort.',
    'One of the more comprehensive blood-marker studies during a timed ultra. The real-time sampling during the race, not just pre/post, makes it especially useful for understanding when organ stress peaks.',
    5,
    2,
    2,
    true
  ),
  (
    '42196277',
    'Oxy-Inflammatory Profile of Finishers and No-Finishers in an Extreme Ultra-Endurance Trail Race: The 866 km Transpyrenea.',
    'Mrakic-Sposta S, Gussoni M, Mrakic-Sposta F, Giardini G, Pratali L, Montorsi M, Tonacci A, Dellanoce C, Martinelli M, Vezzoli A',
    'International journal of molecular sciences',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42196277/',
    array['Recovery', 'Injury Prevention'],
    'This study compared oxidative stress and inflammatory profiles between finishers and non-finishers of the 866 km Transpyrenea ultra-endurance trail race. Both groups experienced massive oxidative and inflammatory responses, but the athletes who dropped out showed distinct patterns of oxy-inflammatory imbalance that preceded their withdrawal, suggesting these biomarkers may serve as early warning signals of impending failure to finish.',
    'Oxidative stress and systemic inflammation are inevitable at extreme distances, but uncontrolled spikes may predict DNF. Antioxidant-rich nutrition and paced effort in the early stages may help manage the inflammatory load across multi-day events.',
    'At 866 km this is about as extreme as published human endurance research gets. The finisher vs. non-finisher comparison is the most valuable part, as it hints at predictive biomarkers for race attrition.',
    5,
    3,
    2,
    true
  ),
  (
    '42114829',
    'Decoding Neuromuscular Fatigue in Trail Running: A Systematic Review Across Distances and Sex Differences.',
    'Munoz de la Cruz V, Gonzalez-Mohino F, Garcia-Pinillos F, Jaen-Carrillo D',
    'International journal of sports physiology and performance',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42114829/',
    array['Running Economy', 'Strength Training'],
    'This systematic review mapped the fatigue mechanisms that limit trail running performance across different race distances and between sexes. Central fatigue dominates in shorter trail events, while peripheral neuromuscular fatigue becomes more prominent as distances increase. Women showed different fatigue profiles than men at matched distances, potentially explaining sex-based differences in ultra-distance pacing and durability.',
    'Train the fatigue pathway that matches your target distance. For shorter trail races, mental fatigue resistance and central drive matter most. For ultras, peripheral muscle resilience through eccentric strength work and downhill-specific training should be prioritized.',
    'This is the first systematic review to break down trail running fatigue by distance AND sex. The practical implications for sex-specific training and race-distance-specific preparation are significant.',
    5,
    3,
    2,
    true
  ),
  (
    '42104864',
    'Highly Trained Female Runners Show Greater Durability and Physiological Resilience Than Performance-Matched Male Counterparts.',
    'Jaen-Carrillo D, Bruce CD, Lawley JS, Zanini M',
    'Scandinavian journal of medicine & science in sports',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42104864/',
    array['Female Athletes', 'Running Economy', 'Pacing'],
    'When matched for performance level, highly trained female runners maintained their physiological efficiency better than males during prolonged exercise. Women showed less deterioration in running economy, oxygen cost, and biomechanical parameters over time, a concept now termed durability. This challenges the assumption that female athletes simply fatigue less because they run at lower absolute intensities.',
    'Female athletes may benefit from more aggressive pacing strategies in longer events than traditional models suggest, given their superior durability profile. Male athletes should pay more attention to durability training, including long tempo sessions and progressive long runs that extend past the point of initial fatigue.',
    'This is a landmark paper in the emerging field of durability research. The finding that women genuinely resist physiological deterioration better than performance-matched men, not just relatively, has direct implications for race strategy and training design.',
    5,
    4,
    4,
    true
  ),
  (
    '41981959',
    'Effects of race distance and probiotics intervention on kidney, muscle, and gut injury and inflammation biomarker responses during running.',
    'Hansson E, Skinner B, Falcone T, Halder A, Lucas RAI',
    'Journal of the International Society of Sports Nutrition',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41981959/',
    array['Gut Training', 'Supplementation', 'Recovery'],
    'This study examined how running distance affects kidney, muscle, and gut injury markers, and whether probiotic supplementation can reduce that damage. Longer race distances caused progressively greater organ stress, with kidney injury markers being particularly elevated. Probiotic supplementation showed a protective effect on gut barrier integrity and reduced some inflammatory markers, though it did not eliminate the organ stress entirely.',
    'Consider adding a multi-strain probiotic to your supplement protocol during heavy training blocks and race build-ups. The gut-protective effect is most relevant for athletes racing distances where GI distress is common. Train the gut alongside the body.',
    'Adds to the growing evidence that probiotics are not just about GI comfort but may have systemic protective effects during extreme endurance. The dose-response relationship with distance is important for athletes choosing their event.',
    5,
    3,
    3,
    true
  ),
  (
    '41843336',
    '24-Hour Ultra-Marathon Running: A Narrative Review of Performance Factors and Physiological Impacts.',
    'Knechtle B, Braschler L, Weiss K, Scheer V, Duric S, Leite LB, Forte P, Nikolaidis PT, Chlibkova D, Rosemann T',
    'Sports medicine - open',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41843336/',
    array['Pacing', 'Fueling & Nutrition', 'Recovery'],
    'This comprehensive review synthesizes all published research on 24-hour ultra-marathons, covering performance trends, pacing strategies, physiological impacts, and nutritional demands. Key findings include that even pacing correlates with better outcomes, caloric intake rates of 200 to 300 kcal per hour are associated with top finishes, and the physiological toll includes significant cardiac, renal, and musculoskeletal stress that requires extended recovery.',
    'For 24-hour events, commit to even pacing from the first hour. Target 200 to 300 kcal per hour with a mix of solid and liquid calories. Plan for at least two to three weeks of reduced training post-race to allow organ systems to recover.',
    'The most thorough review of 24-hour racing to date. Covers everything from participation trends to medical risks. Essential reading for anyone preparing for or coaching athletes in timed ultra events.',
    5,
    2,
    2,
    true
  ),
  (
    '41893600',
    'Understanding the Behavioural Determinants of Nutrition Practices in Ultra-Endurance Runners in Ireland.',
    'Ryan T, Daly E, Ryan L',
    'Sports (Basel, Switzerland)',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41893600/',
    array['Fueling & Nutrition', 'Gut Training'],
    'This study investigated why ultra-endurance runners eat the way they do, looking beyond what they consume to understand the behavioral drivers of their nutrition choices. Many athletes reported knowledge gaps about optimal fueling despite years of racing experience. Social influences, convenience, and habit drove food choices more than evidence-based guidelines, and many athletes underfueled during training relative to their race nutrition plans.',
    'Practice race nutrition during training, not just on race day. Seek out sport-specific nutrition education rather than relying on peer advice alone. Bridge the gap between what you know works and what you actually do day-to-day.',
    'Most nutrition research tells athletes what to eat. This study asks why they don''t follow the evidence. The behavioral angle is underexplored and practically relevant for coaches trying to change athlete habits.',
    5,
    3,
    3,
    true
  ),
  (
    '41602794',
    'Profiling measures of muscle strength and power throughout a 156 km ultra-trail running event.',
    'Markov A, Edwards BJ, Goutorbe A, Gilli S, Lemire M, Nguyen AP, Mauvieux B',
    'Frontiers in sports and active living',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41602794/',
    array['Strength Training', 'Running Economy', 'Pacing'],
    'Researchers measured strength and power at every lap of a 156 km ultra-trail with 6000 m of elevation change. Knee-extensor strength dropped 41 percent by the finish, while handgrip strength barely changed, confirming that fatigue is localized to the legs. Athletes who dropped out at lap five had 27 percent lower baseline strength than finishers, but among finishers, the magnitude of strength loss did not predict finishing position.',
    'Baseline lower-body strength may determine whether you finish an ultra, not how fast you finish. Prioritize heavy compound leg work in your training plan. The data suggest a minimum strength threshold exists below which completion risk rises sharply.',
    'First-ever continuous in-race strength profiling across an entire ultra-trail. The finding that baseline strength predicts completion but not placement is a game-changer for how we think about strength training for ultra runners.',
    5,
    3,
    2,
    true
  ),
  (
    '41713453',
    'Greater Ankle Plantar Flexor Work Is Predictive of Better Running Economy on Steep Uphill Grades.',
    'Robinson RM, Hahn ME',
    'Journal of applied biomechanics',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41713453/',
    array['Running Economy', 'Strength Training'],
    'This study found that ankle plantar flexor work, specifically calf strength and power, is the strongest predictor of running economy on steep uphill grades of 5 and 10 percent. The relationship was stronger on steeper grades, where the ankle must produce more propulsive force. Hip and knee joint contributions were less predictive of economy on inclines compared to flat running.',
    'For trail and mountain runners, calf-specific strength training may yield larger economy gains than general lower-body work. Include heavy calf raises, single-leg hops, and hill-specific drills that load the ankle plantar flexors through full range of motion.',
    'Running economy research typically focuses on flat surfaces. This study specifically addresses uphill grades relevant to trail, mountain, and gravel athletes. The practical implication for calf-focused training is clear and actionable.',
    5,
    4,
    3,
    true
  ),
  (
    '41493537',
    'Correlations Between the Metabolic Costs of Level and Graded Running: A Secondary Analysis of the Literature.',
    'Espeit L, Besson T, Sabater-Pastor F, Tondut J, Hoogkamer W, Kram R, Lemire M, Millet GP, Savoldelli A, Vercruyssen F, Vernillo G, Millet GY',
    'Sports medicine (Auckland, N.Z.)',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41493537/',
    array['Running Economy', 'VO2max'],
    'This meta-analysis found that flat running economy is only weakly correlated with uphill and downhill running economy. An athlete who is efficient on flat terrain may not be efficient on grades, and vice versa. The metabolic cost of graded running depends on distinct biomechanical and muscular factors that flat testing does not capture, calling into question the practice of using flat-ground economy tests to predict trail performance.',
    'If your goal race involves significant elevation, test and train your economy on grades, not just flat surfaces. A runner with excellent flat economy may have poor uphill or downhill economy. Specific hill training is essential for trail and mountain events.',
    'From the lab of Millet and colleagues, this challenges a fundamental assumption in exercise physiology. For coaches and athletes in hilly sports, the message is clear: flat-ground testing has limited predictive value for graded terrain.',
    5,
    5,
    3,
    true
  ),
  -- ===== CYCLING =====
  (
    '42148565',
    'Physiological and subjective measures of exercise intensity cycling at 55% and 85% of functional threshold power: Findings from a randomised crossover trial.',
    'Denham J, Scott-Hamilton J, Mills D',
    'Journal of sports sciences',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42148565/',
    array['Lactate Threshold', 'HRV'],
    'This study examined what actually happens physiologically when cyclists ride at 55 and 85 percent of their functional threshold power. At 55 percent FTP, most riders were below their first ventilatory threshold, making it genuinely easy aerobic work. At 85 percent FTP, many riders were near or above their second ventilatory threshold, meaning this commonly prescribed zone two intensity may actually be zone three or higher for many athletes.',
    'If you train by FTP zones, verify them against lab-based thresholds. Riding at 85 percent of FTP is not necessarily moderate intensity for all athletes. Use heart rate, RPE, or lactate alongside power to ensure your easy rides are truly easy and your threshold work is properly calibrated.',
    'This is important validation research for the millions of cyclists using FTP-based training. The finding that 85 percent of FTP overshoots moderate intensity for many riders explains why some athletes accumulate excessive fatigue from what they believe is zone two work.',
    3,
    5,
    4,
    true
  ),
  (
    '42103300',
    'Cross-Sectional Body Composition Analysis in Distinct Union Cycliste Internationale Categories of Male Road Cyclists: A Multimodal Approach.',
    'Giorgi A, Campa F, Matias CN, Martinez-Gonzalez B, Franchi MV',
    'International journal of sports physiology and performance',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42103300/',
    array['Fueling & Nutrition'],
    'This study provides the first multimodal body composition analysis across UCI age categories in male road cyclists, from juniors through elite professionals. Body composition profiles differed significantly across categories, with professional riders showing lower fat mass and higher lean mass relative to body weight. The data establish category-specific reference ranges that can guide developmental athletes toward appropriate body composition targets without resorting to unhealthy weight manipulation.',
    'Use age-category-specific body composition references rather than comparing developing riders to elite professionals. Body composition should evolve progressively across a cycling career. Prioritize lean mass development in younger categories before focusing on fat mass reduction.',
    'Fills a major gap in cycling physiology by providing reference data across competitive levels. Especially valuable for coaches of junior and U23 riders who need evidence-based benchmarks.',
    2,
    5,
    4,
    true
  ),
  (
    '41768777',
    'Physical performance and tactical experience: determinants of competition outcomes in amateur vs. elite cyclists - a descriptive study from the UCI tour of Lithuania.',
    'Cesanelli L, Conte D, Ylaite B, Ronnestad BR, Lagoute T, Venckunas T, Zambolin F',
    'Frontiers in physiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41768777/',
    array['Pacing', 'VO2max'],
    'Researchers compared lab testing and in-race power data between elite and amateur cyclists competing in the same five-stage UCI race. Amateur riders had lower VO2max and critical power but could still complete the race. The key difference was tactical: amateurs spent more time above critical power and distributed effort more evenly across the team, while elites used polarized pacing and specialized team roles. Energy management and race IQ were bigger differentiators than raw physiology.',
    'Once your fitness reaches a sufficient threshold, race-specific skills like pacing, tactical positioning, and energy management become the performance limiters. Train race scenarios, not just intervals. Practice surging above threshold and recovering at sub-threshold power in group settings.',
    'A rare study comparing lab and field data in the same multi-stage race. The tactical gap between amateur and elite cyclists is quantified for the first time, showing that amateur cyclists often have enough engine but waste it through poor pacing.',
    3,
    5,
    3,
    true
  ),
  (
    '41745684',
    'Chronic Self-Myofascial Release in Road Cyclists: Effects on Cardiorespiratory Capacity, Metabolism, and Mechanical Power.',
    'Posch D, Antretter M, Burtscher M, Faulhaber M',
    'Sports (Basel, Switzerland)',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41745684/',
    array['Recovery', 'Lactate Threshold'],
    'In this six-month randomized controlled trial, recreational cyclists who foam-rolled after every training session showed no improvement in VO2max but did improve their lactate curve and mechanical power at both aerobic and anaerobic thresholds compared to controls. Foam rolling did not shift the ceiling of aerobic capacity but appeared to improve the efficiency of work production below that ceiling.',
    'Add foam rolling immediately after cycling sessions as a recovery tool. Don''t expect it to raise your VO2max, but it may help you produce more power at threshold over months of consistent use. The key is daily consistency, not occasional use.',
    'Six months and randomized controlled, which is rare for foam rolling research. The finding that it improves metabolic efficiency without changing VO2max suggests a mechanism related to tissue quality and neuromuscular function, not central aerobic adaptations.',
    3,
    5,
    4,
    true
  ),
  (
    '41432746',
    'Limited benefit of repeated post-exercise hot water immersion on exercise performance of well-trained cyclists in warm and hot conditions.',
    'Kjertakov M, Aughey R, Petersen A',
    'European journal of applied physiology',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/41432746/',
    array['Heat Acclimation'],
    'Six consecutive days of post-exercise hot water immersion reduced heart rate, thermal sensation, and perceived exertion during submaximal cycling in both warm and hot conditions, but had zero effect on time-trial performance. The perceptual benefits did not translate into measurable performance gains, suggesting that passive heat acclimation via hot water immersion is not an effective substitute for active heat acclimation in well-trained cyclists.',
    'If you are well-trained, do not rely on post-exercise hot baths as your heat preparation strategy. While you may feel more comfortable, it won''t make you faster. Active heat acclimation through exercising in the heat remains the gold standard for performance gains.',
    'Important negative finding that challenges a popular shortcut. Many athletes and coaches use post-exercise hot water immersion as a convenient heat prep method. This study shows the perceptual adaptation does not equal performance adaptation in trained cyclists.',
    4,
    5,
    4,
    true
  ),
  -- ===== TRIATHLON =====
  (
    '42097586',
    'Durability of International and National Junior and U23 Triathletes: A Simulated Stochastic Sprint Triathlon Cycle Elicits Significant Declines in Running Physiology and Performance Indices.',
    'Langley JO, Knight M, Bloom W, O''Brien H',
    'International journal of sports physiology and performance',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42097586/',
    array['Pacing', 'VO2max', 'Lactate Threshold'],
    'After a simulated sprint-triathlon bike leg with realistic stochastic power surges, junior and U23 triathletes showed significant declines in running VO2peak, velocity at VO2peak, respiratory compensation point, and time to task failure. The key finding is massive interindividual variation: some athletes lost very little running capacity after cycling while others collapsed. This durability profiling should be standard practice.',
    'Test your running physiology in both fresh and fatigued states to quantify your personal durability gap. Train brick sessions that include stochastic cycling efforts, not just steady-state, before running. The athletes who lose the least running capacity off the bike have a huge race-day advantage.',
    'Durability is emerging as the next frontier in endurance sport assessment. This study brings the concept specifically to triathlon with realistic race simulation. The interindividual variation finding is the most actionable: you need to know YOUR durability profile.',
    2,
    3,
    5,
    true
  ),
  (
    '41630831',
    'Pacing of the first and only female finisher in the world''s longest triathlon: The 2024 Triple Deca ultra triathlon.',
    'Duric S, Andrade MS, Leite LB, Forte P, Nikolaidis PT, Cuk I, Weiss K, Rosemann T, Knechtle B',
    'Journal of exercise science and fitness',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41630831/',
    array['Pacing', 'Female Athletes'],
    'This case study documents the pacing strategy of the first woman to complete a Triple Deca ultra triathlon, 30 consecutive full-distance triathlons over 30 days. Her pacing was remarkably consistent across the cycling and running legs throughout the 30 days, with most variation in swimming. She maintained performance by using a conservative, steady approach rather than going hard early and fading.',
    'In multi-day ultra events, consistency is survival. Start conservatively and maintain output rather than chasing fast early splits. The data show that even across 30 consecutive Ironman-distance efforts, pacing discipline prevents the catastrophic performance decay seen in athletes who start too fast.',
    'An extraordinary case study at the absolute extreme of human endurance. The pacing data from a 30-day triathlon provides lessons applicable to any multi-day event or heavy training block.',
    5,
    2,
    5,
    true
  ),
  (
    '41961830',
    'Sex- and nationality-based participation and performance trends in the Swissman Xtreme Triathlon (2019-2025).',
    'Leite LB, Forte P, Andrade MS, Duric S, Nikolaidis PT, Thuany M, Weiss K, Rosemann T, Knechtle B',
    'PloS one',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41961830/',
    array['Pacing', 'Female Athletes'],
    'Analysis of all Swissman Xtreme Triathlon finishers from 2019 to 2025 revealed no sex-based performance differences in any edition, meaning the women who start this extreme event finish just as fast as the men. Race times have been getting slower over the years, driven by intermediate and slower finishers as the event attracts a broader field, while the fastest athletes have maintained their performance.',
    'In extreme triathlon events, sex-based performance gaps can disappear entirely, suggesting that event selection, mental toughness, and preparation may matter more than physiological sex differences at the extreme end. The top performers remain consistent year over year while mid-pack times drift.',
    'Part of the growing XTri World Tour research. The absence of sex differences at this extreme distance challenges conventional thinking about male-female performance gaps and supports the idea that ultraendurance may be an equalizer.',
    5,
    2,
    5,
    true
  ),
  (
    '41985409',
    'Sex-based physiological responses to a 750-m swim at critical velocity estimated by the three-parameter model.',
    'Souza VRDA, Vivan L, Engelke P, de Lira CAB, Vancini RL, Weiss K, Knechtle B, Andrade MS',
    'Clinics (Sao Paulo, Brazil)',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41985409/',
    array['VO2max', 'Lactate Threshold', 'Female Athletes'],
    'Male and female triathletes were tested swimming 750 meters at their critical velocity. Men showed higher perceived exertion, pain, dyspnea, and blood lactate than women at the same relative intensity, suggesting women may tolerate threshold-intensity swimming with less physiological and perceptual strain. The protocol used to determine critical velocity also significantly influenced the estimated values.',
    'Female triathletes may have more headroom at critical swim velocity than males, supporting slightly more aggressive swim pacing in races. For all athletes, the method used to determine your critical swim speed matters, so use consistent protocols when tracking progress.',
    'Adds to the sex-difference literature specifically in the swim leg of triathlon. The lower perceptual and metabolic strain in women at matched relative intensity aligns with broader durability research across endurance sports.',
    3,
    2,
    5,
    true
  ),
  -- ===== NUTRITION =====
  (
    '42184098',
    'Dose-Response of Dietary Carbohydrate Intake on Skeletal Muscle Glycogen, Gastrointestinal Comfort and Body Composition in Endurance-Trained Individuals in Simulated Preparation for Competition.',
    'Jones RO, Areta JL, Bennett S, Pugh J, Louis JB',
    'Scandinavian journal of medicine & science in sports',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42184098/',
    array['Carbohydrate Loading', 'Gut Training', 'Fueling & Nutrition'],
    'This study tested different doses of carbohydrate loading to find the optimal intake for maximizing muscle glycogen before competition. Higher carbohydrate intakes produced higher glycogen stores, but with diminishing returns and increasing gastrointestinal discomfort and body mass gain. The practical sweet spot appears to be around 8 to 10 grams per kilogram per day, above which the GI costs may outweigh the glycogen benefits for many athletes.',
    'When carb loading for a key race, aim for 8 to 10 grams of carbohydrate per kilogram per day in the 24 to 48 hours before competition. Going higher may add minimal glycogen benefit while causing gut distress and uncomfortable weight gain. Practice your loading protocol in training first.',
    'Fills a major gap by testing multiple carbohydrate doses head-to-head. The dose-response curve with GI symptoms is the most practically useful finding, helping athletes find the loading sweet spot.',
    5,
    5,
    5,
    true
  ),
  (
    '42134413',
    'Exogenous Carbohydrate Oxidation Is Higher When Consuming Glucose + Fructose Compared with Glucose Alone during Endurance Exercise Regardless of Energy Status.',
    'Barney DE, Panik KN, Michalak J, Wilson MA, Carrigan CT, Murphy NE, Drummer DJ, Margolis LM',
    'The Journal of nutrition',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42134413/',
    array['Fueling & Nutrition', 'Carbohydrate Loading'],
    'Athletes burn more exogenous carbohydrate during exercise when consuming a glucose-fructose mix compared to glucose alone, and this advantage holds regardless of whether the athlete is in energy balance or energy deficit. Even when underfueled, the dual-transport mechanism of glucose plus fructose delivers more usable energy than glucose alone, confirming the superiority of mixed-sugar fueling products.',
    'Always choose race fuel that contains both glucose and fructose rather than glucose-only products. This is especially important during events where you may be in energy deficit, where the glucose-fructose advantage is maintained. A 1:0.8 or 2:1 glucose-to-fructose ratio is the current standard.',
    'Resolves a lingering question about whether the glucose-fructose advantage disappears under energy deficit conditions. It doesn''t. This has direct product-selection implications for every endurance athlete.',
    5,
    5,
    5,
    true
  ),
  (
    '42105255',
    'Carbohydrate supplementation for endurance exercise in the heat: a systematic review with practical recommendations.',
    'Salame A, Brown D, Oueijan K, McCullough D',
    'Journal of the International Society of Sports Nutrition',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42105255/',
    array['Fueling & Nutrition', 'Heat Acclimation', 'Hydration'],
    'This systematic review found that carbohydrate intake during endurance exercise in the heat does not consistently improve performance, unlike in cooler conditions. Heat may increase the body''s reliance on muscle glycogen regardless of what you consume, meaning exogenous carbs cannot fully compensate for heat-driven glycogen breakdown. Seven of nine studies did not measure GI symptoms, a critical oversight given that heat exacerbates gut problems.',
    'In hot-weather racing, prioritize hydration alongside carbohydrate intake rather than relying on carbs alone to maintain performance. Expect that your fueling strategy may be less effective in the heat than in cool conditions. Practice gut training specifically in hot environments.',
    'A sobering finding for athletes who assume their cool-weather fueling plan will transfer to hot races. The heat changes the metabolic equation. The call for more research on GI symptoms in heat is especially important.',
    5,
    5,
    5,
    true
  ),
  (
    '41634956',
    'Carbohydrate restriction drives greater perturbations in circulating metabolites than low energy availability in elite male athletes.',
    'Dunlop KA, Lawler NG, Whitfield J, McKay AKA, Tee N, Ross ML, Reinke SN, Hawley JA, Broadhurst D, Burke LM',
    'Physiological reports',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41634956/',
    array['Fueling & Nutrition', 'Carbohydrate Loading'],
    'Elite male endurance athletes completed five-day interventions of high-carb, low energy availability, or low-carb high-fat diets. Metabolomics revealed that carbohydrate restriction combined with high fat intake caused far greater metabolic disruption than simply eating less. The low-carb high-fat diet produced elevated fatty acids, dicarboxylic acids, and acylcarnitine intermediates, especially after prolonged exercise, none of which appeared under energy restriction alone.',
    'Short-term low-carb high-fat diets create a unique metabolic stress that goes beyond simple energy deficit. If you periodize low-carb phases, keep them brief and monitor for signs of excessive metabolic strain. Low energy availability from reduced food intake is metabolically less disruptive than active carbohydrate restriction.',
    'From the Burke and Hawley labs using cutting-edge metabolomics. Provides molecular-level evidence for why LCHF diets feel different from simply eating less. Important nuance for athletes experimenting with periodized nutrition.',
    4,
    5,
    4,
    true
  ),
  (
    '41572516',
    'Working Memory Performance is Reduced after a Marathon Race and Associated with Low Energy Availability in Females.',
    'Boere K, Young N, Dauphinee R, Copithorne F, Kirby BS, Krigolson OE, Stellingwerff T',
    'Medicine and science in sports and exercise',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41572516/',
    array['Female Athletes', 'Fueling & Nutrition'],
    'Female marathon runners showed significant declines in high-load working memory within 10 minutes of finishing a marathon. The cognitive decline was linked to both acute low carbohydrate intake during the race, averaging only 28 grams per hour, and chronic low energy availability as measured by the LEAF-Q questionnaire. Brain activity showed increased frontal theta power post-race, indicating the brain was working harder to maintain cognitive function.',
    'Female endurance athletes should target higher in-race carbohydrate intake to protect both physical and cognitive performance. The average of 28 grams per hour in this study is well below current recommendations. Chronic low energy availability compounds the problem, so address fueling habits in daily training, not just on race day.',
    'Novel combination of EEG brain imaging with marathon racing in female athletes. Links both acute and chronic energy availability to cognitive impairment. The practical implication for decision-making, pacing, and safety during endurance events is significant.',
    4,
    3,
    4,
    true
  ),
  (
    '41599941',
    'Coffee Versus Caffeine as Ergogenic Aids: Biological and Methodological Distinctions with Implications for Exercise Performance and Recovery.',
    'Domaszewski P',
    'Nutrients',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41599941/',
    array['Caffeine', 'Supplementation', 'Recovery'],
    'This review compares coffee and isolated caffeine as performance enhancers, finding that coffee can match caffeine''s ergogenic effects for endurance exercise but with more variable responses due to differences in caffeine content and individual sensitivity. Coffee may support post-exercise glycogen resynthesis when consumed with carbohydrates and provides additional antioxidant and anti-inflammatory compounds. Coffee is generally better tolerated than caffeine pills.',
    'For most endurance athletes, coffee is a practical and effective caffeine source that does not need to be replaced with isolated caffeine supplements. If you tolerate coffee well, a strong cup 30 to 60 minutes before exercise delivers comparable ergogenic effects. Consider coffee with carbs post-exercise for enhanced glycogen recovery.',
    'Addresses the gap between how caffeine is studied in labs versus how athletes actually consume it. For the vast majority of athletes who use coffee as their caffeine source, this review validates that approach.',
    4,
    4,
    4,
    true
  ),
  -- ===== CROSS-COUNTRY SKIING / ROWING / WINTER SPORTS =====
  (
    '42177035',
    'No Additional Effects of Block- Compared to Even-Periodization of Low-Intensity Training in Junior Cross-Country Skiers.',
    'Walther J, Hanel L, Krohn R, Grossmann S, Schumann M',
    'International journal of sports physiology and performance',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42177035/',
    array['Periodization', 'VO2max', 'Lactate Threshold'],
    'In this crossover study, junior cross-country skiers performed either block periodization with one high-volume week followed by reduced weeks or evenly distributed training at the same total volume. There was no difference in VO2max, maximal aerobic speed, or lactate threshold improvements between approaches. The block group reported lower mood and perceived recovery during and after the high-volume week, suggesting the concentrated stress was tolerated but provided no additional stimulus.',
    'For low-intensity training, consistency trumps concentration. Distributing your aerobic volume evenly across weeks is as effective as block loading and comes with less perceived stress. Save block periodization for high-intensity or specific race-preparation phases where the concentrated stimulus may have more value.',
    'Important negative finding that challenges the increasingly popular block periodization approach. The key nuance is that this applies to low-intensity volume, not high-intensity work. For coaches, this simplifies planning of base-phase training.',
    4,
    4,
    4,
    true
  ),
  (
    '41764999',
    'Associations Between Laboratory-Based Performance Indicators and On-Snow Competitive Success in Elite Cross-Country Skiing: A 15-Year Analysis of the Swiss National Team.',
    'Bucher E, Wehrlin JP, Trosch S, Millet GP, Steiner T',
    'International journal of sports physiology and performance',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41764999/',
    array['VO2max', 'Lactate Threshold', 'Running Economy'],
    'Fifteen years of Swiss national team data showed that VO2max and velocity at the lactate threshold were the strongest predictors of competitive success in cross-country skiing, with sex- and age-dependent differences. The associations were stronger for sprint events than distance events, suggesting that at the elite level, factors beyond traditional lab tests, like technique, tactics, and race-day execution, play a larger role in distance racing outcomes.',
    'VO2max and threshold metrics remain the foundation of endurance performance, but their predictive power decreases as race distance increases. For distance events, invest in race-specific skills and tactical preparation alongside physiological development. Lab testing is necessary but not sufficient for elite performance.',
    'Fifteen years of national-team data is an exceptionally strong dataset. The finding that lab metrics predict sprint skiing better than distance skiing has implications for all endurance sports: the longer the event, the more non-physiological factors matter.',
    4,
    4,
    4,
    true
  ),
  (
    '42172297',
    'Strength and Speed Training Practices for Olympic Endurance Sports: Insights From World-Class Coaches.',
    'Haugen T, Sandbakk O, Bucher Sandbakk S, Tonnessen E',
    'Journal of strength and conditioning research',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42172297/',
    array['Strength Training', 'Concurrent Training', 'Periodization'],
    'World-class coaches across Olympic endurance sports including running, cycling, XC skiing, rowing, swimming, biathlon, and speed skating described how they integrate strength and speed work into endurance training. Common themes include periodizing strength from general to sport-specific across the season, maintaining one to two strength sessions per week year-round, and using maximal strength rather than strength endurance as the primary stimulus. Sprint and speed work are used sparingly but strategically.',
    'Maintain one to two maximal strength sessions per week year-round, not just in the off-season. Focus on heavy compound lifts at low reps rather than high-rep strength endurance circuits. Periodize from general strength in the base phase to sport-specific power closer to competition.',
    'Companion paper to the earlier Sandbakk et al. best-practice training paper already in the library. Together they provide the most complete picture of how the world''s best endurance programs structure both endurance and strength training.',
    5,
    5,
    5,
    true
  ),
  (
    '42112935',
    'Peak Oxygen Uptake Provides a Better Predictor of Rowing Ergometer Mean Maximal Power Than Maximal Oxygen Extraction in Trained Rowers.',
    'Lanigan BJO, Tinely ZL, Binnie MJ, Peeling P, Scott BR, Peiffer JJ',
    'Journal of strength and conditioning research',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42112935/',
    array['VO2max'],
    'In trained rowers, peak oxygen uptake was a stronger predictor of maximal power output on the rowing ergometer than peripheral oxygen extraction. This suggests that central cardiovascular capacity, the ability to deliver oxygen, remains the primary limiter of rowing performance even in well-trained athletes, rather than the muscles'' ability to extract and use oxygen.',
    'Rowers should prioritize training that improves central cardiovascular capacity: high-volume steady-state work and threshold intervals. Peripheral adaptations like capillary density and mitochondrial function matter, but the central pump is the bigger performance limiter.',
    'Adds rowing-specific evidence to the central vs. peripheral limitation debate in endurance sports. Useful for coaches programming the balance between aerobic base work and peripheral stimulus like strength and interval training.',
    3,
    2,
    4,
    true
  ),
  (
    '41673933',
    'Endurance Training in Olympic Winter Sports: A Narrative Review of the Current Literature and Future Research Priorities.',
    'Sperlich B, Holmberg HC',
    'Scandinavian journal of medicine & science in sports',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41673933/',
    array['Periodization', 'VO2max', 'Concurrent Training'],
    'This comprehensive review synthesizes endurance training practices across all Olympic winter sports ahead of Milan-Cortina 2026. Key themes include the universal adoption of polarized training intensity distribution, the integration of concurrent strength training without compromising endurance adaptations, and the importance of individualized training architectures that account for sport-specific demands like altitude exposure and cold environments.',
    'The polarized training model, with roughly 80 percent of volume below the first ventilatory threshold and most of the remaining 20 percent above the second threshold, is now the dominant framework across elite winter endurance sports. Use it as your starting point and individualize from there based on your sport''s specific demands.',
    'A timely review ahead of the 2026 Winter Olympics that demonstrates how consistent the training principles are across sports as different as XC skiing, speed skating, and biathlon. The cross-sport perspective offers insights that single-sport reviews miss.',
    4,
    4,
    4,
    true
  ),
  (
    '41885788',
    'Internal Load and Fatigue Characteristics in Male Cross-Country Skiers During Summer Training.',
    'Du C, Xu H, Shi J, Wei J, Quan H, Zhu T',
    'Journal of strength and conditioning research',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41885788/',
    array['Periodization', 'HRV', 'Recovery'],
    'This study tracked internal training load and fatigue markers across summer training in male cross-country skiers. Training load distribution was highly polarized, with most volume at low intensity. Fatigue accumulated non-linearly, with delayed spikes in subjective and biochemical fatigue markers appearing days after the hardest training blocks. Heart rate variability tracked fatigue accumulation well and predicted readiness better than subjective measures alone.',
    'Monitor HRV consistently to detect fatigue accumulation that subjective feel may miss, especially during high-volume base-phase training. Expect fatigue markers to spike two to three days after hard blocks, not immediately. Plan recovery days to account for this delayed response.',
    'Useful data from XC skiing that applies to any endurance sport with a summer base-building phase. The delayed fatigue finding is particularly relevant for athletes who feel fine the day after a hard block but crash two days later.',
    4,
    4,
    3,
    true
  ),
  -- ===== GENERAL ENDURANCE =====
  (
    '42072980',
    'Effects of Aging on Determinants of Endurance Performance in Women Masters Athletes: A Scoping Review.',
    'Vangsgaard D, Noumi M, Hayden KA, Doyle-Baker PK',
    'Healthcare (Basel, Switzerland)',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42072980/',
    array['Female Athletes', 'VO2max', 'Lactate Threshold'],
    'This scoping review examined how aging and menopause affect aerobic capacity, lactate kinetics, and exercise economy in women masters athletes. VO2max declines 0.5 to 2.4 percent per year, primarily driven by decreased cardiac output and changes in body composition. However, lactate threshold relative to VO2max generally increases with age, partially compensating for the aerobic decline. Training volume is a key predictor of how well aerobic capacity is maintained.',
    'Women masters athletes should maintain or increase training volume to slow aerobic capacity decline. The silver lining: your ability to sustain effort near threshold improves with age, so race performance at longer distances may hold up better than short-distance speed. Strength training and body composition management become increasingly important.',
    'Fills a major gap by focusing specifically on women masters athletes, a rapidly growing population in endurance sports. Most aging research is on men or mixed populations. The finding that lactate threshold improves relative to VO2max is encouraging for aging female athletes.',
    4,
    4,
    4,
    true
  ),
  (
    '41543030',
    'Effects of Low-Intensity Endurance Training on Aerobic Fitness and Risk Factors of Cardiometabolic Health in Working-Age Adults: A Systematic Review and Meta-Analysis.',
    'Nuuttila OP, Matomaki P, Raitanen J, Sievanen H, Vasankari T',
    'Scandinavian journal of medicine & science in sports',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41543030/',
    array['VO2max', 'Periodization'],
    'This meta-analysis of 50 studies found that training exclusively below the first ventilatory threshold, true zone one work, produces large improvements in VO2max and moderate improvements in threshold and cardiometabolic health markers. Higher intensity within the low-intensity zone was associated with greater VO2max gains, but no minimum effective intensity was identified for most outcomes. Even very easy training produces meaningful adaptations.',
    'Easy training works. If you are struggling with fatigue or life stress, know that keeping your intensity genuinely low still produces significant aerobic gains. The lowest zone is not junk miles. For maximal benefit, push to the upper end of zone one rather than jogging aimlessly, but don''t feel your easy sessions are wasted.',
    'Rigorous meta-analysis that validates the foundation of polarized training. The finding that even the easiest training produces substantial VO2max gains challenges the narrative that you need intensity to improve. Relevant to every endurance athlete questioning the value of their easy days.',
    5,
    5,
    5,
    true
  ),
  (
    '41702691',
    'What do thermal indices lack to help predict heat-related risk in elite Athletics?',
    'Bandiera D, Garrandes F, Kowalski J, Adami PE, Racinais S, Matzarakis A, Pitsiladis YP, Tessitore A, Bermon S',
    'British journal of sports medicine',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41702691/',
    array['Heat Acclimation', 'Hydration'],
    'This study from World Athletics analyzed the frequency of exertional heat stroke, DNF, and medical encounters across elite athletics competitions and evaluated how well standard thermal indices predict these outcomes. Current heat indices poorly predicted which events would produce the most heat casualties. The mismatch suggests that individual factors like acclimatization status, hydration, pacing, and event duration matter more than ambient conditions alone.',
    'Do not rely solely on weather forecasts or WBGT readings to determine your heat risk on race day. Your personal acclimatization status, hydration preparation, and pacing plan are stronger determinants of heat-related problems than the ambient temperature. Arrive heat-acclimatized regardless of the forecast.',
    'Published in BJSM with World Athletics data, this is the definitive analysis of heat risk prediction in competition. The finding that environmental indices alone are poor predictors should change how race organizers and athletes approach heat management.',
    5,
    5,
    5,
    true
  ),
  (
    '42139598',
    'Mechanical Variables Derived From Submaximal Back Squat Performance Are Positively Associated With Running Performance in Highly Trained Endurance Athletes.',
    'Jaen-Carrillo D, Carton-Llorente A, Garcia-Ramos A, Santos L',
    'Journal of strength and conditioning research',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42139598/',
    array['Strength Training', 'Running Economy'],
    'In highly trained endurance athletes, mechanical variables from submaximal back squats, including mean velocity and power, were positively correlated with running performance. Athletes who produced higher velocity and power during light to moderate squats also performed better in running events. The relationship held at submaximal loads, meaning heavy maximal testing is not needed to capture the association.',
    'Track your barbell velocity during submaximal squats as a proxy for neuromuscular readiness and running performance potential. If your squat velocity is declining, your running performance may follow. Use velocity-based training to autoregulate strength sessions within endurance training blocks.',
    'Connects strength room metrics to running outcomes in trained endurance athletes, not just sprinters. The submaximal nature of the testing makes it practical for regular monitoring without the fatigue cost of maximal testing.',
    4,
    4,
    4,
    true
  ),
  (
    '42103299',
    'The Association Between National Aeronautics and Space Administration Task Load Index Subscales, Training-Induced Fatigue, and Physiological Responses in Endurance Athletes.',
    'D''Alleva M, Patini A, Filipas L, Nicolo A, Rothschild JA, De Martino M, Mari L, Rejc E, Zaccaron S, Stafuzza J, Maunder E, Sacchetti M, Lazzer S',
    'International journal of sports physiology and performance',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42103299/',
    array['HRV', 'Recovery', 'Periodization'],
    'This study tested whether the NASA Task Load Index, a multidimensional subjective workload tool, could capture different components of training-induced fatigue in endurance athletes. The NASA-TLX distinguished between physical, mental, and temporal demands of training sessions better than traditional RPE alone. Specific subscales correlated with distinct physiological markers, suggesting it could provide a richer picture of internal training load.',
    'Consider using a multidimensional fatigue tool like the NASA-TLX alongside or instead of simple RPE to track training load. The added dimensions of mental demand, temporal demand, and frustration may help identify when cognitive and psychological fatigue is accumulating alongside physical fatigue.',
    'Introduces a well-validated tool from aerospace research into endurance sport. For athletes and coaches who feel RPE alone is too crude, the NASA-TLX offers a structured alternative that captures multiple fatigue dimensions.',
    4,
    4,
    4,
    true
  ),
  (
    '42133056',
    'Effect of sodium bicarbonate on performance and markers of kidney and gastrointestinal injury during repeated sprints in the heat.',
    'Specht JW, Ramirez M, Raef J, Schwartz M, Bailly AR, Chavez O, Kumbasar O, Dawson JX, Apodaca J, Freire R, Atkins WC, de Castro Magalhaes F, Siegler J, Amorim FT',
    'European journal of applied physiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42133056/',
    array['Sodium Bicarbonate', 'Heat Acclimation', 'Supplementation'],
    'Sodium bicarbonate supplementation was tested during repeated sprints in the heat to see if it improved performance and whether it affected kidney or GI injury markers. Bicarb improved sprint performance in hot conditions, confirming its ergogenic benefit extends to heat stress. Importantly, it did not worsen markers of acute kidney injury, addressing a key safety concern for athletes supplementing in the heat.',
    'Sodium bicarbonate remains a viable ergogenic aid even in hot conditions. The safety profile regarding kidney stress is reassuring for athletes competing in heat. Use the standard dose of 0.3 grams per kilogram body weight taken 60 to 90 minutes before competition, and practice in training first to test GI tolerance.',
    'Addresses two concerns at once: does bicarb work in the heat, and does it stress the kidneys when the body is already under heat strain? Both answers are encouraging. Relevant to any athlete using bicarb for summer racing.',
    4,
    4,
    4,
    true
  ),
  (
    '41653304',
    'Highest oxygen consumption prediction by forced vital capacity in athletes.',
    'Lorenzo-Capella I, Ramos-Alvarez JJ, Jimenez-Herranz ME, Maffulli N, Calderon-Montero FJ, Racil G, Iuliano E, Migliaccio GM, Padulo J',
    'European journal of applied physiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41653304/',
    array['VO2max', 'Respiratory Training'],
    'Across 422 athletes from cycling, swimming, triathlon, and other sports, forced vital capacity predicted VO2max with moderate accuracy at the population level. The prediction was strongest in swimmers and weakest in multisport athletes. While the equations are not precise enough to replace direct VO2max testing for individuals, they provide a practical screening tool for coaches without access to metabolic testing equipment.',
    'A simple spirometry test can provide a rough VO2max estimate when lab testing is not available. The prediction is most accurate for swimmers. For individual athlete tracking, always prefer direct metabolic testing, but spirometry can help coaches screen large groups or identify athletes with unusually high or low aerobic potential.',
    'Practical application for resource-limited settings. The sport-specific differences in prediction accuracy are informative: swimming''s strong correlation likely reflects the respiratory demands unique to the sport.',
    3,
    3,
    4,
    true
  )
on conflict (pubmed_id) do nothing;
