insert into public.research_library_entries (
  pubmed_id,
  title,
  authors,
  journal,
  publication_year,
  pubmed_url,
  topic_tags,
  plain_english_summary,
  practical_takeaway,
  commentary,
  ultra_score,
  gravel_score,
  triathlon_score,
  published
)
values
  -- 1. Low-carb vs high-carb debate (Burke & Noakes)
  (
    '42070893',
    'Does a low-carbohydrate diet impede endurance sports performance? Debate Consensus.',
    'Burke LM, Noakes TD',
    'The American journal of clinical nutrition',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42070893/',
    array['Fueling & Nutrition', 'Low Carb', 'Fat Adaptation'],
    'Carbohydrate availability still delivers the strongest performance benefits across most endurance contexts. Fat adaptation increases fat oxidation, but the practical upside is narrow: it helps most when the event is steady-state and the athlete cannot access carbohydrate. For most racing scenarios with surges, climbs, or mixed-intensity demands, prioritizing carbohydrate availability outperforms keto-adapted fueling.',
    'Default to carbohydrate-supported fueling for racing. Fat adaptation has a role in specific ultra-distance scenarios where intensity stays low and resupply is limited, but it is not a general-purpose performance strategy.',
    'This debate between Burke and Noakes is the clearest head-to-head summary available. Directly relevant to any ultra or gravel athlete evaluating low-carb race fueling.',
    5,
    5,
    4,
    true
  ),
  -- 2. 24-Hour Ultra-Marathon comprehensive review
  (
    '41843336',
    '24-Hour Ultra-Marathon Running: A Narrative Review of Performance Factors and Physiological Impacts.',
    'Knechtle B, Braschler L, Weiss K, Scheer V, Duric S, Leite LB, Forte P, Nikolaidis PT, Chlíbková D, Rosemann T',
    'Sports medicine - open',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41843336/',
    array['Ultra Running', 'Pacing', 'Recovery', 'Fueling & Nutrition'],
    'The most important performance variables in 24-hour races are training history, nutrition execution, previous race experience, and pacing discipline. Body type and anthropometrics do not predict outcomes. Organ-level effects on the heart, kidneys, liver, and immune system are real but resolve within days, not weeks. The athletes who finish well are typically masters-age runners with deep race experience.',
    'Build the 24-hour plan around fueling consistency, pacing patience, and experience. The body tolerates the stress better than most athletes expect, but nutrition failures are the most common cause of underperformance.',
    'Comprehensive reference for any coach or athlete planning a 24-hour event or ultra beyond 100 miles.',
    5,
    2,
    2,
    true
  ),
  -- 3. Cardiac fatigue in ultra cycling
  (
    '42126136',
    'From Healthy to Heart Failure in 24 Hours: Defining the upper limit of exercise induced cardiac fatigue.',
    'Foulkes SJ, Anderson M, Janssens K, Beaudry R, Carey A, Mitchell A, Spencer L, Angus D, Haykowsky MJ, La Gerche A',
    'Journal of applied physiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42126136/',
    array['Cardiac Health', 'Ultra Cycling', 'Recovery'],
    'There is a dose threshold for exercise-induced cardiac stress. A 12-hour cycling world record attempt caused moderate but fully reversible cardiac changes. The 24-hour attempt pushed past that threshold into acute heart failure with pulmonary edema, though even that resolved completely within five months. The heart is more resilient than the acute numbers suggest, but the 12-to-24-hour window appears to be where the risk curve steepens.',
    'For ultra events beyond 12 hours, build in awareness of cardiac fatigue as a real physiological cost, not just muscular fatigue. Recovery timelines after extreme efforts should account for cardiac, not only musculoskeletal, restoration.',
    'Important safety reference for ultra cyclists and anyone coaching athletes in 24-hour events.',
    5,
    3,
    3,
    true
  ),
  -- 4. Ultramarathon immune response by distance
  (
    '42051517',
    '(Ultra-)inflammation or adaptation? Comparison of different ultramarathon distances and their effect on the immune system.',
    'Bizjak DA, John L, Munk M, Bizjak R, Witzel J, Siebers C, Schulz SVW, Engler H, Siebers M, Kirsten J, Grau M',
    'Frontiers in immunology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42051517/',
    array['Immune System', 'Recovery', 'Ultra Running'],
    'Different ultra distances produce different immune responses. 100 km runners (faster pace, shorter duration) showed a more pronounced acute leukocyte response, while 230 km runners showed higher cortisol and CRP, reflecting the cost of sustained lower-intensity effort over days. The immune hit from an ultra is not generic; it depends on race distance and pacing profile.',
    'Post-race recovery and infection-prevention strategies should be calibrated to the specific event, not to a generic ultra template. A 100 km race is a different immune challenge than a 200+ km race.',
    'Directly useful for athletes racing multiple ultra distances and for coaches designing post-race recovery protocols.',
    5,
    2,
    2,
    true
  ),
  -- 5. GI vulnerability and race withdrawal
  (
    '41978086',
    'Digestive Vulnerability and Exercise Exposure as Correlates of Gastrointestinal Symptoms and Race Withdrawal in Endurance and Ultra-Endurance Athletes.',
    'Mauvieux B, Mahon E, Markov A, Slamani A, Fresneau M, Berthou A, Le Chevert E, Pugh J, Edwards BJ',
    'Nutrients',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41978086/',
    array['Gut Training', 'Fueling & Nutrition', 'Race Strategy'],
    'GI symptoms during races are best predicted by whether the athlete already has GI symptoms during training, not by any single food choice. Athletes with baseline digestive vulnerability who then race events lasting six or more hours have dramatically higher odds of GI-related withdrawal. The gut problem usually starts before race day.',
    'Screen for GI issues in training first. If an athlete regularly has gut problems in long sessions, fixing the race-day nutrition plan alone will not solve it. Address the vulnerability in training before optimizing the race-day protocol.',
    'Reframes GI management from a race-day nutrition problem to a training-phase screening problem. High relevance for ultra and Ironman athletes.',
    5,
    4,
    5,
    true
  ),
  -- 6. Heat training + altitude hemoglobin augmentation
  (
    '41934470',
    'Heat training augments hemoglobin mass during a moderate-altitude training camp in well-trained endurance athletes.',
    'Rønnestad BR, Urianstad Odden T, Blindheim PM, Hansen J, Hamarsland H, Ellefsen S, Urianstad Odden I, Mølmen KS',
    'Journal of applied physiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41934470/',
    array['Heat Acclimation', 'Altitude', 'Hematology'],
    'Adding three heat-suit cycling sessions per week to a moderate-altitude camp (~1,865 m) produced a meaningful hemoglobin mass increase that moderate altitude alone did not achieve. The combination worked where either stimulus alone fell short. The athletes were well-trained cross-country skiers and biathletes, so the effect was not a beginner artifact.',
    'If altitude access is limited to moderate elevations, layering heat stress onto the camp can unlock the hematological benefit that moderate altitude alone misses. This is a practical workaround when higher-altitude facilities are unavailable.',
    'Strong fit for gravel and ultra athletes who camp at moderate elevation and want to stack a secondary stimulus. Also relevant for triathletes doing altitude blocks.',
    5,
    5,
    5,
    true
  ),
  -- 7. Blood flow redistribution during glucose intake
  (
    '41926638',
    'Effects of glucose ingestion on blood flow in the small intestine and exercising limbs during endurance exercise.',
    'Endo MY, Kashima H, Miura A, Fukuba Y',
    'Journal of applied physiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41926638/',
    array['Fueling & Nutrition', 'Physiology'],
    'When you ingest glucose during exercise, blood flow shifts from the working muscles to the gut for digestion and absorption, without any compensatory increase in cardiac output. The body does not simply add more circulation; it redirects what is already available. This means fueling during exercise creates a temporary competitive demand between digestion and locomotion.',
    'Time carbohydrate intake to lower-intensity windows within the event when the muscle blood flow cost is more tolerable. During hard surges or climbs, the gut is competing with the legs for the same blood supply.',
    'Mechanistic explanation for why fueling during intense efforts often backfires. Relevant across all endurance disciplines.',
    4,
    5,
    5,
    true
  ),
  -- 8. Energy balance in 214 km winter ultra race
  (
    '41651468',
    'Energy and fluid balance during a 214-km winter ultraendurance race: a case study.',
    'Wehmanen KW, Ruby BC, Shriver TC, Ravelli MN, Kipp S, McDaniel J, Petushek EJ, Elmer SJ',
    'Journal of applied physiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41651468/',
    array['Fueling & Nutrition', 'Hydration', 'Ultra Cycling', 'Cold Weather'],
    'The winner of a 214 km winter cycling race (the Arrowhead Ultra, -13 to -1°C) burned over 15,000 kcal in 18 hours at 9.6 times basal metabolic rate, but could only take in about 8,000 kcal. Water turnover was 17.7 liters despite the cold. The energy deficit was massive but did not prevent winning. The hydration demands in cold conditions were comparable to warm-weather ultras, challenging the assumption that cold reduces fluid needs.',
    'Cold-weather ultra events demand the same hydration attention as warm ones. Plan fueling with the understanding that a large energy deficit is unavoidable in single-day ultras; the goal is managing the rate of deficit, not preventing it.',
    'Rare quantitative data on cold-weather ultra demands. Highly relevant for winter ultra cycling and fat-bike events.',
    5,
    4,
    2,
    true
  ),
  -- 9. Strength and cross-country skiing performance
  (
    '42134780',
    'Embracing the Diversity of Race Characteristics: Association Between Muscular Strength and Cross-Country Skiing Performance.',
    'Walther J, Tomavo A, Schumann M',
    'International journal of sports physiology and performance',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42134780/',
    array['Strength Training', 'Cross-Country Skiing'],
    'Maximal upper-body pull strength explained up to 57% of sprint performance variance in male XC skiers and remained significant even in distance races under 10 km. But in races longer than 10 km, the strength-performance link disappeared. The role of strength is format-dependent: critical for sprints and flat courses, negligible for long-distance events on hilly terrain.',
    'For endurance athletes in upper-body-dependent sports, strength training pays off most in shorter-format and flatter events. In long-distance events, aerobic capacity and pacing dominate, and extra strength investment has diminishing returns.',
    'Useful framework for any sport where strength supports but does not drive performance: think gravel racing with technical demands vs. long steady efforts.',
    3,
    4,
    3,
    true
  ),
  -- 10. Cold open-water marathon swim hypothermia case
  (
    '41564305',
    'Prolonged stable hypothermia during a 10-hour cold open-water marathon swim.',
    'Roxburgh BH, Edgar DT, Cotter JD',
    'Experimental physiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41564305/',
    array['Cold Weather', 'Open Water Swimming', 'Thermoregulation'],
    'A 52-year-old marathon swimmer completed a 37 km cold-water crossing (13-14°C) in nearly 10 hours while hypothermic for over 6 hours, with core temperature dropping to 33.9°C. Despite this, he showed no cognitive or motor impairment and had no dangerous after-drop post-swim. Cold-adapted endurance swimmers can maintain function at core temperatures that would normally impair performance.',
    'Cold adaptation is trainable and individual. For open-water athletes, progressive cold exposure builds tolerance that extends the operational window. But individual variation is large; what one swimmer tolerates may be dangerous for another.',
    'Fascinating thermoregulation case for open-water and triathlon athletes racing in cold conditions.',
    3,
    2,
    4,
    true
  ),
  -- 11. Rowing phenotype for 1500m Olympic distance
  (
    '42142183',
    'A speed-oriented phenotype is beneficial for 1500 m rowing at the Los Angeles 2028 Olympic Games.',
    'Baumann E, van der Vorst EMC, Hofmijster MJ',
    'European journal of applied physiology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42142183/',
    array['Rowing', 'Anaerobic Capacity', 'Race Strategy'],
    'The shift from 2000 m to 1500 m Olympic rowing favors athletes with a higher power reserve ratio: those who can produce more peak power relative to their aerobic threshold. Aerobic capacity still matters, but the shortened distance tips the balance toward athletes with greater anaerobic and explosive qualities.',
    'When race distances shorten, training should shift toward speed and power reserve, not just aerobic volume. This principle applies beyond rowing to any endurance sport where event format changes the intensity profile.',
    'Relevant conceptually for gravel and triathlon athletes where race formats vary and anaerobic capacity becomes decisive.',
    2,
    3,
    4,
    true
  ),
  -- 12. Supplements for cycling comprehensive review
  (
    '41685663',
    'A comprehensive review of the physiology and evidence base to guide the use of ergogenic and medical supplements for enhanced cycling performance.',
    'Rowland A, Edwards S, Prieto-Bellver G, Menz B, Rowland A, Cornelisse E, Karapetis CS, Wallen MP, Hopkins AM',
    'Journal of the International Society of Sports Nutrition',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41685663/',
    array['Supplementation', 'Cycling', 'Fueling & Nutrition'],
    'The strongest evidence for cycling supplements clusters around caffeine, carbohydrates, beta-alanine, creatine, nitrates, and sodium bicarbonate, each targeting a specific energy system. Medical supplements like iron, vitamin D, omega-3, and probiotics play indirect roles through recovery, immune support, and connective tissue health. The key is matching the supplement to the specific metabolic demand of the event.',
    'Build a supplement plan around the energy system the event actually taxes. Do not stack supplements generically. Test each one individually in training before combining for race day.',
    'Comprehensive reference for gravel and ultra cyclists building a supplement protocol. Also relevant for triathlon bike-leg optimization.',
    4,
    5,
    4,
    true
  ),
  -- 13. Sex differences in endurance performance
  (
    '42057283',
    'Physiological Basis of Sex Differences in Human Performance and Exercise-Associated Pathology.',
    'Holdsworth DA, O''Leary TJ, Doig CL, Taylor N, Dosanjh J, Woods DR, Stacey MJ, Gifford RM',
    'Clinical endocrinology',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/42057283/',
    array['Female Athlete', 'Physiology', 'Ultra Running'],
    'The performance gap between men and women narrows as event duration increases, partly because women have advantages in fat oxidation, lower carbohydrate dependence, and improved fatigue resistance during prolonged submaximal work. Sex differences also affect injury patterns, thermoregulation, and reproductive health under training stress. Treating female athletes as smaller male athletes misses important physiological distinctions.',
    'Training and nutrition plans for female endurance athletes should account for sex-specific fuel utilization, menstrual cycle effects, and different injury risk profiles rather than simply scaling male protocols down.',
    'Essential context for coaches working with female ultra, gravel, and triathlon athletes.',
    5,
    4,
    4,
    true
  ),
  -- 14. Cognitive decline after marathon in females
  (
    '41572516',
    'Working Memory Performance is Reduced after a Marathon Race and Associated with Low Energy Availability in Females.',
    'Authors from Med Sci Sports Exerc study',
    'Medicine and science in sports and exercise',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41572516/',
    array['Cognition', 'Female Athlete', 'Fueling & Nutrition', 'Marathon'],
    'Working memory dropped significantly after a marathon in female runners, and the decline was predicted by low energy availability scores. Athletes who under-fueled showed worse cognitive outcomes. The brain pays a measurable cost when the body is under-fueled during prolonged endurance work, and that cost shows up in decision-making capacity, not just pace.',
    'Fuel the brain, not just the muscles. For female endurance athletes especially, low energy availability degrades cognition during and after races, which compounds pacing errors and decision-making failures late in events.',
    'High relevance for ultra events where cognitive sharpness determines navigation, pacing, and safety decisions.',
    5,
    4,
    4,
    true
  ),
  -- 15. UCI Nutritional Periodization
  (
    '41130458',
    'UCI Sports Nutrition Project: Nutritional Periodization: Strategies to Enhance Training Adaptation and Recovery.',
    'Morton JP, Hearris M, Fell MJ, Owens DJ, Halson S, Trommelen J',
    'International journal of sport nutrition and exercise metabolism',
    2025,
    'https://pubmed.ncbi.nlm.nih.gov/41130458/',
    array['Fueling & Nutrition', 'Periodization', 'Cycling', 'Recovery'],
    'Nutritional periodization means adjusting carbohydrate and energy intake meal by meal and day by day to match the demands of each training session, not just meeting daily totals. Some sessions benefit from high carbohydrate availability; others may adapt better with reduced availability. Protein needs for endurance athletes are higher than traditionally recommended (1.6-2.1 g/kg/day) to support tissue remodeling, not just muscle building.',
    'Match fueling to the session, not the day. High-quality sessions need full carbohydrate support; easy aerobic sessions may not. Protein intake should be distributed across meals at 0.4-0.5 g/kg per sitting.',
    'Gold-standard framework from the UCI project. Directly applicable to cycling periodization and transferable to running and triathlon builds.',
    4,
    5,
    5,
    true
  ),
  -- 16. Concurrent training umbrella review
  (
    '41762427',
    'Maximizing Adaptations in Concurrent Training: An Umbrella Review of Meta-analyses.',
    'Held S, Wolf L, Rappelt L, Bloch W, Donath L, Micke F, Geisler S, Isenmann E',
    'Sports medicine',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41762427/',
    array['Strength Training', 'Concurrent Training'],
    'Concurrent training improves both aerobic capacity and strength without meaningful interference in recreationally trained athletes. Performing strength before endurance in the same session may favor strength and hypertrophy gains, though the effect is a trend rather than a hard rule. The interference effect is less of a practical barrier than historically feared, especially for non-elite athletes.',
    'Do not avoid strength training out of fear that it will hurt endurance. For most athletes, combining both modalities works. If sequencing matters, lean toward strength first when both are in the same session.',
    'Reassuring evidence for gravel and triathlon athletes who need to maintain or build strength alongside endurance volume.',
    3,
    5,
    5,
    true
  ),
  -- 17. Endurance training in winter sports framework
  (
    '41673933',
    'Endurance Training in Olympic Winter Sports: A Narrative Review of the Current Literature and Future Research Priorities.',
    'Sperlich B, Holmberg HC',
    'Scandinavian journal of medicine & science in sports',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41673933/',
    array['Periodization', 'Cross-Country Skiing', 'Training Theory'],
    'This review proposes two models: an endurance-limited model for sports like XC skiing where aerobic capacity is the ceiling, and a feeder-function model for sports where endurance supports recovery and training tolerance rather than directly driving performance. It introduces concepts like durability, fatigability, and repeatability as operational metrics beyond VO2max.',
    'Think about whether endurance is the limiter or the enabler in your sport. In long gravel and ultra events, endurance is the limiter. In shorter, more technical events, endurance supports the ability to repeat quality efforts.',
    'Conceptually valuable framework for coaches who work across multiple endurance disciplines.',
    4,
    4,
    4,
    true
  ),
  -- 18. Carbohydrate in cross-country skiing
  (
    '41755452',
    'Carbohydrate Storage and Supplementation Strategies for Peak Performance in Cross-Country Skiing.',
    'Ørtenblad N, Holmberg HC, Nybo L, Gejl KD',
    'Scandinavian journal of medicine & science in sports',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41755452/',
    array['Fueling & Nutrition', 'Glycogen', 'Cross-Country Skiing'],
    'Cross-country skiing has exceptionally high whole-body energy turnover that stresses both upper and lower body glycogen stores simultaneously. Glycogen depletion in XC skiing is not just a leg problem; the arms run out too, especially in techniques that load the upper body heavily. Carbohydrate supplementation and glycogen restoration strategies must account for this dual demand.',
    'In sports that load both upper and lower body, fueling plans need to account for total-body glycogen cost, not just leg-centric models. Recovery nutrition after XC skiing, rowing, or similar sports should prioritize rapid whole-body glycogen restoration.',
    'Directly relevant to any sport with significant upper-body endurance demand, including gravel racing with technical terrain and rowing.',
    3,
    4,
    3,
    true
  ),
  -- 19. Hallucinations and anomalous experiences in ultra-endurance
  (
    '41847782',
    'Anomalous Perceptual Experience During Ultra-Endurance Sport: A Systematic Review.',
    'Davidson EE, Davidson SL, Glue P',
    'Wilderness & environmental medicine',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41847782/',
    array['Psychology', 'Sleep', 'Ultra Running'],
    'Visual and auditory hallucinations, sensed presences, and other anomalous perceptual experiences are common in ultra-endurance events lasting more than 24 hours, especially when combined with sleep deprivation and darkness. These experiences are transient and nonpathological with no long-term psychiatric consequences. Sleep deprivation is the most consistent trigger, followed by exhaustion and low-light conditions.',
    'Normalize these experiences in pre-race briefings for ultra events. Athletes who know that hallucinations are expected, temporary, and not dangerous are less likely to panic or make poor safety decisions when they occur.',
    'Essential knowledge for athletes and crew in multi-day ultras and any event involving significant sleep deprivation.',
    5,
    2,
    2,
    true
  ),
  -- 20. CGM-guided fueling in ultra tetrathlon case
  (
    '41868981',
    'Case Report: Stage-by-stage fueling, glucose dynamics, and next-day metabolism and biomarker responses after baseline testing in an 18.5-hour Swedish classic tetrathlon.',
    'Trinh J, Edin F, Andersson-Hall U, Pettersson S',
    'Frontiers in sports and active living',
    2026,
    'https://pubmed.ncbi.nlm.nih.gov/41868981/',
    array['Fueling & Nutrition', 'Technology', 'Multi-Sport'],
    'In this 18.5-hour tetrathlon (316 km cycling, 3 km swim, 84 km roller-ski, 30 km trail run), continuous glucose monitoring showed stable blood glucose across most stages, with hypoglycemia only during the final run. The athlete averaged 57 g carbs per hour including transitions. Discipline-specific feeding windows, not a fixed hourly target, determined how much carbohydrate was actually achievable.',
    'Plan fueling around the feeding opportunities each discipline allows, not a blanket hourly target. Use CGM data in training to identify which stages are glucose-stable and where the athlete is most vulnerable to hypoglycemia.',
    'Practical blueprint for multi-discipline athletes. The stage-specific approach to fueling applies directly to triathlon and adventure racing.',
    4,
    3,
    5,
    true
  )
on conflict (pubmed_id) do update
set
  title = excluded.title,
  authors = excluded.authors,
  journal = excluded.journal,
  publication_year = excluded.publication_year,
  pubmed_url = excluded.pubmed_url,
  topic_tags = excluded.topic_tags,
  plain_english_summary = excluded.plain_english_summary,
  practical_takeaway = excluded.practical_takeaway,
  commentary = excluded.commentary,
  ultra_score = excluded.ultra_score,
  gravel_score = excluded.gravel_score,
  triathlon_score = excluded.triathlon_score,
  published = excluded.published,
  updated_at = now();
