import TrustLayout from '../components/TrustLayout';
import { SUPPORT_EMAIL, SUPPORT_MAILTO } from '../lib/supportContact';
export default function PrivacyPage() {
  return <TrustLayout title="Privacy" intro="Understand what you share, who can see it, and how to get a copy of your records or leave Threshold.">
    <section><h2 className="text-xl font-semibold">What Threshold stores</h2><p>Threshold stores the profile and sign-in information needed for your account, the training and race details you enter, check-ins and notes, coach connections and messages, and records imported from integrations you choose to connect. Training records can include wellbeing scores and activity location, heart rate, pace, distance, and elevation when a connected provider supplies them.</p></section>
    <section><h2 className="text-xl font-semibold">How your information is used</h2><p>We use these records to run your account, show your training history, support the coach and athlete workflow, reconcile billing, troubleshoot failures, and respond to support requests. Session cookies keep you signed in. Browser storage caches account details so navigation responds quickly. Diagnostic logs may record technical information about requests and errors.</p></section>
    <section><h2 className="text-xl font-semibold">What a connected coach can see</h2><p>An active coach connection lets that coach review the training records used in the coaching workflow, including your profile and race context, check-ins, logged interventions, planned and completed workouts, and information you exchange in messages. Coaches can add plans, feedback, and coach notes. Only connect to a coach you intend to share this information with.</p><p className="mt-3">Review or disconnect a coach from Account Settings → Coach Connection. Disconnecting prevents ongoing connected access; it cannot remove copies or messages the coach already received. Contact support if you need help with previously shared records.</p></section>
    <section><h2 className="text-xl font-semibold">Service providers and connected accounts</h2><p>Threshold uses Supabase for account and database services, Vercel for hosting, and Stripe for payments. When configured, Resend delivers account emails and Sentry receives error reports, performance information, and session replays used to investigate problems. These services process information needed for their function. Card payment details are handled by Stripe. If you connect Strava or another supported provider, its own privacy terms also apply; connecting gives Threshold permission to retrieve the data covered by that authorization. Strava may collect information about API usage for its own purposes, including service improvements, support, and compliance with its agreement.</p></section>
    <section><h2 className="text-xl font-semibold">Your records and choices</h2><p>Account Settings → Your data provides a JSON download of your profile and personal training records. The download excludes provider credentials, uploaded file contents, coach-only notes, and other athletes’ records; it lists unavailable sections if an older deployment lacks a feature. For additional access requests, correction, deletion help, or questions about shared records, email <a className="text-ink font-semibold underline" href={SUPPORT_MAILTO}>{SUPPORT_EMAIL}</a>. We may need to verify account ownership before acting.</p></section>
    <section><h2 className="text-xl font-semibold">Deletion and retention</h2><p>The account deletion control removes the account and associated training records handled by Threshold’s deletion workflow and first attempts to stop its linked Stripe billing. A failure is shown so you can retry or request help. Provider-held records, messages already received by others, diagnostic records, and backups may have separate retention or deletion processes. We do not promise immediate removal of every copy. Contact support about anything the self-service workflow does not cover.</p></section>
    <section><h2 className="text-xl font-semibold">Questions and changes</h2><p>Email <a className="text-ink font-semibold underline" href={SUPPORT_MAILTO}>{SUPPORT_EMAIL}</a> with privacy questions. This notice describes the current pilot and will be updated when the service or its data practices change.</p></section>
  </TrustLayout>;
}
