import TrustLayout from '../components/TrustLayout';
import { LEGAL_OPERATOR, SUPPORT_EMAIL, SUPPORT_MAILTO } from '../lib/supportContact';
export default function SupportPage() {
  return <TrustLayout title="How can we help?" intro="Get help with your account, training records, coach connection, or billing.">
    <section><h2 className="text-xl font-semibold">Our company</h2><p>Threshold is operated by {LEGAL_OPERATOR}.</p></section>
    <section><h2 className="text-xl font-semibold">Contact Threshold</h2><p>Email <a className="text-ink font-semibold underline break-all" href={SUPPORT_MAILTO}>{SUPPORT_EMAIL}</a>. Include your account email, the page you were using, and what happened. A screenshot or approximate time can help. Never send a password, sign-in link, full card number, or provider access token.</p><p className="mt-3">Support is handled personally during the pilot. There is no guaranteed response time or emergency support service.</p></section>
    <section><h2 className="text-xl font-semibold">Billing and cancellation</h2><p>Open <a className="text-ink font-semibold underline" href="/account">Account Settings</a> → Manage Billing to update a payment method or cancel. Stripe shows the cancellation date and any plan-change charges or credits before you confirm. Use Refresh billing status if a completed payment has not appeared. Email us if billing is not linked or you need help with a charge.</p></section>
    <section><h2 className="text-xl font-semibold">Privacy, export, and deletion</h2><p>Account Settings → Your data provides your personal training archive and the account deletion control. Download first if you want to keep a copy. For additional privacy or deletion requests, email the support address above; we may verify account ownership. The <a className="text-ink font-semibold underline" href="/privacy">privacy notice</a> explains shared data and retention limits.</p></section>
    <section><h2 className="text-xl font-semibold">Coach connections and sign-in</h2><p>Review a coach connection in Account Settings → Coach Connection. If you cannot sign in, use <a className="text-ink font-semibold underline" href="/forgot-password">password recovery</a> or the Google/Strava method you originally used. You can also consult the <a className="text-ink font-semibold underline" href="/guide">guide</a> for training workflows.</p></section>
  </TrustLayout>;
}
