import TrustLayout from '../components/TrustLayout';
import { LEGAL_OPERATOR, SUPPORT_EMAIL, SUPPORT_MAILTO } from '../lib/supportContact';
export default function TermsPage() {
  return <TrustLayout title="Terms of use" intro="The practical rules for using Threshold during the pilot and managing any paid subscription.">
    <section><h2 className="text-xl font-semibold">Who operates Threshold</h2><p>Threshold is operated by {LEGAL_OPERATOR}. These terms describe your use of the service provided by Threshold LLC.</p></section>
    <section><h2 className="text-xl font-semibold">The pilot service</h2><p>Threshold provides training planning, logging, and coach communication tools. The coach pilot is limited to separately approved participants. Choosing Coach during signup does not grant pilot access or a paid subscription. Features may change or be unavailable while the pilot is being developed.</p></section>
    <section><h2 className="text-xl font-semibold">Your account and training</h2><p>Provide accurate account information, keep sign-in credentials private, and only upload records you have permission to use. You control which coach connections you request or accept. Do not access another person’s account, disrupt the service, or share someone else’s private records without permission.</p><p className="mt-3">Threshold is a training tool. Its scores, calculations, and training information are not a diagnosis or emergency service. You and your coach remain responsible for training decisions and for seeking qualified professional help when needed.</p></section>
    <section><h2 className="text-xl font-semibold">Payments, renewals, and plan changes</h2><p>A paid plan starts only through a payment confirmation in Stripe. Review the recurring price, billing period, and final total there before approving. Subscriptions renew automatically until cancelled. A plan change may create a prorated charge or credit; Stripe shows the applicable invoice details before confirmation. A pilot grant is separate from paid billing.</p></section>
    <section><h2 className="text-xl font-semibold">Cancellation and billing help</h2><p>To cancel, open Account Settings → Manage Billing and use Stripe’s cancellation control. Read the effective cancellation date shown there; cancellation and account deletion are different actions. For a missing billing link, disputed charge, refund request, or cancellation problem, contact <a className="text-ink font-semibold underline" href={SUPPORT_MAILTO}>{SUPPORT_EMAIL}</a>. A refund is not automatically promised by deleting an account.</p></section>
    <section><h2 className="text-xl font-semibold">Your content and connected providers</h2><p>You keep your rights in the records and content you submit. You allow Threshold to store and process that content to provide the service and share it through the coach connections and messages you choose. Connected services, including Strava and Stripe, have their own terms. Threshold is independently operated and is not sponsored by Strava.</p></section>
    <section><h2 className="text-xl font-semibold">Leaving and getting help</h2><p>You can download your personal training archive or request account deletion in Account Settings → Your data. Review the <a className="text-ink font-semibold underline" href="/privacy">privacy notice</a> for scope and retention limits. If a control fails, contact support before assuming the request or cancellation completed.</p></section>
    <section><h2 className="text-xl font-semibold">Contact</h2><p>Contact Threshold at <a className="text-ink font-semibold underline" href={SUPPORT_MAILTO}>{SUPPORT_EMAIL}</a> about these terms, account problems, or a concern about the service.</p></section>
  </TrustLayout>;
}
